#pragma once

#include "../../../Common/CommonSource/WeaponDefine.h"

namespace WEAPON
{
	enum eINDEX {
		NONE = -1,
		C4 = 0,
		SHUTTLEX,
		C5,
		SP1,
		SP2,
		SP3,
		RPG7,
		RPG7_OUTPOST,
		RPG7_BOSS,
		K201GL,
		SPAS15,
		S870MCS_IN_MODE,
		SSG69_IN_MODE,
		BAREFIST_IN_MODE,
		KNIFE_M7,
		KNIFE_M7_GOLD,
		GH5007,
		GSHELL_POISON,
		GSHELL_K201,
		GSHELL_K201_BOSS,
		GSHELL_ARROW, // GrenadeArrow
		GSHELL_SMOKE_ARROW,
		GSHELL_WPSMOKE_ARROW,
		GSHELL_FLASHBANG_ARROW,
		THROWING_K400,
		THROWING_FLASHBANG,
		THROWING_FLASHBANG_PLUS,
		KNIFE_KUKRII,
		KNIFE_KUKRII_D,
		FANG_BLADE,
		KNIFE_KERIS,
		KNIFE_BALLISTIC,
		KNIFE_BALLISTIC_S,
		KNIFE_BALLISTIC_GRS,
		KNIFE_BALLISTIC_GRS_S,
		CANDYCANE,
		MINIAXE,
		SHOVEL,
		SHOVEL_ROYAL,
		DUALKNIFE_BONE,
		BRASS_KNUCKLE,
		PUMPKIN_KNUCKLE,
		GARENA_KNUCKLE,
		SNIPER_SVU,
		SNIPER_SCAR_LB,
		BOMBTRIGGER_DEFAULT,
		SHOTGUN_M26_LSS,

		CHINESECLEAVER,
		CHINESECLEAVER_DUMMY,
		CHINESECLEAVER_SEIZED,
		CHINESECLEAVER_SEIZED_DUMMY,
		FRYINGPAN,
		FRYINGPAN_DUMMY,
		HAIRDRYER,
		HAIRDRYER_DUMMY,
		GOAT_HAMMER,

		CROWNWATERMELON,
		ON_OBJECT_M197,
		SUB_BOW_COMPOUND_BLUE,
		
		DINO_TREX_CRASH,
		DINO_TREX_HOWL,
		DINO_STING_SPIT,
		DINO_TANK_BUTT,
		DINO_TANK_CRASH,
		DINO_ACID_EXPLOSION,

		DINO_CC_ACID_EXPLOSION,
		DINO_ACID_VULCAN_EXPLOSION,
		DOMI_MEATBOMB,

		SENTRYGUN_TRANSPARENT,
		SENTRYGUN_LV1,
		SENTRYGUN_LV2,
		SENTRYGUN_LV3,
		SENTRYGUN_LV4,
	
		DUMMY_TRANSPARENT,
		DUMMY_LV1,
		DUMMY_LV2,
		DUMMY_LV3,
		DUMMY_LV4,
	
		SUPPLY_HP,
		SUPPLY_AMMO,
		SKILLSHOP,

		SNOW_BALL_BLASTER,	//겨울 탈출 모드 무기
		HANDGUN_MGL32,
		KNIFE_ICICLE, 
		KNIFE_ICE_FORK, 
		CHINESECLEAVER_CNY2015,
		CHINESECLEAVER_CNY2015_DUMMY,

		DUAL_KUNAI,
		KUNAI,

		HALLOWEEN_HAMMER,
	
		eINDEX_MAX
	};

	void				Initialize( void);

	WEAPON::RES_ID		getItemIndex( eINDEX idx);
	UINT32				getItemCount( WEAPON_CLASS_TYPE type);

	void				addSettableItem( WEAPON::RES_ID id);
	UINT32				getSettableItemCount( void);
	WEAPON::RES_ID		getSettableItemIndex( UINT32 cntIndex);
};