
#pragma once

#include "../../../Common/CommonSource/WeaponDefine.h"

#include "WeaponExtInfoBase.h"
#include "WeaponExtGunInfo.h"
#include "WeaponDualMagInfo.h"
#include "WeaponScopeInfo.h"
#include "WeaponSilencerInfo.h"
#include "WeaponZoomInfo.h"

#include "WeaponGlobal.h"
#include "WeaponInfoDataBase.h"

#include "WeaponBase.h"
#include "WeaponShotGun.h"
#include "WeaponShotGun3.h"
#include "WeaponShotGunWithButt.h"
#include "WeaponShotGunMaleFemale.h"
#include "WeaponShotGunGenderWithDual.h"
#include "WeaponShotGun_13PV.h"
#include "WeaponShotGun_Fire13PV.h"
#include "WeaponDualShotGun.h"
#include "WeaponGrenade.h"
#include "WeaponDualGrenade.h"
#include "WeaponK400.h"
#include "WeaponSmoke.h"
#include "WeaponFlash.h"
#include "WeaponKnife.h"
#include "WeaponKnifeGender.h"
#include "WeaponC4.h"
#include "WeaponGrenadeLauncher.h"
#include "WeaponGrenadeShell.h"
#include "WeaponMachineGun.h"
#include "WeaponDualMagazine.h"
#include "WeaponSilencer.h"
#include "WeaponBombTrigger.h"
#include "WeaponC5.h"
#include "WeaponDual.h"
#include "WeaponDualCIC.h"
#include "WeaponDualHandGun.h"
#include "WeaponDualKnife.h"
#include "WeaponCrossFire.h"
#include "WeaponDotLaser.h"
#include "WeaponRocketLauncher.h"
#include "WeaponRocketLauncherShell.h"
#include "WeaponP90Ext.h"
#include "WeaponWPSmoke.h"
#include "WeaponCSSmoke.h"
#include "WeaponDualSMG.h"
#include "WeaponKrissSuperV.h"
#include "WeaponThrowKnife.h"
#include "WeaponMiniAxe.h"
#include "WeaponGrenadeLauncherWithLaser.h"
#include "WeaponShotGunLauncher.h"
#include "WeaponShotGunLauncherWithLaser.h"
#include "WeaponWithGunStock.h"
#include "WeaponDualUzi.h"
#include "WeaponDualUziWithSilencer.h"
#include "WeaponKnuckle.h"
#include "WeaponGunWithKnife.h"
#include "WeaponLoadBullet_Type.h"
#include "WeaponMedicalKit.h"
#include "WeaponBow.h"
#include "WeaponHandGrenade.h"
#include "WeaponSniperDualMagazine.h"
#include "WeaponDecoyBomb.h"
#include "WeaponEventBomb.h"
#include "WeaponClaymore.h"
#include "WeaponM14.h"
#include "WeaponDualThrowKnife.h"
#include "WeaponTouchBomb.h"
#include "WeaponNunchaku.h"

#include "WeaponSupply.h"
#include "WeaponDinoDummy.h"
#include "WeaponDominationObject.h"
#include "../SentryGun/WeaponSentryGun.h"
#include "WeaponMeatBomb.h"

#include "WeaponDinoExplosion.h"
#include "WeaponDinoButt.h"
#include "WeaponDinoCrash.h"
#include "WeaponDinoHowl.h"
#include "WeaponDinoBreath.h"
#include "WeaponWatermelon.h"
#include "WeaponFryingPan.h"
#include "WeaponSmokeShell.h"
#include "WeaponWPSmokeShell.h"
#include "WeaponFlashbangShell.h"

#include "GameWeaponManager.h"

