; once a semicolon(;) is appeared, all of left string are treated as comments.
;---------------------------------------------------------------------------------------------------------
[Default]
LogFilePath		= "d:\\PbLog\\Physics"	; LogFilePath
UdpIp			= "192.168.2.3"			; This server's UdpIp 
UdpPort			= 50000					; This server's port
;---------------------------------------------------------------------------------------------------------
; Timing Value
; The preferable UpdateTime, EpsilonTime values ara (16,1), (64, 3)
;
UpdateTime		= 16	; task thread update time
EpsilonTime		= 2		; equivalant to zero
;---------------------------------------------------------------------------------------------------------
; log level
; - error  : critical error 
; - waring : error + invalid information 
; - message: warning + system message (write all)
LogLevel		= 0		; 0:message, 1:waring, 2:error 
;---------------------------------------------------------------------------------------------------------
[BattleServerList]
Count			= 1 	; max 16	
0IP				= "192.168.2.3"
;---------------------------------------------------------------------------------------------------------
[Raycast]
RayCount		= 5 	; ray count ( 1, 3-default, 5 )
;---------------------------------------------------------------------------------------------------------
