#if !defined( __I3G_DEFINE_H)
#define __I3G_DEFINE_H

///////////////////////////////////////////////////////////////////////////////////////
// Image Format
//

#define I3G_IMAGE_FORMAT_MASK_INDEXED				0x10000000
#define I3G_IMAGE_FORMAT_MASK_ALPHA					0x20000000
#define I3G_IMAGE_FORMAT_MASK_DEPTH					0x40000000
#define I3G_IMAGE_FORMAT_MASK_COMPRESSED			0x80000000
#define I3G_IMAGE_FORMAT_MASK_ZLIB					0x01000000
#define I3G_IMAGE_FORMAT_MASK_HDRI					0x02000000

#define I3G_IMAGE_FORMAT_MASK_PC					0x00010000
#define I3G_IMAGE_FORMAT_MASK_PSP					0x00020000
#define I3G_IMAGE_FORMAT_MASK_PS2					0x00040000
#define I3G_IMAGE_FORMAT_MASK_XBOX					0x00080000
#define I3G_IMAGE_FORMAT_MASK_XBOX2					0x00100000

#define	I3G_IMAGE_FORMAT_MASK_PLATFORM				0x00FF0000

enum I3G_IMAGE_FORMAT
{
	I3G_IMAGE_FORMAT_NONE			=	0,

	I3G_IMAGE_FORMAT_DEFAULT_COLOR	= (0x0001 | I3G_IMAGE_FORMAT_MASK_ALPHA),

	// -------------------------
	// General(Linear) Formats
	// -------------------------

	// 4~8 bit format
	I3G_IMAGE_FORMAT_I4				= (0x0101 | I3G_IMAGE_FORMAT_MASK_INDEXED),	// Indexed
	I3G_IMAGE_FORMAT_I8				= (0x0102 | I3G_IMAGE_FORMAT_MASK_INDEXED), // Indexed
	i3G_IMAGE_FORMAT_L8				= (0x0103), // Luminance
	i3G_IMAGE_FORMAT_A8				= (0x0104 | I3G_IMAGE_FORMAT_MASK_ALPHA), // Alpha

	// 16 bit formats
	I3G_IMAGE_FORMAT_RGB_565		= (0x0201),
	I3G_IMAGE_FORMAT_BGR_565		= (0x0202),
	I3G_IMAGE_FORMAT_XRGB_1555		= (0x0203),
	I3G_IMAGE_FORMAT_ARGB_1555		= (0x0204 | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_XBGR_1555		= (0x0205),
	I3G_IMAGE_FORMAT_ABGR_1555		= (0x0206 | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_XRGB_4444		= (0x0207),
	I3G_IMAGE_FORMAT_ARGB_4444		= (0x0208 | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_XBGR_4444		= (0x0209),
	I3G_IMAGE_FORMAT_ABGR_4444		= (0x020A | I3G_IMAGE_FORMAT_MASK_ALPHA),

	// 24 bit formats
	I3G_IMAGE_FORMAT_RGB_888		= (0x0301),
	I3G_IMAGE_FORMAT_BGR_888		= (0x0302),

	// 32 bit formats
	I3G_IMAGE_FORMAT_RGBX_8888		= (0x0401),
	I3G_IMAGE_FORMAT_BGRX_8888		= (0x0402),
	I3G_IMAGE_FORMAT_RGBA_8888		= (0x0405 | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_BGRA_8888		= (0x0406 | I3G_IMAGE_FORMAT_MASK_ALPHA),

	// -------------------------
	// Bump-map
	// -------------------------
	I3G_IMAGE_FORMAT_VU_88			= (0x0501),
	I3G_IMAGE_FORMAT_QWVU_8888		= (0x0502),

	// -------------------------
	// Compressed formats
	// -------------------------
	I3G_IMAGE_FORMAT_DXT1_X			= (0x0680 | I3G_IMAGE_FORMAT_MASK_COMPRESSED),	// RGB Only
	I3G_IMAGE_FORMAT_DXT1			= (0x0681 | I3G_IMAGE_FORMAT_MASK_COMPRESSED | I3G_IMAGE_FORMAT_MASK_ALPHA),	// 1 bit alpha
	I3G_IMAGE_FORMAT_DXT2			= (0x0601 | I3G_IMAGE_FORMAT_MASK_COMPRESSED | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_DXT3			= (0x0602 | I3G_IMAGE_FORMAT_MASK_COMPRESSED | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_DXT4			= (0x0603 | I3G_IMAGE_FORMAT_MASK_COMPRESSED | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_DXT5			= (0x0604 | I3G_IMAGE_FORMAT_MASK_COMPRESSED | I3G_IMAGE_FORMAT_MASK_ALPHA),

	// -------------------------
	// HDR
	// -------------------------
	I3G_IMAGE_FORMAT_ABGR_16F		= (0x0801 | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_ABGR_32F		= (0x0802 | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_ABGR_16		= (0x0803 | I3G_IMAGE_FORMAT_MASK_ALPHA),
	I3G_IMAGE_FORMAT_GR_16F			= (0x0804),
	I3G_IMAGE_FORMAT_R_32F			= (0x0805),
	I3G_IMAGE_FORMAT_GR_32F			= (0x0806),

	// -------------------------
	// depth, stencil, vertex buffers
	// -------------------------
	I3G_IMAGE_FORMAT_D16			= (0x0700 | I3G_IMAGE_FORMAT_MASK_DEPTH),
	I3G_IMAGE_FORMAT_D24S8			= (0x0701 | I3G_IMAGE_FORMAT_MASK_DEPTH),
	I3G_IMAGE_FORMAT_D24X8			= (0x0702 | I3G_IMAGE_FORMAT_MASK_DEPTH),
	I3G_IMAGE_FORMAT_D32			= (0x0703 | I3G_IMAGE_FORMAT_MASK_DEPTH),
	I3G_IMAGE_FORMAT_D32F			= (0x0704 | I3G_IMAGE_FORMAT_MASK_DEPTH),
	I3G_IMAGE_FORMAT_D24FS8			= (0x0705 | I3G_IMAGE_FORMAT_MASK_DEPTH),

	// -------------------------
	// YUV... for movie
	// -------------------------

	// -------------------------
	// Swizzled (Xbox)
	// -------------------------

	I3G_IMAGE_FORMAT_FORCE_DWORD	=	0xFFFFFFFF
};

enum I3G_VERTEXBLEND_METHOD
{
	I3G_VERTEXBLEND_NONE			= 0,
	I3G_VERTEXBLEND_SOFTWARE,
	I3G_VERTEXBLEND_NONINDEXED,
	I3G_VERTEXBLEND_INDEXED,
	I3G_VERTEXBLEND_SHADER,
};

enum I3G_POINT_SPRITE_SIZE_SPACE
{
	I3G_POINT_SPRITE_SIZE_SPACE_CAMERA	=	0,
	I3G_POINT_SPRITE_SIZE_SPACE_SCREEN
};

////////////////////////////////////////////////////////////////////////////////////////
// Primitives
enum I3G_PERSIST_PRIMITIVE
{
	I3G_PERSIST_PRIM_NONE			=	0,
	I3G_PERSIST_PRIM_POINTLIST,
	I3G_PERSIST_PRIM_LINELIST,
	I3G_PERSIST_PRIM_LINESTRIP,
	I3G_PERSIST_PRIM_TRILIST,
	I3G_PERSIST_PRIM_TRISTRIP,
	I3G_PERSIST_PRIM_TRIFAN,
	I3G_PERSIST_PRIM_POINTSPRITE,
};

////////////////////////////////////////////////////////////////////////////////////////
// Render Mode
enum I3G_PERSIST_RENDER_MODE
{
	I3G_PERSIST_RENDER_MODE_POINT	=	1,
	I3G_PERSIST_RENDER_MODE_LINE,
	I3G_PERSIST_RENDER_MODE_POLYGON
};

////////////////////////////////////////////////////////////////////////////////////////
// Shade Mode
enum I3G_PERSIST_SHADE_MODE
{
	I3G_PERSIST_SHADE_MODE_FLAT		=	1,
	I3G_PERSIST_SHADE_MODE_GOURAUD,
	I3G_PERSIST_SHADE_MODE_PHONG,
	I3G_PERSIST_SHADE_MODE_PPL,
	I3G_PERSIST_SHADE_MODE_LUXMAP,
};

////////////////////////////////////////////////////////////////////////////////////////
// Face-Cull Mode
enum I3G_PERSIST_FACE_CULL
{
	I3G_PERSIST_FACE_CULL_NONE		=	1,
	I3G_PERSIST_FACE_CULL_BACK,
	I3G_PERSIST_FACE_CULL_FRONT,
};

////////////////////////////////////////////////////////////////////////////////////////
// Blend
enum I3G_PERSIST_BLEND
{
	I3G_PERSIST_BLEND_ZERO			=	1,
	I3G_PERSIST_BLEND_ONE,
	I3G_PERSIST_BLEND_SRCCOLOR,
	I3G_PERSIST_BLEND_INVSRCCOLOR,
	I3G_PERSIST_BLEND_SRCALPHA,
	I3G_PERSIST_BLEND_INVSRCALPHA,
	I3G_PERSIST_BLEND_DESTALPHA,
	I3G_PERSIST_BLEND_INVDESTALPHA,
	I3G_PERSIST_BLEND_DESTCOLOR,
	I3G_PERSIST_BLEND_INVDESTCOLOR,
	I3G_PERSIST_BLEND_SRCALPHASAT,
	I3G_PERSIST_BLEND_FACTOR,
	I3G_PERSIST_BLEND_INVFACTOR
};

enum I3G_PERSIST_BLEND_OP
{
	I3G_PERSIST_BLEND_OP_NONE		=	0,
	I3G_PERSIST_BLEND_OP_ADD,
	I3G_PERSIST_BLEND_OP_SUBTRACT,
	I3G_PERSIST_BLEND_OP_REVSUBTRACT,
	I3G_PERSIST_BLEND_OP_MIN,
	I3G_PERSIST_BLEND_OP_MAX,
};

////////////////////////////////////////////////////////////////////////////////////////
// Fog Mode
enum I3G_PERSIST_FOG_MODE
{
	I3G_PERSIST_FOG_NONE				=	1,
	I3G_PERSIST_FOG_LINEAR,
	I3G_PERSIST_FOG_EXP,
	I3G_PERSIST_FOG_EXP2
};

////////////////////////////////////////////////////////////////////////////////////////
// Stencil Operations
enum I3G_PERSIST_STENCIL_OP
{
	I3G_PERSIST_STENCIL_OP_KEEP		=	1,
	I3G_PERSIST_STENCIL_OP_ZERO,
	I3G_PERSIST_STENCIL_OP_REPLACE,
	I3G_PERSIST_STENCIL_OP_INC_CLAMP,
	I3G_PERSIST_STENCIL_OP_DEC_CLAMP,
	I3G_PERSIST_STENCIL_OP_INVERT,
	I3G_PERSIST_STENCIL_OP_INC,
	I3G_PERSIST_STENCIL_OP_DEC
};

////////////////////////////////////////////////////////////////////////////////////////
// Cmpare Functions (Alpha, Z, Stencil)
enum I3G_PERSIST_COMP_FUNC
{
	I3G_PERSIST_COMP_NEVER			=	1,
	I3G_PERSIST_COMP_LESS,
	I3G_PERSIST_COMP_EQUAL,
	I3G_PERSIST_COMP_LEQUAL,
	I3G_PERSIST_COMP_GREATER,
	I3G_PERSIST_COMP_NOTEQUAL,
	I3G_PERSIST_COMP_GEQUAL,
	I3G_PERSIST_COMP_ALWAYS
};

///////////////////////////////////////////////////////////////////////////////////////
// Texture Wrap Mode
enum I3G_PERSIST_TEXTURE_WRAP
{
	I3G_PERSIST_TEXTURE_WRAP_WRAP			=	1,
	I3G_PERSIST_TEXTURE_WRAP_CLAMP,
	I3G_PERSIST_TEXTURE_WRAP_BORDER,
};

////////////////////////////////////////////////////////////////////////////////////////
// Texture Filter Mode
enum I3G_PERSIST_TEXTURE_FILTER
{
	I3G_PERSIST_TEXTURE_FILTER_NONE			= 0,
	I3G_PERSIST_TEXTURE_FILTER_POINT,
	I3G_PERSIST_TEXTURE_FILTER_LINEAR,
	I3G_PERSIST_TEXTURE_FILTER_POINT_MIPMAP_POINT,
	I3G_PERSIST_TEXTURE_FILTER_POINT_MIPMAP_LINEAR,
	I3G_PERSIST_TEXTURE_FILTER_LINEAR_MIPMAP_POINT,
	I3G_PERSIST_TEXTURE_FILTER_LINEAR_MIPMAP_LINEAR,
	I3G_PERSIST_TEXTURE_FILTER_ANISOTROPIC, 
};

////////////////////////////////////////////////////////////////////////////////////////
// Mipmap Mode
enum I3G_PERSIST_MIPMAP
{
	I3G_PERSIST_MIPMAP_DISABLE			= 0,
	I3G_PERSIST_MIPMAP_AUTO_GEN,
	I3G_PERSIST_MIPMAP_LOAD,
};

////////////////////////////////////////////////////////////////////////////////////////
// Texture Coordinates Source Mode
enum I3G_PERSIST_TEXTURE_COORD_SOURCE
{
	I3G_PERSIST_TEXTURE_COORD_SOURCE_VERTEX						=	0,
	I3G_PERSIST_TEXTURE_COORD_SOURCE_CAMERA_SPACE_POSITION,
	I3G_PERSIST_TEXTURE_COORD_SOURCE_CAMERA_SPACE_NORMAL,
	I3G_PERSIST_TEXTURE_COORD_SOURCE_CAMERA_SPACE_REFLECTION,
};

////////////////////////////////////////////////////////////////////////////////////////
// Texture Function
enum I3G_PERSIST_TEXTURE_FUNCTION
{
	I3G_PERSIST_TEXTURE_FUNC_REPLACE	= 0,
	I3G_PERSIST_TEXTURE_FUNC_MODULATE,
	I3G_PERSIST_TEXTURE_FUNC_ADD,
	I3G_PERSIST_TEXTURE_FUNC_SPECULAR_HIGHLIGHT,
};

////////////////////////////////////////////////////////////////////////////////////////
// Cube Texture Faces
enum I3G_PERSIST_CUBE_TEXTURE_FACE
{
	I3G_PERSIST_CUBE_TEXTURE_FACE_PX	=	0,
	I3G_PERSIST_CUBE_TEXTURE_FACE_NX,
	I3G_PERSIST_CUBE_TEXTURE_FACE_PY,
	I3G_PERSIST_CUBE_TEXTURE_FACE_NY,
	I3G_PERSIST_CUBE_TEXTURE_FACE_PZ,
	I3G_PERSIST_CUBE_TEXTURE_FACE_NZ,
};

///////////////////////////////////////////////////////////////////////////////////////
// Usage
enum I3G_PERSIST_USAGE
{
	I3G_PERSIST_USAGE_NONE				= 0,
	I3G_PERSIST_USAGE_FREQUENT_UPDATE,
	I3G_PERSIST_USAGE_SOFTWAREPROCESSING,
	I3G_PERSIST_USAGE_WRITEONLY,
	I3G_PERSIST_USAGE_POINT_SPRITES,
};

//////////////////////////////////////////////////////////////////////////////////////
// Light type
enum I3G_PERSIST_LIGHT_TYPE
{
	I3G_PERSIST_LIGHT_NONE						= 0,
	I3G_PERSIST_LIGHT_DIRECTIONAL,
	I3G_PERSIST_LIGHT_SPOT,
	I3G_PERSIST_LIGHT_POINT,
};

//////////////////////////////////////////////////////////////////////////////////////
// GPU Type
enum I3G_GPU_TYPE
{
	I3G_GPU_NONE	= 0,
	I3G_GPU_PS2		= 1,		
	I3G_GPU_PSP		= 2,
	I3G_GPU_PS3		= 3,
	I3G_GPU_XBOX	= 4,
	I3G_GPU_XBOX2	= 5,
	I3G_GPU_EX3D	= 6,
	I3G_GPU_GP3D	= 7
};

enum I3G_TEXTURE_BIND
{
	I3G_TEXTURE_BIND_DIFFUSE = 0,
	I3G_TEXTURE_BIND_DIFFUSE1,
	I3G_TEXTURE_BIND_DIFFUSE2,
	I3G_TEXTURE_BIND_DIFFUSE3,
	I3G_TEXTURE_BIND_SHADOW,
	I3G_TEXTURE_BIND_SPECULAR,
	I3G_TEXTURE_BIND_REFLECT,
	I3G_TEXTURE_BIND_NORMAL,
	I3G_TEXTURE_BIND_PRT,
	I3G_TEXTURE_BIND_LUX,
	I3G_TEXTURE_BIND_LIGHT,
	I3G_TEXTURE_BIND_EMISSIVE,
	I3G_TEXTURE_BIND_REFLECT_MASK,

	I3G_TEXTURE_BIND_MAX
};

enum I3G_MATERIAL_FLAG
{
	I3G_MATERIAL_AMBIENT	= 0x00000001,
	I3G_MATERIAL_DIFFUSE	= 0x00000002,
	I3G_MATERIAL_SPECULAR	= 0x00000004,
	I3G_MATERIAL_EMISSIVE	= 0x00000008,
	I3G_MATERIAL_SHININESS	= 0x00000010
};


#if defined( I3G_DX)
	#include "i3GfxDefineDX.h"
	#include "i3GfxPSPCommandBuilder.h"
#elif defined( I3G_OGL)
 #include "i3GfxDefineOpenGL.h"
#elif defined( I3G_XBOX)
 #include "i3GfxDefineXbox.h"
#elif defined( I3G_PS2)
 #include "i3GfxDefineXbox.h"
#elif defined( I3G_PSP)
	#include "i3GfxDefinePSP.h"
	#include "i3GfxPSPCommandBuilder.h"
#elif defined( I3G_OGLES)
	#include "i3GfxDefineOGLES.h"
#endif

#endif
