#if !defined( __I3G_RENDER_STATE_XB_H)
#define __I3G_RENDER_STATE_XB_H

#if !defined(I3_XBOX) || !defined(I3G_XBOX)
#error "This header file is only for Xbox."
#endif

enum I3G_RENDER_STATE
{
	I3G_RS_ALPHA_TEST_ENABLE				=	D3DRS_ALPHATESTENABLE,
	I3G_RS_ALPHA_BLEND_ENABLE				=	D3DRS_ALPHABLENDENABLE,
	I3G_RS_ALPHA_REF_VALUE					=	D3DRS_ALPHAREF,
	I3G_RS_ALPHA_FUNC						=	D3DRS_ALPHAFUNC,

	I3G_RS_Z_ENABLE							=	D3DRS_ZENABLE,
	I3G_RS_Z_WRITE_ENABLE					=	D3DRS_ZWRITEENABLE,
	I3G_RS_Z_FUNC							=	D3DRS_ZFUNC,
	I3G_RS_Z_BIAS							=	D3DRS_ZBIAS,

	I3G_RS_RENDER_MODE						=	D3DRS_FILLMODE,
	I3G_RS_SHADE_MODE						=	D3DRS_SHADEMODE,
	// I3G_RS_LINE_PATTERN						=	D3DRS_LINEPATTERN,
	I3G_RS_FACE_CULL_MODE					=	D3DRS_CULLMODE,
	
	I3G_RS_SRC_BLEND						=	D3DRS_SRCBLEND,
	I3G_RS_DEST_BLEND						=	D3DRS_DESTBLEND,
	
	I3G_RS_SPECULAR_ENABLE					=	D3DRS_SPECULARENABLE,

	I3G_RS_FOG_ENABLE						=	D3DRS_FOGENABLE,
	I3G_RS_FOG_COLOR						=	D3DRS_FOGCOLOR,
	I3G_RS_FOG_TABLE_MODE					=	D3DRS_FOGTABLEMODE,
	I3G_RS_FOG_NEAR							=	D3DRS_FOGSTART,
	I3G_RS_FOG_FAR							=	D3DRS_FOGEND,
	I3G_RS_FOG_DENSITY						=	D3DRS_FOGDENSITY,
	I3G_RS_FOG_RANGE_ENABLE					=	D3DRS_RANGEFOGENABLE,
	// I3G_RS_FOG_MODE							=	D3DRS_FOGVERTEXMODE,

	I3G_RS_EDGE_ANTIALIASE_ENABLE			=	D3DRS_EDGEANTIALIAS,

	I3G_RS_STENCIL_ENABLE					=	D3DRS_STENCILENABLE,
	I3G_RS_STENCIL_OP_SFAIL					=	D3DRS_STENCILFAIL,
	I3G_RS_STENCIL_OP_ZFAIL					=	D3DRS_STENCILZFAIL,
	I3G_RS_STENCIL_OP_PASS					=	D3DRS_STENCILPASS,
	I3G_RS_STENCIL_FUNC						=	D3DRS_STENCILFUNC,
	I3G_RS_STENCIL_REF_VALUE				=	D3DRS_STENCILREF,
	I3G_RS_STENCIL_READ_MASK				=	D3DRS_STENCILMASK,
	I3G_RS_STENCIL_WRITE_MASK				=	D3DRS_STENCILWRITEMASK,
	
	I3G_RS_TEXTURE_FACTOR					=	D3DRS_TEXTUREFACTOR,
	I3G_RS_TEXTURE_WRAP_MODE				=	D3DRS_WRAP0,
	I3G_RS_TEXTURE_WRAP0_MODE				=	D3DRS_WRAP0,
	I3G_RS_TEXTURE_WRAP1_MODE				=	D3DRS_WRAP1,
	I3G_RS_TEXTURE_WRAP2_MODE				=	D3DRS_WRAP2,
	I3G_RS_TEXTURE_WRAP3_MODE				=	D3DRS_WRAP3,
	//I3G_RS_TEXTURE_WRAP4_MODE				=	D3DRS_WRAP4,
	//I3G_RS_TEXTURE_WRAP5_MODE				=	D3DRS_WRAP5,
	//I3G_RS_TEXTURE_WRAP6_MODE				=	D3DRS_WRAP6,
	//I3G_RS_TEXTURE_WRAP7_MODE				=	D3DRS_WRAP7,

	//I3G_RS_CLIPPING_ENABLE					=	D3DRS_CLIPPING,

	I3G_RS_LIGHTING_ENABLE					=	D3DRS_LIGHTING,

	I3G_RS_VERTEXCOLOR_ENABLE				=	D3DRS_COLORVERTEX,

	I3G_RS_NORMALIZE_NORMAL_ENABLE			=	D3DRS_NORMALIZENORMALS,

	I3G_RS_MATERIAL_DIFFUSE					=	D3DRS_DIFFUSEMATERIALSOURCE,
	I3G_RS_MATERIAL_SPECULAR				=	D3DRS_SPECULARMATERIALSOURCE,
	I3G_RS_MATERIAL_EMISSIVE				=	D3DRS_EMISSIVEMATERIALSOURCE,
	I3G_RS_MATERIAL_AMBIENT					=	D3DRS_AMBIENTMATERIALSOURCE,

	I3G_RS_VERTEX_BLEND_MODE				=	D3DRS_VERTEXBLEND,

	//I3G_RS_SOFTWARE_VERTEX_PROCESS_ENABLE	=	D3DRS_SOFTWAREVERTEXPROCESSING,

	I3G_RS_POINT_SPRITE_SIZE				=	D3DRS_POINTSIZE,
	I3G_RS_POINT_SPRITE_SIZE_MIN			=	D3DRS_POINTSIZE_MIN,
	I3G_RS_POINT_SPRITE_SIZE_MAX			=	D3DRS_POINTSIZE_MAX
};

enum I3G_FACECULL
{
	I3G_FACECULL_NONE	=	D3DCULL_NONE,
	I3G_FACECULL_BACK	=	D3DCULL_CCW,
	I3G_FACECULL_FRONT	=	D3DCULL_CW
};

enum I3G_COMP_FUNC
{
	I3G_COMP_NEVER		=	D3DCMP_NEVER,
	I3G_COMP_LESS		=	D3DCMP_LESS,
	I3G_COMP_EQUAL		=	D3DCMP_EQUAL,
	I3G_COMP_LEQUAL		=	D3DCMP_LESSEQUAL,
	I3G_COMP_GREATER	=	D3DCMP_GREATER,
	I3G_COMP_NOTEQUAL	=	D3DCMP_NOTEQUAL,
	I3G_COMP_GEQUAL		=	D3DCMP_GREATEREQUAL,
	I3G_COMP_ALWAYS		=	D3DCMP_ALWAYS
};

enum I3G_RENDER_MODE
{
	I3G_RENDER_POINT		=	D3DFILL_POINT,
	I3G_RENDER_LINE			=	D3DFILL_WIREFRAME,
	I3G_RENDER_POLYGON		=	D3DFILL_SOLID
};

enum I3G_SHADE_MODE
{
	I3G_SHADE_FLAT			=	D3DSHADE_FLAT,
	I3G_SHADE_GOURAUD		=	D3DSHADE_GOURAUD,
};

enum I3G_FACE_CULL
{
	I3G_FACE_CULL_NONE		=	D3DCULL_NONE,
	I3G_FACE_CULL_BACK		=	D3DCULL_CW,
	I3G_FACE_CULL_FRONT		=	D3DCULL_CCW,
};

enum I3G_BLEND
{
	I3G_BLEND_ZERO			=	D3DBLEND_ZERO,
	I3G_BLEND_ONE			=	D3DBLEND_ONE,
	I3G_BLEND_SRCCOLOR		=	D3DBLEND_SRCCOLOR,
	I3G_BLEND_INVSRCCOLOR	=	D3DBLEND_INVSRCCOLOR,
	I3G_BLEND_SRCALPHA		=	D3DBLEND_SRCALPHA,
	I3G_BLEND_INVSRCALPHA	=	D3DBLEND_INVSRCALPHA,
	I3G_BLEND_DESTALPHA		=	D3DBLEND_DESTALPHA,
	I3G_BLEND_INVDESTALPHA	=	D3DBLEND_INVDESTALPHA,
	I3G_BLEND_DESTCOLOR		=	D3DBLEND_DESTCOLOR,
	I3G_BLEND_INVDESTCOLOR	=	D3DBLEND_INVDESTCOLOR,
	I3G_BLEND_SRCALPHASAT	=	D3DBLEND_SRCALPHASAT,
};

enum I3G_FOG_MODE
{
	I3G_FOG_NONE			=	D3DFOG_NONE,
	I3G_FOG_LINEAR			=	D3DFOG_LINEAR,
	I3G_FOG_EXP				=	D3DFOG_EXP,
	I3G_FOG_EXP2			=	D3DFOG_EXP2,
};

enum I3G_STENCIL_OP
{
	I3G_STENCIL_OP_KEEP			=	D3DSTENCILOP_KEEP,
	I3G_STENCIL_OP_ZERO			=	D3DSTENCILOP_ZERO,
	I3G_STENCIL_OP_REPLACE		=	D3DSTENCILOP_REPLACE,
	I3G_STENCIL_OP_INC_CLAMP	=	D3DSTENCILOP_INCRSAT,
	I3G_STENCIL_OP_DEC_CLAMP	=	D3DSTENCILOP_DECRSAT,
	I3G_STENCIL_OP_INVERT		=	D3DSTENCILOP_INVERT,
	I3G_STENCIL_OP_INC			=	D3DSTENCILOP_INCR,
	I3G_STENCIL_OP_DEC			=	D3DSTENCILOP_DECR,
};

#endif