#if !defined( __I3G_RENDER_STATE_DX_H)
#define __I3G_RENDER_STATE_DX_H

#if !defined(I3_WINDOWS) || !defined(I3G_DX)
#error "This header file is only for DirectX and Windows."
#endif

enum I3G_COMP_FUNC
{
	I3G_COMP_NEVER		=	D3DCMP_NEVER,
	I3G_COMP_LESS		=	D3DCMP_LESS,
	I3G_COMP_EQUAL		=	D3DCMP_EQUAL,
	I3G_COMP_LEQUAL		=	D3DCMP_LESSEQUAL,
	I3G_COMP_GREATER	=	D3DCMP_GREATER,
	I3G_COMP_NOTEQUAL	=	D3DCMP_NOTEQUAL,
	I3G_COMP_GEQUAL		=	D3DCMP_GREATEREQUAL,
	I3G_COMP_ALWAYS		=	D3DCMP_ALWAYS
};

enum I3G_RENDER_MODE
{
	I3G_RENDER_POINT		=	D3DFILL_POINT,
	I3G_RENDER_LINE			=	D3DFILL_WIREFRAME,
	I3G_RENDER_POLYGON		=	D3DFILL_SOLID
};

enum I3G_SHADE_MODE
{
	I3G_SHADE_FLAT			=	D3DSHADE_FLAT,
	I3G_SHADE_GOURAUD		=	D3DSHADE_GOURAUD,
	I3G_SHADE_PHONG			=	D3DSHADE_PHONG,
	I3G_SHADE_PPL			=	(D3DSHADE_PHONG + 1),
	I3G_SHADE_LUXMAP		=	(D3DSHADE_PHONG + 2)
};

enum I3G_FACE_CULL
{
	I3G_FACE_CULL_NONE		=	D3DCULL_NONE,
	I3G_FACE_CULL_BACK		=	D3DCULL_CW,
	I3G_FACE_CULL_FRONT		=	D3DCULL_CCW,
};

enum I3G_BLEND
{
	I3G_BLEND_ZERO			=	D3DBLEND_ZERO,			// 1
	I3G_BLEND_ONE			=	D3DBLEND_ONE,			// 2
	I3G_BLEND_SRCCOLOR		=	D3DBLEND_SRCCOLOR,		// 3
	I3G_BLEND_INVSRCCOLOR	=	D3DBLEND_INVSRCCOLOR,	// 4
	I3G_BLEND_SRCALPHA		=	D3DBLEND_SRCALPHA,		// 5
	I3G_BLEND_INVSRCALPHA	=	D3DBLEND_INVSRCALPHA,	// 6
	I3G_BLEND_DESTALPHA		=	D3DBLEND_DESTALPHA,		// 7
	I3G_BLEND_INVDESTALPHA	=	D3DBLEND_INVDESTALPHA,	// 8
	I3G_BLEND_DESTCOLOR		=	D3DBLEND_DESTCOLOR,		// 9
	I3G_BLEND_INVDESTCOLOR	=	D3DBLEND_INVDESTCOLOR,	// 10
	I3G_BLEND_SRCALPHASAT	=	D3DBLEND_SRCALPHASAT,	// 11
	I3G_BLEND_FACTOR		=	D3DBLEND_BLENDFACTOR,
	I3G_BLEND_INVFACTOR		=	D3DBLEND_INVBLENDFACTOR
};

enum I3G_BLEND_OP
{
	I3G_BLEND_OP_NONE			=	0,
	I3G_BLEND_OP_ADD			=	D3DBLENDOP_ADD,
	I3G_BLEND_OP_SUBTRACT		=	D3DBLENDOP_SUBTRACT,
	I3G_BLEND_OP_REVSUBTRACT	=	D3DBLENDOP_REVSUBTRACT,
	I3G_BLEND_OP_MIN			=	D3DBLENDOP_MIN,
	I3G_BLEND_OP_MAX			=	D3DBLENDOP_MAX,
};

enum I3G_FOG_MODE
{
	I3G_FOG_NONE			=	D3DFOG_NONE,
	I3G_FOG_LINEAR			=	D3DFOG_LINEAR,
	I3G_FOG_EXP				=	D3DFOG_EXP,
	I3G_FOG_EXP2			=	D3DFOG_EXP2,
};

enum I3G_STENCIL_OP
{
	I3G_STENCIL_OP_KEEP			=	D3DSTENCILOP_KEEP,
	I3G_STENCIL_OP_ZERO			=	D3DSTENCILOP_ZERO,
	I3G_STENCIL_OP_REPLACE		=	D3DSTENCILOP_REPLACE,
	I3G_STENCIL_OP_INC_CLAMP	=	D3DSTENCILOP_INCRSAT,
	I3G_STENCIL_OP_DEC_CLAMP	=	D3DSTENCILOP_DECRSAT,
	I3G_STENCIL_OP_INVERT		=	D3DSTENCILOP_INVERT,
	I3G_STENCIL_OP_INC			=	D3DSTENCILOP_INCR,
	I3G_STENCIL_OP_DEC			=	D3DSTENCILOP_DECR,
};

#endif