#if !defined( __I3G_RENDER_STATE_PSP_H)
#define __I3G_RENDER_STATE_PSP_H

#if !defined( I3G_PSP)
#error "This header file is only for SONY PSP."
#endif


enum I3G_COMP_FUNC
{
	I3G_COMP_NEVER		=	SCEGU_NEVER,	// 0
	I3G_COMP_LESS		=	SCEGU_LESS,		// 4
	I3G_COMP_EQUAL		=	SCEGU_EQUAL,	// 2
	I3G_COMP_LEQUAL		=	SCEGU_LEQUAL,	// 5
	I3G_COMP_GREATER	=	SCEGU_GREATER,	// 6
	I3G_COMP_NOTEQUAL	=	SCEGU_NOTEQUAL,	// 3
	I3G_COMP_GEQUAL		=	SCEGU_GEQUAL,	// 7
	I3G_COMP_ALWAYS		=	SCEGU_ALWAYS	// 1
};

enum I3G_RENDER_MODE
{
	I3G_RENDER_POINT		=	0,
	I3G_RENDER_LINE,
	I3G_RENDER_POLYGON,
};

enum I3G_SHADE_MODE
{
	I3G_SHADE_FLAT			=	SCEGU_FLAT,
	I3G_SHADE_GOURAUD		=	SCEGU_SMOOTH,
};

enum I3G_FACE_CULL
{
	I3G_FACE_CULL_NONE		=	-1,
	I3G_FACE_CULL_BACK		=	SCEGU_CCW,
	I3G_FACE_CULL_FRONT		=	SCEGU_CW,
};

enum I3G_BLEND
{
	I3G_BLEND_SRCCOLOR		=	SCEGU_SRC_COLOR,				// 0
	I3G_BLEND_INVSRCCOLOR	=	SCEGU_ONE_MINUS_SRC_COLOR,		// 1
	I3G_BLEND_SRCALPHA		=	SCEGU_SRC_ALPHA,				// 2
	I3G_BLEND_INVSRCALPHA	=	SCEGU_ONE_MINUS_SRC_ALPHA,		// 3
	I3G_BLEND_DESTALPHA		=	SCEGU_DST_ALPHA,				// 4
	I3G_BLEND_INVDESTALPHA	=	SCEGU_ONE_MINUS_DST_ALPHA,		// 5
	I3G_BLEND_DESTCOLOR		=	SCEGU_DST_COLOR,				// 0
	I3G_BLEND_INVDESTCOLOR	=	SCEGU_ONE_MINUS_DST_COLOR,		// 1
	I3G_BLEND_ZERO			=	20,								// 10
	I3G_BLEND_ONE			=	21,								// 10
	I3G_BLEND_SRCALPHASAT	=	SCEGU_SRC_ALPHA,				// 2
};
/*
#define SCEGU_SRC_COLOR                    0
#define SCEGU_ONE_MINUS_SRC_COLOR          1
#define SCEGU_DST_COLOR                    0
#define SCEGU_ONE_MINUS_DST_COLOR          1
#define SCEGU_SRC_ALPHA                    2
#define SCEGU_ONE_MINUS_SRC_ALPHA          3
#define SCEGU_DST_ALPHA                    4
#define SCEGU_ONE_MINUS_DST_ALPHA          5
#define SCEGU_DOUBLE_SRC_ALPHA             6
#define SCEGU_ONE_MINUS_DOUBLE_SRC_ALPHA   7
#define SCEGU_DOUBLE_DST_ALPHA             8
#define SCEGU_ONE_MINUS_DOUBLE_DST_ALPHA   9
#define SCEGU_FIX_VALUE                   10
*/
enum I3G_BLEND_OP
{
	I3G_BLEND_OP_NONE			=	-1,
	I3G_BLEND_OP_ADD			=	SCEGU_ADD,
	I3G_BLEND_OP_SUBTRACT		=	SCEGU_SUBTRACT,
	I3G_BLEND_OP_REVSUBTRACT	=	SCEGU_REVERSE_SUBTRACT,
	I3G_BLEND_OP_MIN			=	SCEGU_MIN,
	I3G_BLEND_OP_MAX			=	SCEGU_MAX,
};

enum I3G_FOG_MODE
{
	I3G_FOG_NONE			=	0,
	I3G_FOG_LINEAR			=	1,
	I3G_FOG_EXP				=	2,
	I3G_FOG_EXP2			=	3,
};

enum I3G_STENCIL_OP
{
	I3G_STENCIL_OP_KEEP			=	SCEGU_KEEP,
	I3G_STENCIL_OP_ZERO			=	SCEGU_ZERO,
	I3G_STENCIL_OP_REPLACE		=	SCEGU_REPLACE,
	I3G_STENCIL_OP_INC_CLAMP	=	SCEGU_INCR,
	I3G_STENCIL_OP_DEC_CLAMP	=	SCEGU_DECR,
	I3G_STENCIL_OP_INVERT		=	SCEGU_INVERT,
	I3G_STENCIL_OP_INC			=	SCEGU_INCR,
	I3G_STENCIL_OP_DEC			=	SCEGU_DECR,
};

#endif
