#if !defined( __I3_SHADER_DEFINE_H)
#define __I3_SHADER_DEFINE_H

enum I3G_SHADER_TYPE
{
	I3G_SHADER_TYPE_VERTEX = 0,
	I3G_SHADER_TYPE_BLENDED_VERTEX_1,
	I3G_SHADER_TYPE_BLENDED_VERTEX_2,
	I3G_SHADER_TYPE_BLENDED_VERTEX_3,
	I3G_SHADER_TYPE_BLENDED_VERTEX_4,
	I3G_SHADER_TYPE_PIXEL,

	I3G_SHADER_TYPE_MAX
};

#define	I3G_SHADER_FLAG_DIFFUSE_MAP					0x80000000					// Diffuse Map 대응
#define I3G_SHADER_FLAG_SPECULAR_MAP				0x40000000					// Specular-Map 대응
#define	I3G_SHADER_FLAG_REFLECT_MAP					0x20000000					// Reflect-Map 대응
#define I3G_SHADER_FLAG_EMISSIVE_MAP				0x10000000					// Emissive Map 대응
#define	I3G_SHADER_FLAG_NORMAL_MAP					0x08000000					// Normal Map 대응
#define	I3G_SHADER_FLAG_PPL							0x04000000					// Per-Pixel Lighting
#define	I3G_SHADER_FLAG_VERTEX_COLOR				0x02000000					// vertex Color
#define I3G_SHADER_FLAG_LUX_MAP						0x01000000
#define	I3G_SHADER_FLAG_REFLECT_MASK_MAP			0x00800000
#define	I3G_SHADER_FLAG_LIGHTING					0x00400000
#define I3G_SHADER_FLAG_FRESNEL						0x00200000

#define	I3G_SHADER_SHIFT_LIGHT_ALL					10
#define	I3G_SHADER_MASK_LIGHT_ALL					0x000003FF

////////////////////////////////////////
// Light Model
#define	I3G_SHADER_MASK_LIGHT_MODEL					(0x00000007)
#define	I3G_SHADER_SHIFT_LIGHT_MODEL				0

enum I3G_SHADER_FLAG_LIGHT_MODEL
{
	I3G_SHADER_FLAG_LIGHT_MODEL_NOLIGHT = 0,				// No Lighting
	I3G_SHADER_FLAG_LIGHT_MODEL_PHONG,						// Blinn-Phong light model
	I3G_SHADER_FLAG_LIGHT_MODEL_HSL,						// Hemispheric light model
};


////////////////////////////////////////
// Light Type
#define I3G_SHADER_MASK_LIGHT_TYPE					0x00000007
#define	I3G_SHADER_SHIFT_LIGHT_TYPE					3

enum I3G_SHADER_FLAG_LIGHT_TYPE
{
	I3G_SHADER_FLAG_LIGHT_TYPE_DIRECTIONAL = 1,				// Directional Light
	I3G_SHADER_FLAG_LIGHT_TYPE_POINT,						// Point Light
	I3G_SHADER_FLAG_LIGHT_TYPE_SPOT,						// Spot light
};

#define	I3G_SHADER_MASK_TEXTURE_LIGHT				0x00000001
#define	I3G_SHADER_SHIFT_TEXTURE_LIGHT				6

#define	I3G_SHADER_MASK_SHADOW						0x00000007
#define I3G_SHADER_SHIFT_SHADOW						7

enum I3G_SHADER_FLAG_SHADOW
{
	I3G_SHADER_FLAG_SHADOW_NONE						= 0,
	I3G_SHADER_FLAG_SHADOW_SHADOWMAP,
};

// Light 1

#endif
