#pragma once

namespace ui
{
	enum PRIVATE_WINDOW_MESSAGE_USER
	{
		WMU_ADD_CONTENTS_VIEWLIST			= WM_USER + 1000,
		WMU_UPDATE_CONTENTS_VIEWLIST,
		WMU_CLEAR_CONTENTS_VIEWLIST,
		WMU_INSERT_CONTENTS_SYNCLIST,
		WMU_DELETE_CONTENTS_SYNCLIST,
		WMU_CLEAR_CONTENTS_SYNCLIST,
		WMU_SET_CONTENTS_SYNC_COLOR,
		WMU_SET_CONTENTS_NON_SYNC_COLOR,
		WMU_SET_LOADING_MESSAGE,
		WMU_CUSTOM_PROGRESS_GAUGE_POS,
		WMU_CUSTOM_STATIC_TEXT,
	};

	enum ID_WINDOW_CTRL
	{
		ID_TASK_BAR = 1234,
		ID_SYNC_PLAYER_BAR,
		ID_OUTPUT_BAR,
		ID_CONTENTSVIEW_LIST,
		//ID_SYNCCART_LIST,
		ID_CONTENTSVIEW_TOOLBAR,
		//ID_BUILD_BUTTON,
		ID_COUNTRY_LIST,
		ID_SYNCPLAYER_TH_STATUS_CTRL,
		ID_SYNCPLAYER_TH_MENU_CTRL,
		ID_SYNCPLAYER_CONTENTSLIST_CTRL,
		ID_SYNCPLAYER_PROGRESS_CTRL,
		ID_SYNCPLAYER_PLAYBUTTON_CTRL,
		ID_LOADING_PROGRESS_MSGBOX_TEXT_CTRL,
		ID_SETTING_LIST,
		ID_COUNTRY_SETTING_LIST_CTRL,
		ID_VERSION_SETTING_LIST_CTRL,
		ID_CONTENTS_DESCRIPTION_BAR,
		ID_MQ_CONTENTS_STATUS_BAR,
		ID_QL_CONTENTS_STATUS_BAR,
		ID_CONTENTS_DESC_LIST_CTRL,
		ID_I3PACK_DESCRIPTION_BAR,
		ID_MENU_ADD_CONTENTS_TO_SYNCLIST,
		ID_MENU_DELETE_SYNCLIST,
		ID_TOOL_LIST,
		ID_FILE_SHADER_SOURCE_EDIT_BOX_CTRL,
		ID_MEMORY_SHADER_SOURCE_EDIT_BOX_CTRL,
		ID_FILE_SHADER_LIST_CTRL,
		ID_MEMORY_SHADER_LIST_CTRL,
		ID_BROWSE_SHADER_PATH,
		ID_MQ_CONTENTS_STATUS_TREECTRL,
		ID_QL_CONTENTS_STATUS_TREECTRL,
		ID_BROWSE_PACKTOOL_SOURCE_PATH,
		ID_BROWSE_PACKTOOL_PACK_PATH,
	};

#define COLOR_BLACK					RGB(0,0,0)
#define COLOR_IVORY_BLACK			RGB(40,36,34)
#define COLOR_IVORY_BLACK_LIGHT		RGB(46,41,38)
#define COLOR_SILVER				RGB(192,192,192)
#define COLOR_WHITE					RGB(255,255,255)
#define COLOR_ORANGE				RGB(200,96,35)
#define COLOR_DARK_ORANGE			RGB(139,69,0)
#define COLOR_DEEP_DARK_ORANGE		RGB(205,102,0)
#define	COLOR_GRAY					RGB(13,13,13)
#define COLOR_VIOLET_RED			RGB(255,62,150)
#define COLOR_MAGENTA				RGB(255,0,255)
#define COLOR_TAN3_PERU				RGB(205,133,63)
#define COLOR_SKYBLUE				RGB(0,191,255)
#define COLOR_RED					RGB(255,0,0)
#define COLOR_MAROON				RGB(176,48,96)
#define COLOR_GREEN					RGB(0, 255, 0)
}
