#if !defined( __I3_TEXT_COMMON_DEFINE_H)
#define __I3_TEXT_COMMON_DEFINE_H

enum TEXT_HORZ_ALIGN
{
	ALIGN_LEFT,
	ALIGN_CENTER,
	ALIGN_RIGHT,
};

enum TEXT_VERT_ALIGN 
{
	ALIGN_TOP,
	ALIGN_MIDDLE,
	ALIGN_BOTTOM,
};

enum FONT_SHADOW_QUALITY
{
	FONT_SHADOW_QUALITY_LOW = 0,
	FONT_SHADOW_QUALITY_NORMAL,
	FONT_SHADOW_QUALITY_HIGH,
};

#endif	//__I3_TEXT_COMMON_DEFINE_H