;(semicolon) is command

[Default]
ServerIp			= "192.168.1.1"			; 
ServerPort			= 39130				; 
ServerLogFile			= "D:/PBLog/Billing"		; LogFilePath

[Control]							; Control Server (Use Control App)
ControlServerIp			= "192.168.1.1"			; 
ControlServerPort		= 39120				; 

[Link]
LinkMethod			= 4				; 1: NO, 2: Auto, 2: TCP, 3: Web, 4: DB, 5: LIB
LINK_IP				= ""
LINK_PORT			= 
LINK_HTTP			= ""
LINK_DB				= ""

[Connect]
ServerCount			= 2
ServerIP_00			= "192.168.1.1"
ServerIP_01			= "192.168.1.1"

[LogD]								; NC LOGD Server
LogDActive			= 0				; 0 : Not Use, 1: Use
LogDServerIp			= "192.168.1.1"			; 
LogDServerPort			= 10204				; 



