//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// i3UIEditor.rc에서 사용되고 있습니다.
//
#define ID_SELKEY                       3
#define ID_BTN_SETACTIVE                6
#define ID_BTN_SHOWHIDE                 7
#define ID_BTN_CLOSESCENE               8
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_PANE_WORKSPACE              101
#define IDS_PANE_SCREEN                 102
#define IDS_PANE_TEMPLATE               103
#define IDS_PANE_PROPERTIES             104
#define IDC_POINTER                     104
#define IDS_PANE_TIMELINE               105
#define IDS_PANE_SCRIPT                 106
#define IDS_PANE_OUTPUT                 107
#define ID_TEMPLATE_SCRIPT              108
#define IDS_PANE_TEMPLATEEXPLORER       109
#define IDB_WRITESMALL                  110
#define IDS_TREEVIEW                    110
#define IDB_WRITELARGE                  111
#define IDS_ICONVIEW                    111
#define IDB_MAIN                        112
#define IDS_REPORTVIEW                  112
#define IDB_BUTTONS                     113
#define IDS_PANE_PROPERTIES2            113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_i3UIEditorTYPE              130
#define IDB_SCREEN_SMALL                130
#define IDB_SCREEN_LARGE                131
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EDIT_MENU                   306
#define ID_PANE_WORKSPACE               310
#define IDR_SCREEN_RESOLUTION           310
#define ID_PANE_SCREEN                  311
#define IDR_MENU_TEMPLATE               311
#define ID_PANE_TEMPLATE                312
#define IDD_DLG_SELECTMETA_TEMPLATE     312
#define ID_PANE_PROPERTIES              313
#define IDR_MENU_SCREEN                 313
#define ID_PANE_TIMELINE                314
#define IDD_UV_SELECTOR                 314
#define ID_SCREEN_TREECTRL              315
#define IDR_MENU_PROJECT                315
#define ID_TEMPLATE_TREECTRL            316
#define ID_PANE_SCRIPT                  318
#define ID_PANE_SCRIPT_LISTBOX          319
#define ID_PANE_OUTPUT                  320
#define ID_VIEW_OUTPUT_PANE             321
#define IDR_MENU_UVSELECTOR             322
#define ID_TEMPLATE_IEH                 322
#define IDI_ICON_BTN                    323
#define IDI_ICON_BTN_SEL                324
#define ID__SELECTALL                   324
#define IDI_ICON_CHECK                  325
#define ID_PANE_TEMPLATEEXPLORER        325
#define IDI_ICON_CHECK_SEL              326
#define ID_TBBTN_TREEVIEW               326
#define IDI_ICON_COMBO                  327
#define ID_TBBTN_ICONVIEW               327
#define IDI_ICON_COMBO_SEL              328
#define ID_TBBTN_REPORTVIEW             328
#define IDI_ICON_EDIT                   329
#define ID_TBBTN_UPPERLEVEL             329
#define IDI_ICON_EDIT_SEL               330
#define ID_TBBTN_NEWFILTER              330
#define IDI_ICON_FRAMEWND               331
#define ID_TBBTN_NEWTEMPLATE            331
#define IDI_ICON_FRAMEWND_SEL           332
#define ID_TBBTN_EDIT                   332
#define IDI_ICON_GROUPCTRL              333
#define ID_TBBTN_EDITSCRIPT             333
#define IDI_ICON_GROUPCTRL_SEL          334
#define ID_TE_CHILD_TOOLBAR             334
#define IDI_ICON_HSCROLLBAR             335
#define ID_TE_CHILD_LISTVIEW            335
#define IDI_ICON_HSCROLLBAR_SEL         336
#define ID_TE_CHILD_STATUSBAR           336
#define IDI_ICON_LISTBOX                337
#define ID_TBBTN_REMOVE                 337
#define IDI_ICON_LISTBOX_SEL            338
#define ID_VIEW_TEMPLATE_EXPLORER_PANE  338
#define IDI_ICON_PROGRESS               339
#define ID_TE_CHILD_TREEVIEW            339
#define IDI_ICON_PROGRESS_SEL           340
#define ID_PROJECT_RESOLUTION           340
#define IDI_ICON_RADIO                  341
#define ID_EDIT_DELETE                  341
#define IDI_ICON_RADIO_SEL              342
#define IDI_ICON_STATICIMAGE            343
#define IDI_ICON_STATICIMAGE_SEL        344
#define IDI_ICON_SLIDER                 345
#define IDI_ICON_SLIDER_SEL             346
#define IDI_ICON_SPIN                   347
#define IDI_ICON_SPIN_SEL               348
#define IDI_ICON_STATICTEXT             349
#define IDI_ICON_STATICTEXT_SEL         350
#define IDI_ICON_TABCTRL                351
#define IDI_ICON_TABCTRL_SEL            352
#define IDI_ICON_TREECTRL               353
#define IDI_ICON_TREECTRL_SEL           354
#define IDI_ICON_UIFILTER               355
#define IDI_ICON_UIFILTER_SEL           356
#define IDI_ICON_UIHIDE                 357
#define IDI_ICON_UILOCK                 358
#define IDI_ICON_UIUNLOCK               359
#define IDI_ICON_UISCREEN               360
#define IDI_ICON_UISCREEN_SEL           361
#define IDI_ICON_UISHOW                 362
#define IDI_ICON_VSCROLLBAR             363
#define IDI_ICON_VSCROLLBAR_SEL         364
#define IDB_TB_SM                       365
#define IDB_TB_LA                       366
#define IDR_RIBBON_TEMPLATE             367
#define IDB_PANEL_BACKGROUND            368
#define IDR_RIBBON_DEBUG                369
#define IDD_SELECT_TEXTURE              370
#define IDR_RIBBON_VIEW                 371
#define IDB_BITMAP1                     372
#define IDD_DLG_GOTOLINE                373
#define IDR_MENU_SHAPELIST              374
#define IDD_DLG_FIND                    375
#define IDD_DLG_SHAPEINFO               376
#define IDD_DLG_LEFTALIGN_VALUE         377
#define IDD_DIALOG1                     378
#define IDD_DLG_SELECT_RUNMODULE        379
#define IDD_DRAGDROP_OPTION             380
#define IDR_MENU_OUTPUT                 381
#define IDD_DLG_SELECTSCENE             382
#define IDR_MENU_SCRIPT                 383
#define IDD_DLG_INSERTEVENTHANDLER      384
#define IDR_RIBBON_HOME                 386
#define IDB_TEMPLATE_EXPLORER_TOOLBAR   389
#define IDR_MENU_TEMPLATE_EXPLORER      390
#define IDB_TEMPLATE_EXPLORER_REPORT    393
#define IDB_TEMPLATE_EXPLORER_ICON      397
#define IDR_POPUP_SUBSET                398
#define IDI_ICON_SUBSET                 399
#define IDD_DLG_SUBSET_SPEC             400
#define IDR_NATION                      401
#define IDD_DLG_PROGRESS                402
#define IDI_ICON_PROGRESS_IMAGE         403
#define IDI_ICON_PROGRESS_IMAGE_SEL     404
#define IDI_ICON_PROGRESS_SPLIT_SEL     405
#define IDI_ICON_PROGRESS_SPLIT         406
#define IDB_BITMAP2                     418
#define IDC_CB_SELMETA_TEMPLATE         1000
#define IDC_ST_COLORKEY                 1001
#define IDC_EDIT1                       1002
#define IDC_ED_GOTOLINE                 1002
#define IDC_EDIT_SHAPEINFO_STRING       1002
#define IDC_EDIT_POS_LEFT               1002
#define IDC_EDIT_COLUMN_COUNT           1002
#define IDC_ED_MODULENAME               1002
#define IDC_ED_IEH_DESC                 1002
#define IDC_ED_SEARCH                   1002
#define IDC_UVLEFT                      1002
#define IDC_ED_PATH                     1002
#define IDC_TEMPLATE_LIST               1003
#define IDC_EDIT_SHAPEINFO_WIDTH        1003
#define IDC_UVTOP                       1003
#define IDC_ED_FILE                     1003
#define IDC_BTN_ADD                     1004
#define IDC_EDIT_SHAPEINFO_POSX         1004
#define IDC_UVRIGHT                     1004
#define IDC_ED_SIZE                     1004
#define IDC_EDIT_SHAPEINFO_STRING4      1005
#define IDC_EDIT_SHAPEINFO_HEIGHT       1005
#define IDC_UVBOTTOM                    1005
#define IDC_ST_GOTOLINE                 1006
#define IDC_EDIT_SHAPEINFO_POSY         1006
#define IDC_COMBO1                      1007
#define IDC_CHECK1                      1008
#define IDC_CHECK2                      1009
#define IDC_CHECK3                      1010
#define IDC_EDIT_POS_TOP                1011
#define IDC_EDIT_MARGIN_VALUE           1012
#define IDC_CHK_MODULERUN_ENABLE        1013
#define IDC_RADIO1                      1014
#define IDC_RADIO2                      1015
#define IDC_LB_IEH_CLASSES              1015
#define IDC_RADIO3                      1016
#define IDC_TAB_IEH_CATEGORY            1016
#define IDC_LB_IEH_HANDLERS             1017
#define IDC_LV_SCENELIST                1018
#define IDC_TREE1                       1019
#define IDC_TREE                        1019
#define IDC_SCROLLBAR1                  1027
#define IDC_BTN_DELETE_TEXTURE          1028
#define IDC_BTN_SELECT_ADJUST_TEXTURE   1029
#define IDC_BUTTON1                     1030
#define IDC_BTN_SELECT_ADJUST_VTEXLIST  1030
#define IDC_BTN_CHANGE_FORMAT           1031
#define IDC_PROGRESS1                   1032
#define IDC_BTN_COPY_N_RELOAD_VTEXINFO  1032
#define IDC_EDIT_SHAPE_COUNT            1033
#define IDC_ADJUST_PROGRESS             1033
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_SCR_RES_800X600              32771
#define ID_SCR_RES_1024X768             32772
#define ID_SCR_RES_1280X800             32773
#define ID_SCR_RES_1280X1024            32774
#define ID_SCR_RES_1600X1080            32775
#define ID_SCR_RES_1920X1080            32776
#define ID_SCR_RES_1920X1200            32777
#define ID_TEMPLATE_NEW_FILTER          32778
#define ID_TEMPLATE_NEW_TEMPLATE        32779
#define ID_TEMPLATE_COPY                32780
#define ID_TEMPLATE_CUT                 32781
#define ID_TEMPLATE_PASTE               32782
#define ID_TEMPLATE_RENAME              32783
#define ID_TEMPLATE_COLLAPSE            32784
#define ID_TEMPLATE_EXPAND              32785
#define ID_TEMPLATE_SELECTALL           32786
#define ID_TEMPLATE_UNSELECTALL         32787
#define ID__ADDCONTROL                  32788
#define ID__REMOVECONTROL               32789
#define ID__RENAME                      32790
#define ID_SCREEN_NEWCTRL               32791
#define ID_SCREEN_DELCTRL               32792
#define ID_SCREEN_RENCTRL               32793
#define ID_VIEW_SELECTTEXTURE           32794
#define ID_PROJECT_WORKINGFOLDER        32795
#define ID_PROJECT_ADJUSTVIRTUALTEXTURE 32796
#define ID_PROJECT_IMPORTTEMPLATELIBRARY 32797
#define ID_PROJECT_EXPORTTEMPLATELIBRARY 32798
#define ID_PROJECT_SELECTSCREENRESOLUTION 32799
#define ID_PROJECT_SCREENEDITMODE       32800
#define ID_PROJECT_TEMPLATEEDITMODE     32801
#define ID_PROJECT_PREVIEWMODE          32802
#define ID_SELECTED_EDIT                32803
#define ID_TEMPLATE_EDIT                32804
#define ID_VIEWOPTION_RCHANNEL          32805
#define ID_VIEWOPTION_GCHANNEL          32806
#define ID_VIEWOPTION_BCHANNEL          32807
#define ID_VIEWOPTION_RGBCHANNEL        32808
#define ID_VIEWOPTION_RGBACHANNEL       32809
#define ID_VIEWOPTION_A                 32810
#define ID_VIEWOPTION_R                 32811
#define ID_VIEWOPTION_G                 32812
#define ID_VIEWOPTION_B                 32813
#define ID_VIEWOPTION_RGB               32814
#define ID_VIEWOPTION_RGBA              32815
#define ID_VIEW_SELECTUV                32816
#define ID_PROJECT_CREATEVIRTUALTEXTURE 32817
#define ID_PROJECT_O                    32818
#define ID_PROJECT_OPENVIRTUALTEXTURE   32819
#define ID_PROJECT_SAVETEMPLATELIBRARY  32820
#define ID_TEMPLATE_ADDANEWTEMPLATE     32821
#define ID_TEMPLATE_ADD_TEMPLATE_START  32822
#define IDC_SHAPE_LIST                  32824
#define ID_TEMPLATE_ADD_TEMPLATE_END    33822
#define ID_DEBUG_DUMPVIRTUALTEXTURE     33823
#define ID_DEBUG_TEXTURELIST            33824
#define ID_PROJECT_RUN                  33824
#define ID_PROJECT_STOP                 33825
#define ID_VIEW_SPREADLAYOUT            33826
#define ID_VIEW_ADJUSTLAYOUT            33827
#define ID__SETSCRIPT                   33828
#define ID__EDITSCRIPT                  33829
#define ID_SCREEN_SETSCRIPT             33830
#define ID_EDIT_SCRIPT                  33831
#define ID_SCREEN_EDITSCRIPT            33832
#define ID_PROJECT_COMPILESCRIPT        33834
#define ID_PROJECT_SAVESCRIPT           33835
#define ID_VIEW_SCRIPT_PANE             33838
#define ID_VIEW_SCREEN_PANE             33839
#define ID_VIEW_TEMPLATEPANE            33840
#define ID_VIEW_TIMELINEPANE            33841
#define ID_VIEW_PROPERTIESPANE          33842
#define ID_VIEW_TEMPLATE_PANE           33843
#define ID_VIEW_TIMELINE_PANE           33844
#define ID_VIEW_PROPERTIES_PANE         33845
#define ID__REMOVESCRIPT                33846
#define ID_SCREEN_REMOVESCRIPT          33847
#define ID_SHAPELIST_ADDSHAPE           33848
#define ID_SHAPELIST_REMOVESHAPE        33849
#define ID_SHAPELIST_EDITSHAPEINFO      33850
#define ID_SELECTED_DELETE              33851
#define ID_VIEW_SELECTALLSHAPES         33852
#define ID_SHAPELIST_MAKECLONE          33853
#define ID_VIEW_ALIGNLEFTTOP            33854
#define ID_VIEW_SPREAD                  33855
#define ID_VIEW_SPREADCONTROL           33856
#define ID_VIEW_LEFTALIGN               33857
#define ID_VIEW_RIGHTALIGN              33858
#define ID_VIEW_TOPALIGN                33859
#define ID_VIEW_ALIGNBOTTOM             33860
#define ID_OPTION_EDITOROPTION          33861
#define ID_SELECTED_EDITSCRIPT          33862
#define ID_TEMPLATE_EDITSCRIPT          33863
#define ID_SELECTED_SETSCRIPT           33864
#define ID_SELECTED_SCRIPT              33865
#define ID_TEMPLATE_SETSCRIPT           33866
#define ID__CLEARALL                    33867
#define ID__TEST                        33868
#define ID_SCRIPT_REMOVESCRIPT          33869
#define ID_TEMPLATE_REMOVESCRIPT        33870
#define ID_SCRIPT_TESTSCRIPT            33871
#define ID__INSERTEVENTHANDLER          33872
#define ID__FIND                        33873
#define ID__GOTOLINE                    33874
#define ID__INSERTEVENTHANDLER33875     33875
#define ID__SCREEN_IEH                  33876
#define ID__COPY                        33877
#define ID__CUT                         33878
#define ID__PASTE                       33879
#define ID_PROJECT_SELECTSCENEFROMCLIENT 33880
#define ID_B_INSERTEVENTHANDLER         33881
#define ID_EDIT_COPY33882               33882
#define ID_EDIT_CUT33883                33883
#define ID_EDIT_PASTE33884              33884
#define ID_EDIT_UNDO33885               33885
#define ID_EDIT_REDO33886               33886
#define ID_EDIT_ALIGNLEFT               33887
#define ID_EDIT_ALIGNRIGHT              33888
#define ID_EDIT_ALIGNTOP                33889
#define ID_EDIT_ALIGNBOTTOM             33890
#define ID_EDIT_RELOCATIONHORZ          33891
#define ID_EDIT_RELOCATIONVERT          33892
#define ID_EDIT_SAMEWIDTH               33893
#define ID_EDIT_SAMEHEIGHT              33894
#define ID_EDIT_SNAPSIZE                33897
#define ID_C_SELECTALL                  33898
#define ID_BUTTON33899                  33899
#define ID_LISTVIEW_NEWFILTER           33900
#define ID_LISTVIEW_NEWTEMPLATE         33901
#define ID_LISTVIEW_VIEW                33902
#define ID_VIEW_TREEVIEW                33903
#define ID_VIEW_ICONVIEW                33904
#define ID_VIEW_REPORTVIEW              33905
#define ID_LISTVIEW_EDIT                33906
#define ID_LISTVIEW_EDITSCRIPT          33907
#define ID_LISTVIEW_DELETE              33908
#define ID_LISTVIEW_COPY                33909
#define ID_LISTVIEW_CUT                 33910
#define ID_LISTVIEW_PASTE               33911
#define ID_VIEW_REPORTVIEW33912         33912
#define ID_LISTVIEW_COPY33913           33913
#define ID_LISTVIEW_PASTE33914          33914
#define ID_LISTVIEW_PASTE33915          33915
#define ID_LISTVIEW_DELETE33916         33916
#define ID_SINGLESELECT_INSERTEVENTHANDLER 33921
#define ID_SINGLESELECT_COPY            33922
#define ID_SINGLESELECT_PASTE           33923
#define ID_SINGLESELECT_CUT             33924
#define ID_SINGLESELECT_SELECTALL       33925
#define ID_VIEW_INSERTEVENTHANDLER      33926
#define ID_VIEW_COPY                    33927
#define ID_VIEW_CUT                     33928
#define ID_VIEW_PASTE                   33929
#define ID_VIEW_SELECTALL               33930
#define ID_NONESELECT_SELECTALL         33931
#define ID_MULTIPLESELECT_COPY          33932
#define ID_MULTIPLESELECT_CUT           33933
#define ID_MULTIPLESELECT_PASTE         33934
#define ID_MULTIPLESELECT_DELETE        33935
#define ID_VIEW_DELETE                  33936
#define ID_SINGLESELECT_DELETE          33937
#define ID_MULTIPLESELECT_SELECTALL     33938
#define ID_NONESELECT_COPY              33939
#define ID_NONESELECT_CUT               33940
#define ID_NONESELECT_PASTE             33941
#define ID_NONESELECT_DELETE            33942
#define ID_PROJECT_MODIFYVIRTUALTEXTURE 33943
#define ID__MOVEUP                      33944
#define ID_Menu                         33945
#define ID__MODE_DOWN                   33946
#define ID_MODE_DOWN                    33947
#define ID_MOVE_DOWN                    33948
#define ID_MOVEUP                       33949
#define ID_MOVEDOWN                     33950
#define ID_SINGLESELECT_MOVEUP          33951
#define ID_SINGLESELECT_MOVEDOWN        33952
#define ID__VIEWTEMPLATE                33953
#define ID_SINGLESELECT_VIEWTEMPLATE    33954
#define ID__INSERTUISCENE               33955
#define ID__EXPORTUISCENE               33956
#define ID__IMPORTUISCENE               33957
#define ID_FILE_EXPORT                  33958
#define ID_Menu33959                    33959
#define ID_LISTVIEW_REMOVESCRIPT        33960
#define ID_LISTVIEW_SETSCRIPT           33961
#define ID_FILE_EXPORTLIBRARY           33962
#define ID_SUBSET_NEWSUBSET             33963
#define ID_SUBSET_DELETESUBSETS         33964
#define ID_SUBSET_PROPERTY              33965
#define ID_PROJECT_EXTRACTREFTEXTURE    33966
#define ID_PROJECT_NATION               33967
#define ID_EDIT_ALIGNCENTER             33980
#define ID_VIEW_CENTERALIGN             33981
#define ID_LISTVIEW_EXPORTTEMPLATE      34000
#define ID_DEBUG_EXPORTALL              34001
#define ID_CLEARCOLOR                   34002
#define ID_SHAPELIST_SELECTTEXTURE      34003
#define ID_SHAPELIST_SELECTUV           34004
#define ID__LISTBOXONOFF                34009
#define ID_LISTBOXONOFF                 34010
#define ID__LISTBOXDUMMYLINE            34011
#define ID_LISTBOXDUMMYLINE             34012
#define ID_SINGLESELECT_LISTBOXDUMMYLINE 34013
#define ID_SINGLESELECT_LISTBOXONOFF    34014
#define ID_PROJECT_CREATEVTEXLIST       34015
#define ID_PROJECT_ADJUSTVTEXLIST       34016
#define ID_PROJECT_SAVETEMPLATELIBRARY_NEW 34017
#define ID_LANGUAGE_DEV                 35001
#define ID_LANGUAGE_MIDDLEEAST          35002
#define ID_LANGUAGE_THAILAND            35003
#define ID_LANGUAGE_ENGLISH             35004
#define ID_LANGUAGE_PHILIPPINES         35005
#define ID_LANGUAGE_SINGMAL             35006
#define ID_LANGUAGE_NORTHAMERICA        35007
#define ID_LANGUAGE_INDONESIA           35008
#define ID_LANGUAGE_ITALY               35009
#define ID_LANGUAGE_KOREAN              35010
#define ID_LANGUAGE_BRAZIL              35011
#define ID_LANGUAGE_RUSSIA              35012
#define ID_LANGUAGE_LATINAMERICA        35013
#define ID_LANGUAGE_THAIWAN             35014
#define ID_LANGUAGE_TURKY               35015
#define ID_LANGUAGE_VIETNAM             35016
#define ID_LANGUAGE_ARABIC              35017
#define ID_LANGUAGE_CHINA               35018
#define ID_LANGUAGE_SPANISH             35019
#define ID_LANGUAGE_TAIWAN              35020
#define ID_LANGUAGE_JAPAN               35021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        420
#define _APS_NEXT_COMMAND_VALUE         34018
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           342
#endif
#endif
