//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AvatarViewer.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_PART_PROP_PART              101
#define IDS_PART_PROP_SCALE             102
#define IDS_PART_PROP_TRANS             103
#define IDS_PART_PROP_PART_TYPE         104
#define IDS_PART_PROP_PART_NAME         105
#define IDS_PART_PROP_PART_TYPE_DETAIL  106
#define IDS_PART_PROP_PART_NAME_DETAIL  107
#define IDS_PART_PROP_PART_DEFAULT      108
#define IDS_PART_PROP_X                 109
#define IDB_WRITESMALL                  110
#define IDS_PART_PROP_Y                 110
#define IDB_WRITELARGE                  111
#define IDS_PART_PROP_Z                 111
#define IDB_MAIN                        112
#define IDS_PART_PROP_A                 112
#define IDB_BUTTONS                     113
#define IDS_PART_PROP_SCALE_X_DETAIL    113
#define IDB_FILELARGE                   114
#define IDS_PART_PROP_SCALE_Y_DETAIL    114
#define IDB_FILESMALL                   115
#define IDS_PART_PROP_SCALE_Z_DETAIL    115
#define IDS_PART_PROP_TRANS_X_DETAIL    116
#define IDS_PART_PROP_TRANS_Y_DETAIL    117
#define IDS_PART_PROP_TRANS_Z_DETAIL    118
#define IDR_POPUP_EDIT                  119
#define IDS_PART_PROP_SCALE_A_DETAIL    119
#define ID_STATUSBAR_PANE1              120
#define IDS_PART_PROP_PART_MASK         120
#define ID_STATUSBAR_PANE2              121
#define IDS_PART_PROP_PART_MASK_DETAIL  121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_AvatarViewerTYPE            130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EDIT_MENU                   306
#define ID_PANEL_ASSET                  310
#define IDB_ICONS_24                    310
#define ID_PANEL_AVATAR                 311
#define IDB_ICONS_32                    311
#define ID_PANEL_ANIM                   312
#define IDD_PANEL_AVATAR                312
#define ID_PANEL_SG                     313
#define IDD_DIALOG1                     313
#define IDD_DLG_SETPOSSCALE             313
#define ID_PANEL_PART                   314
#define IDD_PANEL_ANIMATION             315
#define IDD_DLG_SELECTBODY              316
#define IDD_PANEL_CAMERASET             317
#define IDC_TREE                        1000
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_TREE_ANIMATION              1002
#define IDC_EDIT3                       1003
#define IDC_CMB_BODYLISt                1003
#define IDC_EDIT4                       1004
#define IDC_ADD_LIST                    1004
#define IDC_INCLUDE_LIST                1004
#define IDC_EXCLUDE_LIST                1005
#define IDC_EDIT5                       1005
#define IDC_ED_CAM_RHO                  1005
#define IDC_BTN_ADD                     1006
#define IDC_BTN_REMOVE                  1007
#define IDC_ED_CAM_POS_X                1007
#define IDC_ED_CAM_POS_Y                1008
#define IDC_ED_CAM_POS_Z                1009
#define IDC_ED_CAM_THETA                1010
#define IDC_EDIT_FOV                    1011
#define IDC_BUTTON1                     1012
#define IDC_BTN_CAM_APPLY               1012
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_VIEW_GRID                    32771
#define ID_OPTIONS_CLEARCOLOR           32772
#define ID_OPTIONS_AMBIENTCOLOR         32773
#define ID_OPTIONS_LIGHTCOLOR           32774
#define ID_OPTIONS_LIGHTINTENSITY       32775
#define ID_VIEW_SHADOW                  32776
#define ID_OPTIONS_SHADOWSIZE           32777
#define ID_OPTIONS_REFLECTMAP           32778
#define ID_TOOLS_GEOMETRY               32779
#define ID_TOOLS_TEXTURES               32780
#define ID_TOOLS_PROJECTCONFIG          32781
#define ID_VIEW_ASSET                   32782
#define ID_VIEW_AVATAR                  32783
#define ID_VIEW_ANIM                    32784
#define ID_FILE_SAVE32785               32785
#define ID_FILE_SAVEAS                  32786
#define ID_OPTIONS_LOD                  32787
#define ID_EDIT_SETPOSITIONSCALE        32788
#define ID_VIEW_PART                    32789
#define ID_COLOR_BLUE_TEAM              32791
#define ID_COLOR_RED_TEAM               32792
#define ID_MAKE_SAVEMERGEDTEXTURE       32793
#define ID_COLOR_OFF                    32794
#define ID_ATTACHMENT_ATTACHRIGHTHAND   32795
#define ID_ATTACHMENT_ATTACHBACKPACK    32796
#define ID_MAKE_CONVERTSGBYMACROTEXTURE 32797
#define ID_MAKE_CONVERTBLENDINDEX       32798
#define ID_ATTACHMENT_WEAPONLIST        32799
#define ID_CAMERA_SET                   32800
#define ID_CAMERA_SAVE                  32801
#define ID_CAMERA_LOAD                  32802
#define ID_CAMERA_2                     32803
#define ID_CAMERA_1PV                   32804
#define ID_OPTIONS_LIGHTVERTICAL	    32805
#define ID_OPTIONS_LIGHTHORIZON			32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
