#ifndef INNOVA_BILLING_ERRORS_H
#define INNOVA_BILLING_ERRORS_H

namespace innbill {

enum error_codes
{
    INTEGRATION_API_DB_NOT_IMPLEMENTED = -1,

    INTEGRATION_API_DB_SUCCESS = 0,

    ///@ DB LIB ERRORS
    INTEGRATION_API_DB_CONNECTION_FAILED = 100,
    INTEGRATION_API_DB_STATEMENT_FAILED = 101,
    INTEGRATION_API_DB_EXECUTE_FAILED = 102,
    INTEGRATION_API_DB_FETCH_FAILED = 103,
    INTEGRATION_API_DB_ALREADY_CONNECTED = 104,
    INTEGRATION_API_DB_NOT_INITIALIZED = 105,

    ///@ NETWORK ERRORS
    INTEGRATION_API_DB_SOCKET_FAILED = 200,
    INTEGRATION_API_DB_BIND_FAILED = 201,
    INTEGRATION_API_DB_CONNECT_FAILED = 202,
    INTEGRATION_API_DB_LISTEN_FAILED = 203,
    INTEGRATION_API_DB_SET_SOCKET_OPTION_FAILED = 204,
    INTEGRATION_API_DB_RECV_FAILED = 205,
    INTEGRATION_API_DB_SEND_FAILED = 206,
    INTEGRATION_API_DB_ACCEPT_FAILED = 207,
    INTEGRATION_API_INIT_WINSOCK_FAILED = 208,
    INTEGRATION_API_UNKNOWN_HOST = 209,
    INTEGRATION_API_HTTP_PARS_ANSWER_FAILED = 210,
    INTEGRATION_API_HTTP_RECV_HEADER_FAILED = 211,
    INTEGRATION_API_HTTP_PARS_NAME_FAILED = 212,
    INTEGRATION_API_HTTP_PARS_VALUE_FAILED = 213,

    
    ///@ CONFIGURATION FILE ERROR
    INTEGRATION_API_FILE_NOT_FOUND = 300,
    INTEGRATION_API_FILE_OPEN_FAILED = 301,
    INTEGRATION_API_FILE_HAS_INVALID_FORMAT = 302,
    INTEGRATION_API_MISSED_PARAMETER = 303,
    INTEGRATION_API_PARAMETER_HAS_INVALID_VALUE = 304,
    INTEGRATION_API_NULL_FETCHED = 305,

    ///@ PRORAMM ERRORS
    INTEGRATION_API_INVALID_LOGIN = 400,
    INTEGRATION_API_INVALID_PASSWORD = 401,
    INTEGRATION_API_INVALID_USER_ID = 402,
    INTEGRATION_API_INVALID_INPUT_ARG = 403,

    INTEGRATION_API_INVALID_INTEGER = 404,
    INTEGRATION_API_SYBC_OBJ_ERROR = 405,
    INTEGRATION_API_INVALID_DOUBLE = 406,

    /// integration service errors
    INTEGRATION_API_SERVICE_INTERNAL_ERROR = 407,
    INTEGRATION_API_SERVICE_NO_ACCESS = 408,
    INTEGRATION_API_SERVICE_NO_SERVICE = 409,
    INTEGRATION_API_SERVICE_INVALID_TICKET = 410,
    INTEGRATION_API_SERVICE_NO_ITEM = 411,
    INTEGRATION_API_SERVICE_REG_QUEUE = 412,
    INTEGRATION_API_SERVICE_ACCOUNT_DELETED = 413,
    INTEGRATION_API_SERVICE_INVALID_RECOVERY_CODE = 414,
    INTEGRATION_API_SERVICE_LOGIN_IN_USE = 415,
    INTEGRATION_API_SERVICE_NICKNAME_IN_USE = 416,
    INTEGRATION_API_SERVICE_EMAIL_IN_USE = 417,
    INTEGRATION_API_SERVICE_NO_EMAIL_OR_CONFIRM_CODE = 418,
    INTEGRATION_API_SERVICE_EMAIL_CONFIRMED_ALREADY = 419,
    INTEGRATION_API_SERVICE_INVALID_REG_CODE = 420,
    INTEGRATION_API_SERVICE_RECOVERY_TYPE_UNAVAIABLE = 421,
    INTEGRATION_API_SERVICE_CONTACT_FIELD_NOT_CONFIRMED = 422,
    INTEGRATION_API_SERVICE_NOT_ENOUGH_FUNDS = 423,
    INTEGRATION_API_SERVICE_NOT_CANCEL_SALE = 424,
    INTEGRATION_API_SERVICE_DATA_NOT_FOUND_IN_CANCEL_SALE = 425,
    INTEGRATION_API_SERVICE_NO_SUCH_PARTNER = 426,
    INTEGRATION_API_SERVICE_CUSTOM_PASSWORD_REQUIRED = 427,
    INTEGRATION_API_SERVICE_ACCOUNT_BANNED = 428,
    INTEGRATION_API_SERVICE_ACCOUNT_FROZEN = 429,
    INTEGRATION_API_SERVICE_ACCOUNT_BLOCKED = 430,
    INTEGRATION_API_SERVICE_CONTACT_IS_BANNED = 431,
    INTEGRATION_API_SERVICE_CONFIRM_CODE_IS_NOT_VALID = 432,
    INTEGRATION_API_SERVICE_CANT_SEND_NOTIFICATION = 433,
    INTEGRATION_API_SERVICE_EXT_PROD_ID_DUPLICATED = 434,
    INTEGRATION_API_SERVICE_PROD_UPDATE_PROHIBITED = 435,
    INTEGRATION_API_SERVICE_BONUS_ALREADY_ADDED = 436,
    INTEGRATION_API_SERVICE_AUTH_TICKET_EXPIRED = 437,
    INTEGRATION_API_SERVICE_AUTH_TICKET_INVALID_VERSION = 438,
    INTEGRATION_API_SERVICE_AUTH_TICKET_EXP_TIME_EXCEED = 439,
    INTEGRATION_API_SERVICE_USER_HAS_NO_REQ_ROLES = 440,
    INTEGRATION_API_SERVICE_CANT_RESOLVE_SERVICE_ACCOUNT_ID = 441,
    INTEGRATION_API_SERVICE_PHONE_LINK_FORBIDDEN = 442,

    // errors for buy_item
    INTEGRATION_API_UNSUCCESSFUL_SALE = 500,
    INTEGRATION_API_OPERATION_BLOCKED_BY_DB = 501,
    INTEGRATION_API_INCORRECT_PRICE = 502,

    INTEGRATION_API_DB_UNKNOWN_ERROR = 1000
};

}

#endif //INNOVA_BILLING_ERRORS_H

