//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by i3CharaEditor.rc
//
#define IDOK1                           1
#define IDOK2                           2
#define IDOK3                           3
#define IDOK4                           4
#define IDOK5                           5
#define IDOK6                           6
#define IDOK7                           7
#define IDOK8                           8
#define IDOK9                           9
#define IDOK11                          10
#define IDOK10                          12
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_RSC_NEWAI                    101
#define ID_RSC_ADDLOD                   102
#define ID_RSC_LOD_MOVEUP               103
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_RSC_LOD_MOVEDOWN             104
#define ID_RSC_LOD_SORT                 105
#define ID_RSC_AI_EXPORT                106
#define ID_RSC_AI_IMPORT                107
#define ID_RSC_OPTIMIZEANIM             108
#define ID_RSC_ANIMPACK                 109
#define ID_RSC_RENAMEFOLDER             110
#define ID_RSC_ADDAISTATETOCHILDS       111
#define IDR_HTML_DLGAIANI               112
#define ID_RSC_AI_DUMP                  119
#define IDR_MAINFRAME                   128
#define IDR_i3CharaEditorTYPE           129
#define IDD_PANEL_RESOURCE              130
#define IDD_PANEL_SCENEGRAPH            131
#define IDD_PANEL_AI_GRAPH              132
#define IDD_PANEL_SPEC                  133
#define IDD_PANEL_TIMETRACK             134
#define IDD_PANEL_LUA                   135
#define IDD_PANEL_LOG                   136
#define IDD_PANEL_RENDER                137
#define IDD_DLG_OPTION                  139
#define IDR_POPUP_RSC                   140
#define IDD_SPEC_AI                     141
#define IDI_CREATEAI                    143
#define IDI_CREATENEXT                  144
#define IDD_SPEC_AISTATE                145
#define IDD_DLG_SELECTSOUND             147
#define IDD_SPEC_LOD                    148
#define IDD_SPEC_CHARA                  149
#define IDD_SPEC_ANIM                   150
#define IDR_POPUP_AIDRAG                152
#define IDD_DLG_EXPORT                  153
#define IDD_SPEC_SOUNDNODE              154
#define IDD_DIALOG1                     155
#define IDD_DLG_RENAMEFOLDER            155
#define IDD_DLG_ADDAISTATE_CHILDS       156
#define IDD_MERGE_1PV_3PV               157
#define IDD_DLG_REPLACE                 159
#define IDD_DLG_REFRESCPY               160
#define IDD_DLG_DUMP_ANIMATIONLIST      163
#define IDD_NOGADA_MASK                 170
#define IDD_NOGADA_AISTATE              171
#define IDB_AISTATE_STATEIMG            181
#define IDD_ANIPACKFILE_PROGRESS        191
#define IDD_DLG_AIANI                   193
#define IDD_DLG_AIANI_V1_PRESET         197
#define IDC_RSC_TREE                    1000
#define IDC_LIST_LOG                    1001
#define IDC_LIST2                       1002
#define IDC_EDIT1                       1003
#define IDC_BTN_WORKPATH                1004
#define IDC_ED_BONECOUNT                1004
#define IDC_ED_CONST                    1004
#define IDC_ED_DEST                     1004
#define IDC_EDIT4                       1004
#define IDC_ED_MAXDIST                  1004
#define IDC_ED_NAME                     1005
#define IDC_CHK_ENABLE                  1006
#define IDC_CB_INITSTATE                1007
#define IDC_CHK_ENABLE2                 1007
#define IDC_CHK_ENABLE3                 1008
#define IDC_BTN_SELMODE                 1009
#define IDI_SELMODE                     1009
#define IDC_BTN_CREATEAI                1010
#define IDC_BTN_CREATENEXT              1011
#define IDC_CHK_TERM_WITHANIM           1012
#define IDC_CHK_TERM_TIME               1013
#define IDC_CB_ANIM                     1015
#define IDC_ED_ID                       1016
#define IDC_ED_RUN_SCRIPT               1017
#define IDC_ED_FINISH_SCRIPT            1018
#define IDC_CB_NEXTSTATE                1019
#define IDC_ED_TIMELENGTH               1020
#define IDC_CB_AISTATE                  1021
#define IDC_ED_BLEND                    1022
#define IDC_CB_BLENDTYPE                1023
#define IDC_CHK_ANIM_LOOP               1024
#define IDC_SOUND_LIST                  1025
#define IDC_CB_SG                       1026
#define IDC_ED_TRICOUNT                 1027
#define IDC_ED_SLOPE                    1028
#define IDC_ED_TRACKCOUNT               1029
#define IDC_ED_DURATION                 1030
#define IDC_TRACKLIST                   1031
#define IDC_ED_SRCTEXT                  1032
#define IDC_ED_COMMENTTEXT              1033
#define IDC_CB_FILTER                   1034
#define IDC_CHK_VIEWPATH                1035
#define IDC_CHK_I3S                     1036
#define IDC_CHK_I3CHR                   1037
#define IDC_CHK_GENC                    1038
#define IDC_ED_DRIVERMETA               1039
#define IDC_CHK_ROTATEAXIS              1040
#define IDC_CHK_LOOP                    1041
#define IDC_ED_LOOPCOUNT                1042
#define IDC_CHK_POSITIONAL              1043
#define IDC_ED_PRIORITY                 1044
#define IDC_SLIDER_VOL                  1045
#define IDC_CHK_OPTIMIZE_GENMIPMAP      1046
#define IDC_CHK_OPTIMIZE_DXT            1047
#define IDC_EDIT_SOUNDNODE_NAME         1048
#define IDC_CHK_CAST_SHADOW             1049
#define IDC_CHECK_REMOVE_SAMEIMAGE      1050
#define IDC_CHK_OPTIMIZE_DXT_ALPHA      1051
#define IDC_CHK_ADDCHILDS_LOOP          1052
#define IDC_CHK_ONLYNAME                1053
#define IDC_EDIT_FOLDER_RENAME          1054
#define IDC_EDIT_FOLDER_FILTER          1055
#define IDC_CHK_EXTERN_I3I              1056
#define IDC_CHK_OPTIMIZE_ANIM           1057
#define IDC_CHK_GEN_ANIMPACK            1058
#define IDC_ED_ADDCHILDS_BLENDTIME      1059
#define IDC_COMBO_ADDCHILDS_ANIMNAME    1060
#define IDC_EDIT3                       1061
#define IDC_EDIT_ADDCHILDS_FILTER       1062
#define IDC_ED_ADDCHILDS_NAME           1063
#define IDC_CHK_MUTEATMAX               1064
#define IDC_CHK_MUTEATMAX2              1065
#define IDC_CHK_STOP_ON_RESET           1066
#define IDC_BTN_SAVE                    1067
#define IDC_ED_ANIMNAME                 1068
#define IDC_ED_CHARAS                   1069
#define IDC_BTN_CHECK_TEMPLATE          1070
#define IDC_BTN_ADJUST                  1071
#define IDC_BTN_REPLACE                 1072
#define IDC_ED_SRC                      1073
#define IDC_ED_I3SNAME                  1074
#define IDC_GROUP_ADDCHILDS_POSITION    1075
#define IDC_RADIO_ADDCHILDS_POS_AUTO    1076
#define IDC_RADIO_ADDCHILDS_POS_BOTTOM  1077
#define IDC_RADIO_ADDCHILDS_POS_RIGHT   1078
#define IDC_CHK_USE_OWN_PATH            1079
#define IDC_ED_ADDCHILD_ROOTNODE        1080
#define IDC_REFRESCPY_EB_FILE           1081
#define IDC_ED_MINDIST                  1082
#define IDC_REFRESCPY_EB_COPYTO         1083
#define IDC_IDC_REFRESCPY_LB_COPYLOG    1084
#define IDC_REFRESCPY_BT_COPY           1085
#define IDC_REFRESCPY_EB_WORKDIR        1086
#define IDC_AUTOMAT_OPERHERO_ACIDPOL    1110
#define IDC_AUTOMAT_OPERHERO_BELLA      1111
#define IDC_AUTOMAT_OPERHERO_CHOU       1112
#define IDC_AUTOMAT_OPERHERO_DFOX       1113
#define IDC_AUTOMAT_OPERHERO_HIDE       1114
#define IDC_AUTOMAT_OPERHERO_KEENEYES   1115
#define IDC_AUTOMAT_OPERHERO_LEOPARD    1116
#define IDC_AUTOMAT_OPERHERO_REDBULLS   1117
#define IDC_AUTOMAT_OPERHERO_TARANTULA  1118
#define IDC_AUTOMAT_OPERHERO_VIPERRED   1119
#define IDC_AUTOMAT_OPERHERO_CHECK_ALL  1130
#define IDC_AUTOMAT_OPERHERO_UNCHECKALL 1131
#define IDC_AUTOMAT_EB_WORKDIR          1140
#define IDC_AUTOMAT_LB_LOG              1141
#define IDC_AUTOMAT_BT_SAVELOG          1142
#define IDC_AUTOMAT_MASK_BT_GO          1151
#define IDC_AUTOMAT_MASK_ST_DROPMASKDIR 1152
#define IDC_AUTOMAT_MASK_IMPL_DROPMASKDIR 1153
#define IDC_AUTOMAT_MASK_LB_PATH        1154
#define IDC_AUTOMAT_MASK_EB_PATH        1155
#define IDC_AUTOMAT_MASK_BT_ADD         1156
#define IDC_AUTOMAT_MASK_BT_DEL         1157
#define IDC_AUTOMAT_MASK_BT_RESET       1158
#define IDC_AUTOMAT_MASK_BT_LODFILENAME_EVAL 1161
#define IDC_AUTOMAT_MASK_BT_LODFILENAME_PRESET 1162
#define IDC_AUTOMAT_MASK_EB_LODFILENAMEPAT 1163
#define IDC_AUTOMAT_MASK_ST_LODFILENAME_EVAL 1164
#define IDC_BUTTON1                     1170
#define IDC_EDIT_DUMP_ANIM_PATH         1171
#define IDC_AIANI_V1P_BT_UNSET          1171
#define IDC_EDIT2                       1172
#define IDC_AIED_ST_AREA_AISTATE        1180
#define IDC_AIED_LV_AISTATE             1181
#define IDC_AIED_BT_FIND_UPPER_WEAPON_BY_NAME 1182
#define IDC_AIED_EB_FIND_UPPER_WEAPON_NAME 1183
#define IDC_AIED_CB_UPPER_WEAPON_NAME   1184
#define IDC_AIED_CB_UPPER_WEAPON_CLASS  1185
#define IDC_AIED_BT_RESCAN_WEAPON_CLASSANDNAME 1186
#define IDC_AIED_BT_QUERY_UPPER_WEAPON  1187
#define IDC_I3ANIPAKPG_PB_PHASE         1300
#define IDC_I3ANIPAKPG_ST_PHASE_REMAIN  1301
#define IDC_I3ANIPAKPG_ST_PHASE_DESC    1302
#define IDC_I3ANIPAKPG_PB_TASK          1303
#define IDC_I3ANIPAKPG_ST_TASK_REMAIN   1304
#define IDC_I3ANIPAKPG_ST_TASK_DESC     1305
#define IDC_ED_PATH_1                   1312
#define IDC_ED_PATH_2                   1313
#define IDC_EXCEPT_LIST                 1314
#define IDC_ED_PATH_3                   1315
#define IDC_ED_PATH_4                   1316
#define IDC_EXCEPT_LIST2                1317
#define IDC_AI_LIST                     1318
#define IDC_AIANI_V1P_LB_PRESET         1319
#define IDC_AIANI_V1P_CB_PRESET         1320
#define IDC_AIANI_BT_INS_FROM_PRESET    1321
#define IDC_AIANI_V1P_BT_SET            1322
#define IDC_AIANI_V1P_ST_WORKPATH       1323
#define IDC_AIANI_LB_LOGMSG             1324
#define ID_FILE_SAVEAS                  32775
#define ID_TOOL_OPTION                  32777
#define ID_RSC_DELETE                   32778
#define ID_FILE_EXPORTI3CHR             32780
#define ID_TRACK_DELETE                 32781
#define ID_AI_MOVE                      32782
#define ID_AI_CREATECLONE               32783
#define ID_AUTOSET_COLLIDEE             32785
#define ID_VIEW_LINERENDER              32787
#define ID_TOOLS_CHECKBONES             32789
#define ID_BUILD_ANIMPACK               32791
#define ID_TOOL_DUMP_AI                 32793
#define ID_32794                        32794
#define ID_CONVERT_ANIM_TEMPLATE        32795
#define ID_MERGE_1PV_3PV                32797
#define ID_TOOL_CHECK_ANIMTEMPLATE      32799
#define ID_COPY_REFERENCED_FILE         32800
#define ID_COPY_REF_FILE                32801
#define ID_TOOL_OUTPUT_SHAREDANIM       32805
#define ID_NOGADA_AISTATE               32810
#define ID_POPUPMENUITEM_NOGADA_MASK    32811
#define ID_POPUPMENUITEM_NOGADA_AISTATE 32812
#define ID_32817                        32817

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1325
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
