#ifndef __SIA_PROTOCOL_H__
#define __SIA_PROTOCOL_H__

enum PROTOCOL_MASK
{
	PROTOCOL_MASK_CONNECT = 0x0001,
	PROTOCOL_MASK_HEARTBIT,

	PROTOCOL_MASK_LOGIN,
	PROTOCOL_MASK_LOGIN_WAIT,

	PROTOCOL_MASK_LOGOUT,

	PROTOCOL_MASK_BUY_GOODS,				// 상품 구입
	PROTOCOL_MASK_GET_CASH,					// 잔액 조회
	PROTOCOL_MASK_USE_GIFTCOUPON,			// 쿠폰 사용

	// 웹젠 연동서버 요청 ( TRANS->SIA )
	PROTOCOL_MASK_PCCAFE_LOGIN_REQ,			// 재로그인
	PROTOCOL_MASK_PCCAFE_CHECK_AMOUNT_REQ,	// 정량확인

	// 웹젠 연동서버 응답 ( SIA->TRANS )
	PROTOCOL_MASK_PCCAFE_SUBTRACTION_ACK,	// 차감알림
	PROTOCOL_MASK_PCCAFE_CONNECT_ACK,		// 컨넥
	PROTOCOL_MASK_PCCAFE_LOGIN_ACK,			// 재로그인결과
	PROTOCOL_MASK_PCCAFE_EMPTY_AMOUNT_ACK,	// 정량소진알림
	PROTOCOL_MASK_PCCAFE_CHECK_AMOUNT_ACK,	// 정량확인결과 알림
	PROTOCOL_MASK_PCCAFE_DISCONNECT_ACK,	// 디스커넥
};

#endif