I3_PRJ_DIR	=	$(I3_WIPI_ROOT)/Project/I3_WIPI
include			$(I3_PRJ_DIR)/Common/makedef

TARGET		=	$(OUTDIR)/libi3SceneUtil.a

OBJS		=	i3SceneUtil.o i3SceneUtilCollision.o

INCS		=	-I$(I3SCENEUTIL_INC)

include			$(I3_PRJ_DIR)/Common/makebase

vpath %.cpp		$(I3SCENEUTIL_SRC)
