#if !defined( __I3_ATTR_ID_H)
#define __I3_ATTR_ID_H

enum I3_ATTRID
{
	I3_ATTRID_ALPHA_FUNC	=	0,		//  0
	I3_ATTRID_ALPHA_TEST_ENABLE,		//  1
	I3_ATTRID_BLEND_ENABLE,				//  2
	I3_ATTRID_BLEND_MODE,				//  3
	I3_ATTRID_CLIPPING_ENABLE,			//  4
	I3_ATTRID_COLOR,					//  5
	I3_ATTRID_FACECULL_MODE,			//  6
	I3_ATTRID_FOG_COLOR,				//  7
	I3_ATTRID_FOG_DENSITY,				//  8
	I3_ATTRID_FOG_ENABLE,				//  9
	I3_ATTRID_FOG_MODE,					// 10
	I3_ATTRID_FOG_NEARFAR,				// 11
	I3_ATTRID_LIGHTING_ENABLE,			// 12
	I3_ATTRID_MATERIAL,					// 13
	I3_ATTRID_RENDER_MODE,				// 14
	I3_ATTRID_SHADE_MODE,				// 15
	I3_ATTRID_STENCIL_FUNC,				// 16
	I3_ATTRID_STENCIL_OPERATION,		// 17
	I3_ATTRID_STENCILTEST_ENABLE,		// 18
	I3_ATTRID_Z_FUNC,					// 19
	I3_ATTRID_Z_TEST_ENABLE,			// 20
	I3_ATTRID_Z_WRITE_ENABLE,			// 21
	I3_ATTRID_Z_BIAS,					// 22
	I3_ATTRID_PROJECT_MATRIX,			// 23
	I3_ATTRID_VIEW_MATRIX,				// 24
	I3_ATTRID_MODEL_VIEW_MATRIX,		// 25
	I3_ATTRID_TEXTURE_ENABLE,			// 26
	I3_ATTRID_TEXTURE_BIND,				// 27
	I3_ATTRID_TEXTURE_FILTER,			// 28
	I3_ATTRID_TEXTURE_WRAP,				// 29
	I3_ATTRID_TEXTURE_FUNCTION,			// 30
	I3_ATTRID_TEXTURE_COORD_SOURCE,		// 31
	I3_ATTRID_TEXTURE_MATRIX,			// 32
	I3_ATTRID_TEXTURE_COORD_SCALE,		// 33
	I3_ATTRID_TEXTURE_COORD_OFFSET,		// 34
	I3_ATTRID_BONEMATRIXLIST,			// 35
	I3_ATTRID_LIGHT,					// 36
	I3_ATTRID_RENDER_ATTR_LIST,			// 37
	I3_ATTRID_GEOMETRY,					// 38
	I3_ATTRID_POINTSPRITE,				// 39
	I3_ATTRID_QUAD,						// 40
	I3_ATTRID_SPRITE,					// 41
	I3_ATTRID_BILLBOARD,				// 42
	I3_ATTRID_RENDERTARGET,				// 43
	I3_ATTRID_CLEARRENDERTARGET,		// 44
	I3_ATTRID_TEXT,						// 45
	I3_ATTRID_GPUCOMMANDLIST,			// 46
	I3_ATTRID_SPRITE2D,					// 47
	I3_ATTRID_SHADER,					// 48
	I3_ATTRID_SHADOWMAP_ENABLE,			// 49
	I3_ATTRID_NORMALMAP_ENABLE,			// 50
	I3_ATTRID_SPECULARMAP_ENABLE,		// 51
	I3_ATTRID_NORMALMAP_BIND,			// 52
	I3_ATTRID_SPECULARMAP_BIND,			// 53
	I3_ATTRID_LUXMAP_ENABLE,			// 54
	I3_ATTRID_LUXMAP_BIND,				// 55
	I3_ATTRID_NORMALMAP_WRAP,			// 56
	I3_ATTRID_SPECULARMAP_WRAP,			// 57
	I3_ATTRID_LUXMAP_WRAP,				// 58
	I3_ATTRID_USER,						// 59
	I3_ATTRID_VIEWPORT,					// 60
	I3_ATTRID_TEXTDX,					// 61
	I3_ATTRID_TEXTDX2,					// 62
	I3_ATTRID_DISPLAYLIST,				// 63
	I3_ATTRID_REFLECTMAP_ENABLE,			// 64
	I3_ATTRID_REFLECTMAP_BIND,				// 65
	I3_ATTRID_REFLECTMAP_WRAP,				// 66
	I3_ATTRID_REFLECTMASKMAP_ENABLE,		// 67
	I3_ATTRID_REFLECTMASKMAP_BIND,			// 68
	I3_ATTRID_REFLECTMASKMAP_WRAP,			// 69
	I3_ATTRID_FRESNEL,						// 70

	I3_ATTR_MAX,
};

#endif
