INCS		=	-I$(STDINC) -I$(GCCLIB_INC) -I$(TC_INC) -I$(I3_PSP_ROOT)/include -I$(I3SCENEUTIL_INC)

TARGET		=	$(OUTDIR)/libi3SceneUtil.a

OBJS		=	i3SceneUtil.o i3SceneUtilCollision.o

include		../Common/makebase

vpath %.cpp		\
			$(I3SCENEUTIL_SRC)

