; Event Quest Card Setting
[EventQuestCard]
0	="Quest\\EventCard_Valentine_2013.mqf"			; None
1	="Quest\\EventCard_Valentine_2013.mqf"			; Korea
2	="Quest\\EventCard_NewYear2014.mqf"			; Thai
3	="Quest\\EventCard_NewYear2014_Unicorn.mqf"		; Indonesia
4	="Quest\\EventCard_Xmas_2013_KerisXmas.mqf"		; Russia
5	="Quest\\EventCard_NewYear_TR_2014.mqf"			; Turkey
6	="Quest\\EventCard_Valentine_2013.mqf"			; China
7	="Quest\\EventCard_NewYear2014_Unicorn.mqf"		; Taiwan
8	="Quest\\EventCard_Valentine_2013.mqf"			; Japan
9	="Quest\\EventCard_NewYear2014_Uni_Keris.mqf"		; Brazil
10	="Quest\\EventCard_NewYear2014_Unicorn.mqf"		; LatinAmerica
11	="Quest\\EventCard_Summer_Mission_Card_NAM20130625.mqf"	; NorthAmerica
12	="Quest\\EventCard_Xmas_2013_KerisXmas.mqf"		; Italy
13	="Quest\\EventCard_Valentine_2013.mqf"			; Sale
14	="Quest\\EventCard_Xmas_2013_KerisXmas.mqf"		; MiddleEast
15	="Quest\\EventCard_Easter_2013.mqf"			; Phillippines
16	="Quest\\EventCard_Valentine_2013.mqf"			; Match
