; once a semicolon(;) is appeared, all of left string are treated as comments.
;---------------------------------------------------------------------------------------------------------
[Default]
LogFilePath		= "d:\\PbLog\\Dedi"	; LogFilePath
UdpIp			= "127.0.0.1"		; UdpIp 클라이언트가 붙을 Ip
UdpIpActive		= "127.0.0.1"		; Proxy존재시 실제로 클라이언트가 붙을 Ip
UpdateTime		= 61			; 업데이트 타임 수정하지 마세요. 
;----------------------------------------------------------------------------------------------------------				
; log level
; - error  : critical error 
; - waring : error + invalid information 
; - message: warning + system message (write all)
LogLevel		= 0			; 0:message, 1:warning, 2:error 
;----------------------------------------------------------------------------------------------------------
RoomCount		= 1000			; 개설가능한 최대 룸의 수
IoThreadCount		= 10			; iocp work thread의 수 (>= port_count, max: 32)
TaskThreadCount		= 10			; task processor thread의 수 (>=1, max: 63)
;---------------------------------------------------------------------------------------------------------
[Control]
ControlServerIp		= "127.0.0.1"		;Control Server IP
ControlServerPort	= 39120			;Control Server Port
;---------------------------------------------------------------------------------------------------------
[HackCheck] 
; Locale Code (1~12) - be positively necessery 
; 1:Indonesia, 2:Russia, 3:Thai, 4:Korea, 5:Turkey, 6:Brazil 
; 7:LatinAmerica, 8:NorthAmerica, 9:China, 10:Italy, 11:Philippines, 12:Middle East, 13:Taiwan
TRANS_METHOD		= 4			; Locale Code(1~13)
;USE_FREEZE		= 1			; 0:disconnect 1:freeze
;---------------------------------------------------------------------------------------------------------
[Raycast]
; The preferable UpdateTime, EpsilonTime values ara (16, 2), (64, 3)
PhysicsActive		= 0			; ray cast on/off (0:off, 1:on)
PhysicsUpdateTime	= 16			; task thread update time (ms)
PhysicsEpsilonTime	= 2			; equivalant to zero (ms)
RayCount		= 5 			; ray count ( 1, 3-default, 5 )
BothDirection		= 1			; enable inverse direction (0:disable, 1:enable)
;---------------------------------------------------------------------------------------------------------
; 레벨팀 테스트 용도입니다. 이 섹션은 없어도 서버가 실행됩니다.
[Debug]
RelayMode   		= 0			; 0 =  OFF , 1 = ON	
;---------------------------------------------------------------------------------------------------------