#include "pch.h"
#include "DediDef.h"

BOOL ChangeAvailableWeapon( EWEAPON_TYPE eWeapon, T_ItemID& TItemID, WEAPON_SLOT_TYPE& eSlot )
{
	switch( eWeapon )
	{
	case WT_RPG7_OUTPOST:		TItemID = Weapon::GetItemID( WEAPON_CLASS_ROCKET_LAUNCHER,	ROCKET_LAUNCHER_RPG7_OUTPOST );	eSlot = WEAPON_SLOT_PRIMARY;	return TRUE;
	case WT_RPG7_BOSS:			TItemID = Weapon::GetItemID( WEAPON_CLASS_ROCKET_LAUNCHER,	ROCKET_LAUNCHER_RPG7_BOSS );	eSlot = WEAPON_SLOT_PRIMARY;	return TRUE;
	case WT_K201:				TItemID = Weapon::GetItemID( WEAPON_CLASS_ASSAULT,			ASSAULT_K201_GL );				eSlot = WEAPON_SLOT_PRIMARY;	return TRUE;
	case WT_CHINESE_CLEAVER:	TItemID = Weapon::GetItemID( WEAPON_CLASS_KNIFE,			KNIFE_CHINESE_CLEAVER_SEIZED );	eSlot = WEAPON_SLOT_MELEE;	return TRUE;
	case WT_CROWNWATERMELON:	TItemID = Weapon::GetItemID(WEAPON_CLASS_MISSION, MISSION_CROWN_WATER_MELON);		eSlot = WEAPON_SLOT_PRIMARY;	return TRUE;
	}
	return FALSE;
}