#if !defined( __I3G_UTIL_H)
#define __I3G_UTIL_H

#include "i3GfxDefine.h"
#include "i3RenderState.h"

namespace i3Gfx
{
	// 각 Raster Format들에 대해, 한 Pixel의 크기를 Bits 단위로 반환한다.
	I3_EXPORT_GFX INT32 GetImageFormatBitCount( I3G_IMAGE_FORMAT format);

	I3_EXPORT_GFX INT32	GetImageFormatComponentCount( I3G_IMAGE_FORMAT format);

	I3_EXPORT_GFX const char *	GetImageFormatName( I3G_IMAGE_FORMAT format);
	I3_EXPORT_GFX const wchar_t* GetImageFormatNameW( I3G_IMAGE_FORMAT format);

	// 각 Raster Format들에 대해, 버퍼 사이즈를 Byte 단위로 리턴
	I3_EXPORT_GFX INT32	CalcRasterBufferSize( INT32 width, INT32 height, INT32 align, I3G_IMAGE_FORMAT format);

	I3_EXPORT_GFX UINT32	CalcVertexCount( I3G_PRIMITIVE Prim, UINT32 PrimCount);
	I3_EXPORT_GFX UINT32	CalcPrimCount( I3G_PRIMITIVE Prim, UINT32 VertexCount);

	I3_EXPORT_GFX I3G_PERSIST_USAGE					Convert( I3G_USAGE usage);
	I3_EXPORT_GFX I3G_USAGE							Convert( I3G_PERSIST_USAGE usage);

	I3_EXPORT_GFX I3G_PERSIST_RENDER_MODE			Convert( I3G_RENDER_MODE mode);
	I3_EXPORT_GFX I3G_RENDER_MODE					Convert( I3G_PERSIST_RENDER_MODE mode);

#ifndef I3G_OGLES
	I3_EXPORT_GFX I3G_PERSIST_SHADE_MODE			Convert( I3G_SHADE_MODE mode);
	I3_EXPORT_GFX I3G_SHADE_MODE					Convert( I3G_PERSIST_SHADE_MODE mode);
#endif

	I3_EXPORT_GFX I3G_PERSIST_FACE_CULL				Convert( I3G_FACE_CULL mode);
	I3_EXPORT_GFX I3G_FACE_CULL						Convert( I3G_PERSIST_FACE_CULL mode);

	I3_EXPORT_GFX I3G_PERSIST_BLEND					Convert( I3G_BLEND blend);
	I3_EXPORT_GFX I3G_BLEND							Convert( I3G_PERSIST_BLEND blend);

	I3_EXPORT_GFX I3G_PERSIST_BLEND_OP				Convert( I3G_BLEND_OP blend);
	I3_EXPORT_GFX I3G_BLEND_OP						Convert( I3G_PERSIST_BLEND_OP blend);

	I3_EXPORT_GFX I3G_PERSIST_FOG_MODE				Convert( I3G_FOG_MODE mode);
	I3_EXPORT_GFX I3G_FOG_MODE						Convert( I3G_PERSIST_FOG_MODE mode);

	I3_EXPORT_GFX I3G_PERSIST_STENCIL_OP			Convert( I3G_STENCIL_OP op);
	I3_EXPORT_GFX I3G_STENCIL_OP					Convert( I3G_PERSIST_STENCIL_OP op);

	I3_EXPORT_GFX I3G_PERSIST_COMP_FUNC				Convert( I3G_COMP_FUNC func);
	I3_EXPORT_GFX I3G_COMP_FUNC						Convert( I3G_PERSIST_COMP_FUNC func);

	I3_EXPORT_GFX I3G_PERSIST_TEXTURE_WRAP			Convert( I3G_TEXTURE_WRAP mode);
	I3_EXPORT_GFX I3G_TEXTURE_WRAP					Convert( I3G_PERSIST_TEXTURE_WRAP mode);

	I3_EXPORT_GFX I3G_PERSIST_TEXTURE_FILTER		Convert( I3G_TEXTURE_FILTER mode);
	I3_EXPORT_GFX I3G_TEXTURE_FILTER				Convert( I3G_PERSIST_TEXTURE_FILTER mode);

	I3_EXPORT_GFX I3G_PERSIST_PRIMITIVE				Convert( I3G_PRIMITIVE prim);
	I3_EXPORT_GFX I3G_PRIMITIVE						Convert( I3G_PERSIST_PRIMITIVE prim);

	I3_EXPORT_GFX I3G_PERSIST_LIGHT_TYPE			Convert( I3G_LIGHT_TYPE type);
	I3_EXPORT_GFX I3G_LIGHT_TYPE					Convert( I3G_PERSIST_LIGHT_TYPE type);

	I3_EXPORT_GFX I3G_PERSIST_TEXTURE_COORD_SOURCE	Convert( I3G_TEXTURE_COORD_SOURCE mode);
	I3_EXPORT_GFX I3G_TEXTURE_COORD_SOURCE			Convert( I3G_PERSIST_TEXTURE_COORD_SOURCE mode);

	I3_EXPORT_GFX I3G_PERSIST_TEXTURE_FUNCTION		Convert( I3G_TEXTURE_FUNCTION func);
	I3_EXPORT_GFX I3G_TEXTURE_FUNCTION				Convert( I3G_PERSIST_TEXTURE_FUNCTION func);

	I3_EXPORT_GFX I3G_PERSIST_CUBE_TEXTURE_FACE		Convert( I3G_CUBE_TEXTURE_FACE face);
	I3_EXPORT_GFX I3G_CUBE_TEXTURE_FACE				Convert( I3G_PERSIST_CUBE_TEXTURE_FACE face);

	I3_EXPORT_GFX INT32								GetNearestPowerOfTwo( INT32 val);

	I3_EXPORT_GFX INT32								FontPointToPixel( INT32 point);
	I3_EXPORT_GFX INT32								FontPixelToPoint( INT32 pixel);
};

#endif
