#if !defined( __I3G_RENDER_STATE_OGLES_H)
#define __I3G_RENDER_STATE_OGLES_H

#if !defined( I3G_OGLES)
#error "This header file is only for OpenGL-ES."
#endif

enum I3G_COMP_FUNC
{
	I3G_COMP_NEVER		=	GL_NEVER,	// 0
	I3G_COMP_LESS		=	GL_LESS,		// 4
	I3G_COMP_EQUAL		=	GL_EQUAL,	// 2
	I3G_COMP_LEQUAL		=	GL_LEQUAL,	// 5
	I3G_COMP_GREATER	=	GL_GREATER,	// 6
	I3G_COMP_NOTEQUAL	=	GL_NOTEQUAL,	// 3
	I3G_COMP_GEQUAL		=	GL_GEQUAL,	// 7
	I3G_COMP_ALWAYS		=	GL_ALWAYS	// 1
};

enum I3G_RENDER_MODE
{
	I3G_RENDER_POINT		=	0,
	I3G_RENDER_LINE,
	I3G_RENDER_POLYGON,
};

enum I3G_SHADE_MODE
{
	I3G_SHADE_FLAT			=	GL_FLAT,
	I3G_SHADE_GOURAUD		=	GL_SMOOTH,
};

enum I3G_FACE_CULL
{
	I3G_FACE_CULL_NONE		=	-1,
	I3G_FACE_CULL_BACK		=	GL_CCW,
	I3G_FACE_CULL_FRONT		=	GL_CW,
};

enum I3G_BLEND
{
	I3G_BLEND_SRCCOLOR		=	GL_SRC_COLOR,				// 0
	I3G_BLEND_INVSRCCOLOR	=	GL_ONE_MINUS_SRC_COLOR,		// 1
	I3G_BLEND_SRCALPHA		=	GL_SRC_ALPHA,				// 2
	I3G_BLEND_INVSRCALPHA	=	GL_ONE_MINUS_SRC_ALPHA,		// 3
	I3G_BLEND_DESTALPHA		=	GL_DST_ALPHA,				// 4
	I3G_BLEND_INVDESTALPHA	=	GL_ONE_MINUS_DST_ALPHA,		// 5
	I3G_BLEND_DESTCOLOR		=	GL_DST_COLOR,				// 0
	I3G_BLEND_INVDESTCOLOR	=	GL_ONE_MINUS_DST_COLOR,		// 1
	I3G_BLEND_ZERO			=	GL_ZERO,					// 10
	I3G_BLEND_ONE			=	GL_ONE,						// 10
	I3G_BLEND_SRCALPHASAT	=	GL_SRC_ALPHA,				// 2
};

enum I3G_BLEND_OP
{
	I3G_BLEND_OP_NONE			=	-1,
	I3G_BLEND_OP_ADD			=	0,
	I3G_BLEND_OP_SUBTRACT		=	1,
	I3G_BLEND_OP_REVSUBTRACT	=	2,
	I3G_BLEND_OP_MIN			=	3,
	I3G_BLEND_OP_MAX			=	4,
};

enum I3G_FOG_MODE
{
	I3G_FOG_NONE			=	0,
	I3G_FOG_LINEAR			=	1,
	I3G_FOG_EXP				=	2,
	I3G_FOG_EXP2			=	3,
};

enum I3G_STENCIL_OP
{
	I3G_STENCIL_OP_KEEP			=	GL_KEEP,
	I3G_STENCIL_OP_ZERO			=	GL_ZERO,
	I3G_STENCIL_OP_REPLACE		=	GL_REPLACE,
	I3G_STENCIL_OP_INC_CLAMP	=	GL_INCR,
	I3G_STENCIL_OP_DEC_CLAMP	=	GL_DECR,
	I3G_STENCIL_OP_INVERT		=	GL_INVERT,
	I3G_STENCIL_OP_INC			=	GL_INCR,
	I3G_STENCIL_OP_DEC			=	GL_DECR,
};

#endif
