//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// i3LevelDesign.rc에서 사용되고 있습니다.
//
#define ID_BTN_NEWEVENT                 4
#define ID_BTN_DELETE_EVENT             5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_VIEWERDUMMYWND              101
#define ID_RESPOPUP_NEWWORLD            102
#define IDD_DLG_HITMAP_TIMESET          102
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_PANEL_PROPERTY               104
#define IDD_PANEL_HITMAP                104
#define IDC_POINTER_COPY                105
#define ID_PANEL_TRANSFORM              105
#define IDC_NODROP                      106
#define ID_PANEL_RES                    106
#define ID_PANEL_NAVMESH                107
#define ID_RIBBON_SELECTION             108
#define ID_RIBBON_TRANSLATION           109
#define ID_RIBBON_ROTATION              110
#define ID_RIBBON_SCALE                 111
#define ID_RIBBON_OBJBRUSH              112
#define ID_RIBBON_PATHEDIT              113
#define ID_RIBBON_MODE                  114
#define IDC_BTN_ELM_REDO_CLEAR          115
#define ID_COLOR_FOG                    116
#define ID_COLOR_SKY_FOG                117
#define IDR_MAINFRAME                   128
#define IDR_i3LevelDesignTYPE           129
#define IDD_PANEL_PROPERTY              132
#define IDD_PANEL_SCENETREE             133
#define IDD_PANEL_LOG                   134
#define IDD_PANEL_VIEWER                135
#define IDC_BANDSELECT                  141
#define IDC_BRUSH                       142
#define IDC_MOVE                        143
#define IDC_ROTATE                      144
#define IDC_SCALE                       145
#define IDD_POPUP_LV_TYPE               147
#define IDD_MODAL_OBJECTTYPE            148
#define IDD_PANEL_TRANSFORM             150
#define IDD_OPTION                      151
#define IDD_PROP_WORLD                  152
#define IDD_PROP_LIGHT                  153
#define IDD_COLORDLG                    154
#define IDI_LOCKX                       155
#define IDI_LOCKY                       156
#define IDI_LOCKZ                       157
#define IDD_PROP_LVRES_TEXTURE          158
#define IDD_PROP_LVRES_ANIMATION        159
#define IDD_PROP_LVRES_SOUND            160
#define IDD_PROP_LVRES_SCENEGRAPH       161
#define IDD_DLG_RESSCAN                 167
#define IDD_PROP_LVRES_CHARACTER        168
#define IDD_PANEL_RESOURCE              169
#define IDD_PROP_ELM_COMMON             171
#define IDD_PROP_COMMON                 172
#define IDD_DIALOG1                     173
#define IDD_PROP_SPECIFIC               173
#define IDR_I3LVRES_POPUP_RESOURCE      174
#define IDD_PROP_LVELM_PRIM             176
#define IDD_DLG_TEXTURE_SELECT          177
#define IDD_PANEL_TOOLBAR               178
#define IDD_DLG_ELEMENTLIST             179
#define IDD_DLG_EXPORT                  180
#define IDD_DLG_SELECTSG                184
#define IDD_DIALOG2                     185
#define IDD_PROP_LVELM_PRIM_RESPAWN     185
#define IDD_DLG_ACTIONRESSEL            186
#define IDD_DLG_ENTEREVENTNAME          187
#define IDD_PROP_OBJECT                 188
#define IDD_DLG_WORLDSECTION            190
#define IDD_DLG_WORLDSECTION_INPUT      191
#define IDR_MENU1                       192
#define IDR_POPUP_WORLDSECTION          192
#define IDD_PROP_ACTION_SETWRLSECTION   193
#define IDD_DLG_ACTION_SETWORLDSECTION  193
#define IDD_DLG_LAYER                   195
#define IDI_ICO_ADD                     196
#define IDI_ICO_REMOVE                  197
#define IDI_ICO_NEW                     198
#define IDI_ICO_DELETE                  199
#define ID_PANEL_HITMAP                 200
#define IDI_ICO_FOLDER_COLLAPSED        201
#define IDI_ICO_FOLDER_EXPANDED         202
#define IDC_CURSOR1                     204
#define IDC_SELECT_TARGET               204
#define IDI_ICO_BLANK                   206
#define IDI_ICO_CURRENT_LAYER           207
#define IDD_DLG_REPLACE_RES             209
#define IDD_PROP_CAMERA                 210
#define IDD_PROP_LVELM_PATHPOINT        212
#define IDD_DIALOG3                     213
#define IDD_PROP_LVELM_PATHLINK         213
#define IDD_DLG_MAPSECTION              214
#define IDD_DIALOG4                     215
#define IDD_DLG_SEMAPSECTOR             215
#define IDI_ICO_CHK_UNCHECKED           217
#define IDI_ICO_CHK_CHECKED             218
#define IDI_ICO_CHK_NA                  219
#define IDI_ICO_SEL                     220
#define IDD_DEBUG_SG                    222
#define IDR_POPUP_EDIT                  223
#define IDR_THEME_MENU                  224
#define IDB_BUTTONS                     225
#define IDB_FILELARGE                   227
#define IDB_FILESMALL                   228
#define IDB_WRITELARGE                  229
#define IDB_WRITESMALL                  230
#define IDB_TOOLBAR_16                  231
#define IDB_TOOLBAR_32                  232
#define IDD_DIALOG5                     233
#define IDD_DLG_RENAME                  233
#define IDD_PANEL_NAVMESH               234
#define IDD_NAVMESH_COMMON_ELM          236
#define IDD_NAVMESH_COMMON              236
#define IDD_NAVMESH_EDIT_ELM            238
#define IDD_NAVMESH_EDIT                238
#define IDB_SELECT_TYPE                 241
#define IDB_SELECT_TYPE1                242
#define IDB_SELECT_TYPE_DISABLE         242
#define IDD_NAVMESH_GENERATOR           245
#define IDD_NAVMESH_GENERATOR_PROGRESS  246
#define IDB_BITMAP_X                    249
#define IDD_LOADERROR                   250
#define IDR_POPUP_LAYER_ELEMENT         251
#define IDD_PROP_HITMAP_COMMON          252
#define IDD_PROP_HITMAP                 252
#define IDD_PROP_HITMAP_BUILD           253
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EDIT_MENU                   306
#define IDC_LOGLIST                     1000
#define IDC_OBJLIST                     1001
#define IDC_BTN_DISP_TYPE               1002
#define IDC_BTN_DISP_MODE               1006
#define IDC_BTN_SELALL                  1010
#define IDC_BTN_SELREV                  1011
#define IDC_BTN_UNSELALL                1012
#define ID_CLOSE                        1013
#define IDC_CB_TYPE                     1014
#define IDC_ED_POS_X                    1015
#define IDC_ED_POS_Y                    1016
#define IDC_ED_OPTION_WORKINGDIR        1016
#define IDC_ED_POS_Z                    1017
#define IDC_BTN_WORKINGDIR              1017
#define IDC_ED_ROT_X                    1018
#define IDC_ED_WORLDCOL                 1018
#define IDC_ED_OPTION_RESPATH           1018
#define IDC_ED_ROT_Y                    1019
#define IDC_BTN_WORLDCOL_SEL            1019
#define IDC_BTN_RESPATH                 1019
#define IDC_ED_ROT_Z                    1020
#define IDC_ED_HEROCOL                  1020
#define IDC_ED_SCALE_X                  1021
#define IDC_BTN_HEROCOL_SEL             1021
#define IDC_ED_SCALE_Y                  1022
#define IDC_ED_HITCOL                   1022
#define IDC_ED_SCALE_Z                  1023
#define IDC_BTN_HITCOL_SEL              1023
#define IDC_ED_SKYPATH                  1024
#define IDC_CHK_SHOWRENDERABLEMESH      1025
#define IDC_COL_RESET                   1026
#define IDC_EDIT_COLOR_A                1027
#define IDC_BTN_SELSKYPATH              1027
#define IDC_EDIT_COLOR_R                1028
#define IDC_CHK_ENFOGWORLD              1028
#define IDC_EDIT_COLOR_G                1029
#define IDC_CHK_ENFOG_SKY               1029
#define IDC_EDIT_COLOR_B                1030
#define IDC_ED_LIGHTVOLUME              1030
#define IDC_BTN_COLSEL                  1031
#define IDC_BTN_HITCOL_SEL2             1031
#define IDC_BTN_LIGHTVOLUME             1031
#define IDC_STATIC_COLOR                1032
#define IDC_BTN_WORLD_SEL               1032
#define IDC_BTN_SEL_AMBIENT             1033
#define IDC_STATIC_AMBIENT              1034
#define IDC_STATIC_DIFFUSE              1035
#define IDC_BTN_SEL_DIFFUSE             1036
#define IDC_STATIC_SPECULAR             1037
#define IDC_BTN_SEL_SPECULAR            1038
#define IDC_EDIT_LIGHT_DISTANCE         1039
#define IDC_STATIC_AMBIENT2             1039
#define IDC_EDIT_LIGHT_ROT_X            1040
#define IDC_BTN_SEL_AMBIENT2            1040
#define IDC_EDIT_LIGHT_ROT_Y            1041
#define IDC_EDIT_LIGHT_POS_X            1042
#define IDC_EDIT_LIGHT_POS_Y            1043
#define IDC_EDIT_LIGHT_POS_Z            1044
#define IDC_EDIT_WFDENSKTY              1045
#define IDC_EDIT_SFDENSITY              1046
#define IDC_COMBO_WFMODE                1047
#define IDC_COMBO_SFMODE                1048
#define IDC_EDIT_WFNEAR                 1049
#define IDC_EDIT_WFFAR                  1050
#define IDC_CHECK_LOCK_X                1050
#define IDC_EDIT_SFNEAR                 1051
#define IDC_ED_PATH                     1051
#define IDC_EDIT_SFFAR                  1052
#define IDC_CHECK_LOCK_Y                1052
#define IDC_CHECK_LOCK_X3               1053
#define IDC_CHECK_LOCK_Z                1053
#define IDC_ED_PATH2                    1053
#define IDC_PROP_LVRES_TEXTURE          1054
#define IDC_PROP_LVRES_ANIMATION        1055
#define IDC_PROP_LVRES_SOUND            1056
#define IDC_PROP_LVRES_SCENEGRAPH       1057
#define IDC_TREE_RESLIST                1059
#define IDC_EDIT1                       1060
#define IDC_ED_TEXTURE                  1060
#define IDC_ED_SEARCHNAME               1060
#define IDC_ED_STATE                    1060
#define IDC_ED_NAME                     1060
#define IDC_ED_WORLD                    1060
#define IDC_ED_ATTENUATION_X            1060
#define IDC_EDIT_ENTEREVENTNAME         1060
#define IDC_EDIT_JUMPPOSX               1060
#define IDC_ED_ID                       1060
#define IDC_ED_WORLD_SECTION            1060
#define IDC_ED_SRC                      1060
#define IDC_ED_CAM_FOV                  1060
#define IDC_ED_CAMERA_FOV               1060
#define IDC_ED_FLOOR                    1060
#define IDC_ED_PRIORITY                 1060
#define IDC_ED_COST                     1060
#define IDC_EDIT_MAPSECTORINDEX         1060
#define IDC_ED_FILE                     1060
#define IDC_ED_SNAP_POS                 1060
#define IDC_EDIT_STARTTIME              1060
#define IDC_CHECK1                      1061
#define IDC_CHK_INITSTATE               1061
#define IDC_CHK_TRIGGER                 1061
#define IDC_CHK_VISIBLE_BOX             1061
#define IDC_CHK_EXPORT_RES              1061
#define IDC_ED_ATTENUATION_Y            1061
#define IDC_ED_RES                      1061
#define IDC_ED_DEST                     1061
#define IDC_ED_CAM_NEAR                 1061
#define IDC_ED_CAMERA_NEAR              1061
#define IDC_CHK_BIDIR                   1061
#define IDC_NAVMESH_CHK_BLANKTEXTURE    1061
#define IDC_NAVMESH_CHK_MONOTONEPARTITION 1061
#define IDC_ED_SNAP_ROTATE              1061
#define IDC_EDIT_ENDTIME                1061
#define IDC_ED_RES_PATH                 1062
#define IDC_ED_UTILE                    1062
#define IDC_ED_ATTENUATION_Z            1062
#define IDC_CHECK3                      1062
#define IDC_ED_CAM_FAR                  1062
#define IDC_ED_CAMERA_FAR               1062
#define IDC_NAVMESH_CHK_WIREFRAME       1062
#define IDC_ED_SNAP_SCALE               1062
#define IDC_ED_RES_PATH_HASH            1063
#define IDC_ED_VTILE                    1063
#define IDC_ED_CAM_WIDTH                1063
#define IDC_ED_CAMERA_WIDTH             1063
#define IDC_NAVMESH_CHK_VISIBLE         1063
#define IDC_CB_INSTANCE_CLASS           1064
#define IDC_ED_CAM_HEIGHT               1064
#define IDC_ED_CAMERA_HEIGHT            1064
#define IDC_CB_DYNAMIC_STATE            1065
#define IDC_ED_CAMERA_UPDATEINTERVAL    1065
#define IDC_ED_INSTANCE_CLASS_HASH      1066
#define IDC_CHK_VISIBLE                 1066
#define IDC_BTN_TEXTURE                 1067
#define IDC_TEX_LIST                    1068
#define IDC_BTN_ELM_SELECTION           1069
#define IDC_BTN_ELM_ROTATION            1070
#define IDC_ELM_LIST                    1070
#define IDC_BTN_ELM_TRANSLATION         1071
#define IDC_ELMTYPE_GROUP               1071
#define IDC_BTN_ELM_SCALE               1072
#define IDC_CHK_VISIBLE_SPHERE          1072
#define IDC_BTN_ELM_OBJBRUSH            1073
#define IDC_CHK_VISIBLE_CAPSULE         1073
#define IDC_BTN_ELM_PATHEDIT            1074
#define IDC_CHK_RESPAWN                 1074
#define IDC_BTN_ELM_EXPORT              1075
#define IDC_CHK_VISIBLE_CHARA           1075
#define IDC_BTN_OPTION                  1076
#define IDC_CHK_VISIBLE_OBJECT          1076
#define IDC_BTN_ELM_LIST                1077
#define IDC_CHK_VISIBLE_EFFECT          1077
#define IDC_CHK_CAPSULE                 1077
#define IDC_CHK_VISIBLE_WORLD           1078
#define IDC_BTN_PARENT_LINK             1078
#define IDC_CHK_VISIBLE_LIGHT           1079
#define IDC_BTN_PARENT_UNLINK           1079
#define IDC_CHK_VISIBLE_CAMERA          1080
#define IDC_BTN_PARENT_UNLINK2          1080
#define IDC_BTN_LAYER                   1080
#define IDC_CHK_VISIBLE_TRIGGER         1081
#define IDC_BTN_ELM_PATHEDIT2           1081
#define IDC_BTN_COLLISION_EDIT          1081
#define IDC_CHK_VISIBLE_PATH            1082
#define IDC_BTN_ELM_UNDO                1082
#define IDC_BTN_VISIBLE_SELALL          1083
#define IDC_BTN_ELM_EXPORT3             1083
#define IDC_BTN_ELM_REDO                1083
#define IDC_BTN_VISIBLE_UNSELALL        1084
#define IDC_BTN_OPTION2                 1084
#define IDC_BTN_HITMAP_TIMESET          1084
#define IDC_BTN_VISIBLE_SELINVERT       1085
#define IDC_CHK_VISIBLE_PATH2           1086
#define IDC_CHK_VISIBLE_STATICOBJECT    1086
#define IDC_BTN_SELINVERT               1088
#define IDC_PROGRESS1                   1091
#define IDC_CHECK2                      1094
#define IDC_SGLIST                      1095
#define IDC_CB_TEAM                     1096
#define IDC_CB_NETWORK_SYNC             1097
#define IDC_CB_NETWORK_SYNC2            1098
#define IDC_CB_COLLISION_GROUP          1098
#define IDC_CB_LIGHT_TYPE               1098
#define IDC_ED_CUTOFFANGLE              1099
#define IDC_EDIT5                       1100
#define IDC_SPOTLIGHT_ANGLE             1100
#define IDC_ED_GAMEBIN                  1100
#define IDC_ED_FALLOFFRATE              1101
#define IDC_BTN_BINARY                  1101
#define IDC_ED_RANGE                    1102
#define IDC_COLOR_PREVIEW_PLACEHOLDER   1102
#define IDC_CB_STAGETYPE                1103
#define IDC_LIST_ACTION_SEL             1104
#define IDC_CB_OBJECTTYPE               1105
#define IDC_CB_OBJTEAM_TYPE             1106
#define IDC_CHK_INVISIBLE               1107
#define IDC_EDIT_JUMPPOSY               1108
#define IDC_EDIT3                       1109
#define IDC_EDIT_JUMPPOSZ               1109
#define IDC_STATIC_JUMP                 1110
#define IDC_BTN_SECTIONEDIT             1111
#define IDC_SECTION_LIST                1112
#define IDC_BTN_SECTOREDIT              1112
#define IDC_SHADOW_MASK                 1114
#define IDC_VISIBILITY_MASK             1115
#define IDC_ED_SECTION_NAME             1115
#define IDC_CB_TRIGGER_CGROUP           1118
#define IDC_BTN_NEW                     1122
#define IDC_BTN_NEWLAYER                1122
#define IDC_BTN_DELETE                  1123
#define IDC_BTN_DELETELAYER             1123
#define IDC_BTN_ADD_ELM                 1124
#define IDC_BTN_REMOVE_ELM              1125
#define IDC_BTN_SELECT_ELM              1126
#define IDC_LAYER_LIST                  1127
#define IDC_CB_CAM_MODE                 1129
#define IDC_CB_CAMERA_MODE              1129
#define IDC_CHK_CAM_MODE                1130
#define IDC_CHK_CAMERA_ENABLE           1130
#define IDC_CB_CAMERA_RT_WIDTH          1131
#define IDC_STT_SCENE_PATH              1131
#define IDC_CB_CAMERA_RT_DEPTH_FORMAT   1132
#define IDC_BTN_SEL_COLOR               1132
#define IDC_CB_CAMERA_RT_HEIGHT         1133
#define IDC_COLOR_PLACEHOLDER           1133
#define IDC_CB_CAMERA_RT_COLOR_FORMAT   1134
#define IDC_LIST_MAPSECTOR              1134
#define IDC_EDIT_SECTORNAME             1135
#define IDC_EDIT_FLOORINDEX             1136
#define IDC_BUTTON1                     1137
#define IDC_BTN_EXPORTSECTOR            1137
#define IDC_BTN_SELALL_SHADOW           1137
#define IDC_BTN_RENAME                  1137
#define IDC_RECREATE_NAVMESH            1137
#define IDC_NAVMESH_EDIT_ADD            1137
#define IDC_NAVMESH_BLANKTEXTURE_COLOR  1137
#define IDC_BUTTON_BUILD                1137
#define IDC_BUTTON_OK                   1137
#define IDC_ST_TITLE                    1138
#define IDC_BTN_SELALL_VISIBLE          1138
#define IDC_NAVMESH_RESET_CFG           1138
#define IDC_BUTTON2                     1138
#define IDC_BUTTON_CANCEL               1138
#define IDC_PROGRESS                    1139
#define IDC_BTN_UNSELALL_SHADOW         1140
#define IDC_BTN_UNSELALL_SHADOW2        1141
#define IDC_BTN_UNSELALL_VISIBLE        1141
#define IDC_TEST_NAVMESH_VERTEX_ADD     1144
#define IDC_TEST_NAVMESH_VERTEX_DEL     1145
#define IDC_TEST_NAVMESH_VERTEX_NMSAVE  1146
#define IDC_NAVMESH_SAVE                1146
#define IDC_NAVMESH_LOAD                1147
#define IDC_NAVMESH_RADIO_VERTEX        1148
#define IDC_NAVMESH_SAVE_AS             1148
#define IDC_RADIO2                      1150
#define IDC_NAVMESH_RADIO_POLY          1150
#define IDC_NAVMESH_EDIT_DEL            1151
#define IDC_NAVMESH_EDIT_CREATEPOLY     1152
#define IDC_NAVMESH_EDIT_CLEARNOUSE     1153
#define IDC_SLIDER1                     1154
#define IDC_NAVMESH_SLIDE_VERTEXSCALE   1154
#define IDC_NAVMESH_TEXT_VERTEXSCALE    1155
#define IDC_NAVMESH_EDIT_INVERTNORMAL   1156
#define IDC_NAVMESH_GENERATE_PROP       1157
#define IDC_NAVMESH_EDIT_CUTPOLY        1157
#define IDC_NAVMESH_SLIDE_CELLSIZE      1158
#define IDC_NAVMESH_TEXT_CELLSIZE       1159
#define IDC_NAVMESH_SLIDE_CELLHEIGHT    1160
#define IDC_NAVMESH_TEXT_FILEPATH       1160
#define IDC_NAVMESH_TEXT_CELLHEIGHT     1161
#define IDC_NAVMESH_SLIDE_EDGEMAXLENGTH 1162
#define IDC_NAVMESH_TEXT_EDGEMAXLENGTH  1163
#define IDC_NAVMESH_SLIDE_EDGEMAXERROR  1164
#define IDC_NAVMESH_TEXT_EDGEMAXERROR   1165
#define IDC_NAVMESH_SLIDE_REGIONMINSIZE 1166
#define IDC_NAVMESH_TEXT_REGIONMINSIZE  1167
#define IDC_NAVMESH_GENERATE_TYPE       1168
#define IDC_NAVMESH_RESET               1169
#define IDC_NAVMESH_GENERATOR_PROGRESS  1170
#define IDC_NAVMESH_GENERATOR_PROGRESS_TEXT 1171
#define IDC_NAVMESH_SLIDE_REGIONMERGESIZE 1174
#define IDC_NAVMESH_TEXT_REGIONMERGESIZE 1175
#define IDC_BUTTON3                     1178
#define IDC_ELMLIST                     1178
#define IDC_LIST_TRIGGER                1179
#define IDC_CB_ROOMSELECT               1180
#define IDC_CB_KILLDEATY_TYPE           1181
#define IDC_LIST_PLAYER                 1183
#define IDC_PROGRESS_BUILD              1184
#define IDC_LIST1                       1185
#define IDC_MONTHCALENDAR_END           1187
#define IDC_MONTHCALENDAR_START         1188
#define IDC_RADIO_ALL                   1188
#define IDC_RADIO_WP                    1189
#define IDC_RADIO_PRIMARY               1189
#define IDC_RADIO_SECOND_WP             1190
#define IDC_RADIO_SECONDARY             1190
#define IDC_RADIO_THROW                 1191
#define IDC_RADIO_THROWING              1191
#define IDC_RADIO_DOWN                  1192
#define IDC_RADIO_MELEE                 1192
#define IDC_RADIO_ETC                   1193
#define ID_LV_CHARACTER                 32771
#define ID_LV_LIGHT                     32772
#define ID_LV_CAMERA                    32773
#define ID_LV_OBJECT                    32774
#define ID_LV_EFFECT                    32775
#define ID_LV_PATH                      32776
#define ID_FILE_SAVEAS                  32781
#define ID_TOOLS_EXPORTPATH             32782
#define ID_VIEW_OPTION_DIALOG           32784
#define ID_TOOLS_EXPORTWORLD            32785
#define ID_EDIT_ADDLIGHT                32787
#define ID_TOOLS_OPTIONS                32790
#define ID_I3LV_RES_COLLAPSE_ALL        32801
#define ID_I3LV_RES_EXPAND_ALL          32802
#define ID_I3LV_RES_ADD                 32803
#define ID_I3LV_RES_DELETE              32804
#define ID_I3LV_RES_SCAN                32805
#define ID_I3LV_RES_SELECT_ALL          32807
#define ID_I3LV_RES_CHECKDB             32811
#define ID_WORLDSECTION_NEW             32812
#define ID_WORLDSECTION_DELETE          32813
#define ID_RESOURCE_REPLACERESOURCEOFELEMENTS 32814
#define ID_DEBUG_SCENE                  32815
#define ID_EDIT_CUT32816                32816
#define ID_EDIT_COPY32817               32817
#define ID_OFFICE2007                   32818
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32819
#define ID_OFFICE2008                   32820
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32821
#define ID_OFFICE2009                   32822
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32823
#define ID_OFFICE2010                   32824
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32825
#define ID_32826                        32826
#define ID_APPLICATIONLOOK_WINDOWS2000  32827
#define ID_VIEW_APPLOOK_WIN_2000        32828
#define ID_APPLICATIONLOOK_OFFICEXP     32829
#define ID_VIEW_APPLOOK_OFF_XP          32830
#define ID_APPLICATIONLOOK_WINDOWSXP    32831
#define ID_VIEW_APPLOOK_WIN_XP          32832
#define ID_APPLICATIONLOOK_OFFICE2003   32833
#define ID_VIEW_APPLOOK_OFF_2003        32834
#define ID_APPLICATIONLOOK_VISUALSTUDIO 32835
#define ID_VIEW_APPLOOK_VS_2005         32836
#define ID_APPLICATIONLOOK_OFFICE2007   32837
#define ID_OFFICE2007_BLUESTYLE         32838
#define ID_OFFICE2007_BLACKSTYLE        32839
#define ID_OFFICE2007_SILVERSTYLE       32840
#define ID_OFFICE2007_AQUASTYLE         32841
#define ID_32842                        32842
#define ID_32843                        32843
#define ID_32844                        32844
#define ID_32845                        32845
#define ID_32846                        32846
#define ID_32847                        32847
#define ID_32848                        32848
#define ID_32849                        32849
#define ID_32850                        32850
#define ID_32851                        32851
#define ID_32852                        32852
#define ID_32853                        32853
#define ID_32854                        32854
#define ID_32855                        32855
#define ID_32856                        32856
#define ID_EDIT_REASSIGN_RES_NAME       32857
#define ID_EDIT_ESCAPE                  32864
#define ID_32867                        32867
#define ID_SNAP_POS                     32868
#define ID_SNAP_SCALE                   32869
#define ID_SNAP_ROTATE                  32870
#define ID_32871                        32871
#define ID_SPACE_MODE                   32872
#define ID_OBJECT_32873                 32873
#define ID_OBJECT_SELECTFIT             32874
#define ID_OBJECT_DELETE                32875
#define ID_SLIDER_BLOOMINTENSITY        32876
#define ID_SLIDER_BLOOMTHRESHOLD        32877
#define ID_EDIT_BLOOMINTENSITY          32878
#define ID_EDIT_BLOOMTHRESHOLD          32879
#define ID_CHECK_BLOOM                  32880
#define ID_EDIT_BLURITERATION           32881
#define ID_EDIT_GAUSSIANTHETA           32882
#define ID_SLIDER_GAUSSIANTHETA         32883

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        261
#define _APS_NEXT_COMMAND_VALUE         32876
#define _APS_NEXT_CONTROL_VALUE         1189
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
