//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by i3EffectEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDC_GRAPH_VIEW                  101
#define IDD_I3EFFECTEDITOR_DIALOG       102
#define IDC_ED_FPS                      103
#define IDR_MAINFRAME                   128
#define IDD_PARTICLESPEC_COLOR          129
#define IDR_MAINMENU                    131
#define IDD_PARTICLESPEC_PARTICLE       134
#define IDD_PARTICLESPEC_OBJECT         136
#define IDD_PARTICLESPEC_EMITTER        137
#define IDD_PARTICLESPEC_POSITION       139
#define IDD_PARTICLESPEC_SCALE          141
#define IDD_PLAYPANEL                   143
#define IDI_ICON_PLAY                   144
#define IDI_ICON_STOP                   145
#define IDI_ICON_PAUSE                  146
#define IDD_TIMETRACKSPEC               147
#define IDD_TEXSEQSPEC                  149
#define IDI_ICON_MAIN                   151
#define IDD_PARTICLESPEC_ROTATE         152
#define IDD_PROPERTY_KEYFRAME           155
#define IDR_ACCELERATOR1                156
#define IDD_DIALOG1                     157
#define IDD_SELECTBONEDIALOG            158
#define IDD_EXPORTOPTIONDIALOG          159
#define IDD_COLORKEYDIALOG              160
#define IDD_DLG_OPTION                  161
#define IDD_DIALOG2                     162
#define IDC_CB_PARTICLE_TYPE            1000
#define IDC_ED_UPDATE_INTERVAL          1001
#define IDC_SPIN_UPDATE_INTERVAL        1002
#define IDC_ED_LIFETIME                 1003
#define IDC_SPIN_LIFETIME               1004
#define IDC_ED_OBJECT_LIFETIME          1005
#define IDC_SPIN_OBJECT_LIFETIME        1006
#define IDC_ED_MASSMIN                  1007
#define IDC_ED_MASSMAX                  1008
#define IDC_ED_MAXCOUNT                 1009
#define IDC_SPIN_MAXCOUNT               1010
#define IDC_ED_INITCOUNT                1011
#define IDC_SPIN_INITCOUNT              1012
#define IDC_CHK_VOLATILE                1013
#define IDC_ED_CAPACITYCOUNT            1013
#define IDC_CB_EMIT_TYPE                1014
#define IDC_SPIN_INSTANCECOUNT          1014
#define IDC_SPIN_CAPACITYCOUNT          1014
#define IDC_ED_UP_DIRX                  1015
#define IDC_ED_UP_DIRY                  1016
#define IDC_ED_UP_DIRZ                  1017
#define IDC_ED_EMIT_DIRX                1018
#define IDC_ED_EMIT_DIRY                1019
#define IDC_ED_EMIT_DIRZ                1020
#define IDC_ED_EMIT_ANGLE               1021
#define IDC_SPIN_EMIT_ANGLE             1022
#define IDC_CB_POS_ARG0_TYPE            1023
#define IDC_ED_EMIT_POSX                1023
#define IDC_ED_EMIT_ANGLE2              1024
#define IDC_SPIN_EMIT_ANGLE2            1025
#define IDC_ED_POS_ARG0_CONST           1026
#define IDC_ED_EMIT_POSY                1026
#define IDC_SPIN_POS_ARG0_CONST         1027
#define IDC_ED_EMIT_POSZ                1027
#define IDC_BTN_POS_ARG0_TABLE          1028
#define IDC_ED_EMIT_ANGLE3              1028
#define IDC_ED_POS_ARG0_FACTOR          1029
#define IDC_ED_EMIT_TARGET_MESH_PATH    1029
#define IDC_SPIN_POS_ARG0_FACTOR        1030
#define IDC_CHK_USE_RANDOM              1031
#define IDC_POS_INTERPOLATION           1032
#define IDC_ED_POS_RANDOM_FACTOR_X      1033
#define IDC_CB_POS_ARG1_TYPE            1035
#define IDC_ED_POS_ARG1_CONST           1036
#define IDC_SPIN_POS_ARG1_CONST         1037
#define IDC_BTN_POS_ARG1_TABLE          1038
#define IDC_BTN_TEXTURE                 1038
#define IDC_ED_POS_ARG1_FACTOR          1039
#define IDC_BTN_PLAY                    1039
#define IDC_SPIN_POS_ARG1_FACTOR        1040
#define IDC_BTN_STOP                    1040
#define IDC_ED_STARTTIME                1040
#define IDC_BTN_PAUSE                   1041
#define IDC_ED_DURATION                 1041
#define IDC_POS_GRAVITY                 1041
#define IDC_CB_TYPE                     1042
#define IDC_POS_CLAMP                   1042
#define IDC_BTN_SCENEGRAPH              1043
#define IDC_ED_POS_CLAMP_MIN            1043
#define IDC_ED_POS_CLAMP_MAX            1044
#define IDC_RES_TEXT                    1045
#define IDC_ED_BILLBOARD_FACTOR         1045
#define IDC_BTN_SEQUENCE                1046
#define IDC_CB_SCALE_ARG0_TYPE2         1047
#define IDC_ST_SEQ                      1047
#define IDC_ED_POS_RANDOM_FACTOR_Z      1047
#define IDC_ED_SCALE_ARG0_CONST2        1048
#define IDC_STATIC_TIME                 1048
#define IDC_ED_POS_RANDOM_FACTOR_Y      1048
#define IDC_BTN_REMOVE_SEQUENCE         1048
#define IDC_SPIN_SCALE_ARG0_CONST2      1049
#define IDC_REPEAT                      1049
#define IDC_ED_POS_RANDOM_INTERVAL      1049
#define IDC_BTN_SCALE_ARG0_TABLE2       1050
#define IDC_FRAME_WIDTH                 1050
#define IDC_ED_POS_ARG0_FACTOR2         1051
#define IDC_FRAME_HEIGHT                1051
#define IDC_SPIN_SCALE_ARG0_FACTOR2     1052
#define IDC_FRAME_COUNT                 1053
#define IDC_SCALE_INTERPOLATION         1054
#define IDC_FRAME_INTERVAL              1054
#define IDC_RANDOM                      1055
#define IDC_BUTTON1                     1056
#define IDC_CB_SCALE_ARG1_TYPE2         1057
#define IDC_TEXTURE_WIDTH               1057
#define IDC_ED_SCALE_ARG1_CONST2        1058
#define IDC_TEXTURE_HEIGHT              1058
#define IDC_CB_BLEND_MODE               1058
#define IDC_SPIN_POS_ARG1_CONST2        1059
#define IDC_CB_BLEND_OP                 1059
#define IDC_CB_ROT_ARG0_TYPE            1059
#define IDC_FRAME_INTERVAL2             1059
#define IDC_FRAME_STARTINDEX            1059
#define IDC_BTN_SCALE_ARG1_TABLE2       1060
#define IDC_BTN_ROT_ARG0_TABLE          1060
#define IDC_ED_POS_ARG1_FACTOR2         1061
#define IDC_ED_ROT_ARG0_CONST           1061
#define IDC_SPIN_SCALE_ARG1_FACTOR2     1062
#define IDC_ED_ROT_ARG0_FACTOR          1062
#define IDC_IMAGEVIEW_PLACEHOLDER       1063
#define IDC_UPDATE_INTERVAL             1064
#define IDC_UPDATE_FRAME                1065
#define IDC_FACTOR_X                    1066
#define IDC_INITIAL_RANDOM_FACTOR       1066
#define IDC_FACTOR_X2                   1067
#define IDC_CHECK1                      1067
#define IDC_FACTOR_X3                   1068
#define IDC_EDIT1                       1068
#define IDC_RANDOM_VARIATION            1068
#define IDC_ED_TEX_NAME                 1068
#define IDC_ED_PATH                     1068
#define IDC_ED_R                        1068
#define IDC_ED_WORKFOLDER               1068
#define IDC_EDIT_SND_LOOPCNT            1068
#define IDC_CHK_USE_COLOR_RANDOM        1069
#define IDC_INITIAL_VARIATION           1069
#define IDC_ED_G                        1069
#define IDC_COLOR_INTERPOLATION         1070
#define IDC_ED_B                        1070
#define IDC_ED_COLOR_RANDOM_FACTOR      1071
#define IDC_BONELIST                    1071
#define IDC_ED_R2                       1071
#define IDC_ED_A                        1071
#define IDC_SPIN_COLOR_RANDOM_FACTOR    1072
#define IDC_CHK_ATTACHBONE              1072
#define IDC_CB_COLOR_RGB_TYPE           1073
#define IDC_FPS_PLACEHOLDER             1073
#define IDC_BTN_RGB_TABLE_R             1074
#define IDC_CHK_EXPORT_TEX              1074
#define IDC_ED_RGB_CONST_R              1075
#define IDC_ED_RGB_CONST_G              1076
#define IDC_ED_RGB_CONST_B              1077
#define IDC_BTN_RGB_TABLE_G             1078
#define IDC_BTN_RGB_TABLE_B             1079
#define IDC_CB_COLOR_ALPHA_TYPE2        1080
#define IDC_BTN_RGB_TABLE_ALPHA         1081
#define IDC_ED_RGB_CONST_ALPHA          1082
#define IDC_BTN_EDITKEY                 1083
#define IDC_BTN_EDITALPHAKEY            1084
#define IDC_CB_TEXTYPE                  1084
#define IDC_ED_ZBIAS_SLOPE              1085
#define IDC_ED_ZBIAS_BIAS               1086
#define IDC_CHK_FACETOCAMERA            1087
#define IDC_CHK_LIGHTING                1088
#define IDC_BTN_WORKFOLDER              1088
#define IDC_CHK_DECAL                   1089
#define IDC_CHK_DEPTHWRITE              1090
#define IDC_CHK_DEPTHTEST               1091
#define IDC_STATIC_MESH                 1092
#define IDC_BTN_MESH                    1093
#define IDC_CHECK_RANDOM_MESH           1094
#define ID_FILE_OPENSCENE               32771
#define ID_FILE_OPENSCENEASWORLD        32772
#define ID_FILE_OPENSCENEASSKY          32773
#define ID_FILE_SAVE32774               32774
#define ID_FILE_SAVEAS                  32775
#define ID_FILE_EXIT                    32776
#define ID_TIMETRACKMENU_ENABLE         32777
#define ID_TIMETRACKMENU_DELETE         32778
#define ID_TIMETRACKMENU_SETTOPARTICLE  32779
#define ID_TIMETRACKMENU_LOADSCENE      32780
#define ID_TIMETRACKMENU_SETTOSOUND     32781
#define ID_TIMETRACKMENU_NEWSCENE       32782
#define ID_TIMETRACKMENU_NEWSOUND       32783
#define ID_TIMETRACKMENU_NEWPARTICLE    32784
#define ID_NEWPARTICLE_FOUNTAIN         32785
#define ID_NEWPARTICLE_SMOKE            32786
#define ID_NEWPARTICLE_SHOW             32787
#define ID_NEWPARTICLE_RAIN             32788
#define ID_NEWPARTICLE_SPLINTERS        32789
#define ID_NEWPARTICLE_DUST             32790
#define ID_TIMETRACKMENU_ADDCLONE       32791
#define ID_CONTROL_PLAY                 32792
#define ID_FILE_OPENSCENEASMODEL        32794
#define ID_FILE_EXPORTTOI3S             32795
#define ID_TIMETRACKMENU_DISABLE        32796
#define ID_FILE_REMOVEWORLD             32797
#define ID_FILE_REMOVESKY               32798
#define ID_FILE_REMOVEMODEL             32799
#define ID_FILE_NEWPROJECT              32800
#define ID_MODEL_SELECTBONE             32801
#define ID_TIMETRACKMENU_DUMP           32802
#define ID_TOOLS_OPTIONS                32803
#define ID_TOOLS_BGCOLOR                32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
