; once a semicolon(;) is appeared, all of left string are treated as comments.

;---------------------------------------------------------------------------------------------------------
; Game Server Setting 
[Common]
Gateway				= 1					; 0: GatewayServer, 1:GameServer
Version				= 1					; Version
UdpClientPort		= 29890				; Client P2P UDP PORT
LogFilePath			= "D:\\PBLog\\Game"	; LogFilePath
LobbyChatting		= 1					; 0: NOT USE, 1: USE
NcGameId			= 10				; Korea:34, Thailand:57, Indonesia:10
RelayActive			= 1					; Relay Server Active 0: NOT USE, 1: USE
GameGuard			= 0					; 0: NOT USE, 1:nProtect, 2:AhnHackShield, 3:XTrap
ServerPass			= "password"		; Server Enter Pass ( Max 12 Length )
AbusingCheck		= 1					; 0: NOT USE, 1: USE
;PassEquipCheck		= 1					; 0: CheckEquip, 1: Pass CheckEquip

[Address]
Count				= 1					; Fix
Ip0					= "127.0.0.1"		; Public IP
Port0				= 39190				; PORT
ProxyIp0			= "127.0.0.1"		; Proxy IP (Client Use)
TimeOut0			= 5					; TCP Connect TimeOut 
;---------------------------------------------------------------------------------------------------------

;---------------------------------------------------------------------------------------------------------
; Each Server Setting 
[Trans]
TransServerIp		= "127.0.0.1"		; Trans Server Ip Address(Private IP)
TransServerPort		= 39100				; PORT

[Clan]	
ClanActive			= 0					; 0: NOT USE, 1: USE
ClanServerIp		= "127.0.0.1"		; Private IP 
ClanServerPort		= 39110				; Port

[Messenger]
MessengerActive		= 0					; 0: NOT USE, 1: USE
MessengerServerIp	= "127.0.0.1"		; Private IP 
MessengerServerPort	= 39220				; Port

[Control]
ControlActive		= 1					; 0: NOT USE, 1: USE
ControlServerIp		= "127.0.0.1"		; Private IP
ControlServerPort	= 39120				; 
;---------------------------------------------------------------------------------------------------------

;---------------------------------------------------------------------------------------------------------
;NC Module Setting 
[LogD]									; NC LOGD Server
LogDActive			= 0					; 0: NOT USE, 1: USE
LogDServerIp		= "127.0.0.1"		; IP
LogDServerPort		= 20204				; LogD Port	Korea:10204, Thailand:20204

[Gip]
GipActive			= 0					; 0: NOT USE, 1: USE
GipServerIp			= "192.168.1.1"		; 
GipServerPort		= 30271				; 
;---------------------------------------------------------------------------------------------------------

;---------------------------------------------------------------------------------------------------------
; Channel Type Setting 
;0 : NONE 1 : NORMAL, 2: BEGINNER KILL, 3: BEGINNER  4:CLAN, 5:NONE
[Channel]
ChannelCount		= 10				; Channel Count
ChannelType0		= 1					; 
ChannelType1		= 1					; 
ChannelType2		= 1					; 
ChannelType3		= 1					; 
ChannelType4		= 1					; 
ChannelType5		= 1					; 
ChannelType6		= 1					; 
ChannelType7		= 1					; 
ChannelType8		= 4					; 
ChannelType9		= 4					; 
ChannelSessionCount	= 500				; UserCount of the channel 
ExtraUserCount		= 300				; SuperUser's Count of the channel
;---------------------------------------------------------------------------------------------------------

;---------------------------------------------------------------------------------------------------------
; String Setting 
[Notice]
NormalText			="PB [하자하자] 유저분들은 통합 서버 002에 접속하여 게임하시기를 부탁드립니다.(^0^) "	;
EmergencyText		="--"				; 
;---------------------------------------------------------------------------------------------------------

;---------------------------------------------------------------------------------------------------------
; Hacking Check
[Hack]
HackCheck			= 1					; 0 =  OFF , 1 = ON , 2 = ON BUT NOT USE GRAVITY CHECK
;---------------------------------------------------------------------------------------------------------

;---------------------------------------------------------------------------------------------------------
; CCMode Open
[CCMode]
StingCCModeOpen		= 1					; 0 =  OFF , 1 = ON, 2 = Local_Total에서의 일반공룡사용국가(터키,브라질,필리핀) 사용시
;---------------------------------------------------------------------------------------------------------

[OPTION]
MacAddressCheck		= 1					; 0 = OFF, 1 = ON.