//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by i3Export2.rc
//
#define ID_SELALL                       3
#define ID_UNSELALL                     4
#define ID_REVSEL                       5
#define ID_UPDATE                       6
#define IDS_LIBDESC                     102
#define IDS_CLASSNAME                   103
#define IDD_DIALOG_ABOUT                103
#define IDS_CATEGORY                    104
#define IDB_I3LOGO                      105
#define IDS_FRAME_NAME                  105
#define IDD_OPTION                      106
#define IDS_IMAGE_CLASSNAME             106
#define IDD_TOOLBAR                     107
#define IDS_IMAGE_CATEGORY              107
#define IDD_SELECTBONE                  108
#define IDB_I3LOGO32                    109
#define IDB_I3LOGO16                    110
#define IDD_DIALOG_LOG                  111
#define IDI_I3ICON                      112
#define IDR_POPUP_SELBONE               113
#define IDD_MULTI_EXPORT                114
#define IDR_POPUP_TOOLS                 115
#define IDD_DLG_ADJUSTMATERIAL          116
#define IDD_DLG_IMAGEABOUT              117
#define IDD_DLG_HELP                    119
#define IDD_ROLLUP_PROPERTIES           120
#define IDD_DLG_CONVERT_TGA             122
#define IDD_DLG_OPTIEXP                 124
#define IDD_DLG_OPTIEXP_SETUPOPER       125
#define IDD_DLG_OPTIEXP_TASKPROGRESS    126
#define IDD_DLG_OPTIEXP_SETUP_PARAM     127
#define IDC_CHK_SELECTONLY              1001
#define IDC_CHK_ROTATEAXIS              1002
#define IDC_CHK_EXPORT_LIGHT            1003
#define IDC_CHK_EXPORT_CAMERA           1004
#define IDC_CHK_EXPORT_MESH             1005
#define IDC_CHK_REPORTERR               1006
#define IDC_CHK_EXPORT_ANIM             1007
#define IDC_RAD_KEY_PICKED              1009
#define IDC_RAD_KEY_SAMPLE              1010
#define IDC_BTN_SELBONE                 1011
#define IDC_ED_INTERVAL                 1012
#define IDC_ED_NAME                     1014
#define IDC_BTN_EXPORT                  1015
#define IDC_BTN_OPTION                  1016
#define IDC_ED_PATH                     1017
#define IDC_BTN_PATH                    1018
#define IDC_BONETREE                    1019
#define IDC_BTN_EXPORT2                 1019
#define IDC_BTN_SEL_EXPORT              1019
#define IDC_BTN_LOG                     1021
#define IDC_LIST_LOG                    1022
#define IDC_CHK_EXPORT_I3S              1024
#define IDC_ED_EXCLUDE_NODENAME         1025
#define IDC_BTN_SELECT                  1026
#define IDC_ED_EXPORT_PATH              1027
#define IDC_BTN_EXPORT_PATH             1028
#define IDC_BTN_GO                      1029
#define IDC_ED_PREFIX                   1030
#define IDC_FILECOUNT                   1031
#define IDC_BTN_MULTIEXPORT             1032
#define IDC_CHK_FORCE_EXPORT_ANIM       1034
#define IDC_BTN_POPUP                   1035
#define IDC_ED_A_R                      1036
#define IDC_ED_A_G                      1037
#define IDC_ED_A_B                      1038
#define IDC_ED_A_A                      1039
#define IDC_ED_D_R                      1040
#define IDC_ED_D_G                      1041
#define IDC_ED_D_B                      1042
#define IDC_ED_D_A                      1043
#define IDC_ED_S_R                      1044
#define IDC_ED_S_G                      1045
#define IDC_ED_S_B                      1046
#define IDC_ED_S_A                      1047
#define IDC_ED_S_LEVEL                  1048
#define IDC_ED_GLOSS                    1049
#define IDC_ST_A                        1052
#define IDC_ST_D                        1053
#define IDC_ST_S                        1054
#define IDC_CHECK1                      1055
#define IDC_CHK_PREVIEW                 1055
#define IDC_CHK_FORCEEXPORT             1055
#define IDC_ED_SKINWIDTH                1056
#define IDC_CHK_EXPORT_PHYSICSGEOM      1057
#define IDC_CHK_EXPORT_SHAPE_AS_CONVEX  1059
#define IDC_BTN_HELP                    1060
#define IDC_STATIC_HELP                 1061
#define IDC_CHK_CREATE_RAPPING_CONVEX   1062
#define IDC_CB_REVERBTYPE               1063
#define IDC_EDIT_THICKNESS              1064
#define IDC_CHECK_OPTION_SM             1065
#define IDC_EDIT_PORTAL                 1065
#define IDC_CHK_TREATASBONE             1066
#define IDC_TEX_LIST                    1067
#define IDC_CB_PHYSICSTYPE              1070
#define IDC_BTN_PROXY                   1071
#define IDC_CHK_NODENAMEFM              1073
#define IDC_BTN_OPTIEXPORT              1074
#define IDC_OPTIEXP_CTLSTART            1080
#define IDC_OPTIEXP_CB_EXPSETTINGS      1081
#define IDC_OPTIEXP_BT_SETUP_EXPORTER   1082
#define IDC_OPTIEXP_LV_OPER             1083
#define IDC_OPTIEXP_BT_SETUP_OPER       1084
#define IDC_OPTIEXP_BT_OPER_SETUP       1085
#define IDC_OPTIEXP_BT_EXPORT           1086
#define IDC_OPTIEXP_ST_OPER_DESC        1087
#define IDC_OPTIEXP_CK_LOGGINGTOFILE    1088
#define IDC_OPTIEXP_ST_PHYSX_COOKLIB    1089
#define IDC_OPTIEXP_ST_VER              1090
#define IDC_OPTIEXP_SETUPOPER_ST_AREA   1095
#define IDC_OPTIEXPTP_PB_00             1096
#define IDC_OPTIEXPTP_ST_00             1097
#define IDC_OPTIEXPTP_ST_01             1098
#define IDC_OPTIEXP_CTLEND              1100
#define IDC_BTN_UPPER                   1112
#define IDC_BTN_LOWER                   1113
#define IDC_BTN_ALL                     1114
#define IDC_BTN_ALLBIPED                1114
#define ID_SELBONE_SELECTALLCHILDREN    40001
#define ID_SELBONE_UNSELECTALLCHILDREN  40002
#define ID_TOOLS_ADJUSTALLMATERIALS     40003
#define ID_TOOLS_CONVERTTEXTURETOTGAFORMAT 40004
#define ID_TOOLS_MATCHMATERIALNAMESWITHTEXTURES 40005
#define ID_TOOLS_CHECKCOLLISIONMESHES   40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
