//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ItemTool.rc
//
#define ID_PANEL_SCENEGRAPH             100
#define IDD_ABOUTBOX_ITEMTOOL           101
#define IDB_WRITESMALL                  102
#define IDB_WRITELARGE                  103
#define IDB_MAIN                        104
#define IDB_BUTTONS                     105
#define IDB_FILELARGE                   106
#define IDB_FILESMALL                   107
#define IDR_POPUP_EDIT                  108
#define ID_STATUSBAR_PANE1              109
#define ID_STATUSBAR_PANE2              110
#define IDS_STATUS_PANE1                111
#define IDS_STATUS_PANE2                112
#define IDS_SHORTCUTS                   113
#define IDS_OUTLOOKBAR                  114
#define IDS_FOLDERS                     115
#define IDR_MAINFRAME_ITEMTOOL          116
#define IDR_MAINFRAME_256               117
#define IDR_ItemToolTYPE                118
#define IDR_PASTE_MENU                  119
#define IDR_WINDOWS_MENU                120
#define ID_VIEW_NAVIGATION              121
#define IDR_THEME_MENU                  122
#define ID_SET_STYLE                    123
#define ID_VIEW_APPLOOK_WIN_2000        124
#define ID_VIEW_APPLOOK_OFF_XP          125
#define ID_VIEW_APPLOOK_WIN_XP          126
#define ID_VIEW_APPLOOK_OFF_2003        127
#define ID_VIEW_APPLOOK_VS_2005         128
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   129
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  130
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 131
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   132
#define IDS_RIBBON_FILE                 133
#define IDS_RIBBON_NEW                  134
#define IDS_RIBBON_OPEN                 135
#define IDS_RIBBON_SAVE                 136
#define IDS_RIBBON_SAVEAS               137
#define IDS_RIBBON_PRINT                138
#define IDS_RIBBON_PRINT_LABEL          139
#define IDS_RIBBON_PRINT_QUICK          140
#define IDS_RIBBON_PRINT_PREVIEW        141
#define IDS_RIBBON_PRINT_SETUP          142
#define IDS_RIBBON_CLOSE                143
#define IDS_RIBBON_RECENT_DOCS          144
#define IDS_RIBBON_EXIT                 145
#define IDS_RIBBON_HOME                 146
#define IDS_RIBBON_CLIPBOARD            147
#define IDS_RIBBON_PASTE                148
#define IDS_RIBBON_CUT                  149
#define IDS_RIBBON_COPY                 150
#define IDS_RIBBON_SELECTALL            151
#define IDS_RIBBON_WINDOW               152
#define IDS_RIBBON_WINDOWS              153
#define IDS_RIBBON_STYLE                154
#define IDS_RIBBON_STYLE_TIP            155
#define IDS_RIBBON_STYLE_DESC           156
#define IDS_RIBBON_STATUSBAR            157
#define IDS_RIBBON_VIEW                 158
#define IDS_EDIT_MENU                   159
#define ID_PANEL_ATTR                   160
#define ID_PANEL_PROPERTY               161
#define IDR_TOOLBAR1                    162
#define IDB_BITMAP1                     163
#define IDR_TOOLBAR2                    164
#define IDB_BITMAP3                     165
#define IDR_TOOLBAR_MENU                166
#define IDD_WEAPON_EDIT                 167
#define IDD_WEAPON_RESLIST              168
#define IDD_WEAPON_TIME_TRACK           169
#define IDR_TOOLBAR3                    170
#define IDD_DLG_SELECTSOUND             171
#define IDD_SELECTSOUND                 172
#define IDD_DLG_ADD_RESOURCE            173
#define IDD_ADD_RESOURCE                174
#define IDB_PAGES                       175
#define IDB_PAGES_HC                    176
#define IDB_PAGES_SMALL                 177
#define IDB_PAGES_SMALL_HC              179
#define IDD_PANEL_TEMP                  180
#define IDD_DLG_FILE_LOADER             181
#define IDD_AIDRIVER_LIST               182
#define IDD_NEW_WEAPON                  183
#define IDC_WEAPON_ANI                  184
#define IDC_WEAPON_RESLIST              185
#define IDC_RSC_TREE                    186
#define IDC_WEAPON_RENDERING            187
#define IDC_WEAPON_TRACK                188
#define IDC_WEAPON_TRACK2               189
#define IDC_WEAPON_PROP                 190
#define IDC_SLIDER1                     191
#define IDC_SOUND_LIST                  192
#define IDC_TREE_EXPLORER               193
#define IDC_LIST_FILES                  194
#define IDC_CHECK_FILE_ALL              195
#define IDC_CHECK_FILE_I3S              196
#define IDC_EDIT_PATH                   197
#define IDC_CHECK_FILE_I3I              198
#define IDC_CHECK_FILE_WAV              199
#define IDC_CHECK_FILE_ALL2             200
#define IDC_CHECK_FILE_WEAPON           201
#define IDC_SUBPATH_WEAPON              202
#define IDC_CHECK_FILE_I3S2             203
#define IDC_SUBPATH_WAV                 204
#define IDC_BTN_RES_ADD                 205
#define IDC_OPEN_PATH_DLG               206
#define IDC_BTN_FOLDER_ADD              207
#define IDC_CHECK_FILE_WAV2             208
#define IDC_SUBPATH_ROOT                209
#define IDC_BTN_OPEN_RESDLG             210
#define IDC_BTN_OPEN_AIDRIVER           211
#define IDC_LIST_AIDRIVER               212
#define IDC_BTN_ADD_AI_ENUM             212
#define IDC_LIST_AIDRIVER_WEAPON        213
#define IDC_BTN_CREATE                  214
#define IDC_BTN_FOLDER_DEL              215
#define IDC_BTN_CREATE2                 215
#define IDC_BTN_SAVE                    215
#define IDC_LIST_AIDRIVER_TABLE         216
#define IDC_ADD_WEAPON                  217
#define IDC_COMBO_WEAPON_LIST           218
#define IDC_EDIT_NEW_WEAPON_NAME        219
#define IDC_BUTTON_DO_CLONE             220
#define IDC_LIST_CURR_WEAPONS           221
#define IDC_EDIT_SEARCH_WEAPON          222
#define IDC_SELECTED_WEAPON_NAME        223
#define IDC_RES_NAME                    224
#define IDC_RADIO_AIDRIVER_SEARCH       225
#define IDC_RADIO_WEAPON_SEARCH         226
#define IDC_RADIO_TABLE_SEARCH          227
#define ID_WRITE_PASTEASHYPERLINK       228
#define ID_TOOLBAR_BTN1                 229
#define ID_TOOLBAR_BTN2                 230
#define ID_VIEW_WEAPON_TAB              231
#define ID_VIEW_GOODS_TAB               232
#define ID_VIEW_CHARACTER_TAB           233
#define ID_VIEW_ABILITY_TAB             234
#define ID_VIEW_EQUIPMENT_TAB           235
#define ID_WEAPON_ID                    236
#define ID_BTN_WEAPON_EDITOR            237
#define ID_SCROLLBAR_MAINVIEW           238
#define ID_222_ID                       239
#define ID_EDIT_PATH                    240
#define IDD_AI_ENUM_LIST                347
#define IDC_BUTTON_CREATE_NEW_WEAPON    1032
#define IDC_LIST_AI_ENUM_LIST           1033
#define IDC_LIST_AI_ENUM_LIST2          1034
#define IDC_EDIT_ENUM_EXPLAIN           1035
#define IDC_BUTTON_ADD_ENUM             1037
#define IDC_NEW_EXPLAIN                 1039
#define IDC_COMBO_PANNEL_CATEGORY       1040
#define IDC_CHECK1                      1041
#define IDC_CHECK_DO_ROTATE             1041

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        350
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
