; once a semicolon(;) is appeared, all of left string are treated as comments.

;---------------------------------------------------------------------------------------------------------
[Default]
Ip				= "127.0.0.1"				; Private IP
Port				= 39220					; Private Port
LogFilePath			= "d:\\PBLog\\Messenger"		; LogFilePath
ErrorLogFilePath		= "d:\\PBLog\\Messenger"		; Update Error(Nick, Rank)
;---------------------------------------------------------------------------------------------------------

;---------------------------------------------------------------------------------------------------------
[Control]								; Control Server 
ControlServerIp			= "127.0.0.1"				;
ControlServerPort		= 39120					;
;---------------------------------------------------------------------------------------------------------

[Dev]	; 개발서버 용도로만 사용하는 필드입니다. 릴리즈버전에는 배포하지 마세요.
UC			= 1000					; 