#if !defined( __COMMON_DEF_H__)
#define __COMMON_DEF_H__

enum GIC_SHAPE_MODE
{
	GIC_SHAPE_MODE_NONE = -1,
	GIC_SHAPE_MODE_RECT,
	GIC_SHAPE_MODE_RECTBAR,
	GIC_SHAPE_MODE_CIRCLE,
	GIC_SHAPE_MODE_CIRCLEBAR,
	GIC_SHAPE_MODE_TEXT,
};

enum PANE_MODE
{
	PANE_MODE_NONE = -1,
	PANE_MODE_SHAPE,
	PANE_MODE_DESIGN,
};

enum WM_GIC
{
	WM_GIC_SELECTSHAPE = (WM_USER + 510),
	WM_GIC_UNSELECTSHAPE,
};

#endif
