//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by i3GICShapeTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_i3GICShapeToolTYPE          130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_CAPTIONBAR           295
#define IDS_EDIT_MENU                   306
#define IDD_PANE_TEMPLATE               310
#define IDD_PANE_SHAPES                 311
#define IDD_PANE_PREVIEW                312
#define IDD_PANE_SPECIFIC               313
#define IDD_PANE_LOG                    314
#define IDD_PANE_DESIGN                 315
#define IDD_DLG_DIAGRAMVIEW             316
#define IDR_TOOLBAR1                    318
#define IDR_TOOLBAR2                    322
#define IDR_TOOLBAR3                    324
#define IDR_TOOLBAR4                    326
#define IDR_MENU1                       328
#define IDR_DUMMY_MENU                  328
#define IDR_WRITE_FONTCASE_MENU         329
#define IDR_FONT                        332
#define IDD_RIBBON                      336
#define IDR_SHAPETOOLS                  337
#define IDR_POPUP_TEMPLATE              340
#define IDB_BTN_MODE                    341
#define IDC_LIST_SHAPES                 1001
#define IDC_COMBO2                      1004
#define IDC_LIST_SPECIFIC               1011
#define IDC_CHK_RIBBON_GRID             1012
#define IDC_LIST_TEMPLATE               1013
#define IDC_CB_FONT                     1014
#define IDC_CB_FONTSIZE                 1015
#define IDC_CB_MAGNETIC                 1016
#define IDC_CHK_MAGNETIC                1016
#define IDC_CHK_GRIDSNAP                1016
#define IDC_CHK_LINKSNAP                1019
#define IDC_SPIN1                       1020
#define IDC_SPIN_GRIDSIZE               1020
#define IDC_BTN_MODE_SELECT             1021
#define IDC_BUTTON2                     1022
#define IDC_BTN_MODE_LINK               1022
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_EDIT_32771                   32771
#define ID_EDIT_DELETE                  32772
#define ID_FONT_COLOR                   32773
#define ID_FONT_BKCOLOR                 32774
#define ID_FONT_UNDERLINE               32775
#define ID_FONT_HIGHLIGHT               32776
#define ID_FONT_STOP_HIGHLIGHT          32777
#define ID_WRITE_FONT                   32778
#define ID_BTN_SHAPETOOLS_ALIGN_LEFT    32780
#define ID_BTN_SHAPETOOLS_ALIGN_CENTER  32781
#define ID_BTN_SHAPETOOLS_ALIGN_RIGHT   32782
#define ID_BTN_SHAPETOOLS_ALIGN_TOP     32783
#define ID_BTN_SHAPETOOLS_ALIGN_MIDDLE  32784
#define ID_BTN_SHAPETOOLS_ALIGN_BOTTOM  32785
#define ID_NEWTEMPLATE_DELETETEMPLATE   32786
#define ID_NEWTEMPLATE_COPYTEMPLATE     32787
#define ID_NEWTEMPLATE_PASTETEMPLATE    32788
#define ID_TEMPLATE_NEWTEMPLATE         32789
#define ID_TEMPLATE_COPY                32790
#define ID_TEMPLATE_NEW                 32791
#define ID_NEWTEMPLATE_PASTE            32792
#define ID_NEWTEMPLATE_DELETE           32793
#define ID_TEMPLATE_PASTE               32794
#define ID_TEMPLATE_DELETE              32795
#define ID_FONT_ITALIC                  32796
#define ID_FONT_STRETCH                 32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        342
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
