@echo off


set LOCALE=Turkey
set EXE_NAME=PointBlank
set EXEC_NAME=PointBlank
set LOG_PATH=.
set EXE_ROOT=%CLIENT_EXES%\TurkeyLive
set EXE_LIVE_FILE_DIR=%EXE_ROOT%
set BUILD_NAME=%LOCALE%_Live
set DIST_TYPE=Default
set SECURITY_TYPE=Null
set SECURITY_TYPE=HackShield_NoThemida
set SECURITY_PATH=HackShield_R.5.7.3.1(Build467)
set HSB_OUTPUT_PATH=%PB_SRC_ROOT%\HackShield\Server\HackShield_Turkey
set BUILD_CONFIG_QA=%CONFIG_QA%_%LOCALE%
set BUILD_CONFIG_LIVE=%CONFIG_Live%_%LOCALE%
set BUILD_RESULT_QA=%PB_SRC_ROOT%\ClientSource\%BUILD_CONFIG_QA%
set BUILD_RESULT_LIVE=%PB_SRC_ROOT%\ClientSource\%BUILD_CONFIG_LIVE%
