@echo off


set LOCALE=Russia
set EXE_NAME=PointBlank
set EXEC_NAME=PointBlank
set LOG_PATH=.
set EXE_ROOT=%CLIENT_EXES%\RussiaLive
set EXE_LIVE_FILE_DIR=%EXE_ROOT%\Distribute
set BUILD_NAME=%LOCALE%_Live
set DIST_TYPE=NC_Distribute
set SECURITY_TYPE=Themida_Russia
set SECURITY_PATH=Themida
set Enc_WinLockDLL=0
set BUILD_CONFIG_QA=%CONFIG_QA%_%LOCALE%
set BUILD_CONFIG_LIVE=%CONFIG_Live%_%LOCALE%
set BUILD_RESULT_QA=%PB_SRC_ROOT%\ClientSource\%BUILD_CONFIG_QA%
set BUILD_RESULT_LIVE=%PB_SRC_ROOT%\ClientSource\%BUILD_CONFIG_LIVE%

