#ifndef __I3UILISTVIEW_H__
#define __I3UILISTVIEW_H__

enum ECELLTYPE
{
	ECELLTYPE_TEXT = 0,
	ECELLTYPE_IMAGE,
	ECELLTYPE_TEMPLATE,

	ECELLTYPE_COUNT
};

static const char* s_pszCellType[ECELLTYPE_COUNT] = 
{
	"Text",
	"Image",
	"Template"
};

enum ECOMMAND_SCOPE
{
	ECOMMAND_SCOPE_ALL = 0,
	ECOMMAND_SCOPE_HEADER,
	ECOMMAND_SCOPE_ITEM,
	ECOMMAND_SCOPE_ROW,
	ECOMMAND_SCOPE_COLUMN,
	ECOMMAND_SCOPE_CELL,
	ECOMMAND_SCOPE_DATA,
	ECOMMAND_SCOPE_BOX,

	ECOMMAND_SCOPE_COUNT
};

#endif //__I3UILISTVIEW_H__