//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// i3UIAnimation.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_ANIMATION_ADD               105
#define IDD_UV_IMAGELIST                106
#define IDD_IMAGELIST                   106
#define IDD_ANIMATIONLIST               107
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MFCApplication2TYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDB_ICONS_24                    312
#define IDB_BITMAP1                     313
#define IDB_ICONS_32                    315
#define IDI_ICON_BTN                    323
#define IDR_ANIMATION                   323
#define IDI_ICON_BTN_SEL                324
#define IDI_ICON_CHECK                  325
#define IDI_ICON_CHECK_SEL              326
#define IDI_ICON_COMBO                  327
#define IDI_ICON_COMBO_SEL              328
#define IDI_ICON_EDIT                   329
#define IDI_ICON_EDIT_SEL               330
#define IDI_ICON_FRAMEWND               331
#define IDI_ICON_FRAMEWND_SEL           332
#define IDI_ICON_GROUPCTRL              333
#define IDI_ICON_GROUPCTRL_SEL          334
#define IDI_ICON_HSCROLLBAR             335
#define IDI_ICON_HSCROLLBAR_SEL         336
#define IDI_ICON_LISTBOX                337
#define IDI_ICON_LISTBOX_SEL            338
#define IDI_ICON_PROGRESS               339
#define IDI_ICON_PROGRESS_SEL           340
#define IDI_ICON_RADIO                  341
#define IDI_ICON_RADIO_SEL              342
#define IDI_ICON_STATICIMAGE            343
#define IDI_ICON_STATICIMAGE_SEL        344
#define IDI_ICON_SLIDER                 345
#define IDI_ICON_SLIDER_SEL             346
#define IDI_ICON_SPIN                   347
#define IDI_ICON_SPIN_SEL               348
#define IDI_ICON_STATICTEXT             349
#define IDI_ICON_STATICTEXT_SEL         350
#define IDI_ICON_TABCTRL                351
#define IDI_ICON_TABCTRL_SEL            352
#define IDI_ICON_TREECTRL               353
#define IDI_ICON_TREECTRL_SEL           354
#define IDI_ICON_UIFILTER               355
#define IDI_ICON_UIFILTER_SEL           356
#define IDI_ICON_UIHIDE                 357
#define IDI_ICON_UILOCK                 358
#define IDI_ICON_UIUNLOCK               359
#define IDI_ICON_UISCREEN               360
#define IDI_ICON_UISCREEN_SEL           361
#define IDI_ICON_UISHOW                 362
#define IDI_ICON_VSCROLLBAR             363
#define IDI_ICON_VSCROLLBAR_SEL         364
#define IDB_TEMPLATE_EXPLORER_TOOLBAR   389
#define IDB_TEMPLATE_EXPLORER_REPORT    393
#define IDB_TEMPLATE_EXPLORER_ICON      397
#define IDI_ICON_SUBSET                 399
#define IDI_ICON_PROGRESS_IMAGE         403
#define IDI_ICON_PROGRESS_IMAGE_SEL     404
#define IDI_ICON_PROGRESS_SPLIT_SEL     405
#define IDI_ICON_PROGRESS_SPLIT         406
#define IDC_BUTTON1                     1000
#define IDC_BUTTON_OK                   1000
#define IDC_TREE_RESOURCELIST           1001
#define IDC_BUTTON_CANCEL               1001
#define IDC_LIST_UVSHAPE                1002
#define IDC_LIST_UVLIST                 1004
#define IDC_UVLIST                      1006
#define IDC_EDIT_TITLE                  1007
#define IDC_EDIT_LIFETIME               1008
#define IDC_LIST_ANIMATION              1008
#define IDC_SPIN1                       1009
#define ID_PROJECT_PATH                 32771
#define ID_Menu                         32772
#define ID_VIEW_MESH                    32774
#define d                               32774
#define ID_VIEW_NORMAL                  32775
#define ID_VIEW_COLLIDER                32777
#define ID_ANIMATION_REMOVE             32777
#define ID_SAVE_ANIMATIONLIST           32778
#define ID_VIEW_WIRE                    32779
#define ID_OPEN_ANIMATIONLIST           32779
#define ID_NEW_ANIMATION                32780
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_SPLIT                 0xE135
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        324
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
