//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BuildTool.rc에서 사용되고 있습니다.
//
#define ID_ADD_COUNTRY                  3
#define ID_DELETE_COUNTRY               4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_BuildToolTYPE               130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_PROGRESS             310
#define IDD_DIALOG_LOADING_PROGRESS     310
#define IDD_DIALOG_COUNTRY_SETTING      314
#define IDD_CONTENTSVIEW_TOOLBAR        320
#define IDD_DIALOG_SYNCPLAYER           322
#define IDB_BITMAP1                     324
#define IDD_DIALOG1                     325
#define IDD_DIALOG_VERSION_SETTING      325
#define IDD_DIALOG_SHADER_SYNC          327
#define IDD_DIALOG_PACKTOOL             331
#define IDD_DIALOG_MAKE_I3PACK_NAME     333
#define IDD_DIALOG_PACKEDFILESEARCH     335
#define IDD_DIALOG_DUPLICATED_PACKFILES 341
#define IDC_EDIT_SEARCH_CONTENTS        1005
#define IDC_STATIC_FINDBYKEYWORDS       1007
#define IDC_STATIC_CONTENTSVIEW_TOPIC   1008
#define IDC_BUTTON_FORCE_COPY_MODE      1009
#define IDC_BUTTON_PLAY_ALL_MODE        1010
#define IDC_BUTTON_PLAY                 1011
#define IDC_PROGRESS_SYNC               1012
#define IDC_BUTTON_EXPORT_PEF_RSC       1013
#define IDC_STATIC_CURR_SYNC_CONTENTS_NAME 1015
#define IDC_STATIC_CURR_SYNC_COUNTRY_NAME 1016
#define IDC_STATIC_BKGND_BOTTOM         1018
#define IDC_STATIC_LOADING_WHAT         1019
#define IDC_RADIO_ORIGIN                1025
#define IDC_RADIO_FILE_SHADER_ORIGIN_MODE 1025
#define IDC_RADIO_FORMAT                1026
#define IDC_RADIO_COMBINE               1027
#define IDC_RADIO_FILE_SHADER_COMBINE_MODE 1027
#define IDC_GRPBOX_FILE_SHADER_VIEW     1028
#define IDC_GRPBOX_MEMORY_SHADER_VIEW   1029
#define IDC_BUTTON_SYNC_SHADERS         1030
#define IDC_GRPBOX_FILE_SHADER_LIST     1031
#define IDC_GRPBOX_MEMORY_SHADER_LIST   1032
#define IDC_MFCEDITBROWSE_I3ENGINE_PATH 1033
#define IDC_RADIO_MEMORY_SHADER_ORIGIN_MODE 1033
#define IDC_RADIO_MEMORY_SHADER_DECRYPT_MODE 1035
#define IDC_EDIT_FILE_SHADER            1036
#define IDC_EDIT_MEMORY_SHADER          1037
#define IDC_PROGRESS_SYNC_TEXT          1037
#define IDC_RADIO_MEMORY_SHADER_DECRYPT_COMBINED_MODE 1038
#define IDC_STATIC_PACKTOOL_SOURCE_PATH 1038
#define IDC_STATIC_PACKTOOL_PACK_PATH   1039
#define IDC_BUTTON_PACKTOOL_NEWPACK     1041
#define IDC_BUTTON_PACKTOOL_SAVEPACK    1042
#define IDC_EDIT_I3PACK_NAME            1042
#define IDC_BUTTON_PACKTOOL_ADDFILE     1043
#define IDC_STATIC_I3PACK_NAME          1043
#define IDC_BUTTON_PACKTOOL_ADDFOLDER   1044
#define IDC_EDIT_PACKEDFILESEARCH       1045
#define IDC_BUTTON_PACKEDFILESEARCH     1046
#define IDC_STATIC_PACKEDFILESEARCH     1047
#define IDC_COMBO_NATION                1048
#define IDC_BUTTON_REFRESH              1049
#define IDC_LIST_DUPLICATED_PACKFILES   1051
#define IDC_LIST_DEST_PACKFILES         1053
#define IDC_EDIT_SAVEPATH               1054
#define IDC_BUTTON_OK                   1055
#define IDC_LIST_DUPLICATED_PACKINNERFILES 1056
#define IDC_BUTTON_EXPLOLER             1057
#define IDC_CHECK_EXPORT_LOG            1058
#define IDC_CHECK_DUPLICATEDFILES       1059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        343
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
