USE [PBOption]
/***************************************
* DELETE ALL INFO
***************************************/
DELETE dbo.PB_BT_Medal_Normal
DELETE dbo.PB_BT_Medal_Set

/***************************************
* INSERT Normal Medal
***************************************/
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(1, N'Flaming Trench', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(2, N'Rules of Battlefield', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(3, N'The Fuse', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(4, N'Assault Rifle Master', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(5, N'SMG Master', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(6, N'Shotguns Maser', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(7, N'Sniper Master', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(8, N'Handgun Master', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(9, N'Assassin', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(10, N'Firestorm', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(11, N'Trapper', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(12, N'Dual Shock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(13, N'Triple Shock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(14, N'AirHole', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(16, N'AK-47 Ext. Predator', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(17, N'MP5K Ext. Predator', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(18, N'PSG1 Predator', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(19, N'MK46 Ext. Predator', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(20, N'SPAS-15 Predator', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(21, N'Winner', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(22, N'Deathmatch Master', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(23, N'Elimination Master', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(24, N'Demolition Master', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(25, N'Master Huntsman', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(26, N'Rifle Master', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(27, N'SMG Sweeper', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(28, N'Terminator', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(29, N'Sharpshooter', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(30, N'Outlaw', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(31, N'Assassin2', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(32, N'Bomberman', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(33, N'Rambo', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(35, N'Deathmatch Conquerer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(36, N'Bomb Conquerer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(37, N'Elimination Conquerer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(38, N'Defense Conquerer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(39, N'Destroy Conquerer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(40, N'Cross-Counter Conquerer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(41, N'Escape Conquerer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(42, N'Dino Killer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(43, N'Dual Shock2', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(44, N'Triple Shock2', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(45, N'Chain Killer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(46, N'Bomb Blaster', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(47, N'Satay', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(48, N'Ace Runner', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(49, N'Destroyer', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(50, N'Winchester M70 Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(51, N'M1887 Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(52, N'P90 Ext Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(53, N'SPAS-15 Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(54, N'Glock 18 Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(55, N'AK SOPMOD Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(56, N'AUG A3 Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(57, N'L115A1 Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(58, N'Kriss SuperV Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(59, N'Dual Desert Eagle Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(60, N'C.Python Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(61, N'SC-2010 Unlock', N'')
INSERT INTO dbo.PB_BT_Medal_Normal (i16MedalIdx, strMedalName, strDescription) VALUES(62, N'OA-93 Unlock', N'')

/***************************************
* INSERT Set Medal
***************************************/
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(35, 8, 2, N'Kill 25 players in Machu Pichu', N'SMDAILY21', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(36, 8, 2, N'Kill 25 players in Red Rock', N'SMDAILY21', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(37, 8, 2, N'Win Eliminate mode 5times', N'SMDAILY21', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(38, 8, 2, N'Kill 25 players in Library', N'SMDAILY21', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(39, 8, 2, N'Kill 25 players in MStation', N'SMDAILY21', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(40, 8, 2, N'Win Deathmatch mode 5 times', N'SMDAILY21', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(41, 9, 2, N'Kill 25 players in Midnight Zone', N'SMDAILY22', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(42, 9, 2, N'Kill 25 players in Downtown', N'SMDAILY22', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(43, 9, 2, N'Win Escape mode 5 times', N'SMDAILY22', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(44, 9, 2, N'Kill 25 players in Burning Hall', N'SMDAILY22', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(45, 9, 2, N'Kill 25 players in Crackdown', N'SMDAILY22', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(46, 9, 2, N'Kill 25 players in Midnight Zone', N'SMDAILY22', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(47, 10, 2, N'Kill 25 players in Luxville', N'SMDAILY23', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(48, 10, 2, N'Kill 25 players in Storm Tube', N'SMDAILY23', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(49, 10, 2, N'Headshot 20 players', N'SMDAILY23', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(50, 10, 2, N'Kill 25 players in Training Camp', N'SMDAILY23', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(51, 10, 2, N'Kill 25 players in Desert Camp', N'SMDAILY23', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(52, 10, 2, N'Eliminate 15 enemies with AR', N'SMDAILY23', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(53, 11, 2, N'Kill 25 players in Outpost', N'SMDAILY24', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(54, 11, 2, N'Kill 25 players in Eastern Road', N'SMDAILY24', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(55, 11, 2, N'Eliminate 15 enemies with SMG', N'SMDAILY24', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(56, 11, 2, N'Kill 25 players in Breeding Nest', N'SMDAILY24', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(57, 11, 2, N'Kill 25 players in Sand Storm', N'SMDAILY24', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(58, 11, 2, N'Eliminate 15 enemies with Shotgun', N'SMDAILY24', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(59, 12, 2, N'Kill 25 players in Saint Mansion', N'SMDAILY25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(60, 12, 2, N'Kill 25 players in Supply Base', N'SMDAILY25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(61, 12, 2, N'Eliminate 15 enemies with Shotgun', N'SMDAILY25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(62, 12, 2, N'Eliminate 15 enemies with Sniper Rifle', N'SMDAILY25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(63, 12, 2, N'Kill 25 players in Kick Point', N'SMDAILY25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(64, 12, 2, N'Eliminate 15 enemies with Handgun', N'SMDAILY25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(65, 13, 2, N'Kill 10 Time in BlueTeam', N'VTDAILY13', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(66, 13, 2, N'Kill 5 Time in MStation', N'VTDAILY13', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(67, 13, 2, N'Kill 5 Time in MachuPichu', N'VTDAILY13', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(68, 13, 2, N'Kill 5 Time in OutPost', N'VTDAILY13', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(69, 13, 2, N'Kill 5 Time in EsternRoad', N'VTDAILY13', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(70, 13, 2, N'Kill 5 Time in TrainingCamp', N'VTDAILY13', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(71, 14, 2, N'Kill 10 Time in RedTeam', N'VTDAILY14', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(72, 14, 2, N'Kill 5 Time in SandStorm', N'VTDAILY14', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(73, 14, 2, N'Kill 5 Time in BreedingNest', N'VTDAILY14', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(74, 14, 2, N'Kill 5 Time in MidnightZone', N'VTDAILY14', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(75, 14, 2, N'Kill 5 Time in CrackDown', N'VTDAILY14', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(76, 14, 2, N'Kill 5 Time in PortAkaba', N'VTDAILY14', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(77, 15, 2, N'Kill 1~3 Rank Player 5 Times', N'VTDAILY15', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(78, 15, 2, N'Kill 5 Time in RedRock', N'VTDAILY15', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(79, 15, 2, N'Kill 5 Time in Library', N'VTDAILY15', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(80, 15, 2, N'Kill 5 Time in DownTown', N'VTDAILY15', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(81, 15, 2, N'Kill 5 Time in SaintMansion', N'VTDAILY15', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(82, 15, 2, N'Kill 5 Time in BurningHoll', N'VTDAILY15', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(83, 16, 2, N'Kill 5 Time in Luxvill', N'VTDAILY16', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(84, 16, 2, N'Kill 4~6 Rank Player 5 Times', N'VTDAILY16', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(85, 16, 2, N'Kill 5 Time in StormTube', N'VTDAILY16', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(86, 16, 2, N'Kill 5 Time in DesertCamp', N'VTDAILY16', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(87, 16, 2, N'Kill 5 Time in SupplyBase', N'VTDAILY16', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(88, 16, 2, N'Kill 7~9 Rank Player 5 Times', N'VTDAILY16', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(89, 17, 2, N'Kill 5 Time in MStation', N'TestQuest', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(90, 17, 2, N'Kill 5 Time in MStation', N'TestQuest', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(91, 17, 2, N'Kill 5 Time in MStation', N'TestQuest', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(92, 17, 2, N'Kill 5 Time in MStation', N'TestQuest', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(93, 17, 2, N'Kill 5 Time in MStation', N'TestQuest', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(94, 17, 2, N'Kill 5 Time in MStation', N'TestQuest', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(95, 18, 2, N'Enter Balttle 1 Time', N'MasterMedal', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(132, 25, 2, N'Kill 10 players in RedTeam', N'PH_Daily_25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(133, 25, 2, N'Kill 10 players in BlueTeam', N'PH_Daily_25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(134, 25, 2, N'Kill 5 players(Rank1~3)', N'PH_Daily_25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(135, 25, 2, N'Kill 5 players(Rank4~6)', N'PH_Daily_25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(136, 25, 2, N'Kill 5 players(Rank7~9)', N'PH_Daily_25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(137, 25, 2, N'Kill 5 players in PortAkaba', N'PH_Daily_25', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(138, 26, 2, N'Kill 5 players in MachuPichu', N'PH_Daily_26', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(139, 26, 2, N'Kill 5 players in RedRock', N'PH_Daily_26', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(140, 26, 2, N'Kill 5 players in Library', N'PH_Daily_26', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(141, 26, 2, N'Kill 5 players in MStation', N'PH_Daily_26', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(142, 26, 2, N'Kill 5 players in MidnightZone', N'PH_Daily_26', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(143, 26, 2, N'Kill 5 players in DownTown', N'PH_Daily_26', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(144, 27, 2, N'Kill 5 players in Burning Hall', N'PH_Daily_27', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(145, 27, 2, N'Kill 5 players in Crackdown', N'PH_Daily_27', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(146, 27, 2, N'Kill 5 players in Luxville', N'PH_Daily_27', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(147, 27, 2, N'Kill 5 players in Storm Tube', N'PH_Daily_27', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(148, 27, 2, N'Kill 5 players in Training Camp', N'PH_Daily_27', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(149, 27, 2, N'Kill 5 players in Desert Camp', N'PH_Daily_27', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(150, 28, 2, N'Kill 5 players in Outpost', N'PH_Daily_28', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(151, 28, 2, N'Kill 5 players in Eastern Road', N'PH_Daily_28', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(152, 28, 2, N'Kill 5 players in Breeding Nest', N'PH_Daily_28', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(153, 28, 2, N'Kill 5 players in Sand Storm', N'PH_Daily_28', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(154, 28, 2, N'Kill 5 players in Saint Mantion', N'PH_Daily_28', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(155, 28, 2, N'Kill 5 players in Supply Base', N'PH_Daily_28', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(180, 33, 2, N'Win 1 in Bombmode', N'KR_Daily_33', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(181, 33, 2, N'ChaneStopper 1', N'KR_Daily_33', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(182, 33, 2, N'Kill 5 players in Outpost', N'KR_Daily_33', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(183, 33, 2, N'Kill 5 players in BreedingNest', N'KR_Daily_33', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(184, 33, 2, N'Kill 5 players in RedRock', N'KR_Daily_33', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(185, 33, 2, N'Kill 10 players in BlueTeam', N'KR_Daily_33', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(186, 34, 2, N'HeadShot 3', N'KR_Daily_34', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(187, 34, 2, N'ChaneKill 1', N'KR_Daily_34', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(188, 34, 2, N'Kill 5 players in EasternRoad', N'KR_Daily_34', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(189, 34, 2, N'Kill 5 players in MidnightZone', N'KR_Daily_34', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(190, 34, 2, N'Kill 5 players in Library', N'KR_Daily_34', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(191, 34, 2, N'Kiil 10 players in RedTeam', N'KR_Daily_34', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(192, 35, 2, N'DoubleKill 2', N'KR_Daily_35', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(193, 35, 2, N'Kill 5 players in MStation', N'KR_Daily_35', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(194, 35, 2, N'Kill 5 players in TraningCamp', N'KR_Daily_35', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(195, 35, 2, N'Kill 5 players in CrackDown', N'KR_Daily_35', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(196, 35, 2, N'Kill 5 players in DownTown', N'KR_Daily_35', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(197, 35, 2, N'Kill 10 players in DestroyMode', N'KR_Daily_35', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(198, 36, 2, N'Kill 30 players', N'KR_Daily_36', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(199, 36, 2, N'Kill 5 players in MachuPichu', N'KR_Daily_36', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(200, 36, 2, N'Kill 5 players in SandStorm', N'KR_Daily_36', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(201, 36, 2, N'Kill 5 players in PortAkaba', N'KR_Daily_36', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(202, 36, 2, N'Kill 5 players in SaintMansion', N'KR_Daily_36', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(203, 36, 2, N'Kill 10 players in EscapeMode', N'KR_Daily_36', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(510, 505, 1, N'Win 20 games in Dragon Alley map', N'SM_HNY2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(511, 505, 1, N'Headshot 100 players', N'SM_HNY2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(512, 505, 1, N'Perform 20 Triple Kills', N'SM_HNY2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(513, 505, 1, N'Kill 10 enemies with grenade', N'SM_HNY2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(514, 505, 1, N'Kill 200 enemies with SMG', N'SM_HNY2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(515, 506, 1, N'Win 20 games in DeathMatch Mode', N'SM_Val2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(516, 506, 1, N'Win 20 games in Bomb Mode', N'SM_Val2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(517, 506, 1, N'Headshot 100 players', N'SM_Val2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(518, 506, 1, N'Win 20 games', N'SM_Val2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(519, 506, 1, N'Kill 200 players using Assault Rifles.', N'SM_Val2014', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(520, 507, 1, N'Enter Battle 100 times', N'SMEVENT3', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(521, 507, 1, N'Kill 20 players using Grenades.', N'SMEVENT3', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(522, 507, 1, N'Perform a Mass Kill 5 times.', N'SMEVENT3', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(523, 507, 1, N'Buy a PrimaryWeapon 3 times in Shop', N'SMEVENT3', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(524, 507, 1, N'Kill 1000 times', N'SMEVENT3', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(525, 508, 1, N'Win 15 times', N'VTEVENT508', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(526, 508, 1, N'HeadShot 100 times', N'VTEVENT508', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(527, 508, 1, N'DoubleKill 20 times', N'VTEVENT508', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(528, 508, 1, N'C5 Kill 5 times', N'VTEVENT508', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(529, 508, 1, N'Kill 250 times', N'VTEVENT508', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(530, 509, 1, N'Kill 250 times', N'SM_Event_509', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(531, 509, 1, N'AceAttacker 10 times', N'SM_Event_509', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(532, 509, 1, N'Kill 100 times using Assault', N'SM_Event_509', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(533, 509, 1, N'Kill 100 times in DinoTeam', N'SM_Event_509', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(534, 509, 1, N'Kill 100 times using ShotGun', N'SM_Event_509', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(536, 510, 1, N'Win 15 games in any mode', N'PH_Event_510', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(537, 510, 1, N'Headshot 100 players', N'PH_Event_510', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(538, 510, 1, N'Perform 20 Double Kills', N'PH_Event_510', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(539, 510, 1, N'Kill 5 enemies with C-5', N'PH_Event_510', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(540, 510, 1, N'Kill 250 enemies', N'PH_Event_510', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(541, 511, 1, N'Win 15 games in any mode', N'PH_Event_511', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(542, 511, 1, N'Headshot 100 players', N'PH_Event_511', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(543, 511, 1, N'Perform 20 Double Kills', N'PH_Event_511', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(544, 511, 1, N'Kill 5 enemies with C-5', N'PH_Event_511', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(545, 511, 1, N'Kill 250 enemies', N'PH_Event_511', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(546, 512, 1, N'InterEnter 50', N'KR_Event_512', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(547, 512, 1, N'Win 50', N'KR_Event_512', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(548, 513, 1, N'Kill 100 times', N'SM_Event_513', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(549, 513, 1, N'Headshot 10 times', N'SM_Event_513', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(550, 513, 1, N'Kill 10 times using grenade', N'SM_Event_513', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(551, 513, 1, N'Win 10 times in BombMode', N'SM_Event_513', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(552, 513, 1, N'TripleKill 10 times', N'SM_Event_513', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(553, 514, 1, N'Kill 200 times', N'SM_Event_514', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(554, 514, 1, N'HeadShot 20 times', N'SM_Event_514', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(555, 514, 1, N'MassKill 3 times', N'SM_Event_514', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(556, 514, 1, N'Win 20 times', N'SM_Event_514', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(557, 514, 1, N'Win 10 times in Pumpkin Hollow', N'SM_Event_514', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(558, 514, 1, N'TripleKill 7 times', N'SM_Event_514', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(559, 515, 1, N'Win 5 times in BombMode', N'SM_Event_515', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(560, 515, 1, N'HeadShot 30 times', N'SM_Event_515', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(561, 515, 1, N'Kill 10 times using Grenade', N'SM_Event_515', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(562, 515, 1, N'Win 20 times in BlackMamba', N'SM_Event_515', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(563, 515, 1, N'Kill 150 times using Sniper', N'SM_Event_515', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(564, 515, 1, N'ChaneKill 30 times', N'SM_Event_515', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(565, 516, 1, N'Win 10 games in team death match', N'SM_Event_516', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(566, 516, 1, N'Kill 20 enemies with explosives', N'SM_Event_516', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(567, 516, 1, N'Kill 50 Enemies with Headshot', N'SM_Event_516', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(568, 516, 1, N'Kill 100 Enemies with Melee', N'SM_Event_516', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(569, 516, 1, N'Kill 200 enemies with SMG', N'SM_Event_516', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(570, 517, 1, N'Win 10 matches in Destroy mode', N'SM_Event_517', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(571, 517, 1, N'Get 5 mass kills', N'SM_Event_517', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(572, 517, 1, N'Kill 50 Enemies with Headshot', N'SM_Event_517', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(573, 517, 1, N'Kill 100 Enemies with Shot Gun', N'SM_Event_517', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(574, 517, 1, N'Kill 150 Enemies with Sniper Rifles', N'SM_Event_517', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(575, 517, 1, N'Kill 300 Enemies', N'SM_Event_517', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(576, 518, 1, N'Win 15 games in team death match', N'PH_Event_518', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(577, 518, 1, N'Kill 500 enemies', N'PH_Event_518', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(578, 518, 1, N'Kill 200 enemies with Sniper', N'PH_Event_518', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(579, 518, 1, N'Kill 50 enemies with explosives', N'PH_Event_518', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(580, 518, 1, N'Kill 100 Enemies with Melee', N'PH_Event_518', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(581, 518, 1, N'Kill 200 enemies with SMG', N'PH_Event_518', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(582, 519, 1, N'Kill 50 Enemies with Headshot', N'SM_EVENT_519', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(583, 519, 1, N'Make 30 Chain kill', N'SM_EVENT_519', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(584, 519, 1, N'Win 50 matches in West Station map', N'SM_EVENT_519', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(585, 519, 1, N'Kill 100 Enemies with Melee Weapons', N'SM_EVENT_519', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(586, 519, 1, N'Kill 150 enemies with Shotgun', N'SM_EVENT_519', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(587, 519, 1, N'Kill 500 Enemies', N'SM_EVENT_519', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(588, 520, 1, N'Win 20 Matches In Dino Alley', N'PH_EVENT_520', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(589, 520, 1, N'Make 100 HeadShot', N'PH_EVENT_520', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(590, 520, 1, N'Make 20 Triple kill', N'PH_EVENT_520', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(591, 520, 1, N'Make 5 Mass kill', N'PH_EVENT_520', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(592, 520, 1, N'Kill 200 enemies with SMG', N'PH_EVENT_520', N'')
INSERT INTO dbo.PB_BT_Medal_Set (i16MedalIdx, i16MedalSetIdx, ui8MedalSetType, strMedalName, strSetName, strDescription)   VALUES(593, 520, 1, N'Make 5 Chain kill', N'PH_EVENT_520', N'')
