[Option]

; 실행 과정 정보 출력 여부 (default: No)
OutputInfo = Yes

; 파일 생성 방식 (default: No) 
; New 		- 파일명 뒤에 _NEW를 붙여 새로 저장된다. 
; OverWrite 	- 같은 파일에 덮어 쓰기
; No 		- 파일을 생성하지 않는다. (*.i3s)
OutputFile = New

; 도중에 실패해도 계속 진행할지 여부 (default: No)
IgnoreRun = No

[i3OptBuildIndexedGeometry]

; IndexArray를 만들지 여부 (default: No)
BuildIndex = No

[i3OptBuildTriStrip]

; 지원하는 Primitive Type (default: I3G_PRIM_NONE)
; I3G_PRIM_TRILIST
; I3G_PRIM_TRISTRIP
TargetPrimType = I3G_PRIM_TRISTRIP

; TriangleStrip으로 변환시 Vertex를 연결할지 여부 (default: Yes)
StitchStrips = Yes

; TriangleStrip으로 변환시 생성될수 있는 최소 Vertex 갯수 
; StitchStrips가 No 일때만 (default: 0) 
MinStripSize = 0
