//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// i3TDK.rc에서 사용되고 있습니다.
//
#define IDD_SELECTNODETYPEDIALOG        101
#define IDD_SINGLESELECTNODETYPEDIALOG  102
#define ID_TDK_SGTREECTRL               102
#define IDI_ANIM                        103
#define IDI_ANIM_UNSEL                  104
#define IDI_BONE                        105
#define IDI_BONE_UNSEL                  106
#define IDC_TDK_NODROP                  106
#define IDI_CAMERA                      107
#define IDI_CAMERA_UNSEL                108
#define IDI_GEOMETRY                    109
#define IDI_GEOMETRY_UNSEL              110
#define IDI_NODE                        111
#define IDI_NODE_UNSEL                  112
#define IDI_ATTR                        113
#define IDI_ATTR_UNSEL                  114
#define IDI_RESOURCE                    115
#define IDI_RESOURCE_UNSEL              116
#define IDI_SOUND                       117
#define IDI_SOUND_UNSEL                 118
#define IDI_TEXTURE                     119
#define IDI_TEXTURE_UNSEL               120
#define IDC_TDK_DRAG                    121
#define IDD_SELECTATTRTYPEDIALOG        122
#define IDD_SINGLESELECTATTRTYPEDIALOG  123
#define IDB_CAPTION_BACK                130
#define IDB_CAPTION_BACK_LEFT           131
#define IDB_CAPTION_BACK_RIGHT          132
#define IDB_CAPTION_GRIP                133
#define IDB_SELECTED_CAPTION_BACK       135
#define IDB_SELECTED_CAPTION_BACK_LEFT  136
#define IDB_SELECTED_CAPTION_BACK_RIGHT 137
#define IDB_SELECTED_CAPTION_GRIP       138
#define IDB_EDIT_BACK                   140
#define IDB_TAB_SEL_RIGHT               141
#define IDB_TAB_SEL_LEFT                142
#define IDR_POPUP_NODE                  143
#define IDB_TAB_SEL_MID                 143
#define IDB_TAB_BACK_LEFT               144
#define IDB_TAB_BACK_MID                145
#define IDB_TAB_BACK_RIGHT              146
#define IDB_CAPTION_CLOSE               147
#define IDB_SELECTED_CAPTION_CLOSE      148
#define IDB_CAPTION_COLLAPSE            149
#define IDB_CAPTION_EXPAND              150
#define IDB_SELECTED_CAPTION_COLLAPSE   151
#define IDB_SELECTED_CAPTION_EXPAND     152
#define IDB_FLOAT_GRIP                  153
#define IDD_OPTSPEC_GATHERUPATTRIBUTE   155
#define IDD_OPTSPEC_RESIZEIMAGE         156
#define IDD_OPTSPEC_CONVERTDXTTEXTURE   158
#define IDB_TIMESEQ_RULER_BACK          161
#define IDB_TIMESEQ_GUAGE               162
#define IDB_TIMESEQ_SLIDE_BACK          163
#define IDB_TIMESEQ_SLIDE_DISABLE_BODY  164
#define IDB_TIMESEQ_SLIDE_DISABLE_LEFT  165
#define IDB_TIMESEQ_SLIDE_DISABLE_RIGHT 166
#define IDB_TIMESEQ_SLIDE_NORMAL_BODY   167
#define IDB_TIMESEQ_SLIDE_NORMAL_LEFT   168
#define IDB_TIMESEQ_SLIDE_NORMAL_RIGHT  169
#define IDB_TIMESEQ_SLIDE_SELECT_BODY   170
#define IDB_TIMESEQ_SLIDE_SELECT_LEFT   171
#define IDB_TIMESEQ_SLIDE_SELECT_RIGHT  172
#define IDB_TIMESEQ_TRACK_BODY          173
#define IDB_TIMESEQ_TRACK_DISABLE_BODY  174
#define IDB_TIMESEQ_TRACK_DISABLE_LEFT  175
#define IDB_TIMESEQ_TRACK_DISABLE_RIGHT 176
#define IDB_TIMESEQ_TRACK_LEFT          177
#define IDB_TIMESEQ_TRACK_RIGHT         178
#define IDB_TIMESEQ_TRACK_SELECT_BODY   179
#define IDB_TIMESEQ_TRACK_SELECT_LEFT   180
#define IDB_TIMESEQ_TRACK_SELECT_RIGHT  181
#define IDR_POPUP_TIMESEQ               182
#define IDD_TDK_DLG_RENAME              183
#define IDD_DLG_COLORPICKER             184
#define IDD_PROFILINGVIEWER_DIALOG      186
#define IDC_TDK_RGBPICK                 188
#define IDB_BMP_PRIMARYCOLOR_PICK       191
#define IDB_BMP_PRIMARYCOLOR_PICK_MASK  193
#define IDI_TDK_WORLD_PARTITION         198
#define IDI_TDK_BOX                     199
#define IDI_TDK_CAMERA_GROUP            200
#define IDI_TDK_CHARACTER               201
#define IDI_TDK_CHARACTER_GROUP         202
#define IDI_TDK_CYLINDER                203
#define IDI_TDK_LIGHT_DIRECTIONAL       204
#define IDI_TDK_EFFECT                  205
#define IDI_TDK_EFFECT_GROUP            206
#define IDI_TDK_ELEMENT_BRUSH           207
#define IDI_TDK_ELEMENT_ROTATION        208
#define IDI_TDK_ELEMENT_SCALE           209
#define IDI_TDK_ELEMENT_SELECTION       210
#define IDI_TDK_ELEMENT_TRANSITION      211
#define IDI_TDK_EXPORT                  212
#define IDI_TDK_LAYER                   213
#define IDI_TDK_LEVEL                   214
#define IDI_TDK_LIGHT_GROUP             215
#define IDI_TDK_OBJECT                  216
#define IDI_TDK_OBJECT_GROUP            217
#define IDI_TDK_OPTION                  218
#define IDI_TDK_PATH_EDIT               219
#define IDI_TDK_LIGHT_POINT             220
#define IDI_TDK_RESPAWN                 221
#define IDI_TDK_SPHERE                  222
#define IDI_TDK_LIGHT_SPOT              223
#define IDI_TDK_WORLD                   224
#define IDC_TDK_PATH_EDIT               228
#define IDC_TDK_ELEMENT_BRUSH           229
#define IDC_TDK_ELEMENT_ROTATION        230
#define IDC_TDK_ELEMENT_SCALE           231
#define IDC_TDK_ELEMENT_SELECTION       232
#define IDC_TDK_ELEMENT_TRANSITION      233
#define IDR_POPUP_TIMEEVENT             234
#define IDB_TIMEEVENT_SLIDE_SELECT      236
#define IDB_TIMEEVENT_SLIDE_NORMAL      237
#define IDB_TIMEEVENT_SLIDE_DISABLE     238
#define IDD_TDK_DLG_SELECTACTION        240
#define IDI_TDK_ELEMENTLIST             241
#define IDD_TDK_DLG_PHYSIX_SET          242
#define IDI_TDK_PHS_TRANS               243
#define IDI_TDK_PHS_SHAPESET            244
#define IDI_TDK_PHS_OTHER               245
#define IDR_TDK_POPUP_SHAPESET          247
#define IDD_TDK_BUILD_SHAPESET          248
#define IDI_TDK_PARENT_LINK             251
#define IDI_TDK_PARENT_UNLINK           252
#define IDI_TDK_COLLISION_EDIT          253
#define IDD_ACTION_SOUND                254
#define IDI_BLANK                       254
#define IDD_OPTSPEC_BSPBUILDER          255
#define IDD_OPTSPEC_NODEFLAG            256
#define IDD_OPTSPEC_MACROTEXTURE        257
#define IDD_TDK_DLG_CONTAINER           258
#define IDD_OPTSPEC_SPATIALPARTITION    259
#define IDC_LV_BANDSELECT               260
#define IDC_LV_BRUSH                    261
#define IDC_LV_MOVE                     262
#define IDC_LV_POINTER_COPY             263
#define IDC_LV_ROTATE                   264
#define IDC_LV_SCALE                    265
#define IDC_LV_SELECT_TARGET            266
#define IDD_DLG_CHANGECOLLISIONGROUP    267
#define IDD_TDK_DLG_TIMEEVENT           270
#define IDD_OPTSPEC_MIPMAPGEN           271
#define IDC_LV_PATH_EDIT                272
#define IDD_DLG_OPTPROGRESS             273
#define IDD_TDK_ENVSET                  274
#define IDR_POPUP_PROJECT               275
#define IDD_TDK_SPEC_NODE               276
#define IDD_TDK_SPEC_ATTRSET            277
#define IDD_TDK_SPEC_TRANSFORM          278
#define IDD_TDK_SPEC_BONEREF            279
#define IDD_TDK_SPEC_ATTR_BOOL          280
#define IDD_TDK_SPEC_ALPHAFUNC          281
#define IDD_TDK_SPEC_ATTR_BLENDMODE     283
#define IDD_TDK_SPEC_ATTR_COLOR         285
#define IDD_TDK_SPEC_ATTR_FACECULL      286
#define IDD_TDK_SPEC_ATTR_FOGCOLOR      288
#define IDD_TDK_SPEC_ATTR_FOGDENSITY    289
#define IDD_TDK_SPEC_ATTR_FOGMODE       290
#define IDD_TDK_SPEC_ATTR_FOGNEARFAR    292
#define IDD_TDK_SPEC_ATTR_FRESNEL       293
#define IDD_TDK_SPEC_ATTR_GEOMETRY      294
#define IDD_TDK_SPEC_ATTR_TEXBIND       296
#define IDD_TDK_SPEC_ATTR_TEXWRAP       298
#define IDD_TDK_SPEC_ATTR_MATERIAL      300
#define IDD_TDK_SPEC_ATTR_RENDERMODE    301
#define IDD_TDK_SPEC_ATTR_SHADEMODE     303
#define IDD_TDK_DLG_GEOMETRYTOOL        307
#define IDD_TDK_DLG_TEXTOOL             308
#define IDD_TDK_SPEC_BODY               309
#define IDD_TDK_DLG_SKELETON            310
#define IDD_OPTSPEC_OCTREE_BUILDER      311
#define IDD_TDK_SPEC_ATTR_TEXMAT        313
#define IDD_TDK_SPEC_TRANSFORM2         314
#define IDD_TDK_SPEC_SHAPESET           316
#define IDD_TDK_SPEC_SHAPESET_LOCALPOS  318
#define IDD_TDK_SPEC_SHAPESET_GLOBALPOS 319
#define IDD_OPTSPEC_REMOVEVERTEXCOMPONENT 320
#define IDD_TDK_DLG_NODEFLAG            321
#define IDR_POPUP_GAMENODE              322
#define IDD_TDK_SELECT_IMAGE_EXT        323
#define IDD_TDK_DLG_PHYSIX_TOOL         326
#define IDD_TDK_SPEC_ATTR_SHADER        327
#define IDD_TDK_DLG_CHANGETEX           330
#define IDR_POPUP_CHANGETEX_EDIT_CLONED_I3S 334
#define IDR_POPUP_CHANGETEX_EDIT_REF_I3S 335
#define IDD_OPTSPEC_RENATTR             336
#define IDD_BOUND_RESET                 339
#define IDR_POPUP_SKELETON              340
#define IDR_POPUP_CHANGETEX_EDIT_PEFLIST 341
#define TDC_CB_TYPE                     1001
#define IDC_TYPELIST                    1004
#define IDC_TDK_ED_SCALE                1006
#define IDC_ED_MAX_W                    1007
#define IDC_ED_MAX_H                    1008
#define IDC_ED_MIN_W                    1009
#define IDC_ED_MIN_H                    1010
#define IDC_ST_SCALE                    1011
#define IDC_ST_LIMIT                    1012
#define IDC_ST_MAX                      1013
#define IDC_ST_MIN                      1014
#define IDC_ST_W                        1015
#define IDC_ST_H                        1016
#define IDC_CB_QUALITY                  1017
#define IDC_CHK_BINARYALPHA             1018
#define IDC_ED_ALPHAREF                 1019
#define IDC_ST_ALPHAREF                 1020
#define IDC_TDK_CHK_DITHER              1021
#define IDC_CB_TARGETFORMAT             1022
#define IDC_ST_QUALITY                  1023
#define IDC_TDK_NAME                    1024
#define IDC_TDK_ED_R                    1040
#define IDC_TDK_ED_R2                   1041
#define IDC_TDK_CB_ACTION               1041
#define IDC_TDK_ED_G                    1042
#define IDC_TDK_ACTION_HELP             1042
#define IDC_TDK_ED_G2                   1043
#define IDC_NARRATION                   1043
#define IDC_TDK_ED_B                    1044
#define IDC_TDK_PHYSIXTREE              1044
#define IDC_TDK_ED_B2                   1045
#define IDC_TDK_CB_USAGE                1045
#define IDC_TDK_ED_A                    1046
#define IDC_TDK_ED_SHAPETYPE            1046
#define IDC_TDK_ED_B4                   1047
#define IDC_TDK_ED_A2                   1047
#define IDC_TDK_ED_VERTEXCOUNT          1047
#define IDC_TDK_CB_GROUP                1048
#define IDC_TDK_ED_RESTITUTION          1049
#define IDC_TDK_ED_STATIC_FRICTION      1050
#define IDC_TDK_RBTN_CONVEX             1050
#define IDC_TDK_ED_DYNAMIC_FRICTION     1051
#define IDC_TDK_RBTN_TRIMESH            1051
#define IDC_TDK_ED_DYNAMIC_FRICTION2    1052
#define IDC_TDK_RBTN_DYNAMIC            1052
#define IDC_TDK_RBTN_STATIC             1053
#define IDC_TDK_ED_LINEAR_DAMPING       1053
#define IDC_TDK_ED_SFRICTION            1054
#define IDC_TDK_ED_RESTITUTION3         1054
#define IDC_TDK_ED_ANGULAR_DAMPING      1054
#define IDC_TDK_ED_DFRICTION            1055
#define IDC_TDK_ED_SKIN_WIDTH           1055
#define IDC_TDK_ED_MASS                 1056
#define IDC_TDK_ED_LINEAR_DAMP          1057
#define IDC_TDK_ED_ANGULAR_DAMP         1058
#define IDC_TDK_SHAPELIST               1059
#define IDC_TDK_CB_TERRAIN              1060
#define IDC_CB_TERRAIN_TYPE             1061
#define IDC_EDIT_SND_RES                1062
#define IDC_BUTTON_SND_SELRES           1063
#define IDC_EDIT_SND_VOLUME             1064
#define IDC_EDIT_SND_LISTENERVOLUME     1065
#define IDC_EDIT_SND_MINDIST            1066
#define IDC_EDIT_SND_MAXDIST            1067
#define IDC_EDIT_SND_INSIDEANGLE        1068
#define IDC_EDIT_SND_OUTSIDEANGLE       1069
#define IDC_EDIT_SND_OUTSIDEVOLUME      1070
#define IDC_EDIT_SND_DIRECTION_X        1071
#define IDC_EDIT_SND_DIRECTION_Y        1072
#define IDC_EDIT_SND_DIRECTION_Z        1073
#define IDC_CHECK_SND_MUTEAT_MAXDIST    1074
#define IDC_OK2                         1075
#define IDC_COMPLETE                    1075
#define IDC_CHK_COND_CONVEX             1076
#define IDC_CHECK_SND_RANDOMENABLE      1076
#define IDC_CHECK_SND_RANDOM_ENABLE     1076
#define IDC_CHK_COND_DEPTH              1077
#define IDC_CHK_COND_POLYCOUNT          1078
#define IDC_CHK_DISABLE                 1078
#define IDC_ED_DEPTHLIMIT               1079
#define IDC_TDK_CHK_INVISIBLE           1079
#define IDC_EDIT_SND_RANDOM_FACTOR      1079
#define IDC_ED_POLYCOUNTLIMIT           1080
#define IDC_CHK_MUSTBEPROCESS           1080
#define IDC_TDK_CHK_MUSTBEPROCESS       1080
#define IDC_CB_PLANETYPE                1081
#define IDC_CHK_TRANSFORM               1081
#define IDC_CHECK4                      1082
#define IDC_CHK_SPLIT_POLY              1082
#define IDC_CHK_TRANSPARENT             1082
#define IDC_TDK_CHK_DUMPMACROTEX        1082
#define IDC_TDK_CHK_SRGB_IN             1082
#define IDC_TDK_CHK_TRANSPARENT         1082
#define IDC_CHK_STATIC                  1083
#define IDC_TDK_CHK_SRGB_OUT            1083
#define IDC_TDK_CHK_TRANSPARENT2        1083
#define IDC_TDK_CHK_STATIC              1083
#define IDC_EDIT_THICKNESS              1084
#define IDC_TDK_CHK_VOLATILE            1084
#define IDC_TDK_CHK_CONTROL             1085
#define IDC_TDK_CHK_MANUAL_UPDATE       1086
#define IDC_TDK_CHK_MANUALUPDATE        1086
#define IDC_CHK_DISABLE_SHADOW_CAST     1087
#define IDC_TDK_CHK_DYNAMICUPDATE       1087
#define IDC_CHK_DISABLE_SHADOW_RECEIVE  1088
#define IDC_TDK_CHK_DISABLESHADOWCASTER 1088
#define IDC_CHK_NOWORK                  1089
#define IDC_TDK_CHK_NOWORK              1089
#define IDC_CHK_DISABLE2                1090
#define IDC_TDK_CHK_ATTACH_POINT        1090
#define IDC_CHK_INVISIBLE2              1091
#define IDC_TDK_CHK_DISABLESHADOWCASTER2 1091
#define IDC_TDK_CHK_DISABLESHADOWRECEIVE 1091
#define IDC_CHK_MUSTBEPROCESS2          1092
#define IDC_CHK_TRANSFORM2              1093
#define IDC_CHK_TRANSPARENT2            1094
#define IDC_CHK_STATIC2                 1095
#define IDC_CHK_VOLATILE2               1096
#define IDC_CHK_CONTROL2                1097
#define IDC_CHK_MANUAL_UPDATE2          1098
#define IDC_CHK_DISABLE_SHADOW_CAST2    1099
#define IDC_CHK_DISABLE_SHADOW_RECEIVE2 1100
#define IDC_CHK_NOWORK2                 1101
#define IDC_TDK_ED_WIDTH                1104
#define IDC_TDK_ED_HEIGHT               1105
#define IDC_TDK_ED_LEVEL                1106
#define IDC_TDK_BTN_BACK                1107
#define IDC_TDK_ED_X                    1108
#define IDC_TDK_ED_Y                    1109
#define IDC_TDK_ED_Z                    1110
#define IDC_TDK_ED_TRICOUNT             1111
#define IDC_TDK_CHK_SPLIT               1112
#define IDC_EDIT_COLLISIONGROUPIDX      1113
#define IDC_TDK_CHK_REPEAT              1114
#define IDC_CHK_LIMITSIZE               1115
#define IDC_ED_LIMITCX                  1116
#define IDC_ED_LIMITCY                  1117
#define IDC_CHK_LIMITLEVEL              1118
#define IDC_ED_MAXLEVEL                 1119
#define IDC_TDK_CB_FILTER               1120
#define IDC_TDK_CHK_MIRROR_U            1122
#define IDC_TDK_CHK_MIRROR_V            1123
#define IDC_TDK_ED_NAME                 1123
#define IDC_TDK_CHK_MIRROR_U3           1124
#define IDC_TDK_CHK_MIRROR_W            1124
#define IDC_TDK_PROGRESS1               1124
#define IDC_TDK_ST_PROGRESS             1125
#define IDC_TDK_ST_LOGPH                1126
#define IDC_TDK_PROGRESS_SUB            1127
#define IDC_TDK_PROJECT_LIST            1127
#define IDC_TDK_ST_PROGRESS_SUB         1128
#define IDC_TDK_ED_WORKDIR              1128
#define IDC_TDK_BTN_WORKDIR             1129
#define IDC_TDK_RICHED_DESC             1131
#define IDC_TDK_ED_FLAGS                1134
#define IDC_TDK_BTN_FLAGS               1135
#define IDC_TDK_ED_BOUND                1136
#define IDC_TDK_ED_PRIO                 1137
#define IDC_TDK_BTN_FLAGS2              1137
#define IDC_TDK_BTN_BOUND               1137
#define IDC_TDK_ED_M00                  1138
#define IDC_TDK_ED_M01                  1139
#define IDC_TDK_ED_M02                  1140
#define IDC_TDK_ED_M03                  1141
#define IDC_TDK_ED_M10                  1142
#define IDC_TDK_ED_M11                  1143
#define IDC_TDK_ED_M12                  1144
#define IDC_TDK_ED_M13                  1145
#define IDC_TDK_ED_M20                  1146
#define IDC_TDK_ED_M21                  1147
#define IDC_TDK_ED_M22                  1148
#define IDC_TDK_ED_M23                  1149
#define IDC_TDK_ED_M30                  1150
#define IDC_TDK_ED_M31                  1151
#define IDC_TDK_ED_M32                  1152
#define IDC_TDK_ED_M33                  1153
#define IDC_TDK_ED_ANIM                 1154
#define IDC_BTN_ANIM                    1155
#define IDC_TDK_CB_BONE                 1157
#define IDC_TDK_CHK_ENABLE              1158
#define IDC_TDK_ED_REF                  1159
#define IDC_TDK_CB_FUNC                 1160
#define IDC_TDK_CB_SRC                  1161
#define IDC_TDK_CB_DEST                 1162
#define IDC_TDK_CB_OP                   1163
#define IDC_TDK_ST_COLOR_PH             1163
#define IDC_TDK_CB_CULL                 1164
#define IDC_TDK_ED_DENSITY              1165
#define IDC_TDK_CB_MODE                 1166
#define IDC_TDK_ED_NEAR                 1167
#define IDC_TDK_ED_FAR                  1168
#define IDC_TDK_ED_IOR                  1169
#define IDC_ST_COLORPH                  1170
#define IDC_TDK_CB_PRIMTYPE             1171
#define IDC_TDK_ED_PRIMCOUNT            1172
#define IDC_CHK_FORMAT_POS              1174
#define IDC_CHK_FORMAT_NORMAL           1175
#define IDC_CHK_FORMAT_COLOR            1176
#define IDC_CHK_FORMAT_TANGENT          1177
#define IDC_CHK_FORMAT_BINORMAL         1178
#define IDC_CHK_FORMAT_TRANSFORMED      1179
#define IDC_TDK_ED_TEXSET               1180
#define IDC_TDK_ED_TEXCOORD             1181
#define IDC_TDK_ED_BLENDIDX             1182
#define IDC_TDK_ED_BLENDWEIGHT          1183
#define IDC_TDK_ED_INDEXBUFFER          1184
#define IDC_TDK_ED_STARTIDX             1185
#define IDC_TDK_ED_FORMAT_PERSIST       1187
#define IDC_TDK_ED_FORMAT_RUNTIME       1188
#define IDC_TDK_CB_MIPMAPGEN            1189
#define IDC_TDK_CB_MIPMAP_GENFILTER     1190
#define IDC_TDK_ED_PATH                 1191
#define IDC_TDK_BTN_FILE                1192
#define IDC_TDK_IMAGEPH                 1193
#define IDC_TDK_CB_HWRAP                1194
#define IDC_TDK_CB_VWRAP                1195
#define IDC_TDK_CHK_DIFF                1195
#define IDC_TDK_CHK_SPEC                1196
#define IDC_ST_DIFFPH                   1197
#define IDC_ST_SPECPH                   1198
#define IDC_TDK_CHK_EMIS                1199
#define IDC_ST_EMISPH                   1200
#define IDC_TDK_CHK_SHINI               1201
#define IDC_TDK_ED_SHINI                1202
#define IDC_TDK_CB_RENDERMODE           1203
#define IDC_TDK_LIST_GEO                1205
#define IDC_TDK_BTN_REMOVE_COLOR        1206
#define IDC_TDK_BTN_REMOVE_NORMAL       1207
#define IDC_TDK_BTN_NONINDEXEDGEO       1208
#define IDC_TDK_TEX_LIST                1208
#define IDC_TDK_BTN_INDEXEDGEO          1209
#define IDC_TDK_BTN_SELALL              1209
#define IDC_TDK_BTN_TRISTRIP            1210
#define IDC_TDK_BTN_UNSELALL            1210
#define IDC_TDK_BTN_TRYLIST             1211
#define IDC_TDK_BTN_SELDIFF             1211
#define IDC_TDK_BTN_SELNORMAL           1212
#define IDC_TDK_BTN_SELSPEC             1213
#define IDC_TDK_BTN_SELLUX              1214
#define IDC_TDK_BTN_SAVETEX             1218
#define IDC_TDK_BTN_RESTORETEX          1219
#define IDC_TDK_BTN_RSTRTEX_SEARCH      1220
#define IDC_TDK_BTN_INTERNAL            1221
#define IDC_TDK_BTN_EXTERNAL            1222
#define IDC_TDK_ST_TOTALCNT             1223
#define IDC_TDK_ST_IMAGEVIEWPH          1224
#define IDC_TDK_AUTOLOD                 1225
#define IDC_TDK_ED_SLOPE                1226
#define IDC_TDK_ED_CONST                1227
#define IDC_TDK_BTN_ANIM                1230
#define IDC_TDK_BTN_FRAMESKEL           1231
#define IDC_TDK_SKEL                    1232
#define IDC_TDK_BTN_ROTATEINIT          1232
#define IDC_TDK_ED_SHAPESET             1234
#define IDC_TDK_BTN_SHAPESET            1235
#define IDC_TDK_CHK_SPLITMESH           1238
#define IDC_TDK_CHK_LIMITDEPTH          1239
#define IDC_TDK_ED_MAXDEPTH             1240
#define IDC_TDK_CHK_MINPOLY             1241
#define IDC_TDK_ED_MINPOLY              1242
#define IDC_TDK_ED_MINPOLY2             1243
#define IDC_TDK_ED_MINPOLY3             1244
#define IDC_TDK_CB_CENTERMETHOD         1245
#define IDC_TDK_ED_MINPOLY4             1246
#define IDC_TDK_ED_EXTENT               1246
#define IDC_TDK_CB_UB                   1249
#define IDC_TDK_ED_JOINT                1251
#define IDC_TDK_BTN_JOINT               1252
#define IDC_TDK_ED_UB1                  1252
#define IDC_TDK_ED_UB2                  1253
#define IDC_TDK_CB_VB                   1257
#define IDC_TDK_ED_VB1                  1258
#define IDC_TDK_ED_VB2                  1259
#define IDC_TDK_ST_UB                   1260
#define IDC_TDK_ST_VB                   1261
#define IDC_TDK_ED_PROJECTIVE           1262
#define IDC_TDK_ED_ELEMENTCOUNT         1263
#define IDC_TDK_CB_BINDTYPE             1264
#define IDC_TDK_EDIT_SHAPENAME          1266
#define IDC_TDK_EDIT_SHAPETYPE          1267
#define IDC_TDK_EDIT_RESTITUTION        1268
#define IDC_TDK_EDIT_SFRICTION          1269
#define IDC_TDK_CB_FORMAT               1270
#define IDC_TDK_ED_SHAPE_NUMBER         1271
#define IDC_TDK_EDIT_SHAPEGROUP         1272
#define IDC_TDK_EDIT_SKINWIDTH          1273
#define IDC_TDK_EDIT_DFRICTION          1274
#define IDC_TDK_ED_SHAPE_COUNT          1275
#define IDC_TDK_BTN_LOCAL_MATRIX        1276
#define IDC_TDK_BTN_GLOBAL_MATRIX       1277
#define IDC_TDK_EDIT_MASS               1278
#define IDC_TDK_EDIT_LINEAR_DAMPING     1279
#define IDC_TDK_EDIT_SLEEP_LINEAR       1280
#define IDC_TDK_EDIT_ANGULAR_DAMPING    1281
#define IDC_TDK_EDIT_SLEEP_ANGULAR      1282
#define IDC_TDK_ED_LOCALPOSEX           1283
#define IDC_TDK_ED_LOCALPOSEY           1284
#define IDC_TDK_ED_LOCALPOSEZ           1285
#define IDC_TDK_ED_INERTIATENSORX       1286
#define IDC_TDK_ED_INERTIATENSORY       1287
#define IDC_TDK_ED_INERTIATENSORZ       1288
#define IDC_TDK_BTN_CALCLOCALCENTER     1289
#define IDC_TDK_EDIT_TERRAINCOUNT       1291
#define IDC_TDK_ED_THICKNESS            1292
#define IDC_TDK_CHK_ALLTERRAIN          1293
#define IDC_TDK_CB_TERRAINTYPE          1294
#define IDC_TDK_ED_LOCAL_MAT_00         1295
#define IDC_TDK_ED_LOCAL_MAT_01         1296
#define IDC_TDK_ED_LOCAL_MAT_02         1297
#define IDC_TDK_ED_LOCAL_MAT_03         1298
#define IDC_TDK_ED_LOCAL_MAT_10         1299
#define IDC_TDK_ED_LOCAL_MAT_11         1300
#define IDC_TDK_ED_LOCAL_MAT_12         1301
#define IDC_TDK_ED_LOCAL_MAT_13         1302
#define IDC_TDK_ED_LOCAL_MAT_20         1303
#define IDC_TDK_ED_LOCAL_MAT_21         1304
#define IDC_TDK_ED_LOCAL_MAT_22         1305
#define IDC_TDK_ED_LOCAL_MAT_23         1306
#define IDC_TDK_ED_LOCAL_MAT_30         1307
#define IDC_TDK_ED_LOCAL_MAT_31         1308
#define IDC_TDK_ED_LOCAL_MAT_32         1309
#define IDC_TDK_ED_LOCAL_MAT_33         1310
#define IDC_TDK_ED_GLOBAL_MAT_00        1311
#define IDC_TDK_ED_GLOBAL_MAT_01        1312
#define IDC_TDK_ED_GLOBAL_MAT_02        1313
#define IDC_TDK_ED_GLOBAL_MAT_03        1314
#define IDC_TDK_ED_GLOBAL_MAT_10        1315
#define IDC_TDK_ED_GLOBAL_MAT_11        1316
#define IDC_TDK_ED_GLOBAL_MAT_12        1317
#define IDC_TDK_ED_GLOBAL_MAT_13        1318
#define IDC_TDK_ED_GLOBAL_MAT_20        1319
#define IDC_TDK_ED_GLOBAL_MAT_21        1320
#define IDC_TDK_ED_GLOBAL_MAT_22        1321
#define IDC_TDK_ED_GLOBAL_MAT_23        1322
#define IDC_TDK_ED_GLOBAL_MAT_30        1323
#define IDC_TDK_ED_GLOBAL_MAT_31        1324
#define IDC_TDK_ED_GLOBAL_MAT_32        1325
#define IDC_TDK_ED_GLOBAL_MAT_33        1326
#define IDC_TDK_CHK_NORMAL              1327
#define IDC_TDK_CHK_COLOR               1328
#define IDC_TDK_ED_TOTALPRIM            1328
#define IDC_TDK_CHK_TEX                 1329
#define IDC_TDK_ED_TOTALVERTEX          1329
#define IDC_TDK_CHK_CREATEBOUNDBOX      1329
#define IDC_TDK_CHK_TANGNET             1330
#define IDC_TDK_ED_VACOUNT              1330
#define IDC_TDK_CHK_DISABLE             1330
#define IDC_TDK_ED_IACOUNT              1331
#define IDC_TDK_CHK_ALL_TEX             1331
#define IDC_CB_EXT                      1334
#define IDC_ST_BONECOUNT                1335
#define IDC_TDK_LIST_SHAPESET           1336
#define IDC_TDK_LIST_SHAPES             1337
#define IDC_TDK_ST_SUM                  1338
#define IDC_TDK_CHK_ADDCACHE            1339
#define IDC_TDK_ED_SRC                  1340
#define IDC_TDK_BTN_RECOMPILE           1341
#define IDC_TDK_CB_VS_VERSION           1342
#define IDC_TDK_CB_PS_VERSION           1343
#define IDC_CLONED_I3S_LIST             1343
#define IDD_TDK_SPEC_JOINT              1344
#define IDC_REF_I3S_LIST                1344
#define IDC_TDK_ED_MOTION_X             1345
#define IDC_TDK_ST_IMAGE_ORIG           1345
#define IDC_TDK_ED_MOTION_Y             1346
#define IDC_TDK_ST_IMAGE_ORIG2          1346
#define IDC_TDK_ST_IMAGE_TARGET         1346
#define IDC_TDK_ED_MOTION_Z             1347
#define IDC_TDK_BTN_SAVEPEF             1347
#define IDC_TDK_ED_MOTION_SWING1        1348
#define IDC_TDK_ED_MOTION_SWING2        1349
#define IDC_TDK_BTN_PEFPATH             1349
#define IDC_TDK_ED_MOTION_TWIST         1350
#define IDC_REF_CATEGORY_LIST           1350
#define IDC_TDK_ED_JOINTNAME            1351
#define IDC_STATIC_CHANGETEX_LIST_DUMMY 1351
#define IDC_TDK_ED_LINEARLIMIT_VALUE    1352
#define IDC_REF_CATEGORY_LIST2          1352
#define IDC_CHANGETEX_PEF_LIST          1352
#define IDC_TDK_ED_LINEARLIMIT_RESTITUTION 1353
#define IDC_TDK_ED_LINEARLIMIT_SPRING   1354
#define IDC_TDK_ED_LINEARLIMIT_DAMPING  1355
#define IDC_TDK_ED_SWING1LIMIT_VALUE    1356
#define IDC_TDK_ED_SWING1LIMIT_RESTITUTION 1357
#define IDC_TDK_ED_SWING1LIMIT_SPRING   1358
#define IDC_TDK_ED_SWING1LIMIT_DAMPING  1359
#define IDC_TDK_ED_SWING2LIMIT_VALUE    1360
#define IDC_TDK_ED_SWING2LIMIT_RESTITUTION 1361
#define IDC_TDK_ED_SWING2LIMIT_SPRING   1362
#define IDC_TDK_ED_SWING2LIMIT_DAMPING  1363
#define IDC_TDK_ED_GEARRATIO            1364
#define IDC_TDK_ED_TWISTLIMIT_HIGH_VALUE 1365
#define IDC_TDK_ED_TWISTLIMIT_HIGH_RESTITUTION 1366
#define IDC_TDK_ED_TWISTLIMIT_HIGH_SPRING 1367
#define IDC_TDK_ED_TWISTLIMIT_HIGH_DAMPING 1368
#define IDC_TDK_ED_TWISTLIMIT_LOW_VALUE 1369
#define IDC_TDK_ED_TWISTLIMIT_LOW_RESTITUTION 1370
#define IDC_TDK_ED_TWISTLIMIT_LOW_SPRING 1371
#define IDC_TDK_ED_TWISTLIMIT_LOW_DAMPING 1372
#define IDC_TDK_OPTRENATTR_CHK_PRESERVE_EMPTYATTRSET 1375
#define IDC_EDIT_BR_MIN_X               1381
#define IDC_CHECK_CHANGETEX_LOD_SEPERATION 1382
#define IDC_BUTTON_OPEN_REF_I3S         1383
#define IDC_STATIC_CHANGETEX_ENVSET     1384
#define IDC_STATIC_CHANGETEX_WORKDIR    1385
#define IDC_SPIN1                       1386
#define IDC_STATIC_CHANGETEX_WORKDIR2   1386
#define IDC_TDK_SPIN_VALUE_X            1387
#define IDC_TDK_SPIN_ROTATE_X           1387
#define IDC_TDK_SPIN_VALUE_Y            1388
#define IDC_TDK_SPIN_ROTATE_Y           1388
#define IDC_TDK_SPIN_VALUE_Z            1389
#define IDC_TDK_SPIN_ROTATE_Z           1389
#define IDC_EDIT_BR_MIN_Y               1390
#define IDC_TDK_ET_VALUE_X              1390
#define IDC_TDK_ET_ROTATE_X             1390
#define IDC_EDIT_BR_MIN_Z               1391
#define IDC_TDK_ET_VALUE_Y              1391
#define IDC_TDK_ET_ROTATE_Y             1391
#define IDC_TDK_ET_VALUE_Z              1392
#define IDC_TDK_ET_ROTATE_Z             1392
#define IDC_TDK_CHECK_USEOBJECT         1393
#define IDC_TDK_SPIN_VALUE_Z2           1394
#define IDC_TDK_SPIN_POS_X              1394
#define IDC_BTN_SKELETONBONE            1395
#define IDC_TDK_ET_VALUE_W              1396
#define IDC_TDK_ET_ROTATE_W             1396
#define IDC_STATIC_CHANGETEX_PEFPATH    1396
#define IDC_TDK_ET_POS_X                1397
#define IDC_CHECK_CHANGETEX_PEF         1397
#define IDC_CHECK_CHANGETEX_SAVE_PEF    1397
#define IDC_EDIT_BR_MAX_X               1398
#define IDC_TDK_SPIN_POS_Y              1398
#define IDC_EDIT_BR_MAX_Y               1399
#define IDC_TDK_ET_POS_Y                1399
#define IDC_EDIT_BR_MAX_Z               1400
#define IDC_TDK_SPIN_POS_Z              1400
#define IDC_TDK_ET_POS_Z                1401
#define ID_NODE_DELETE                  32771
#define ID_NODE_EXPAND                  32772
#define ID_NODE_COLLAPSENODE            32773
#define ID_NODE_COLLAPSETRANSFORM       32774
#define ID_NODE_SELECTALLDESCENDANT     32775
#define ID_NODE_SELECTBYTYPE            32776
#define ID_NODE_REVERSESELECTION        32777
#define ID_NODE_REMOVENODENAMES         32778
#define ID_NODE_SELECTALL               32779
#define ID_NODE_UNSELECTALL             32780
#define ID_NODE_UNSELECTALLDESCENDANTS  32781
#define ID_NODE_COLLAPSE                32782
#define ID_NODE_REMOVEBOUNDBOX          32791
#define ID_NODE_SELECT                  40001
#define ID_NODE_NODE                    40002
#define ID_BOUNDBOX_SETBOUNDBOX         40004
#define ID_NODE_INSERTNODE              40005
#define ID_ATTRIBUTE_INSERTATTRIBUTES   40007
#define ID_ATTRIBUTE_REMOVEATTRIBUTEFROMDESCENDENTS 40008
#define ID_NODE_IMPORTSCENE             40010
#define ID_NODE_EXPORTSCENE             40011
#define ID_NODE_SHOW                    40012
#define ID_SHOW_NAME                    40013
#define ID_SHOW_FLAGS                   40014
#define ID_SHOW_RENDERATTRIBUTES        40015
#define ID_NODE_OPTIMIZE                40016
#define ID_TIMESEQCTRL_SELECTALL        40017
#define ID_TIMESEQCTRL_UNSELECTALL      40018
#define ID_TIMESEQCTRL_DELETE           40019
#define ID_TIMESEQCTRL_COPY             40020
#define ID_TIMESEQCTRL_PASTE            40021
#define ID_TIMESEQCTRL_RENAME           40022
#define ID_TIMEEVENT_SELECTALL          40023
#define ID_TIMEEVENT_UNSELECTALL        40024
#define ID_TIMEEVENT_DELETE             40025
#define ID_TIMEEVENT_RENAME             40026
#define ID_TIMEEVENT_NEWEVENT           40027
#define ID_SHAPESET_INSERTNEWCONVEX     40030
#define ID_SHAPESET_REMOVENODE          40031
#define ID_SHAPESET_REMOVESHAPESONLY    40032
#define ID_SHAPESET_LOADNEWCOLLISIONSHAPE 40033
#define ID_BOUNDBOX_VISIBLEBOUNDBOX     40034
#define ID_TIMEEVENT_TIMEEVENTSETTINGS  40035
#define ID_PROJECT_NEW                  40036
#define ID_PROJECT_DELETE               40037
#define ID_PROJECT_SETACTIVEPROJECT     40038
#define ID_GG_EXPAND                    40039
#define ID_GG_COLLAPSE                  40040
#define ID_GG_SELECT                    40041
#define ID_SELECT_UNSELECTALL           40043
#define ID_SELECT_SELECTALLDESCENDANTS  40044
#define ID_SELECT_UNSELECTALLDESCENDANTS 40045
#define ID_SELECT_SELECTBYTYPE          40046
#define ID_SELECT_REVERSESELECTION      40047
#define ID_GG_DELETE                    40048
#define ID_GG_SELECTALL                 40049
#define ID_SELECT_ALL                   40050
#define ID_ADD_CLONED_I3S               40053
#define ID_DELETE_CLONED_I3S            40055
#define ID_EDITI3S_ADDCURRENT           40056
#define ID_EDITI3S_DELETE               40057
#define ID_ADD_REF_I3S                  40058
#define ID_DELETE_REF_I3S               40059
#define ID_SKELETON_EXPAND              40060
#define ID_SKELETON_COLLAPSE            40061
#define IDC_TDK_ED_POSX                 40062
#define ID_ADD_PEFFILE                  40062
#define IDC_TDK_ED_POSY                 40063
#define ID_EDITPEFFILE_DELETE           40063
#define IDC_TDK_ED_POSZ                 40064
#define ID_DELETE_PEFFILE               40064
#define IDC_TDK_ED_SCALEX               40065
#define ID_EDITPEFFILE_NEWFILE          40065
#define IDC_TDK_ED_SCALEY               40066
#define ID_NEW_PEFFILE                  40066
#define IDC_TDK_ED_SCALEZ               40067
#define IDC_TDK_ED_ROTX                 40068
#define IDC_TDK_ED_ROTY                 40069
#define IDC_TDK_ED_ROTZ                 40070

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        343
#define _APS_NEXT_COMMAND_VALUE         40067
#define _APS_NEXT_CONTROL_VALUE         1398
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
