#include "pch.h"
#include "GlobalVariables.h"
#include "GameCharaAnimControlDefine.h"

//	ID_LOWER_AI와 배열순서가 매칭되야 하며, 문자열 이름들은 I3CHR에 등록된 AIState의 이름과 매칭되어야 합니다.
const char * g_szNameLowerAI [ ID_LOWER_AI_MAX] =
{
	"Idle",					//	ID_LOWER_IDLE

	"Front",				//	ID_LOWER_MOVE_FRONT,
	"FrontLeft",			//	ID_LOWER_MOVE_FRONT_LEFT,
	"FrontRight",			//	ID_LOWER_MOVE_FRONT_RIGHT,
	"Left",					//	ID_LOWER_MOVE_LEFT,
	"Right",				//	ID_LOWER_MOVE_RIGHT,
	"Back",					//	ID_LOWER_MOVE_BACK,
	"BackLeft",				//	ID_LOWER_MOVE_BACK_LEFT,
	"BackRight",			//	ID_LOWER_MOVE_BACK_RIGHT,

	"WalkFront",			//	ID_LOWER_WALK_FRONT,
	"WalkFrontLeft",		//	ID_LOWER_WALK_FRONT_LEFT,
	"WalkFrontRight",		//	ID_LOWER_WALK_FRONT_RIGHT,
	"WalkLeft",				//	ID_LOWER_WALK_LEFT,
	"WalkRight",			//	ID_LOWER_WALK_RIGHT,
	"WalkBack",				//	ID_LOWER_WALK_BACK,
	"WalkBackLeft",			//	ID_LOWER_WALK_BACK_LEFT,
	"WalkBackRight",		//	ID_LOWER_WALK_BACK_RIGHT,

	"JumpStart",			//	ID_LOWER_JUMP_START,
	"JumpEnd",				//	ID_LOWER_JUMP_END,

	"DeathFrontA1",			//	ID_LOWER_DEATH_FRONT_A1,
	"DeathFrontA2",			//	ID_LOWER_DEATH_FRONT_A2,
	"DeathFrontA3",			//	ID_LOWER_DEATH_FRONT_A3,

	"DeathLeftA",			//	ID_LOWER_DEATH_LEFT_A,
	"DeathRightA",			//	ID_LOWER_DEATH_RIGHT_A,
	"DeathBackA",			//	ID_LOWER_DEATH_BACK_A,

	"DeathFrontB",			//	ID_LOWER_DEATH_FRONT_B,
	"DeathLeftB",			//	ID_LOWER_DEATH_LEFT_B,
	"DeathRightB",			//	ID_LOWER_DEATH_RIGHT_B,
	"DeathBackB",			//	ID_LOWER_DEATH_BACK_B,

	"DeathFrontH1",			//	ID_LOWER_DEATH_FRONT_H1,
	"DeathFrontH2",			//	ID_LOWER_DEATH_FRONT_H2,

	"DeathLeftH",			//	ID_LOWER_DEATH_LEFT_H,
	"DeathRightH",			//	ID_LOWER_DEATH_RIGHT_H,
	"DeathBackH",			//	ID_LOWER_DEATH_BACK_H,
	"JumpStartMove",		//	ID_LOWER_DEATH_RIGHT_H,
	"JumpEndMove",			//	ID_LOWER_DEATH_BACK_H,
};


//	ID_LOWER_AI와 배열순서가 매칭되야 하며, 문자열 이름들은 I3CHR에 등록된 AIState의 이름과 매칭되어야 합니다.
const char * g_szNameLowerDinoAI [ ID_LOWER_DINO_AI_MAX] =
{
	"Idle",					//	ID_LOWER_IDLE

	"Front",				//	ID_LOWER_MOVE_FRONT,
	"FrontLeft",			//	ID_LOWER_MOVE_FRONT_LEFT,
	"FrontRight",			//	ID_LOWER_MOVE_FRONT_RIGHT,
	"Left",					//	ID_LOWER_MOVE_LEFT,
	"Right",				//	ID_LOWER_MOVE_RIGHT,
	"Back",					//	ID_LOWER_MOVE_BACK,
	"BackLeft",				//	ID_LOWER_MOVE_BACK_LEFT,
	"BackRight",			//	ID_LOWER_MOVE_BACK_RIGHT,

	"WalkFront",			//	ID_LOWER_WALK_FRONT,
	"WalkFrontLeft",		//	ID_LOWER_WALK_FRONT_LEFT,
	"WalkFrontRight",		//	ID_LOWER_WALK_FRONT_RIGHT,
	"WalkLeft",				//	ID_LOWER_WALK_LEFT,
	"WalkRight",			//	ID_LOWER_WALK_RIGHT,
	"WalkBack",				//	ID_LOWER_WALK_BACK,
	"WalkBackLeft",			//	ID_LOWER_WALK_BACK_LEFT,
	"WalkBackRight",		//	ID_LOWER_WALK_BACK_RIGHT,

	"JumpStart",			//	ID_LOWER_JUMP_START,
	"JumpEnd",				//	ID_LOWER_JUMP_END,

	"DeathFrontA1",			//	ID_LOWER_DEATH_FRONT_A1,
	"DeathFrontA2",			//	ID_LOWER_DEATH_FRONT_A2,
	"DeathFrontA3",			//	ID_LOWER_DEATH_FRONT_A3,

	"DeathLeftA",			//	ID_LOWER_DEATH_LEFT_A,
	"DeathRightA",			//	ID_LOWER_DEATH_RIGHT_A,
	"DeathBackA",			//	ID_LOWER_DEATH_BACK_A,

	"DeathFrontB",			//	ID_LOWER_DEATH_FRONT_B,
	"DeathLeftB",			//	ID_LOWER_DEATH_LEFT_B,
	"DeathRightB",			//	ID_LOWER_DEATH_RIGHT_B,
	"DeathBackB",			//	ID_LOWER_DEATH_BACK_B,

	"DeathFrontH1",			//	ID_LOWER_DEATH_FRONT_H1,
	"DeathFrontH2",			//	ID_LOWER_DEATH_FRONT_H2,

	"DeathLeftH",			//	ID_LOWER_DEATH_LEFT_H,
	"DeathRightH",			//	ID_LOWER_DEATH_RIGHT_H,
	"DeathBackH",			//	ID_LOWER_DEATH_BACK_H,
	"JumpStartMove",		//	ID_LOWER_DEATH_RIGHT_H,
	"JumpEndMove",			//	ID_LOWER_DEATH_BACK_H,
	"Status_Idle",			//	ID_LOWER_DINO_STATUS_IDLE
	"Status_Roar",			//	ID_LOWER_DINO_STATUS_ROAR
	"Status_Stun",			//	ID_LOWER_DINO_STATUS_ROAR
};


//	ID_UPPER_AI와 배열순서가 매칭되야 하며, 문자열 이름들은 I3CHR에 등록된 AIState의 이름과 매칭되어야 합니다.
const char * g_szNameUpperAI[ ID_UPPER_AI_MAX] =
{
	"Idle",					//	ID_UPPER_IDLE,
	"Move",					//	ID_UPPER_MOVE,

	"Attack",				//	ID_UPPER_ATTACK,
	"AttackReady",			//	ID_UPPER_ATTACK_READY,
	"Attack2",				//	ID_UPPER_ATTACK2,
	"SecondaryAttack",		//	ID_UPPER_SECONDARY_ATTACK,

	"LoadMagazine",			//	ID_UPPER_LOAD_MAGAZINE,
	"LoadMagazine2",		//	ID_UPPER_LOAD_MAGAZINE2,
	"LoadBullet",			//	ID_UPPER_LOAD_BULLET,
	"Change",				//	ID_UPPER_SWAP_WEAPON,

	"JumpStart",			//	ID_UPPER_JUMP_START,
	"JumpEnd",				//	ID_UPPER_JUMP_END,

	"ExtensionActivate",	//	ID_UPPER_EXTENSION_ACTIVATE,
	"ExtensionDeactivate",	//	ID_UPPER_EXTENSION_DEACTIVATE,

	"DamageFrontLeftA",		//	ID_UPPER_DAMAGE_FRONT_LEFT_A,
	"DamageFrontRightA",	//	ID_UPPER_DAMAGE_FRONT_RIGHT_A,
	"DamageBackA",			//	ID_UPPER_DAMAGE_BACK_A,
	"DamageFrontLeftB",		//	ID_UPPER_DAMAGE_FRONT_LEFT_B,
	"DamageFrontRightB",	//	ID_UPPER_DAMAGE_FRONT_RIGHT_B,
	"DamageBackB",			//	ID_UPPER_DAMAGE_BACK_B,

	"AttackBurst",			// ID_UPPER_ATTACKBURST
	"Throw",				// ID_UPPER_THROW
	"SecondaryAttackBurst", // ID_UPPER_SECONDARY_ATTACKBURST
	"LoadMagMaster",		// ID_UPPER_LOAD_MAGAZINE_MASTER
	"LoadC_Master",			// ID_UPPER_LOAD_MAGAZINE_SHOTGUN_MASTER_C
	"LoadB_Master",			// ID_UPPER_LOAD_MAGAZINE_SHOTGUN_MASTER_B
	"LoadD_Master",			// ID_UPPER_LOAD_MAGAZINE_SHOTGUN_MASTER_D

	"LoadMagazineReady",	// ID_UPPER_LOAD_MAGAZINE_READY
	"FireBullet",			// ID_UPPER_FIRE_BULLET

	// UI Animation (Lobby, ReadyRoom, Inventory, Shop)
	"UI_IdleA",				// ID_UPPER_NONEBATTLE_IDLE
	"UI_IdleB",				// ID_UPPER_NONEBATTLE_SHOWWEAPON
	"UI_Idle_Change",		// ID_UPPER_NONEBATTLE_IDLE_CHANGE
	"UI_Idle_Stand",		// ID_UPPER_NONEBATTLE_IDLE_STAND

};

const char * g_szNameUpperDualAI[ ID_UPPER_DUAL_AI_MAX] =
{
	"LeftIdle",				// ID_UPPER_DUAL_IDLE_LEFT
	"LeftMove",				// ID_UPPER_DUAL_MOVE_LEFT,
	"LeftAttack",			// ID_UPPER_DUAL_ATTACK_LEFT,
	"LeftJumpStart",		// ID_UPPER_DUAL_JUMP_START_LEFT,
	"LeftJumpEnd",			// ID_UPPER_DUAL_JUMP_END_LEFT,

	"RightIdle",			// ID_UPPER_DUAL_IDLE_RIGHT,
	"RightMove",			// ID_UPPER_DUAL_MOVE_RIGHT,
	"RightAttack",			// ID_UPPER_DUAL_ATTACK_RIGHT,
	"RightJumpStart",		// ID_UPPER_DUAL_JUMP_START_RIGHT,
	"RightJumpEnd",			// ID_UPPER_DUAL_JUMP_END_RIGHT,
};

// ID_UPPER_DINO_AI 도 같이 고쳐 줘야 합니다.
const char * g_szNameUpperAI_Dino[ ID_UPPER_DINO_AI_MAX] =
{
	"Idle",							// ID_UPPER_DINO_IDLE,
	"Move",							// ID_UPPER_DINO_MOVE,
	"Attack_A",					// ID_UPPER_DINO_ATTACK1_A,
	"Attack_B",					// ID_UPPER_DINO_ATTACK1_B,
	"MoveAttack_A",				// ID_UPPER_DINO_ATTACK1_A,
	"MoveAttack_B",				// ID_UPPER_DINO_ATTACK1_B,
	"DamageLeft",					// ID_UPPER_DINO_DAMAGE_LEFT,
	"DamageRight",					// ID_UPPER_DINO_DAMAGE_RIGHT,
	"JumpStart",					// ID_UPPER_DINO_JUMP_START,
	"JumpEnd",						// ID_UPPER_DINO_JUMP_END,
	"MoveDamageLeftA",				// ID_UPPER_DINO_DAMAGE_MOVE_LEFT,
	"MoveDamageRightA",				// ID_UPPER_DINO_DAMAGE_MOVE_RIGHT,
	"Walk_Idle",					// ID_UPPER_DINO_WALK
	"Sit_Idle",
};

const char * g_szNameCommonAI[ ID_COMMON_AI_MAX] =
{
	"Ceremony",
	"Death",
};

const char * g_szNameDefaultAI[ ID_DEFAULT_AI_MAX] =
{
	"Idle",					//	ID_UPPER_IDLE,
	"AttackIdle",			//	ID_UPPER_MOVE,

	"Attack",				//	ID_UPPER_ATTACK,
	"Damage",
	"Death",
};

const char * g_szLowerBoneName[ 10 ] =
{
	"Root",
	"Pelvis",
	"L Thigh",
	"L Calf",
	"L Foot",
	"L Toe",
	"R Thigh",
	"R Calf",
	"R Foot",
	"R Toe",
};
const char * g_szLowerTankBoneName[ CHARA_LOWER_DINO_BONE_COUNT ] =
{
	"Tank_Root",
	"Tank_Root Pelvis",
	"Tank_Root L Thigh",
	"Tank_Root L Calf",
	"Tank_Root L HorseLink",
	"Tank_Root L Foot",
	"Tank_Root L Toe0",
	"Tank_Root L Toe01",
	"Tank_Root L Toe02",
	"Tank_Root L Toe1",
	"Tank_Root L Toe11",
	"Tank_Root L Toe12",
	"Tank_Root L Toe2",
	"Tank_Root L Toe21",
	"Tank_Root L Toe22",
	"Tank_Root R Thigh",
	"Tank_Root R Calf",
	"Tank_Root R HorseLink",
	"Tank_Root R Foot",
	"Tank_Root R Toe0",
	"Tank_Root R Toe01",
	"Tank_Root R Toe02",
	"Tank_Root R Toe1",
	"Tank_Root R Toe11",
	"Tank_Root R Toe12",
	"Tank_Root R Toe2",
	"Tank_Root R Toe21",
	"Tank_Root R Toe22",
	"Tank_Root Tail",
	"Tank_Root Tail1",
	"Tank_Root Tail2",
	"Tank_Root Tail3"

};


const char * g_szLowerStingBoneName[ CHARA_LOWER_DINO_BONE_COUNT ] =
{
	"Sting_Root",
	"Sting_Root Pelvis",
	"Sting_Root L Thigh",
	"Sting_Root L Calf",
	"Sting_Root L HorseLink",
	"Sting_Root L Foot",
	"Sting_Root L Toe0",
	"Sting_Root L Toe01",
	"Sting_Root L Toe02",
	"Sting_Root L Toe1",
	"Sting_Root L Toe11",
	"Sting_Root L Toe12",
	"Sting_Root L Toe2",
	"Sting_Root L Toe21",
	"Sting_Root L Toe22",
	"Sting_Root R Thigh",
	"Sting_Root R Calf",
	"Sting_Root R HorseLink",
	"Sting_Root R Foot",
	"Sting_Root R Toe0",
	"Sting_Root R Toe01",
	"Sting_Root R Toe02",
	"Sting_Root R Toe1",
	"Sting_Root R Toe11",
	"Sting_Root R Toe12",
	"Sting_Root R Toe2",
	"Sting_Root R Toe21",
	"Sting_Root R Toe22",
	"Sting_Root Tail",
	"Sting_Root Tail1",
	"Sting_Root Tail2",
	"Sting_Root Tail3"



};

const char * g_szLowerAcidBoneName[ CHARA_LOWER_DINO_BONE_COUNT ] =
{
	"Acid_Root",
	"Acid_Root Pelvis",
	"Acid_Root L Thigh",
	"Acid_Root L Calf",
	"Acid_Root L HorseLink",
	"Acid_Root L Foot",
	"Acid_Root L Toe0",
	"Acid_Root L Toe01",
	"Acid_Root L Toe02",
	"Acid_Root L Toe1",
	"Acid_Root L Toe11",
	"Acid_Root L Toe12",
	"Acid_Root L Toe2",
	"Acid_Root L Toe21",
	"Acid_Root L Toe22",
	"Acid_Root R Thigh",
	"Acid_Root R Calf",
	"Acid_Root R HorseLink",
	"Acid_Root R Foot",
	"Acid_Root R Toe0",
	"Acid_Root R Toe01",
	"Acid_Root R Toe02",
	"Acid_Root R Toe1",
	"Acid_Root R Toe11",
	"Acid_Root R Toe12",
	"Acid_Root R Toe2",
	"Acid_Root R Toe21",
	"Acid_Root R Toe22",
	"Acid_Root Tail",
	"Acid_Root Tail1",
	"Acid_Root Tail2",
	"Acid_Root Tail3"



};
const char * g_szLowerEliteBoneName[ CHARA_LOWER_DINO_BONE_COUNT ] =
{
	"Elite_Root",
	"Elite_Root Pelvis",
	"Elite_Root L Thigh",
	"Elite_Root L Calf",
	"Elite_Root L HorseLink",
	"Elite_Root L Foot",
	"Elite_Root L Toe0",
	"Elite_Root L Toe01",
	"Elite_Root L Toe02",
	"Elite_Root L Toe1",
	"Elite_Root L Toe11",
	"Elite_Root L Toe12",
	"Elite_Root L Toe2",
	"Elite_Root L Toe21",
	"Elite_Root L Toe22",
	"Elite_Root R Thigh",
	"Elite_Root R Calf",
	"Elite_Root R HorseLink",
	"Elite_Root R Foot",
	"Elite_Root R Toe0",
	"Elite_Root R Toe01",
	"Elite_Root R Toe02",
	"Elite_Root R Toe1",
	"Elite_Root R Toe11",
	"Elite_Root R Toe12",
	"Elite_Root R Toe2",
	"Elite_Root R Toe21",
	"Elite_Root R Toe22",
	"Elite_Root Tail",
	"Elite_Root Tail1",
	"Elite_Root Tail2",
	"Elite_Root Tail3"



};
const char * g_szLowerDinoBoneName[ CHARA_LOWER_DINO_BONE_COUNT ] =
{
	"Velociraptor_Root",
	"Velociraptor Pelvis",
	"Velociraptor L Thigh",
	"Velociraptor L Calf",
	"Velociraptor L HorseLink",
	"Velociraptor L Foot",
	"Velociraptor L Toe0",
	"Velociraptor L Toe01",
	"Velociraptor L Toe02",
	"Velociraptor L Toe1",
	"Velociraptor L Toe11",
	"Velociraptor L Toe12",
	"Velociraptor L Toe2",
	"Velociraptor L Toe21",
	"Velociraptor L Toe22",
	"Velociraptor R Thigh",
	"Velociraptor R Calf",
	"Velociraptor R HorseLink",
	"Velociraptor R Foot",
	"Velociraptor R Toe0",
	"Velociraptor R Toe01",
	"Velociraptor R Toe02",
	"Velociraptor R Toe1",
	"Velociraptor R Toe11",
	"Velociraptor R Toe12",
	"Velociraptor R Toe2",
	"Velociraptor R Toe21",
	"Velociraptor R Toe22",
	"Velociraptor Tail",
	"Velociraptor Tail1",
	"Velociraptor Tail2",
	"Velociraptor Tail3"
};

const char * g_szLowerTRexBoneName[ CHARA_LOWER_TREX_BONE_COUNT ] =
{
	"Dino_T-Rex",
	"Dino_T-Rex Pelvis",
	"Dino_T-Rex L Thigh",
	"Dino_T-Rex L Calf",
	"Dino_T-Rex L HorseLink",
	"Dino_T-Rex L Foot",
	"Dino_T-Rex L Toe0",
	"Dino_T-Rex L Toe01",
	"Dino_T-Rex L Toe02",
	"Dino_T-Rex L Toe1",
	"Dino_T-Rex L Toe11",
	"Dino_T-Rex L Toe12",
	"Dino_T-Rex L Toe2",
	"Dino_T-Rex L Toe21",
	"Dino_T-Rex L Toe22",
	"Dino_T-Rex R Thigh",
	"Dino_T-Rex R Calf",
	"Dino_T-Rex R HorseLink",
	"Dino_T-Rex R Foot",
	"Dino_T-Rex R Toe0",
	"Dino_T-Rex R Toe01",
	"Dino_T-Rex R Toe02",
	"Dino_T-Rex R Toe1",
	"Dino_T-Rex R Toe11",
	"Dino_T-Rex R Toe12",
	"Dino_T-Rex R Toe2",
	"Dino_T-Rex R Toe21",
	"Dino_T-Rex R Toe22",
	"Dino_T-Rex Tail",
	"Dino_T-Rex Tail1",
	"Dino_T-Rex Tail2",
	"Dino_T-Rex Tail3"
};

const char * g_szUpperBoneName[ 51] =
{
	"Spine1",
	"Spine2",
	"Spine3",
	"Neck",
	"Head",
	"R Clavicle",
	"R UpperArm",
	"R Forearm",
	"R Hand",
	"R Thumb1",
	"R Thumb2",
	"R Thumb3",
	"R Index1",
	"R Index2",
	"R Index3",
	"R Middle1",
	"R Middle2",
	"R Middle3",
	"R Ring1",
	"R Ring2",
	"R Ring3",
	"R Little1",
	"R Little2",
	"R Little3",
	"R Twist1",
	"R Twist2",
	"R Twist3",
	"R Twist4",
	"L Clavicle",
	"L UpperArm",
	"L Forearm",
	"L Hand",
	"L Thumb1",
	"L Thumb2",
	"L Thumb3",
	"L Index1",
	"L Index2",
	"L Index3",
	"L Middle1",
	"L Middle2",
	"L Middle3",
	"L Ring1",
	"L Ring2",
	"L Ring3",
	"L Little1",
	"L Little2",
	"L Little3",
	"L Twist1",
	"L Twist2",
	"L Twist3",
	"L Twist4",

};
const char * g_szUpperStingBoneName[ CHARA_UPPER_DINO_BONE_COUNT ] =
{
	"Sting_Root Spine",
	"Sting_Root Spine1",
	"Sting_Root Spine2",
	"Sting_Root Neck",
	"Sting_Root Neck1",
	"Sting_Root Neck2",
	"Sting_Root Head",
	"Sting_Root Ponytail1",
	"Sting_Root Ponytail11",
	"Sting_Root Ponytail2",
	"Sting_Root Ponytail21",
	"Sting_Root Ponytail22",
	"Sting_Root L Clavicle",
	"Sting_Root L UpperArm",
	"Sting_Root L Forearm",
	"Sting_Root L Hand",
	"Sting_Root L Finger0",
	"Sting_Root L Finger01",
	"Sting_Root L Finger02",
	"Sting_Root L Finger1",
	"Sting_Root L Finger11",
	"Sting_Root L Finger12",
	"Sting_Root L Finger2",
	"Sting_Root L Finger21",
	"Sting_Root L Finger22",
	"Sting_Root L ForeTwist",
	"Sting_Root L ForeTwist1",
	"Sting_Root L ForeTwist2",
	"Sting_Root R Clavicle",
	"Sting_Root R UpperArm",
	"Sting_Root R Forearm",
	"Sting_Root R Hand",
	"Sting_Root R Finger0",
	"Sting_Root R Finger01",
	"Sting_Root R Finger02",
	"Sting_Root R Finger1",
	"Sting_Root R Finger11",
	"Sting_Root R Finger12",
	"Sting_Root R Finger2",
	"Sting_Root R Finger21",
	"Sting_Root R Finger22",
	"Sting_Root R ForeTwist",
	"Sting_Root R ForeTwist1",
	"Sting_Root R ForeTwist2",
	"Pivot",
	"Pivot_Camera",
};
const char * g_szUpperEliteBoneName[ CHARA_UPPER_ELITE_BONE_COUNT ] =
{
	"Elite_Root Spine",
	"Elite_Root Spine1",
	"Elite_Root Spine2",
	"Elite_Root Neck",
	"Elite_Root Neck1",
	"Elite_Root Neck2",
	"Elite_Root Head",
	"Elite_Root Ponytail1",
	"Elite_Root Ponytail11",
	"Elite_Root Ponytail2",
	"Elite_Root Ponytail21",
	"Elite_Root Ponytail22",
	"Elite_Root Ponytail23",
	"Elite_Root L Clavicle",
	"Elite_Root L UpperArm",
	"Elite_Root L Forearm",
	"Elite_Root L Hand",
	"Elite_Root L Finger0",
	"Elite_Root L Finger01",
	"Elite_Root L Finger02",
	"Elite_Root L Finger1",
	"Elite_Root L Finger11",
	"Elite_Root L Finger12",
	"Elite_Root L ForeTwist",
	"Elite_Root L ForeTwist1",
	"Elite_Root L ForeTwist2",
	"Elite_Root R Clavicle",
	"Elite_Root R UpperArm",
	"Elite_Root R Forearm",
	"Elite_Root R Hand",
	"Elite_Root R Finger0",
	"Elite_Root R Finger01",
	"Elite_Root R Finger02",
	"Elite_Root R Finger1",
	"Elite_Root R Finger11",
	"Elite_Root R Finger12",
	"Elite_Root R ForeTwist",
	"Elite_Root R ForeTwist1",
	"Elite_Root R ForeTwist2",
	"Pivot",
	"Pivot_Camera",
};
const char * g_szUpperTankBoneName[ CHARA_UPPER_DINO_BONE_COUNT ] =
{
	"Tank_Root Spine",
	"Tank_Root Spine1",
	"Tank_Root Spine2",
	"Tank_Root Neck",
	"Tank_Root Neck1",
	"Tank_Root Neck2",
	"Tank_Root Head",
	"Tank_Root Ponytail1",
	"Tank_Root Ponytail11",
	"Tank_Root Ponytail2",
	"Tank_Root Ponytail21",
	"Tank_Root Ponytail22",
	"Tank_Root L Clavicle",
	"Tank_Root L UpperArm",
	"Tank_Root L Forearm",
	"Tank_Root L Hand",
	"Tank_Root L Finger0",
	"Tank_Root L Finger01",
	"Tank_Root L Finger02",
	"Tank_Root L Finger1",
	"Tank_Root L Finger11",
	"Tank_Root L Finger12",
	"Tank_Root L Finger2",
	"Tank_Root L Finger21",
	"Tank_Root L Finger22",
	"Tank_Root L ForeTwist",
	"Tank_Root L ForeTwist1",
	"Tank_Root L ForeTwist2",
	"Tank_Root R Clavicle",
	"Tank_Root R UpperArm",
	"Tank_Root R Forearm",
	"Tank_Root R Hand",
	"Tank_Root R Finger0",
	"Tank_Root R Finger01",
	"Tank_Root R Finger02",
	"Tank_Root R Finger1",
	"Tank_Root R Finger11",
	"Tank_Root R Finger12",
	"Tank_Root R Finger2",
	"Tank_Root R Finger21",
	"Tank_Root R Finger22",
	"Tank_Root R ForeTwist",
	"Tank_Root R ForeTwist1",
	"Tank_Root R ForeTwist2",
	"Pivot",
	"Pivot_Camera",
};

const char * g_szUpperAcidBoneName[ CHARA_UPPER_DINO_BONE_COUNT ] =
{
	"Acid_Root Spine",
	"Acid_Root Spine1",
	"Acid_Root Spine2",
	"Acid_Root Neck",
	"Acid_Root Neck1",
	"Acid_Root Neck2",
	"Acid_Root Head",
	"Acid_Root Ponytail1",
	"Acid_Root Ponytail11",
	"Acid_Root Ponytail2",
	"Acid_Root Ponytail21",
	"Acid_Root Ponytail22",
	"Acid_Root L Clavicle",
	"Acid_Root L UpperArm",
	"Acid_Root L Forearm",
	"Acid_Root L Hand",
	"Acid_Root L Finger0",
	"Acid_Root L Finger01",
	"Acid_Root L Finger02",
	"Acid_Root L Finger1",
	"Acid_Root L Finger11",
	"Acid_Root L Finger12",
	"Acid_Root L Finger2",
	"Acid_Root L Finger21",
	"Acid_Root L Finger22",
	"Acid_Root L ForeTwist",
	"Acid_Root L ForeTwist1",
	"Acid_Root L ForeTwist2",
	"Acid_Root R Clavicle",
	"Acid_Root R UpperArm",
	"Acid_Root R Forearm",
	"Acid_Root R Hand",
	"Acid_Root R Finger0",
	"Acid_Root R Finger01",
	"Acid_Root R Finger02",
	"Acid_Root R Finger1",
	"Acid_Root R Finger11",
	"Acid_Root R Finger12",
	"Acid_Root R Finger2",
	"Acid_Root R Finger21",
	"Acid_Root R Finger22",
	"Acid_Root R ForeTwist",
	"Acid_Root R ForeTwist1",
	"Acid_Root R ForeTwist2",
	"Pivot",
	"Pivot_Camera",
};

const char * g_szUpperDinoBoneName[ CHARA_UPPER_RAPTOR_BONE_COUNT] =
{
	"Velociraptor Spine",
	"Velociraptor Spine1",
	"Velociraptor Spine2",
	"Velociraptor Neck",
	"Velociraptor Neck1",
	"Velociraptor Neck2",
	"Velociraptor Head",
	"Velociraptor Ponytail1",
	"Velociraptor Ponytail11",
	"Velociraptor Ponytail2",
	"Velociraptor Ponytail21",
	"Velociraptor Ponytail22",
	"Velociraptor Ponytail23",
	"Velociraptor L Clavicle",
	"Velociraptor L UpperArm",
	"Velociraptor L Forearm",
	"Velociraptor L Hand",
	"Velociraptor L Finger0",
	"Velociraptor L Finger01",
	"Velociraptor L Finger02",
	"Velociraptor L Finger1",
	"Velociraptor L Finger11",
	"Velociraptor L Finger12",
	"Velociraptor L Finger2",
	"Velociraptor L Finger21",
	"Velociraptor L Finger22",
	"Velociraptor L Twist",
	"Velociraptor L Twist1",
	"Velociraptor L Twist2",
	"Velociraptor R Clavicle",
	"Velociraptor R UpperArm",
	"Velociraptor R Forearm",
	"Velociraptor R Hand",
	"Velociraptor R Finger0",
	"Velociraptor R Finger01",
	"Velociraptor R Finger02",
	"Velociraptor R Finger1",
	"Velociraptor R Finger11",
	"Velociraptor R Finger12",
	"Velociraptor R Finger2",
	"Velociraptor R Finger21",
	"Velociraptor R Finger22",
	"Velociraptor R Twist",
	"Velociraptor R Twist1",
	"Velociraptor R Twist2",
	"Pivot",
	"Pivot_Camera",
};

const char * g_szUpperTRexBoneName[ CHARA_UPPER_TREX_BONE_COUNT] =
{
	"IK",
	"Dino_T-Rex Spine",
	"Dino_T-Rex Spine1",
	"Dino_T-Rex Spine2",
	"IK_Neck",
	"Dino_T-Rex Neck",
	"Dino_T-Rex Neck1",
	"Dino_T-Rex Neck2",
	"IK_Head",
	"Dino_T-Rex Head",
	"Dino_T-Rex Ponytail1",
	"Dino_T-Rex Ponytail11",
	"Dino_T-Rex Ponytail2",
	"Dino_T-Rex Ponytail21",
	"Dino_T-Rex Ponytail22",
	"Dino_T-Rex Ponytail23",
	"Pivot_Camera",
	"Dino_T-Rex L Clavicle",
	"Dino_T-Rex L UpperArm",
	"Dino_T-Rex L Forearm",
	"Dino_T-Rex L Hand",
	"Dino_T-Rex L Finger0",
	"Dino_T-Rex L Finger01",
	"Dino_T-Rex L Finger02",
	"Dino_T-Rex L Finger1",
	"Dino_T-Rex L Finger11",
	"Dino_T-Rex L Finger12",
	"Dino_T-Rex R Clavicle",
	"Dino_T-Rex R UpperArm",
	"Dino_T-Rex R Forearm",
	"Dino_T-Rex R Hand",
	"Dino_T-Rex R Finger0",
	"Dino_T-Rex R Finger01",
	"Dino_T-Rex R Finger02",
	"Dino_T-Rex R Finger1",
	"Dino_T-Rex R Finger11",
	"Dino_T-Rex R Finger12",
	"Pivot",
};

const char * g_szUpperMutantTRexBoneName[ CHARA_UPPER_MUTANT_TREX_BONE_COUNT] =
{
	"IK",
	"Dino_T-Rex Spine",
	"Dino_T-Rex Spine1",
	"IK_Neck",
	"Dino_T-Rex Neck",
	"Dino_T-Rex Neck1",
	"IK_Head",
	"Dino_T-Rex Head",
	"Dino_T-Rex Ponytail1",
	"Dino_T-Rex Ponytail11",
	"Dino_T-Rex Ponytail2",
	"Dino_T-Rex Ponytail21",
	"Dino_T-Rex Ponytail22",
	"Dino_T-Rex Ponytail23",
	"Pivot_Camera",
	"Dino_T-Rex L Clavicle",
	"Dino_T-Rex L UpperArm",
	"Dino_T-Rex L Forearm",
	"Dino_T-Rex L Hand",
	"Dino_T-Rex L Finger0",
	"Dino_T-Rex L Finger01",
	"Dino_T-Rex L Finger02",
	"Dino_T-Rex L Finger1",
	"Dino_T-Rex L Finger11",
	"Dino_T-Rex L Finger12",
	"Dino_T-Rex R Clavicle",
	"Dino_T-Rex R UpperArm",
	"Dino_T-Rex R Forearm",
	"Dino_T-Rex R Hand",
	"Dino_T-Rex R Finger0",
	"Dino_T-Rex R Finger01",
	"Dino_T-Rex R Finger02",
	"Dino_T-Rex R Finger1",
	"Dino_T-Rex R Finger11",
	"Dino_T-Rex R Finger12",
	"Pivot",
};