#pragma once

enum 
{ 
	MAX_TEAM_SLOT_COUNT = (SLOT_MAX_COUNT >> 1), 
	MAX_ALL_USER = (MAX_TEAM_USER + MAX_TEAM_USER),
	INDICATOR_COUNT_PEROBJ = 8,
	INDICATE_OBJ_COUNT = 2,
	MAX_INDICATOR = (INDICATOR_COUNT_PEROBJ * INDICATE_OBJ_COUNT),	//1종류당 8개 현재 2종류
};

enum HUD_MODE
{
	HUD_MODE_NONE = -1,
	HUD_MODE_DEFAULT = 0,
	HUD_MODE_MISSION_ROUND_START,
	HUD_MODE_MISSION_SCORE,
	HUD_MODE_MISSION_OBSERVER,		// Observer camera mode
	HUD_MODE_MISSION_FLY,			// Fly camera mode
	HUD_MODE_NOTHING,
	HUD_MODE_CHAOS,					// Chaos mode

	HUD_MODE_COUNT,
};

enum GAME_GUI_STATUS
{
	GAME_GUI_RESPAWN =		0,
	GAME_GUI_RESULT,
	GAME_GUI_SCORE,
	GAME_GUI_PRESTART_ROUND,
	GAME_GUI_BATTLE_START,
	GAME_GUI_ROUND_START,
	GAME_GUI_NONE,
};

enum ResultWinState
{
	RS_RED_WIN = 0,
	RS_BLUE_WIN,
	RS_DRAW,

	RS_MAX
};


enum HUD_SPRITE_MISSION
{
	HUD_SPRITE_MISSION_MESSAGE_BG = 0,
	HUD_SPRITE_MISSION_TEAM,
	HUD_SPRITE_MISSION_RESULT,

	HUD_SPRITE_MISSION_COUNT,
};

enum HUD_SPRITE_MISSION_BOMB
{
	HUD_SPRITE_MISSION_BOMB_TIMER_BG = 0,			// 폭탄 타이머BG
	HUD_SPRITE_MISSION_BOMB_LARGE,					// 폭탄 이미지
	HUD_SPRITE_MISSION_BOMB_LARGE_INSTALLED,		// 설치후 폭탄 이미지
	HUD_SPRITE_MISSION_BOMB_GAGE_BG,				// 설치/해제 게이지 BG
	HUD_SPRITE_MISSION_BOMB_GAGE,					// 설치/해제 게이지
	HUD_SPRITE_MISSION_BOMB_WRENCH,					// 해체구분용 랜치

	HUD_SPRITE_MISSION_BOMB_COUNT,
};

enum HUD_TEXT_OBSERVER
{
	HUD_TEXT_OBSERVER_ID,
	HUD_TEXT_OBSERVER_NEXT,
	HUD_TEXT_OBSERVER_PREV,
	HUD_TEXT_OBSERVER_WEAPON,
	HUD_TEXT_OBSERVER_VIEW,

	HUD_TEXT_OBSERVER_COUNT
};

enum HUD_TEXT_OBSERVER_FLY
{
	HUD_TEXT_OBSERVER_FLY_MOVE_SPEED,
	//HUD_TEXT_OBSERVER_FLY_ROTATE_SPEED,

	HUD_TEXT_OBSERVER_FLY_COUNT
};

enum HUD_SPRITE_USURPATION
{
	HUD_SPRITE_USURPATION_WATERMELON = 0,
	HUD_SPRITE_USURPATION_WATERMELON_INDICATOR,

	HUD_SPRITE_USURPATION_COUNT
};

enum HUD_USURPATION_TEXT
{
	HUD_USURPATION_TEXT_NOTICE = 0,

	HUD_USURPATION_TEXT_COUNT
};

enum HUD_MISSION_TEXT
{
	HUD_MISSION_TEXT_MESSAGE = 0,
	HUD_MISSION_TEXT_NOTICE,

	HUD_MISSION_TEXT_COUNT,
};

enum HUD_BOMB_TEXT
{
	HUD_BOMB_TEXT_TIME,

	HUD_BOMB_TEXT_COUNT,
};

enum HUD_SPRITE_HIT
{
	HUD_SPRITE_HIT_DAMAGE = 0,
/*	
	HUD_SPRITE_HIT_FRONT,
	HUD_SPRITE_HIT_BACK,
	HUD_SPRITE_HIT_LEFT,
	HUD_SPRITE_HIT_RIGHT,
*/
	HUD_SPRITE_WARNING_LEFT_FRONT,
	HUD_SPRITE_WARNING_RIGHT_FRONT,
	HUD_SPRITE_WARNING_LEFT_BACK,
	HUD_SPRITE_WARNING_RIGHT_BACK,
	
	HUD_SPRITE_HIT_ANGLE_START,
	HUD_SPRITE_HIT_ANGLE_1,
	HUD_SPRITE_HIT_ANGLE_2,
	HUD_SPRITE_HIT_ANGLE_3,
	HUD_SPRITE_HIT_ANGLE_4,
	HUD_SPRITE_HIT_ANGLE_5,
	HUD_SPRITE_HIT_ANGLE_6,
	HUD_SPRITE_HIT_ANGLE_7,
	HUD_SPRITE_HIT_ANGLE_8,
	HUD_SPRITE_HIT_ANGLE_END,

	HUD_SPRITE_HIT_COUNT,
};
#define HUD_SPRITE_WARNING_MAX		(HUD_SPRITE_WARNING_RIGHT_BACK - HUD_SPRITE_WARNING_LEFT_FRONT + 1)
#define HUD_SPRITE_HIT_ANGLE_MAX	(HUD_SPRITE_HIT_ANGLE_END - HUD_SPRITE_HIT_ANGLE_START + 1)

enum HUD_SPRITE_SKILL				//	임시. 나중에 추가 및 수정하세요.
{
	HUD_SPRITE_SKILL_UNABLE_NUM6 = 0,	//	사용불가 슬롯
	HUD_SPRITE_SKILL_UNABLE_NUM7,
	HUD_SPRITE_SKILL_UNABLE_NUM8,
	HUD_SPRITE_SKILL_UNABLE_NUM9,
	HUD_SPRITE_SKILL_UNABLE_NUM10,
	HUD_SPRITE_SKILL_EMPTY_NUM1,		//	빈 슬롯
	HUD_SPRITE_SKILL_EMPTY_NUM2,
	HUD_SPRITE_SKILL_EMPTY_NUM3,
	HUD_SPRITE_SKILL_EMPTY_NUM4,
	HUD_SPRITE_SKILL_EMPTY_NUM5,
	HUD_SPRITE_SKILL_EMPTY_NUM6,
	HUD_SPRITE_SKILL_EMPTY_NUM7,
	HUD_SPRITE_SKILL_EMPTY_NUM8,
	HUD_SPRITE_SKILL_EMPTY_NUM9,
	HUD_SPRITE_SKILL_EMPTY_NUM10,
	HUD_SPRITE_SKILL_BOOM,			//	폭발탄
	HUD_SPRITE_SKILL_FRAME,			//	화염탄
	HUD_SPRITE_SKILL_SPEED,			//	연사
	HUD_SPRITE_SKILL_SMOKE,			//	연막탄

	HUD_SPRITE_SKILL_COUNT
};

enum HUD_SPRITE_SMALL_NUM
{
	HUD_SPRITE_SMALL_NUM1 = 0,
	HUD_SPRITE_SMALL_NUM2,
	HUD_SPRITE_SMALL_NUM3,
	HUD_SPRITE_SMALL_NUM4,
	HUD_SPRITE_SMALL_NUM5,
	HUD_SPRITE_SMALL_NUM6,
	HUD_SPRITE_SMALL_NUM7,
	HUD_SPRITE_SMALL_NUM8,
	HUD_SPRITE_SMALL_NUM9,
	HUD_SPRITE_SMALL_NUM0,			// 10

    HUD_SPRITE_SMALL_NUM_COUNT,
};

enum HUD_TEXT_TRAINING_RECORD
{
	HUD_TEXT_TRAINING_RECORD_STAGE = 0,
	HUD_TEXT_TRAINING_RECORD_SCORE,
	HUD_TEXT_TRAINING_RECORD_NICK,	

	HUD_TEXT_TRAINING_RECORD_COUNT,
};

struct REVENGE_ARRAY
{
	i3::rc_wstring wstrTargetName;
	INT32 nLosePoint, nWinPoint;
};

#define HUD_OBJECT_REPLY_COUNT	5
#define HUD_NOTICE_COUNT		20
#define HUD_NOTICE_TIME			5.0f
#define HUD_NAME_MAX_COUNT		36
#define HUD_RADIOCHAT_COUNT		11
#define HUD_RADIOCHAT1_COUNT	10
#define HUD_RADIOCHAT2_COUNT	10
#define HUD_RADIOCHAT3_COUNT	10

#define SCR_BACKBUFFER_COUNT		3			//	백버퍼 이미지 갯수
#define SCR_BACKBUFFER_TEX_SIZE		256			//	백버퍼 사이즈

enum HUD_SPRITE_SCORE
{
	// 결과창
	HUD_SCORE_FRAME = 0,
	HUD_SCORE_MY_SLOT,

	HUD_SCORE_RED_NUMBER_0,
	HUD_SCORE_RED_NUMBER_1,
	HUD_SCORE_RED_NUMBER_2,

	HUD_SCORE_BLUE_NUMBER_0,
	HUD_SCORE_BLUE_NUMBER_1,
	HUD_SCORE_BLUE_NUMBER_2,

	HUD_SCORE_RED_TYPE,
	HUD_SCORE_BLUE_TYPE,

	HUD_SCORE_CLAN,

	HUD_SCORE_COUNT,
};

enum HUD_TEXT_SCORE
{
	HUD_TEXT_SCORE_ID_1 = 0,
	HUD_TEXT_SCORE_ID_2,
	HUD_TEXT_SCORE_ID_3,
	HUD_TEXT_SCORE_ID_4,
	HUD_TEXT_SCORE_ID_5,
	HUD_TEXT_SCORE_ID_6,
	HUD_TEXT_SCORE_ID_7,
	HUD_TEXT_SCORE_ID_8,
	HUD_TEXT_SCORE_HERO_KILL_1,
	HUD_TEXT_SCORE_HERO_KILL_2,
	HUD_TEXT_SCORE_HERO_KILL_3,
	HUD_TEXT_SCORE_HERO_KILL_4,
	HUD_TEXT_SCORE_HERO_KILL_5,
	HUD_TEXT_SCORE_HERO_KILL_6,
	HUD_TEXT_SCORE_HERO_KILL_7,
	HUD_TEXT_SCORE_HERO_KILL_8,
	HUD_TEXT_SCORE_DEATH_1,
	HUD_TEXT_SCORE_DEATH_2,
	HUD_TEXT_SCORE_DEATH_3,
	HUD_TEXT_SCORE_DEATH_4,
	HUD_TEXT_SCORE_DEATH_5,
	HUD_TEXT_SCORE_DEATH_6,
	HUD_TEXT_SCORE_DEATH_7,
	HUD_TEXT_SCORE_DEATH_8,
	HUD_TEXT_SCORE_DEATH_MARK_1,
	HUD_TEXT_SCORE_DEATH_MARK_2,
	HUD_TEXT_SCORE_DEATH_MARK_3,
	HUD_TEXT_SCORE_DEATH_MARK_4,
	HUD_TEXT_SCORE_DEATH_MARK_5,
	HUD_TEXT_SCORE_DEATH_MARK_6,
	HUD_TEXT_SCORE_DEATH_MARK_7,
	HUD_TEXT_SCORE_DEATH_MARK_8,

	HUD_TEXT_SCORE_ID_9,
	HUD_TEXT_SCORE_ID_10,
	HUD_TEXT_SCORE_ID_11,
	HUD_TEXT_SCORE_ID_12,
	HUD_TEXT_SCORE_ID_13,
	HUD_TEXT_SCORE_ID_14,
	HUD_TEXT_SCORE_ID_15,
	HUD_TEXT_SCORE_ID_16,
	HUD_TEXT_SCORE_HERO_KILL_9,
	HUD_TEXT_SCORE_HERO_KILL_10,
	HUD_TEXT_SCORE_HERO_KILL_11,
	HUD_TEXT_SCORE_HERO_KILL_12,
	HUD_TEXT_SCORE_HERO_KILL_13,
	HUD_TEXT_SCORE_HERO_KILL_14,
	HUD_TEXT_SCORE_HERO_KILL_15,
	HUD_TEXT_SCORE_HERO_KILL_16,
	HUD_TEXT_SCORE_DEATH_9,
	HUD_TEXT_SCORE_DEATH_10,
	HUD_TEXT_SCORE_DEATH_11,
	HUD_TEXT_SCORE_DEATH_12,
	HUD_TEXT_SCORE_DEATH_13,
	HUD_TEXT_SCORE_DEATH_14,
	HUD_TEXT_SCORE_DEATH_15,
	HUD_TEXT_SCORE_DEATH_16,
	HUD_TEXT_SCORE_DEATH_MARK_9,
	HUD_TEXT_SCORE_DEATH_MARK_10,
	HUD_TEXT_SCORE_DEATH_MARK_11,
	HUD_TEXT_SCORE_DEATH_MARK_12,
	HUD_TEXT_SCORE_DEATH_MARK_13,
	HUD_TEXT_SCORE_DEATH_MARK_14,
	HUD_TEXT_SCORE_DEATH_MARK_15,
	HUD_TEXT_SCORE_DEATH_MARK_16,

	HUD_TEXT_GAMEMODE,
	HUD_TEXT_ROOMNAME,

	HUD_TEXT_SCORE_RED_COLUMN_ORDER,
	HUD_TEXT_SCORE_RED_COLUMN_CLAN,
	HUD_TEXT_SCORE_RED_COLUMN_RANK,
	HUD_TEXT_SCORE_RED_COLUMN_NICK,
	HUD_TEXT_SCORE_RED_COLUMN_KILL,
	HUD_TEXT_SCORE_RED_COLUMN_DEATH,

	HUD_TEXT_SCORE_BLUE_COLUMN_ORDER,
	HUD_TEXT_SCORE_BLUE_COLUMN_CLAN,
	HUD_TEXT_SCORE_BLUE_COLUMN_RANK,
	HUD_TEXT_SCORE_BLUE_COLUMN_NICK,
	HUD_TEXT_SCORE_BLUE_COLUMN_KILL,
	HUD_TEXT_SCORE_BLUE_COLUMN_DEATH,

	HUD_TEXT_SCORE_RED_COLUMN_PING,
	HUD_TEXT_SCORE_BLUE_COLUMN_PING,

	HUD_TEXT_SCORE_COUNT,
};

struct SCORE_ARRAY
{
	i3::rc_wstring wstrNick;

	UINT8 NickColor;
	INT32 nIdx;
	UINT32 nClanIdx;
	UINT32 nClanMark; 
	UINT16 nESport;
	UINT16 nKillCount;
	UINT16 nDeath;
	INT32 nPing;
	bool bDeath;
	REAL32 HP_Rate;		// HP비율입니다. (최대:1.0f, 최소: 0.0f)

	void	Reset()
	{
		wstrNick.clear();
		NickColor = 0;
		nIdx = nPing = 0;
		nKillCount = nDeath = nESport = 0;
		bDeath = false;
		HP_Rate = 0.0f;
	}
};