#ifndef _DESIGNATION_VALUE_SET_H__
#define _DESIGNATION_VALUE_SET_H__

#define DESIGNATION_ABILITY_COUNT	5

// 호칭 효과 ID
enum DESIGNATION_ID
{
	DESIGNATION_ID_NONE = 0,

	/////////////////////////////////////////////////////////////////////////////////////
	//  plus effectㅊ
	DESIGNATION_ID_MOVE_ABILITY_PLUS_1,
	DESIGNATION_ID_MOVE_ABILITY_PLUS_2,
	DESIGNATION_ID_MOVE_ABILITY_PLUS_3,
	DESIGNATION_ID_MOVE_ABILITY_PLUS_4,
	DESIGNATION_ID_MOVE_ABILITY_PLUS_5,

	DESIGNATION_ID_FIRE_SPEED_PLUS_1,
	DESIGNATION_ID_FIRE_SPEED_PLUS_2,
	DESIGNATION_ID_FIRE_SPEED_PLUS_3,
	DESIGNATION_ID_FIRE_SPEED_PLUS_4,
	DESIGNATION_ID_FIRE_SPEED_PLUS_5,

	DESIGNATION_ID_MOVE_SPEED_PLUS_1,
	DESIGNATION_ID_MOVE_SPEED_PLUS_2,
	DESIGNATION_ID_MOVE_SPEED_PLUS_3,
	DESIGNATION_ID_MOVE_SPEED_PLUS_4,
	DESIGNATION_ID_MOVE_SPEED_PLUS_5,

	DESIGNATION_ID_JUMP_ABILITY_PLUS_1,
	DESIGNATION_ID_JUMP_ABILITY_PLUS_2,
	DESIGNATION_ID_JUMP_ABILITY_PLUS_3,
	DESIGNATION_ID_JUMP_ABILITY_PLUS_4,
	DESIGNATION_ID_JUMP_ABILITY_PLUS_5,

	DESIGNATION_ID_ADDSPEED_ABILITY_PLUS_1,
	DESIGNATION_ID_ADDSPEED_ABILITY_PLUS_2,
	DESIGNATION_ID_ADDSPEED_ABILITY_PLUS_3,
	DESIGNATION_ID_ADDSPEED_ABILITY_PLUS_4,
	DESIGNATION_ID_ADDSPEED_ABILITY_PLUS_5,

	DESIGNATION_ID_FALLDOWN_DAMAGE_REDUCE_1,
	DESIGNATION_ID_FALLDOWN_DAMAGE_REDUCE_2,
	DESIGNATION_ID_FALLDOWN_DAMAGE_REDUCE_3,
	DESIGNATION_ID_FALLDOWN_DAMAGE_REDUCE_4,
	DESIGNATION_ID_FALLDOWN_DAMAGE_REDUCE_5,

	DESIGNATION_ID_RELOAD_TIME_REDUCE_1,
	DESIGNATION_ID_RELOAD_TIME_REDUCE_2,
	DESIGNATION_ID_RELOAD_TIME_REDUCE_3,
	DESIGNATION_ID_RELOAD_TIME_REDUCE_4,
	DESIGNATION_ID_RELOAD_TIME_REDUCE_5,

	DESIGNATION_ID_FIRE_RANGE_PLUS_1,
	DESIGNATION_ID_FIRE_RANGE_PLUS_2,
	DESIGNATION_ID_FIRE_RANGE_PLUS_3,
	DESIGNATION_ID_FIRE_RANGE_PLUS_4,
	DESIGNATION_ID_FIRE_RANGE_PLUS_5,

	DESIGNATION_ID_HORIZONTAL_REACTION_REDUCE_1,
	DESIGNATION_ID_HORIZONTAL_REACTION_REDUCE_2,
	DESIGNATION_ID_HORIZONTAL_REACTION_REDUCE_3,
	DESIGNATION_ID_HORIZONTAL_REACTION_REDUCE_4,
	DESIGNATION_ID_HORIZONTAL_REACTION_REDUCE_5,

	DESIGNATION_ID_VERTICAL_REACTION_REDUCE_1,
	DESIGNATION_ID_VERTICAL_REACTION_REDUCE_2,
	DESIGNATION_ID_VERTICAL_REACTION_REDUCE_3,
	DESIGNATION_ID_VERTICAL_REACTION_REDUCE_4,
	DESIGNATION_ID_VERTICAL_REACTION_REDUCE_5,

	DESIGNATION_ID_TARGET_DECLINATION_REDUCE_1,
	DESIGNATION_ID_TARGET_DECLINATION_REDUCE_2,
	DESIGNATION_ID_TARGET_DECLINATION_REDUCE_3,
	DESIGNATION_ID_TARGET_DECLINATION_REDUCE_4,
	DESIGNATION_ID_TARGET_DECLINATION_REDUCE_5,

	DESIGNATION_ID_THROW_SPEED_PLUS_1,
	DESIGNATION_ID_THROW_SPEED_PLUS_2,
	DESIGNATION_ID_THROW_SPEED_PLUS_3,
	DESIGNATION_ID_THROW_SPEED_PLUS_4,
	DESIGNATION_ID_THROW_SPEED_PLUS_5,

	DESIGNATION_ID_BOMB_TIME_REDUCE_1,
	DESIGNATION_ID_BOMB_TIME_REDUCE_2,
	DESIGNATION_ID_BOMB_TIME_REDUCE_3,
	DESIGNATION_ID_BOMB_TIME_REDUCE_4,
	DESIGNATION_ID_BOMB_TIME_REDUCE_5,

	DESIGNATION_ID_BOMB_RANGE_PLUS_1,
	DESIGNATION_ID_BOMB_RANGE_PLUS_2,
	DESIGNATION_ID_BOMB_RANGE_PLUS_3,
	DESIGNATION_ID_BOMB_RANGE_PLUS_4,
	DESIGNATION_ID_BOMB_RANGE_PLUS_5,

	DESIGNATION_ID_WEAPON_REACTION_CONTROL_PLUS_1,
	DESIGNATION_ID_WEAPON_REACTION_CONTROL_PLUS_2,
	DESIGNATION_ID_WEAPON_REACTION_CONTROL_PLUS_3,
	DESIGNATION_ID_WEAPON_REACTION_CONTROL_PLUS_4,
	DESIGNATION_ID_WEAPON_REACTION_CONTROL_PLUS_5,

	DESIGNATION_ID_DPD_RATE_PLUS_1,
	DESIGNATION_ID_DPD_RATE_PLUS_2,
	DESIGNATION_ID_DPD_RATE_PLUS_3,
	DESIGNATION_ID_DPD_RATE_PLUS_4,
	DESIGNATION_ID_DPD_RATE_PLUS_5,

	DESIGNATION_ID_FIRST_SHOT_PLUS_1,
	DESIGNATION_ID_FIRST_SHOT_PLUS_2,
	DESIGNATION_ID_FIRST_SHOT_PLUS_3,
	DESIGNATION_ID_FIRST_SHOT_PLUS_4,
	DESIGNATION_ID_FIRST_SHOT_PLUS_5,

	//////////////////////////////////////////////////////////////////////
	// minus effect

	DESIGNATION_ID_MOVE_ABILITY_MINUS_1,
	DESIGNATION_ID_MOVE_ABILITY_MINUS_2,
	DESIGNATION_ID_MOVE_ABILITY_MINUS_3,
	DESIGNATION_ID_MOVE_ABILITY_MINUS_4,
	DESIGNATION_ID_MOVE_ABILITY_MINUS_5,

	DESIGNATION_ID_FALLDOWN_DAMAGE_INCREASE_1,
	DESIGNATION_ID_FALLDOWN_DAMAGE_INCREASE_2,
	DESIGNATION_ID_FALLDOWN_DAMAGE_INCREASE_3,
	DESIGNATION_ID_FALLDOWN_DAMAGE_INCREASE_4,
	DESIGNATION_ID_FALLDOWN_DAMAGE_INCREASE_5,

	DESIGNATION_ID_ADDSPEED_ABILITY_MINUS_1,
	DESIGNATION_ID_ADDSPEED_ABILITY_MINUS_2,
	DESIGNATION_ID_ADDSPEED_ABILITY_MINUS_3,
	DESIGNATION_ID_ADDSPEED_ABILITY_MINUS_4,
	DESIGNATION_ID_ADDSPEED_ABILITY_MINUS_5,

	DESIGNATION_ID_JUMP_ABILITY_MINUS_1,
	DESIGNATION_ID_JUMP_ABILITY_MINUS_2,
	DESIGNATION_ID_JUMP_ABILITY_MINUS_3,
	DESIGNATION_ID_JUMP_ABILITY_MINUS_4,
	DESIGNATION_ID_JUMP_ABILITY_MINUS_5,

	DESIGNATION_ID_MOVE_SPEED_MINUS_1,
	DESIGNATION_ID_MOVE_SPEED_MINUS_2,
	DESIGNATION_ID_MOVE_SPEED_MINUS_3,
	DESIGNATION_ID_MOVE_SPEED_MINUS_4,
	DESIGNATION_ID_MOVE_SPEED_MINUS_5,

	DESIGNATION_ID_VERTICAL_REACTION_INCREASE_1,
	DESIGNATION_ID_VERTICAL_REACTION_INCREASE_2,
	DESIGNATION_ID_VERTICAL_REACTION_INCREASE_3,
	DESIGNATION_ID_VERTICAL_REACTION_INCREASE_4,
	DESIGNATION_ID_VERTICAL_REACTION_INCREASE_5,

	DESIGNATION_ID_HORIZONTAL_REACTION_INCREASE_1,
	DESIGNATION_ID_HORIZONTAL_REACTION_INCREASE_2,
	DESIGNATION_ID_HORIZONTAL_REACTION_INCREASE_3,
	DESIGNATION_ID_HORIZONTAL_REACTION_INCREASE_4,
	DESIGNATION_ID_HORIZONTAL_REACTION_INCREASE_5,

	DESIGNATION_ID_TARGET_DECLINATION_INCREASE_1,
	DESIGNATION_ID_TARGET_DECLINATION_INCREASE_2,
	DESIGNATION_ID_TARGET_DECLINATION_INCREASE_3,
	DESIGNATION_ID_TARGET_DECLINATION_INCREASE_4,
	DESIGNATION_ID_TARGET_DECLINATION_INCREASE_5,

	DESIGNATION_ID_RELOAD_TIME_INCREASE_1,
	DESIGNATION_ID_RELOAD_TIME_INCREASE_2,
	DESIGNATION_ID_RELOAD_TIME_INCREASE_3,
	DESIGNATION_ID_RELOAD_TIME_INCREASE_4,
	DESIGNATION_ID_RELOAD_TIME_INCREASE_5,

	DESIGNATION_ID_FIRE_RANGE_MINUS_1,
	DESIGNATION_ID_FIRE_RANGE_MINUS_2,
	DESIGNATION_ID_FIRE_RANGE_MINUS_3,
	DESIGNATION_ID_FIRE_RANGE_MINUS_4,
	DESIGNATION_ID_FIRE_RANGE_MINUS_5,

	DESIGNATION_ID_THROW_SPEED_MINUS_1,
	DESIGNATION_ID_THROW_SPEED_MINUS_2,
	DESIGNATION_ID_THROW_SPEED_MINUS_3,
	DESIGNATION_ID_THROW_SPEED_MINUS_4,
	DESIGNATION_ID_THROW_SPEED_MINUS_5,

	DESIGNATION_ID_FIRE_SPEED_MINUS_1,
	DESIGNATION_ID_FIRE_SPEED_MINUS_2,
	DESIGNATION_ID_FIRE_SPEED_MINUS_3,
	DESIGNATION_ID_FIRE_SPEED_MINUS_4,
	DESIGNATION_ID_FIRE_SPEED_MINUS_5,

	DESIGNATION_ID_BOMB_TIME_INCREASE_1,
	DESIGNATION_ID_BOMB_TIME_INCREASE_2,
	DESIGNATION_ID_BOMB_TIME_INCREASE_3,
	DESIGNATION_ID_BOMB_TIME_INCREASE_4,
	DESIGNATION_ID_BOMB_TIME_INCREASE_5,

	DESIGNATION_ID_BOMB_RANGE_MINUS_1,
	DESIGNATION_ID_BOMB_RANGE_MINUS_2,
	DESIGNATION_ID_BOMB_RANGE_MINUS_3,
	DESIGNATION_ID_BOMB_RANGE_MINUS_4,
	DESIGNATION_ID_BOMB_RANGE_MINUS_5,

	DESIGNATION_ID_WEAPON_REACTION_CONTROL_MINUS_1,
	DESIGNATION_ID_WEAPON_REACTION_CONTROL_MINUS_2,
	DESIGNATION_ID_WEAPON_REACTION_CONTROL_MINUS_3,
	DESIGNATION_ID_WEAPON_REACTION_CONTROL_MINUS_4,
	DESIGNATION_ID_WEAPON_REACTION_CONTROL_MINUS_5,

	DESIGNATION_ID_DPD_RATE_MINUS_1,
	DESIGNATION_ID_DPD_RATE_MINUS_2,
	DESIGNATION_ID_DPD_RATE_MINUS_3,
	DESIGNATION_ID_DPD_RATE_MINUS_4,
	DESIGNATION_ID_DPD_RATE_MINUS_5,

	DESIGNATION_ID_FIRST_SHOT_MINUS_1,
	DESIGNATION_ID_FIRST_SHOT_MINUS_2,
	DESIGNATION_ID_FIRST_SHOT_MINUS_3,
	DESIGNATION_ID_FIRST_SHOT_MINUS_4,
	DESIGNATION_ID_FIRST_SHOT_MINUS_5,

	////////////////////////////////////////////////////////////////////////////////////////////////

	DESIGNATION_ID_GET_SLOT2,
	DESIGNATION_ID_GET_SLOT3,
	DESIGNATION_ID_GET_BERET,

	// 순서 바뀌면 안됩니다.
	DESIGNATION_ID_GET_DUAL_KNIFE,
	DESIGNATION_ID_GET_DUAL_HANDGUN,
	DESIGNATION_ID_GET_870MCS_W,
	DESIGNATION_ID_GET_SG550_S,
	DESIGNATION_ID_GET_DRAGUNOV_G,
	DESIGNATION_ID_GET_SPECTRE_W,
	DESIGNATION_ID_GET_C5,
	DESIGNATION_ID_GET_G36C_EXT,
	DESIGNATION_ID_GET_L115A1,
	DESIGNATION_ID_GET_CIC,
	DESIGNATION_ID_GET_P90_EXT,
	DESIGNATION_ID_GET_SPAS15,
	DESIGNATION_ID_GET_PSG1_S,
	DESIGNATION_ID_GET_MP5K_G,
	DESIGNATION_ID_GET_AMOK_KUKRI,
	DESIGNATION_ID_GET_WP_SMOKE,
	DESIGNATION_ID_GET_KRISS_SUPER_V,
	DESIGNATION_ID_GET_DUAL_DESERTEAGLE,	
	DESIGNATION_ID_GET_AK_SOPMOD,
	DESIGNATION_ID_GET_MINI_AXE,
	DESIGNATION_ID_GET_SOMETHING,

	/////////////////////////////////////////////////////////////////////////
	// 새로운 버전으로 업데이트 되면 삭제되야 합니다.
	DESIGNATION_ID_MELEE_SPEED_PLUS_1,
	DESIGNATION_ID_MELEE_RANGE_INCREASE_1,
	DESIGNATION_ID_MELEE_RANGE_REDUCE_1,
	DESIGNATION_ID_DAMAGE_PLUS_1,
	DESIGNATION_ID_DAMAGE_PLUS_2,
	DESIGNATION_ID_DAMAGE_MINUS_1,
	DESIGNATION_ID_SCOOPE_RANGE_PLUS_1,
	DESIGNATION_ID_SCOOPE_RANGE_MINUS_1,
	DESIGNATION_ID_CROSS_RESTORE_TIME_PLUS_1,
	DESIGNATION_ID_CROSS_RESTORE_TIME_MINUS_1,

	DESIGNATION_ID_GET_SLOT2_A,
	DESIGNATION_ID_GET_SLOT2_B,
	DESIGNATION_ID_GET_SLOT2_C,
	DESIGNATION_ID_GET_SLOT3_A,
	DESIGNATION_ID_GET_SLOT3_B,
	DESIGNATION_ID_GET_SLOT3_C,
	DESIGNATION_ID_GET_SLOT3_D,
	DESIGNATION_ID_GET_SLOT3_E,
	DESIGNATION_ID_GET_SLOT3_F,
	DESIGNATION_ID_GET_SLOT3_G,

	DESIGNATION_ID_MELEE_SPEED_MINUS_1,
	DESIGNATION_ID_GET_AUG_A3,
	DESIGNATION_ID_GET_M1887W,
	DESIGNATION_ID_GET_AKS74U,
	DESIGNATION_ID_GET__,

	// 이제까지 무기 구입 권한을 텍스트와 함께 하드코딩되어 있었지만 (DESIGNATION_ID_GET_AKS74U와 같은)
	// 스크립트로 빠졌으므로 이제 권한 인덱스 추가 안해도됩니다. 2010-05-10 komet
	// DesignationSet.pef에 항목 넣으면 자동 적용 됩니다. 
	// 대신 _AddEffect 항목에 (220) DESIGNATION_ID_GET_WEAPON (호칭 무기로 지정한다는 인덱스) 값과 들어가 있다면 
	//	_AuthWeaponClass_0과 _AuthWeaponNumber_0 항목에 무기 인덱스(CommonDef에 정의)를 넣으면 호칭 트리와 상점에 호칭 무기로 적용한다. 
	//
	// 예)	DesignationValue.pef 파일에서 설정
	//		_AddEffect_0		= 220 (DESIGNATION_ID_GET_WEAPON)	<- 220번은 호칭 무기로 지정한다는 인덱스
	//		_AuthWeaponClass_0	= 1번째 호칭 적용할 무기 클래스 (CommonDef.h)
	//		_AuthWeaponNumber_0	= 1번째 호칭 적용할 무기 번호	(CommonDef.h)
	//
	//		_AddEffect_1		= 220 (DESIGNATION_ID_GET_WEAPON)
	//		_AuthWeaponClass_1	= 2번째 호칭 적용할 무기 클래스 (CommonDef.h)
	//		_AuthWeaponNumber_1	= 2번째 호칭 적용할 무기 번호	(CommonDef.h)
	//	
	DESIGNATION_ID_GET_WEAPON,		// 무기 구입 권한 (호칭) <-- 바로 요것(220)이 항목에 설정되면 호칭 무기로 인식한다.

	DESIGNATION_ID_COUNT,
};

#define DESIGNATION_EFFECT_COUNT	2

typedef struct __tagDesignationSet
{
private:
	char	_szName[ MAX_STRING_COUNT];
	char	_szName_E[ MAX_STRING_COUNT];
	char	_szExplain[ MAX_STRING_COUNT];	
	DESIGNATION_APPLY_TYPE	_ApplyType;
	DESIGNATION_TYPE	_Type;
	UINT8	_PlusEffect[ DESIGNATION_EFFECT_COUNT];			// 호칭 추가 능력
	UINT8	_MinusEffect[ DESIGNATION_EFFECT_COUNT];		// 호칭 저하 능력
	UINT8	_AddEffect[ DESIGNATION_EFFECT_COUNT];			// 호칭 추가 효과

	// _AddEffect[]에서 DESIGNATION_ID_GET_WEAPON 로 값이 셋팅되어 있다면 아래 무기에 호칭 제한을 건다. komet
	// 예)
	// _AddEffect[0] = DESIGNATION_ID_GET_WEAPON 이라면
	// _AuthWeaponClass[0]와 _AuthWeaponNum[0]에 등록된 무기에 호칭 제한됨.
	// DESIGNATION_ID_GET_WEAPON 값이 아니라면 아래 호칭제한 무기 설정 무시함. 
	UINT8	_AuthWeaponClass[ DESIGNATION_EFFECT_COUNT];	//	호칭 제한 무기 클래스 (Weapon.pef)
	UINT8	_AuthWeaponNumber[ DESIGNATION_EFFECT_COUNT];	//  호칭 제한 무기 번호 (Weapon.pef)

public:
	UINT8	_ShiftCode;

public:
	void	getName( char * pszOut);
	void	setName( const char * pszIn);

	void	getName_E( char * pszOut);
	void	setName_E( const char * pszIn);

	void	getExplain( char * pszOut);
	void	setExplain( const char * pszIn);
	
	DESIGNATION_APPLY_TYPE	getApplyType( void);
	void	setApplyType( DESIGNATION_APPLY_TYPE type);

	DESIGNATION_TYPE		getType();
	void	setType( DESIGNATION_TYPE type);

	UINT8	getPlusEffect( INT32 idx);
	void	setPlusEffect( INT32 idx, UINT8 val);

	UINT8	getMinusEffect( INT32 idx);
	void	setMinusEffect( INT32 idx, UINT8 val);

	UINT8	getAddEffect( INT32 idx);
	void	setAddEffect( INT32 idx, UINT8 val);

	UINT8	getAuthWeaponClass( INT32 idx);
	void	setAuthWeaponClass( INT32 idx, UINT8 val);

	UINT8	getAuthWeaponNumber( INT32 idx);
	void	setAuthWeaponNumber( INT32 idx, UINT8 val);


} DESIGNATION_SET;


class CDesignationValueSet :	public i3ElementBase
{
	I3_CLASS_DEFINE( CDesignationValueSet, i3ElementBase );

public:
	CDesignationValueSet(void);
	~CDesignationValueSet(void);

	void InitDefault(void);
	void Save(void);
	void Load(void);

	DESIGNATION_SET * getDesignationSet( INT32 idx)					{ I3ASSERT( idx > -1 && idx < MAX_DEFAULT_USER_TITLE_COUNT); return &m_tDesignationSet[ idx]; }	
	USER_TITLE_EFFECT *	getUserTitleEffect( DESIGNATION_ID id)		{ I3_BOUNDCHK( id, DESIGNATION_ID_COUNT);	return &m_UserTitleEffectText[ id]; }
	DESIGNATION_SET * GetDesignationSetByType( INT32 idx);

private:
	USER_TITLE_EFFECT m_UserTitleEffectText[ DESIGNATION_ID_COUNT];
	DESIGNATION_SET	m_tDesignationSet[ MAX_DEFAULT_USER_TITLE_COUNT];
	REAL32	m_fValue[ DESIGNATION_ID_COUNT];

	UINT8	m_encryptShiftCode;

	void	__InitUserTitleEffectText( void);

protected:
	void	_setValue( INT32 id, REAL32 val);
	void	_setUserTitleEffectText( DESIGNATION_ID id, const char * pszIn);

public:
	REAL32	getValue( INT32 id);
	void	getUserTitleEffectText( DESIGNATION_ID id, char * pszOut);
};

extern CDesignationValueSet * g_pDesignationValueSet;

BOOL IsWeaponByDesignationEffect( DESIGNATION_ID nDesignationEffect);

#endif //_DESIGNATION_VALUE_SET_H__