#ifndef __PARSER_HELPER_H__
#define __PARSER_HELPER_H__

extern bool		g_bTemp;
extern REAL32	g_rTemp[4];

#define IF_STR(_STR_)									if(stricmp(szBuf,_STR_)==0)

#define GET_VALUE(_LABEL_,_DEFAULT_,_VAR_)				_GET_VALUE(_LABEL_,_DEFAULT_,_VAR_,FALSE)
#define GET_IMPORTANT_VALUE(_LABEL_,_DEFAULT_,_VAR_)	_GET_VALUE(_LABEL_,_DEFAULT_,_VAR_,TRUE)

#define GET_STRING(_LABEL_,_DEFAULT_,_VAR_,_BUFSZ_)				_GET_STRING(_LABEL_,_DEFAULT_,_VAR_,_BUFSZ_,FALSE)
#define GET_IMPORTANT_STRING(_LABEL_,_DEFAULT_,_VAR_,_BUFSZ_)	_GET_STRING(_LABEL_,_DEFAULT_,_VAR_,_BUFSZ_,TRUE)


#define GET_INDEX(_LABEL_,_STRLIST_,_DEFAULT_,_VAR_)			_GET_INDEX(_LABEL_,_STRLIST_,_DEFAULT_,_VAR_,FALSE)
#define GET_IMPORTANT_INDEX(_LABEL_,_STRLIST_,_VAR_)			_GET_INDEX(_LABEL_,_STRLIST_,0,_VAR_,TRUE)

#define GET_MAX_VEC3D(_LABEL_,_VAR_)						_GET_MAX_VEC3D(_LABEL_,_VAR_,FALSE)	
#define GET_IMPORTANT_MAX_VEC3D(_LABEL_,_VAR_)				_GET_MAX_VEC3D(_LABEL_,_VAR_,TRUE)	

#define GET_RAD_FROM_DEG(_LABEL_,_DEFAULT_,_VAR_)			_GET_RAD_FROM_DEG(_LABEL_,_DEFAULT_,_VAR_,FALSE)
#define GET_IMPORTANT_RAD_FROM_DEG(_LABEL_,_DEFAULT_,_VAR_)	_GET_RAD_FROM_DEG(_LABEL_,_DEFAULT_,_VAR_,TRUE)

#endif //__PARSER_HELPER_H__
