#ifndef _StageDef_h
#define _StageDef_h


/////////////////////////////////////////////////////////////////////
// GUI 테스트용 (상용에 절대 들어가면 안됨)
#if defined (I3_DEBUG)
//#define TEST_LOBBY_ROOM_LIST		//	로비 룸 리스트 더미 테스트 (komet)
//#define TEST_LOBBY_USER_LIST		//	가상으로 로비 유저 리스트를 볼수 있게 (komet)
//#define TEST_CLAN_LIST			//	클랜 목록용 테스트 (클랜 디테일 정보는 올바르지 않을 수 있습니다.)
//#define TEST_CLAN_MEMBER_LIST		//	클랜원 목록용 테스트
//#define TEST_CLAN_SUBSCRITION_LIST	//	가입자 목록용 테스트
//#define TEST_CLAN_MEMBER			//	가상으로 가입자 페이지를 띄울때 komet
//#define TEST_CLAN_BATTLE			//	가상으로 클랜팀과 참가 클랜원을 볼수 있게 (komet)
#endif


// Font Count
#define		FONT_COUNT_32		32
#define		FONT_COUNT_64		64
#define		FONT_COUNT_128		128
#define		FONT_COUNT_256		256
#define		FONT_COUNT_512		512
#define		FONT_COUNT_1024		1024
#define		FONT_COUNT_2048		2048
#define		FONT_COUNT_DEFAULT	FONT_COUNT_256

// 게임에서 사용되는 기본적인 크기

	#define		GAME_FONT_FPS_TEXT								26

#if defined( LOCALE_KOREA)

	#define		GAME_FONT_DEFAULT_SIZE							8
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					8
	#define		GAME_FONT_SMALL_SIZE							8
	#define		GAME_FONT_BIG_SIZE								11
	#define		GAME_FONT_SIZE_VERSION_INFO						11
	#define		GAME_FONT_SIZE_LOADING							20
	#define		GAME_FONT_SIZE_LOADING_TIP						12
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						10
	#define		GAME_FONT_SIZE_HUD_REVENGE						11
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					14
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				11
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				14
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				15
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				11
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				8
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		10
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					8
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		10
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				8
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					14
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						8
	#define		GAME_FONT_POPUPLIST_SIZE						8
	#define		GAME_FONT_CHAT_SIZE								8
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined ( LOCALE_THAILAND)

	#define		GAME_FONT_DEFAULT_SIZE							8
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					8
	#define		GAME_FONT_SMALL_SIZE							8
	#define		GAME_FONT_BIG_SIZE								11
	#define		GAME_FONT_SIZE_VERSION_INFO						11
	#define		GAME_FONT_SIZE_LOADING							20
	#define		GAME_FONT_SIZE_LOADING_TIP						12
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						10
	#define		GAME_FONT_SIZE_HUD_REVENGE						11
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					14
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				11
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				14
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				15
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				11
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				8
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		10
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					8
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		10
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				8
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					14
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				10
	#define		GAME_FONT_SIZE_PROFILE_TEXT						8
	#define		GAME_FONT_SIZE_ANY_TEXT							9
	#define		GAME_FONT_POPUPLIST_SIZE						8
	#define		GAME_FONT_CHAT_SIZE								8
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined ( LOCALE_INDONESIA)

	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								10
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined ( LOCALE_RUSSIA)

	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					10
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_SIZE_ANY_TEXT							7
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								10
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined ( LOCALE_TURKEY)

	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								10
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined ( LOCALE_BRAZIL)

	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								10
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined ( LOCALE_LATIN_AMERICA)

	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								12
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined(LOCALE_NORTHAMERICA)

	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								10
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined(LOCALE_ITALY)

	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								10
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined(LOCALE_ENGLISH)

	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								10
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined(LOCALE_MIDDLE_EAST)

	#define		GAME_FONT_SIZE_MOUSE							8	// revision 55598
	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								10
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined(LOCALE_PHILIPPINES  )

	#define		GAME_FONT_DEFAULT_SIZE							10
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
	#define		GAME_FONT_SMALL_SIZE							10
	#define		GAME_FONT_BIG_SIZE								13
	#define		GAME_FONT_SIZE_VERSION_INFO						13
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
	#define		GAME_FONT_SIZE_PROFILE_TEXT						10
	#define		GAME_FONT_POPUPLIST_SIZE						10
	#define		GAME_FONT_CHAT_SIZE								10
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined ( LOCALE_TAIWAN)

	#define		GAME_FONT_SIZE_MOUSE							8	// revision 55598
	#define		GAME_FONT_DEFAULT_SIZE							14
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					14
	#define		GAME_FONT_SMALL_SIZE							14
	#define		GAME_FONT_BIG_SIZE								16
	#define		GAME_FONT_SIZE_VERSION_INFO						14
	#define		GAME_FONT_SIZE_LOADING							22
	#define		GAME_FONT_SIZE_LOADING_TIP						14
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						14
	#define		GAME_FONT_SIZE_HUD_REVENGE						13
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				18
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				18
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				16
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				14
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		14
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					14
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		14
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				14
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				14
	#define		GAME_FONT_SIZE_PROFILE_TEXT						14
	#define		GAME_FONT_POPUPLIST_SIZE						14
	#define		GAME_FONT_CHAT_SIZE								14
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					14

#elif defined(LOCALE_SINGMAL)

#define		GAME_FONT_DEFAULT_SIZE							10
#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
#define		GAME_FONT_SMALL_SIZE							10
#define		GAME_FONT_BIG_SIZE								13
#define		GAME_FONT_SIZE_VERSION_INFO						13
#define		GAME_FONT_SIZE_LOADING							22
#define		GAME_FONT_SIZE_LOADING_TIP						12
#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
#define		GAME_FONT_SIZE_HUD_REVENGE						13
#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
#define		GAME_FONT_SIZE_PROFILE_TEXT						10
#define		GAME_FONT_POPUPLIST_SIZE						10
#define		GAME_FONT_CHAT_SIZE								10
#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined(LOCALE_VIETNAM)

#define		GAME_FONT_DEFAULT_SIZE							10
#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
#define		GAME_FONT_SMALL_SIZE							10
#define		GAME_FONT_BIG_SIZE								13
#define		GAME_FONT_SIZE_VERSION_INFO						13
#define		GAME_FONT_SIZE_LOADING							22
#define		GAME_FONT_SIZE_LOADING_TIP						14
#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
#define		GAME_FONT_SIZE_HUD_REVENGE						13
#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
#define		GAME_FONT_SIZE_PROFILE_TEXT						10
#define		GAME_FONT_POPUPLIST_SIZE						10
#define		GAME_FONT_CHAT_SIZE								10
#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#elif defined(LOCALE_JAPAN)

#define		GAME_FONT_DEFAULT_SIZE							10
#define		GAME_FONT_DEFAULT_CAPTION_SIZE					11
#define		GAME_FONT_SMALL_SIZE							10
#define		GAME_FONT_BIG_SIZE								13
#define		GAME_FONT_SIZE_VERSION_INFO						13
#define		GAME_FONT_SIZE_LOADING							22
#define		GAME_FONT_SIZE_LOADING_TIP						14
#define		GAME_FONT_SIZE_CHAT_CHANNEL						12
#define		GAME_FONT_SIZE_HUD_REVENGE						13
#define		GAME_FONT_SIZE_HUD_BOMB_TIME					16
#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				13
#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				16
#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				17
#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				13
#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				10
#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
#define		GAME_FONT_SIZE_HUD_TRAINING_HP					10
#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		12
#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				10
#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					16
#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				12
#define		GAME_FONT_SIZE_PROFILE_TEXT						10
#define		GAME_FONT_POPUPLIST_SIZE						10
#define		GAME_FONT_CHAT_SIZE								10
#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#else

	#define		GAME_FONT_DEFAULT_SIZE							8
	#define		GAME_FONT_DEFAULT_CAPTION_SIZE					8
	#define		GAME_FONT_SMALL_SIZE							8
	#define		GAME_FONT_BIG_SIZE								11
	#define		GAME_FONT_SIZE_VERSION_INFO						11
	#define		GAME_FONT_SIZE_LOADING							20
	#define		GAME_FONT_SIZE_LOADING_TIP						12
	#define		GAME_FONT_SIZE_CHAT_CHANNEL						10
	#define		GAME_FONT_SIZE_HUD_REVENGE						11
	#define		GAME_FONT_SIZE_HUD_BOMB_TIME					14
	#define		GAME_FONT_SIZE_HUD_MISSION_MESSAGE				11
	#define		GAME_FONT_SIZE_HUD_MISSION_NOTICE				14
	#define		GAME_FONT_SIZE_HUD_OBSERVER_TITLE				15
	#define		GAME_FONT_SIZE_HUD_OBSERVER_NAME				11
	#define		GAME_FONT_SIZE_HUD_OBSERVER_WEAPON				8
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		10
	#define		GAME_FONT_SIZE_HUD_TRAINING_HP					8
	#define		GAME_FONT_SIZE_HUD_SCOREBOARD_QUEST_TEXT		10
	#define		GAME_FONT_SIZE_HUD_CHALLENGE_TEXT				8
	#define		GAME_FONT_SIZE_HUD_RESPAWN_TEXT					14
	#define		GAME_FONT_SIZE_SERVER_SELECT_NUMBER				10
	#define		GAME_FONT_SIZE_PROFILE_TEXT						8
	#define		GAME_FONT_SIZE_ANY_TEXT							9
	#define		GAME_FONT_POPUPLIST_SIZE						8
	#define		GAME_FONT_CHAT_SIZE								8
	#define		GAME_FONT_TARGET_HP_TEXT_SIZE					11

#endif



// 이벤트카드 최종보상 메달의 종류입니다. (-1의 경우 보상메달이 없는것입니다.)
#define EVENT_CARDSET_PRIZE_MEDAL_TYPE	-1

// DeathCam Temp
#define DEATH_CAM_RADIUS			2.0f
#define DEATH_CAM_THETA				I3_PI4
#define USE_AWAY_INPUT

// Away Input Timer - Use AwayChecker
//#define AWAY_INPUT_SERVER_TIME		300.0f
#define AWAY_INPUT_SERVER_TIME		9000000000.0f		//기획실 요청
#define AWAY_INPUT_SERVER_CAUTION	10.0f
#if defined( LOCALE_TAIWAN)	// revision 32747 레디룸 장시간 응답없음 대만 빌드에만 시간 늘림 (1200초)
	#define AWAY_INPUT_ROOM_TIME		1200.0f
#else
	#define AWAY_INPUT_ROOM_TIME		300.0f
#endif
#define AWAY_INPUT_ROOM_CAUTION		5.0f
#define AWAY_INPUT_RESPAWN_TIME		60.0f
#define AWAY_INPUT_RESPAWN_CAUTION	5.0f

// Away Input Timer - self timer
#define AWAY_INPUT_BATTLE_TIME		60.0f
#define AWAY_INPUT_BATTLE_CAUTION	55.0f

// Away Input Timer - Room Master GameStart Timer After All User Ready
#define AWAY_INPUT_ROOM_MASTER_GAMESTART_TIME		10.0f
#define AWAY_INPUT_ROOM_MASTER_GAMESTART_CAUTION	5.0f

// HUD Damage Fx
#define HIT_DIRECTION_DECREASE		1.0f/0.01f
#define WARNING_DIRECTION_DECREASE	3.0f/0.01f

// MultiKills ActiveTime
#define ACTIVE_TIME_MULTI_KILLS		3.0f	// 3 sec.

// SlideMenu
#define SLIDE_MENU_TOP				7.0f
#define SLIDE_MENU_BOTTOM			700.0f
#define SLIDE_SPEED_PPS				4600.0f	// PPS - Pixel Per Second

enum SLIDE_MENU_STATE_TYPE
{
	SLIDE_MENU_STATE_TOP = 0,
	SLIDE_MENU_STATE_BOTTOM,
	SLIDE_MENU_STATE_UP,
	SLIDE_MENU_STATE_DOWN,
	MAX_SLIDE_MENU_STATE
};


// GUI ID offset
#define GUI_ID_OFFSET_LOGIN				0
#define GUI_ID_OFFSET_SERVER			1000
#define GUI_ID_OFFSET_LOBBY				2000
#define GUI_ID_OFFSET_ROOM				3000
#define GUI_ID_OFFSET_MENUBAR			4000
#define GUI_ID_OFFSET_OPTION			5000
#define GUI_ID_OFFSET_EQUIP_VIEW		6000
#define GUI_ID_OFFSET_INVEN				7000
#define GUI_ID_OFFSET_SHOP				8000
#define GUI_ID_OFFSET_EXTENSION			9000
#define GUI_ID_OFFSET_BATTLE			10000

// GUI Shpae offst
#define GUI_SHAPE_OFFSET				0

#define MAX_MOUSE_SENSIVITY				1.2f
#define MIN_MOUSE_SENSIVITY				0.1f
#define MAX_CAM_FOV						80.0f
#define MIN_CAM_FOV						35.0f
#define DEF_CAM_FOV						70.0f


#define MAX_ROOM_PER_PAGE				10

#define MAX_ROOM_PER_PAGE_EX			10

#define MAX_LOBBY_USER_SLOT				8		//	로비 유저 목록

#define ROOM_BATTLE_MARK_KNIFE			0		//	칼전 마크
#define ROOM_BATTLE_MARK_HANDGUN		1		//	권총전 마크
#define ROOM_BATTLE_MARK_RPG7			2		//	RPG7전 마크
#define ROOM_BATTLE_MARK_SNIPER			3		//	저격전 마크
#define ROOM_BATTLE_MARK_SHOTGUN		4		//	샷건전 마크
#define ROOM_BATTLE_MARK_KNUCKLE		5		//	너클전 마크

#define SET_ROOM_BATTLE_MARK_KNIFE(control)		{ control->SetEnable(true); control->SetAllShapeEnable(false); control->SetShapeEnable( ROOM_BATTLE_MARK_KNIFE, true);}
#define SET_ROOM_BATTLE_MARK_HANDGUN(control)	{ control->SetEnable(true); control->SetAllShapeEnable(false); control->SetShapeEnable( ROOM_BATTLE_MARK_HANDGUN, true);}
#define SET_ROOM_BATTLE_MARK_RPG7(control)		{ control->SetEnable(true); control->SetAllShapeEnable(false); control->SetShapeEnable( ROOM_BATTLE_MARK_RPG7, true);}
#define SET_ROOM_BATTLE_MARK_SNIPER(control)	{ control->SetEnable(true); control->SetAllShapeEnable(false); control->SetShapeEnable( ROOM_BATTLE_MARK_SNIPER, true);}
#define SET_ROOM_BATTLE_MARK_SHOTGUN(control)	{ control->SetEnable(true); control->SetAllShapeEnable(false); control->SetShapeEnable( ROOM_BATTLE_MARK_SHOTGUN, true);}
#define SET_ROOM_BATTLE_MARK_KNUCKLE(control)		{ control->SetEnable(true); control->SetAllShapeEnable(false); control->SetShapeEnable( ROOM_BATTLE_MARK_KNUCKLE, true);}

#define UNSET_ROOM_BATTLE_MARK(control)			{ control->SetEnable(false); control->SetAllShapeEnable(false); }

#define MAX_SLOT_PER_TEAM				8
#define MAX_CHAT_LINE_FOR_ROOM			7
#define MAX_CHAT_LINE_FOR_LOBBY			6
#define MAX_CHAT_LINE_FOR_TEAM_LOBBY	11
#define MAX_CHAT_LINE_FOR_CLAN_MEMNER	13
#define ROOM_CHAT_SIZE					60
#define MAX_SLOT_FOR_EQUIP_VIEW			5
#define MAX_SLOT_FOR_INVEN_WEAPON		8
#define MAX_SLOT_FOR_INVEN_CHARACTER	9
#define MAX_SLOT_FOR_INVEN_ITEM			9
#define MAX_CATEGORY_WEAPON				5
#define MAX_CATEGORY_CHARACTER			4

#define BATTLE_RESULT_TIME				8.0f

#define MAX_EXP_PER_BATTLE				1000
#define WIN_EXP_POINT					100
#define DRAW_EXP_POINT					50
#define LOSE_EXP_POINT					30
#define RESULT_EXP_TYPE_COUNT			4

#define RESULT_GAUGE_RATE				(BATTLE_RESULT_TIME / 1.5f / RESULT_EXP_TYPE_COUNT)

#define MAX_CHALLENGE_COUNT				4	// 최대 진행 임무 수


// Lobby Room List
#define MAX_ROOM_BUFFER_COUNT			608		// 300 * 2 이상
#define ENTER_LOBBY_WAIT_TIME			2.0f	// 2.0 sec. Lobby 입장 후 RoomList를 받기위한 대기 시간

// Stage Macro Functions
#define LOOP_INCREASE_DISP(cur,min,max,disp)	((cur) >= (max) ? (min) : (cur) + (disp))	// assert(0 < disp)
#define LOOP_DECREASE_DISP(cur,min,max,disp)	((cur) <= (min) ? (max) : (cur) - (disp))	// assert(0 < disp)
#define LOOP_INCREASE(cur,min,max)				LOOP_INCREASE_DISP(cur,min,max,1)
#define LOOP_DECREASE(cur,min,max)				LOOP_DECREASE_DISP(cur,min,max,1)
#define HINIBBLE(byte)							((((UINT8)(byte) >> 4) & 0xF))
#define LONIBBLE(byte)							(((UINT8)(byte) & 0xF))
#define MAKEBYTE(hiNibble,loNibble)				((UINT8)(loNibble) | ((UINT8)(hiNibble) << 4))

// GUI Control Link Macro Functions
#define LINK_CONTROL(str,control,class,id)	{if( i3String::Compare( pControl->GetName(), str) == 0) {control = (class*)pControl; control->SetControlID(id);}}
#define LINK_STATIC(str,control,id)			LINK_CONTROL(str,control,i3GuiStatic,id)
#define LINK_BUTTON(str,control,id)			LINK_CONTROL(str,control,i3GuiButton,id)
#define LINK_CHECKBOX(str,control,id)		LINK_CONTROL(str,control,i3GuiCheckBox,id)
#define LINK_EDIT(str,control,id)			LINK_CONTROL(str,control,i3GuiEditBox,id)
#define LINK_SLIDER(str,control,id)			LINK_CONTROL(str,control,i3GuiSlider,id)
#define LINK_3DVIEW(str,control,id)			LINK_CONTROL(str,control,i3Gui3DView,id)

// GUI Control Initialize Macro Functions
#define INIT_BUTTON(control)				{control->setClickAction(true);control->SetUserDefine( I3GUI_CONTROL_STATE_NORMAL, 0);control->SetUserDefine( I3GUI_CONTROL_STATE_ONMOUSE, 1);control->setInputMode(I3GUI_INPUT_MODE_PRESS);}
#define INIT_SCROLL_BUTTON(control)			{control->setClickAction(true);control->SetUserDefine( I3GUI_CONTROL_STATE_NORMAL, 0);control->SetUserDefine( I3GUI_CONTROL_STATE_ONMOUSE, 1);control->setInputMode(I3GUI_INPUT_MODE_REPEAT);}

// Gui Control State Macro Functions
#define SET_CONTROL_DISABLE_WITH_ALPHA(control)	{ control->setControlState( I3GUI_CONTROL_STATE_DISABLED); control->SetColor( I3GUI_CONTROL_STATE_DISABLED, 255, 255, 255, 80); control->SetCaptionColor(GetColor(GCT_STATIC));}
#define SET_CONTROL_ENABLE_WITH_ALPHA(control)	{ control->setControlState( I3GUI_CONTROL_STATE_NORMAL); control->SetColor( I3GUI_CONTROL_STATE_DISABLED, 255, 255, 255, 255); control->SetCaptionColor(GetColor(GCT_VALUE));}


#endif //_StageDef_h
