#if !defined( __UI_LOTTERY_GACHA_DEF_H__)
#define __UI_LOTTERY_GACHA_DEF_H__

enum GACHA_ANIM_STATE
{
	GACHA_PLAY_IDLE		= 0,
	GACHA_PLAY_IDLES,
	GACHA_PLAY_WEAPON_IN,
	GACHA_PLAY_WEAPON_OUT,
	GACHA_PLAY_SELECT_A,
	GACHA_PLAY_SELECT_B,
	GACHA_PLAY_SELECT_C,
	GACHA_CASE_MAX,
};

enum GACHA_WEAPON_POS
{
	GACHA_POS_1 = 0,
	GACHA_POS_2,
	GACHA_POS_3,
	GACHA_POS_4,
	GACHA_POS_5,
	GACHA_POS_6,
	GACHA_POS_7,
	GACHA_POS_MAX,
};

enum GACHA_STATE
{
	GACHA_STATE_IDLE,
	GACHA_STATE_START,
	GACHA_STATE_FINISH,
	GACHA_STATE_WEAPON_IN,
	GACHA_STATE_WEAPON_OUT,	
};

#endif