#pragma once

#define pp_tuple_to_seq_impl(size, tuple)	pp_tuple_to_seq_i(size, tuple)
#define pp_tuple_to_seq_i(s, t)				pp_tuple_to_seq_ii(pp_tuple_to_seq_ ## s t)
#define pp_tuple_to_seq_ii(res)				res

#define pp_tuple_to_seq_0()
#define pp_tuple_to_seq_1(a) (a)
#define pp_tuple_to_seq_2(a, b) (a)(b)
#define pp_tuple_to_seq_3(a, b, c) (a)(b)(c)
#define pp_tuple_to_seq_4(a, b, c, d) (a)(b)(c)(d)
#define pp_tuple_to_seq_5(a, b, c, d, e) (a)(b)(c)(d)(e)
#define pp_tuple_to_seq_6(a, b, c, d, e, f) (a)(b)(c)(d)(e)(f)
#define pp_tuple_to_seq_7(a, b, c, d, e, f, g) (a)(b)(c)(d)(e)(f)(g)
#define pp_tuple_to_seq_8(a, b, c, d, e, f, g, h) (a)(b)(c)(d)(e)(f)(g)(h)
#define pp_tuple_to_seq_9(a, b, c, d, e, f, g, h, i) (a)(b)(c)(d)(e)(f)(g)(h)(i)
#define pp_tuple_to_seq_10(a, b, c, d, e, f, g, h, i, j) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)
#define pp_tuple_to_seq_11(a, b, c, d, e, f, g, h, i, j, k) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)
#define pp_tuple_to_seq_12(a, b, c, d, e, f, g, h, i, j, k, l) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)
#define pp_tuple_to_seq_13(a, b, c, d, e, f, g, h, i, j, k, l, m) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)
#define pp_tuple_to_seq_14(a, b, c, d, e, f, g, h, i, j, k, l, m, n) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)
#define pp_tuple_to_seq_15(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)
#define pp_tuple_to_seq_16(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)
#define pp_tuple_to_seq_17(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)
#define pp_tuple_to_seq_18(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)
#define pp_tuple_to_seq_19(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)(s)
#define pp_tuple_to_seq_20(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)(s)(t)
#define pp_tuple_to_seq_21(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)(s)(t)(u)
#define pp_tuple_to_seq_22(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)(s)(t)(u)(v)
#define pp_tuple_to_seq_23(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)(s)(t)(u)(v)(w)
#define pp_tuple_to_seq_24(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)(s)(t)(u)(v)(w)(x)
#define pp_tuple_to_seq_25(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y) (a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)(s)(t)(u)(v)(w)(x)(y)
