#ifndef		__ITEMLIST_H__
#define		__ITEMLIST_H__

// 아래 아이템 리스트는 사용하지 않습니다,
// 참고용으로만 사용합니다.
#if 0

INT32 GameIdToItemFlag(UINT32 gameItemId)
{
	switch(gameItemId)
	{
	// 무기
	case MAKE_ITEM_ID(1, 2):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_SG550_DOTSIGHT"));	// SG550 Ext.
	case MAKE_ITEM_ID(1, 4):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_AK47_DUALMAG"));		// AK-47 Ext.
	case MAKE_ITEM_ID(1, 6):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_M4A1_SCOPE2"));		// M4A1 Ext.
	case MAKE_ITEM_ID(1, 7):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_K2"));				// K-2
	case MAKE_ITEM_ID(1, 8):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_F2000_SCOPE2"));		// F2000 Ext.
	case MAKE_ITEM_ID(1, 9):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT,		GetItemIndex("ASSAULT_K201_GL"));			// K-201 Ext.
	case MAKE_ITEM_ID(1, 10):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT,		GetItemIndex("ASSAULT_AK47_GOLD"));			// AK-47 G
	case MAKE_ITEM_ID(1, 11):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT,		GetItemIndex("ASSAULT_M4A1_CAMO"));			// M4A1 S	
	case MAKE_ITEM_ID(1, 12):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT,		GetItemIndex("ASSAULT_SG550_SE"));			// SG 550 S
	case MAKE_ITEM_ID(1, 13):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT,		GetItemIndex("ASSAULT_G36C_SCOPE2"));		// G36C Ext.
	case MAKE_ITEM_ID(1, 14):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT,		GetItemIndex("ASSAULT_AK_SOPMOD"));			// AK SOPMOD
	case MAKE_ITEM_ID_EX(1, 15) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_AK47_SILVER"));
	case MAKE_ITEM_ID_EX(1, 16) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_SG550_MB"));
	case MAKE_ITEM_ID_EX(1, 17) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_SG550_SILVER"));
	case MAKE_ITEM_ID_EX(1, 18) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_SG550_WHITE"));
	case MAKE_ITEM_ID_EX(1, 19) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_M4A1_SILVER"));
	case MAKE_ITEM_ID_EX(1, 20) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_M4A1_WHITE"));
	case MAKE_ITEM_ID_EX(1, 21) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_M4A1_G_EXP_PT_30"));
	case MAKE_ITEM_ID_EX(1, 22) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_AK47_S_POINT15"));
	case MAKE_ITEM_ID_EX(1, 23) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_SG550_MB_EXP_PT_10"));
	case MAKE_ITEM_ID_EX(1, 24) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_G36C_EVENT"));
	case MAKE_ITEM_ID_EX(1, 25) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_G36C_SILVER"));
	case MAKE_ITEM_ID_EX(1, 26) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_SG550_MB_EXP_PT_20"));
	case MAKE_ITEM_ID_EX(1, 27) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_G36C_SI_SPECIAL_EXP_PT_20"));
	case MAKE_ITEM_ID(1, 53) :		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_PINDAD_SS2_V4"));
	case MAKE_ITEM_ID(1, 57) :		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_VZ52"));
	case MAKE_ITEM_ID(1, 58) :		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_AK_FC"));

	case MAKE_ITEM_ID(2, 43):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_PINDAD_SS1_R5"));			// MP5K Ext.
	case MAKE_ITEM_ID(2, 1):		return -1;		// MP5K == 없어진 무기
	case MAKE_ITEM_ID(2, 2):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_MP5K_SILENCER"));			// MP5K Ext.
	case MAKE_ITEM_ID(2, 3):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_SPECTRE_STEADYAIM"));		// Spectre Ext.
	case MAKE_ITEM_ID(2, 4):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_K1"));						// K-1
	case MAKE_ITEM_ID(2, 5):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_K1_ZOOM"));				// K-1 Ext.
	case MAKE_ITEM_ID(2, 6):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_MP7_DOTSIGHT"));			// MP7 Ext.
	case MAKE_ITEM_ID(2, 7):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_MP5K_SERIF"));				// MP5K Serif
	case MAKE_ITEM_ID(2, 8):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_UMP45_DUALMAG"));			// UMP45
	case MAKE_ITEM_ID(2, 9):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_SPECTRE_SE"));				// Spectre W
	case MAKE_ITEM_ID(2, 10):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_P90_DOTSIGHT"));			// P90 Ext.
	case MAKE_ITEM_ID(2, 12):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,			GetItemIndex("SMG_KRISSSUPERV"));			// Kriss Super V
	case MAKE_ITEM_ID_EX(2, 13) : 	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG, 			GetItemIndex("SMG_MP5K_SILVER"));	
	case MAKE_ITEM_ID_EX(2, 14) : 	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG, 			GetItemIndex("SMG_SPECTRE_WHITE"));
	case MAKE_ITEM_ID_EX(2, 15) : 	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG, 			GetItemIndex("SMG_MP5K_WHITE"));
	case MAKE_ITEM_ID_EX(2, 16) : 	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG, 			GetItemIndex("SMG_SPECTRE_SILVER"));

	case MAKE_ITEM_ID(3, 1):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER,		GetItemIndex("SNIPER_PSG1") );				// HK-PSG1
	case MAKE_ITEM_ID(3, 2):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER,		GetItemIndex("SNIPER_DRAGUNOV"));			// SVD-Dragunov
	case MAKE_ITEM_ID(3, 3):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER,		GetItemIndex("SNIPER_SSG69"));				// SSG-69	
	case MAKE_ITEM_ID(3, 4):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER,		GetItemIndex("SNIPER_SSG69_CAMO"));			// SSG-69 S
	case MAKE_ITEM_ID(3, 5):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER,		GetItemIndex("SNIPER_L115A1"));				// L115A1
	case MAKE_ITEM_ID(3, 6):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER,		GetItemIndex("SNIPER_DRAGUNOV_GOLD"));		// Dragunov G
	case MAKE_ITEM_ID(3, 7):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER,		GetItemIndex("SNIPER_PSG1_S"));				// PSG1 S
	case MAKE_ITEM_ID_EX(3, 8)	:	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER, 		GetItemIndex("SNIPER_SSG69_SILVER"));		
	case MAKE_ITEM_ID_EX(3, 9)	:	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER, 		GetItemIndex("SNIPER_PSG1_SILVER"));		
	case MAKE_ITEM_ID_EX(3, 10) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER, 		GetItemIndex("SNIPER_DRAGUNOV_SILVER") );		
	case MAKE_ITEM_ID_EX(3, 11) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_SNIPER, 		GetItemIndex("SNIPER_DRAGUNOV_KING_COBRA_GOLD") );		
	case MAKE_ITEM_ID_EX(3, 12) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_SNIPER, 		GetItemIndex("SNIPER_DRAGUNOV_KING_COBRA_SILVER") );
	case MAKE_ITEM_ID_EX(3, 30) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_SNIPER, 		GetItemIndex("SNIPER_CHEYTAC") );
	case MAKE_ITEM_ID_EX(3, 32) :	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY, 		WEAPON_CLASS_SNIPER, 		GetItemIndex("SNIPER_BARRETT") );

	case MAKE_ITEM_ID(4, 1):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SHOTGUN,		GetItemIndex("SHOTGUN_870MCS"));				// 870MCS
	case MAKE_ITEM_ID(4, 2):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SHOTGUN,		GetItemIndex("SHOTGUN_870MCS_EVENT"));		// 강철중 샷건
	case MAKE_ITEM_ID(4, 3):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SHOTGUN,		GetItemIndex("SHOTGUN_870MCS_W"));			// 870MCS W
	case MAKE_ITEM_ID(4, 4):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SHOTGUN,		GetItemIndex("SHOTGUN_SPAS15"));				// SPAS-15
	case MAKE_ITEM_ID_EX(4, 5)	: 	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SHOTGUN,		GetItemIndex("SHOTGUN_M1887"));
	case MAKE_ITEM_ID_EX(4, 6)	: 	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SHOTGUN,		GetItemIndex("SHOTGUN_SPAS15_SILVER"));
	
	case MAKE_ITEM_ID(5, 1):		return MAKE_ITEM_ID(ITEM_TYPE_SECONDARY,	WEAPON_CLASS_HANDGUN,		GetItemIndex("HANDGUN_DESERTEAGLE"));		// Desert Eagle
	case MAKE_ITEM_ID(5, 2):		return MAKE_ITEM_ID(ITEM_TYPE_SECONDARY,	WEAPON_CLASS_HANDGUN,		GetItemIndex("HANDGUN_MK23_SILENCER"));		// Mark23 Ext.
	case MAKE_ITEM_ID(5, 3):		return MAKE_ITEM_ID(ITEM_TYPE_SECONDARY,	WEAPON_CLASS_HANDGUN,		GetItemIndex("HANDGUN_K5"));					// K-5
	case MAKE_ITEM_ID(5, 4):		return MAKE_ITEM_ID(ITEM_TYPE_SECONDARY,	WEAPON_CLASS_HANDGUN,		GetItemIndex("HANDGUN_DESERTEAGLE_REF"));	// Desert Eagle S
	case MAKE_ITEM_ID(5, 5):		return MAKE_ITEM_ID(ITEM_TYPE_SECONDARY, 	WEAPON_CLASS_CIC,			GetItemIndex("CIC_P99"));						// CIC
	case MAKE_ITEM_ID(5, 6):		return MAKE_ITEM_ID(ITEM_TYPE_SECONDARY, 	WEAPON_CLASS_DUALHANDGUN,	GetItemIndex("DUALHANDGUN_MK23_K5"));	// Dual HandGun
	case MAKE_ITEM_ID(5, 7):		return MAKE_ITEM_ID(ITEM_TYPE_SECONDARY,	WEAPON_CLASS_DUALHANDGUN,	GetItemIndex("DUALHANDGUN_DESERTEAGLE"));	// Dual DesertEagle
	case MAKE_ITEM_ID_EX(5, 8)	:	return MAKE_ITEM_ID(ITEM_TYPE_SECONDARY,	WEAPON_CLASS_CIC,			GetItemIndex("CIC_P99_SILVER"));
	case MAKE_ITEM_ID(5, 23):		return MAKE_ITEM_ID(ITEM_TYPE_SECONDARY,	WEAPON_CLASS_HANDGUN,		GetItemIndex("HANDGUN_IMI_UZI_9"));				// IMI_UZI_9

	case MAKE_ITEM_ID(6, 1):		return MAKE_ITEM_ID(ITEM_TYPE_MELEE,		WEAPON_CLASS_KNIFE,			GetItemIndex("KNIFE_M7"));					// M-7
	case MAKE_ITEM_ID(6, 2):		return MAKE_ITEM_ID(ITEM_TYPE_MELEE,		WEAPON_CLASS_DUALKNIFE,		GetItemIndex("DUALKNIFE_M9"));				// Dual Knife
	case MAKE_ITEM_ID(6, 3):		return MAKE_ITEM_ID(ITEM_TYPE_MELEE,		WEAPON_CLASS_KNIFE,			GetItemIndex("KNIFE_KUKRII"));				// Amok Kukri
	case MAKE_ITEM_ID(6, 4):		return MAKE_ITEM_ID(ITEM_TYPE_MELEE,		WEAPON_CLASS_KNIFE,			GetItemIndex("KNIFE_MINIAXE"));				// Mini Axe
	case MAKE_ITEM_ID_EX(6, 5)	:	return MAKE_ITEM_ID(ITEM_TYPE_MELEE,		WEAPON_CLASS_KNIFE,			GetItemIndex("KNIFE_M7_GOLD"));
	case MAKE_ITEM_ID(6, 17):		return MAKE_ITEM_ID(ITEM_TYPE_MELEE,		WEAPON_CLASS_KNIFE,			GetItemIndex("KNIFE_FANG_BLADE"));			// Mini Axe
	
	case MAKE_ITEM_ID(7, 1):		return MAKE_ITEM_ID(ITEM_TYPE_THROWING1,	WEAPON_CLASS_THROWING1,		GetItemIndex("THROWING_K400"));				// K-400
	case MAKE_ITEM_ID(7, 2):		return MAKE_ITEM_ID(ITEM_TYPE_THROWING1,	WEAPON_CLASS_THROWING1,		GetItemIndex("THROWING_C5"));				// C-5	
	
	case MAKE_ITEM_ID(8, 1):		return MAKE_ITEM_ID(ITEM_TYPE_THROWING2,	WEAPON_CLASS_THROWING2,			GetItemIndex("THROWING_SMOKE"));				// Smoke
	case MAKE_ITEM_ID(8, 2):		return MAKE_ITEM_ID(ITEM_TYPE_THROWING2,	WEAPON_CLASS_THROWING2,			GetItemIndex("THROWING_FLASHBANG"));			// FlashBang
	case MAKE_ITEM_ID(8, 3):		return MAKE_ITEM_ID(ITEM_TYPE_THROWING2,	WEAPON_CLASS_THROWING2,			GetItemIndex("THROWING_WP_SMOKE"));			// 백린탄
	
	// 캐릭터
	//case MAKE_ITEM_ID(9, 1):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_RB,			CHARACTER_RES_ID_MALEDEFAULT);			// 남성 기본 세트
	//case MAKE_ITEM_ID(9, 2):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_RB,			CHARACTER_RES_ID_FEMALEDEFAULT);		// 여성 기본 세트
	case MAKE_ITEM_ID(9, 3):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_RED,			CHARA_RES_ID_TARANTULA);				// 타란튤라(Free Rebels)
	case MAKE_ITEM_ID(9, 4):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_BLUE,		CHARA_RES_ID_SWAT_FEMALE);				// 키나이스(CT-FORCE)
	case MAKE_ITEM_ID(9, 5):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_RED,			CHARA_RES_ID_RED_BULLS);				// 레드 울스(Free Rebels)
	case MAKE_ITEM_ID(9, 6):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_BLUE,		CHARA_RES_ID_ACID_POLE);				// 액시드 폴(CT-FORCE)
	case MAKE_ITEM_ID(9, 7):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_BLUE,		CHARA_RES_ID_LEOPARD);					// Leopard
	case MAKE_ITEM_ID(9, 8):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_RED,			CHARA_RES_ID_D_FOX);					// D-Fox
	case MAKE_ITEM_ID(9, 9):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_BLUE,		CHARA_RES_ID_HIDE);						// 하이드
	case MAKE_ITEM_ID(9, 10):		return MAKE_ITEM_ID(ITEM_TYPE_CHARA,	 	CHARACTER_TEAM_RED,			CHARA_RES_ID_VIPERRED);					// 바이퍼 레드
	
	case MAKE_ITEM_ID(10, 1):		return MAKE_ITEM_ID(ITEM_TYPE_HEADGEAR, 	HEADGEAR_SUBTYPE_NONE,		HEADGEAR_RES_ID_DEFAULT);					// 기본 헤드기어 세트
	case MAKE_ITEM_ID(10, 2):		return MAKE_ITEM_ID(ITEM_TYPE_HEADGEAR, 	HEADGEAR_SUBTYPE_NONE,		HEADGEAR_RES_ID_NORMAL);					// 일반 헤드기어 세트
	case MAKE_ITEM_ID(10, 3):		return MAKE_ITEM_ID(ITEM_TYPE_HEADGEAR, 	HEADGEAR_SUBTYPE_NONE,		HEADGEAR_RES_ID_REINFORCE);					// 강화 헤드기어 세트
	case MAKE_ITEM_ID(10, 4):		return MAKE_ITEM_ID(ITEM_TYPE_HEADGEAR, 	HEADGEAR_SUBTYPE_NONE,		HEADGEAR_RES_ID_TARGET);					// 목표추적 헤드기어 세트
	case MAKE_ITEM_ID_EX(10, 5):	return MAKE_ITEM_ID(ITEM_TYPE_HEADGEAR, 	HEADGEAR_SUBTYPE_NONE,		HEADGEAR_RES_ID_STRENGTHENPLUS);			// 강화 헤드 기어 플러스
	case MAKE_ITEM_ID_EX(10, 6):	return MAKE_ITEM_ID(ITEM_TYPE_HEADGEAR, 	HEADGEAR_SUBTYPE_NONE,		HEADGEAR_RES_ID_SUPER);						// 슈퍼 헤드 기어
	case MAKE_ITEM_ID_EX(10, 9):	return MAKE_ITEM_ID(ITEM_TYPE_HEADGEAR, 	HEADGEAR_SUBTYPE_NONE,		HEAD_RES_ID_SKULL);						// 스컬 헤드 기어
	
	case MAKE_ITEM_ID(14, 1):		return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_MG,			GetItemIndex("MG_MK46"));				// MK.46 Ext.
	case MAKE_ITEM_ID_EX(14, 2)	:	return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_MG,			GetItemIndex("MG_MK46_SILVER"));

	//case MAKE_ITEM_ID_EX(16, 8) : return MAKE_ITEM_ID(ITEM_TYPE_PRIMARY,		WEAPON_CLASS_ASSAULT, 		GetItemIndex("ASSAULT_M4A1_GOLD"));		
	
	// 유료 아이템				
	case MAKE_ITEM_ID(11, 2):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_XP_PLUS_110);				// 경험치 110%			
	case MAKE_ITEM_ID(11, 3):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_XP_PLUS_130);				// 경험치 130%
	case MAKE_ITEM_ID(11, 4):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_XP_PLUS_150);				// 경험치 150%
	case MAKE_ITEM_ID(11, 5):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_PT_PLUS_130);				// 포인트 130%
	case MAKE_ITEM_ID(11, 6):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_COLOR_CLAN);					// 컬러 클랜명
	case MAKE_ITEM_ID(11, 7):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_COLOR_NICK);					// 컬러 닉네임
	case MAKE_ITEM_ID(11, 8):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_SHORT_RESPAWN);				// 리스폰 단축
	case MAKE_ITEM_ID(11, 9):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_AMMO_UP);					// 보유 탄수 증가        
	case MAKE_ITEM_ID(11, 10):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_COLOR_CROSSHAIR);			// 컬러 크로스헤어
	case MAKE_ITEM_ID(11, 11):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_COLOR_CHATTING);				// 컬러 채팅
	case MAKE_ITEM_ID(11, 12):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_DISGUISE_NICK);				// 임시 닉네임
	case MAKE_ITEM_ID(11, 13):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_CLAN_XP_PLUS_150);			// 클랜 경험치 150
	case MAKE_ITEM_ID(11, 14):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_DISGUISE_RANK);				// 위장 계급
	case MAKE_ITEM_ID(11, 15):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_FREE_MOVE);					// 자유이동
	case MAKE_ITEM_ID(11, 16):		return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_CUSTOM_CROSSHAIR);			// 커스텀 크로스헤어
	case MAKE_ITEM_ID_EX(11, 17): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_GET_DROPPED_WEAPON);			// 적군 무기 줍기
	case MAKE_ITEM_ID_EX(11, 18): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_XP_PLUS_X2_12PM);			// 12PM~3PM 경험치x2 
	case MAKE_ITEM_ID_EX(11, 19): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_XP_PLUS_X2_3PM);				// 3PM~6PM 경험치x2 
	case MAKE_ITEM_ID_EX(11, 20): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_XP_PLUS_X2_6PM);				// 6PM~9PM 경험치x2
	case MAKE_ITEM_ID_EX(11, 21): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_XP_PLUS_X2_9PM);				// 9PM~12PM 경험치x2
	case MAKE_ITEM_ID_EX(11, 22): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_PT_PLUS_X2_12PM);			// 12PM~3PM 포인트x2
	case MAKE_ITEM_ID_EX(11, 23): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_PT_PLUS_X2_3PM);				// 3PM~6PM 포인트x2
	case MAKE_ITEM_ID_EX(11, 24): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_PT_PLUS_X2_6PM);				// 6PM~9PM 포인트x2
	case MAKE_ITEM_ID_EX(11, 25): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_PT_PLUS_X2_9PM);				// 9PM~12PM 포인트x2
																			  	
	case MAKE_ITEM_ID_EX(11, 26): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_QUICK_CHANGE_WEAPON);		// 
	case MAKE_ITEM_ID_EX(11, 27): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_QUICK_CHANGE_MAGAZINE);		// 
	case MAKE_ITEM_ID_EX(11, 28): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_MEGA_HP10);					// 
	case MAKE_ITEM_ID_EX(11, 29): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_INCREASE_INVINCIBLE_TIME);	// 
	case MAKE_ITEM_ID_EX(11, 30): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_BULLET_PROOF_VEST);			// 
	case MAKE_ITEM_ID_EX(11, 31): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_FULLMETALJACKETAMMO);		// 
	case MAKE_ITEM_ID_EX(11, 32): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_HOLLOW_POINT_AMMO);			// 
	case MAKE_ITEM_ID_EX(11, 33): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_ANTI_FLASHBANG_MASK);		// 
	case MAKE_ITEM_ID_EX(11, 34): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_C4_SPEED_KIT);				// 
	case MAKE_ITEM_ID_EX(11, 35): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_INCREASE_GRENADE_SLOT);		// 
	case MAKE_ITEM_ID_EX(11, 36): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_JACKETED_HELLOW_POINT_AMMO);	// 
	case MAKE_ITEM_ID_EX(11, 37): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_XP_PLUS_200);				//	경험치 증가 200%
	case MAKE_ITEM_ID_EX(11, 38): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_PT_PLUS_200);				//	포인트 증가 200%
	case MAKE_ITEM_ID_EX(11, 39): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_MEGA_HP5);					//	MEGAHP
	case MAKE_ITEM_ID_EX(11, 40): 	return MAKE_ITEM_ID(ITEM_TYPE_MAINTENANCE,	CASHITEM_DAY_NO,	CASHITEM_GROUP_BULLET_PROOF_VEST_PLUS);		// 
	
	case MAKE_ITEM_ID(12, 1):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1,		CASHITEM_GROUP_XP_PLUS_110);				// 경험치 110% 1일
	case MAKE_ITEM_ID(12, 2):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7,		CASHITEM_GROUP_XP_PLUS_110);				// 경험치 110% 7일
	case MAKE_ITEM_ID(12, 3):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_XP_PLUS_110);				// 경험치 110% 30일
	case MAKE_ITEM_ID(12, 4):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1,		CASHITEM_GROUP_XP_PLUS_130);				// 경험치 130% 1일
	case MAKE_ITEM_ID(12, 5):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7,		CASHITEM_GROUP_XP_PLUS_130);				// 경험치 130% 7일
	case MAKE_ITEM_ID(12, 6):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_XP_PLUS_130);				// 경험치 130% 30일
	case MAKE_ITEM_ID(12, 7):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1,		CASHITEM_GROUP_XP_PLUS_150);				// 경험치 150% 1일
	case MAKE_ITEM_ID(12, 8):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7,		CASHITEM_GROUP_XP_PLUS_150);				// 경험치 150% 7일
	case MAKE_ITEM_ID(12, 9):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_XP_PLUS_150);				// 경험치 150% 30일
	case MAKE_ITEM_ID(12, 10):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT, 	CASHITEM_DAY_NO,	CASHITEM_GROUP_CHANGE_NICK);				// 닉네임 변경
	case MAKE_ITEM_ID(12, 11):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT, 	CASHITEM_DAY_NO,	CASHITEM_GROUP_CLR_HISTORY);				// 전적 초기화
	case MAKE_ITEM_ID(12, 12):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT, 	CASHITEM_DAY_NO,	CASHITEM_GROUP_CLR_SCORE);					// 킬/데스 초기화
	case MAKE_ITEM_ID(12, 13):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT, 	CASHITEM_DAY_NO,	CASHITEM_GROUP_CLR_ESCAPE);					// 이탈률 초기화
	case MAKE_ITEM_ID(12, 14):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_1,		CASHITEM_GROUP_PT_PLUS_130);				// 포인트 130% 1일
	case MAKE_ITEM_ID(12, 15):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_7,		CASHITEM_GROUP_PT_PLUS_130);				// 포인트 130% 7일
	case MAKE_ITEM_ID(12, 16):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_PT_PLUS_130);				// 포인트 130% 30일
	case MAKE_ITEM_ID(12, 17):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT, 	CASHITEM_DAY_NO,	CASHITEM_GROUP_CHANGE_CLAN_NAME);			// 클랜명 변경
	case MAKE_ITEM_ID(12, 18):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT, 	CASHITEM_DAY_NO,	CASHITEM_GROUP_CHANGE_CLAN_MARK);			// 클랜마크 변경
	case MAKE_ITEM_ID(12, 19):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT, 	CASHITEM_DAY_NO,	CASHITEM_GROUP_CLR_CLAN_HISTORY);			// 클랜전적 초기화
	case MAKE_ITEM_ID(12, 20):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1,		CASHITEM_GROUP_COLOR_CLAN);					// 컬러 클랜명 1일
	case MAKE_ITEM_ID(12, 21):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7,		CASHITEM_GROUP_COLOR_CLAN);					// 컬러 클랜명 7일
	case MAKE_ITEM_ID(12, 22):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_COLOR_CLAN);					// 컬러 클랜명 30일
	case MAKE_ITEM_ID(12, 23):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1,		CASHITEM_GROUP_COLOR_NICK);					// 컬러 닉네임 1일
	case MAKE_ITEM_ID(12, 24):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_COLOR_NICK);					// 컬러 닉네임 7일
	case MAKE_ITEM_ID(12, 25):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_COLOR_NICK);					// 컬러 닉네임 30일
	case MAKE_ITEM_ID(12, 26):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1,		CASHITEM_GROUP_SHORT_RESPAWN);				// 리스폰 단축 1일
	case MAKE_ITEM_ID(12, 27):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_SHORT_RESPAWN);				// 리스폰 단축 7일
	case MAKE_ITEM_ID(12, 28):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_SHORT_RESPAWN);				// 리스폰 단축 30일
	case MAKE_ITEM_ID(12, 29):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_AMMO_UP);					// 보유탄수 증가 1일
	case MAKE_ITEM_ID(12, 30):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_AMMO_UP);					// 보유탄수 증가 7일
	case MAKE_ITEM_ID(12, 31):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_AMMO_UP);					// 보유탄수 증가 30일
	case MAKE_ITEM_ID(12, 32):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_RECORDING_GAME);				// 리플레이 녹화
	case MAKE_ITEM_ID(12, 33):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_CLAN_PERSON_PLUS_50);		// 클랜원 증가	
	case MAKE_ITEM_ID(12, 34):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1,		CASHITEM_GROUP_COLOR_CROSSHAIR);			// 컬러 크로스헤어 1일
	case MAKE_ITEM_ID(12, 35):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7,		CASHITEM_GROUP_COLOR_CROSSHAIR);			// 컬러 크로스헤어 7일
	case MAKE_ITEM_ID(12, 36):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30		CASHITEM_GROUP_COLOR_CROSSHAIR);			// 컬러 크로스헤어 30일	
	case MAKE_ITEM_ID(12, 37):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_COLOR_CHATTING);				// 컬러 채팅 1일
	case MAKE_ITEM_ID(12, 38):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7,		CASHITEM_GROUP_COLOR_CHATTING);				// 컬러 채팅 7일
	case MAKE_ITEM_ID(12, 39):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_COLOR_CHATTING);				// 컬러 채팅 30일
	case MAKE_ITEM_ID(12, 40):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_90,	CASHITEM_GROUP_XP_PLUS_130);				// 경험치 130% 90일
	case MAKE_ITEM_ID(12, 41):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_90,	CASHITEM_GROUP_PT_PLUS_130);				// 포인트 130% 90일
	case MAKE_ITEM_ID(12, 42):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_DISGUISE_NICK);				// 임시 닉네임 1일
	case MAKE_ITEM_ID(12, 43):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_DISGUISE_NICK);				// 임시 닉네임 7일
	case MAKE_ITEM_ID(12, 44):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_DISGUISE_NICK);				// 임시 닉네임 30일 
	case MAKE_ITEM_ID(12, 45):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_90,	CASHITEM_GROUP_DISGUISE_NICK);				// 임시 닉네임 90일	
	case MAKE_ITEM_ID(12, 46):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_CLR_CLAN_HISTORY);			// 클랜전 전적 초기화
	case MAKE_ITEM_ID(12, 47):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_CLAN_POINT_RESET);			// 클랜전 포인트 초기화
	case MAKE_ITEM_ID(12, 48):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_1, 	CASHITEM_GROUP_CLAN_XP_PLUS_150);			// 클랜 경험치 150%
	case MAKE_ITEM_ID(12, 49):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_7, 	CASHITEM_GROUP_CLAN_XP_PLUS_150);			// 클랜 경험치 150%
	case MAKE_ITEM_ID(12, 50):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_CLAN_XP_PLUS_150);			// 클랜 경험치 150%
	case MAKE_ITEM_ID(12, 51):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_CLAN_XP_PLUS_150);			// 클랜 경험치 150%
	case MAKE_ITEM_ID(12, 52):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_COLOR_NICK);					// 컬러 닉네임	90일
	case MAKE_ITEM_ID(12, 53):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_SHORT_RESPAWN);				// 리스폰 단축
	case MAKE_ITEM_ID(12, 54):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_COLOR_CROSSHAIR);			// 컬러 클로스 헤어 변경권 90일	
	case MAKE_ITEM_ID(12, 55):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_COLOR_CHATTING);				// 컬러 채팅 90일
	case MAKE_ITEM_ID(12, 56):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_1, 	CASHITEM_GROUP_DISGUISE_RANK);				// 위장 계급 1일
	case MAKE_ITEM_ID(12, 57):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_7, 	CASHITEM_GROUP_DISGUISE_RANK);				// 위장 계급 7일
	case MAKE_ITEM_ID(12, 58):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_DISGUISE_RANK);				// 위장 계급 30일
	case MAKE_ITEM_ID(12, 59):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_DISGUISE_RANK);				// 위장 계급 90일
	case MAKE_ITEM_ID(12, 60):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_BATTLEFIELD_MOVE);			// 전장이동	
	case MAKE_ITEM_ID(12, 61):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_1, 	CASHITEM_GROUP_FREE_MOVE);					// 자유이동
	case MAKE_ITEM_ID(12, 62):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_7, 	CASHITEM_GROUP_FREE_MOVE);					// 자유이동
	case MAKE_ITEM_ID(12, 63):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_FREE_MOVE);					// 자유이동
	case MAKE_ITEM_ID(12, 64):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_FREE_MOVE);					// 자유이동
	case MAKE_ITEM_ID(12, 65):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_CUSTOM_CROSSHAIR_MAKE);		// 커스텀 크로스헤어 등록권
	case MAKE_ITEM_ID(12, 66):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_1, 	CASHITEM_GROUP_CUSTOM_CROSSHAIR);			// 커스텀 크로스헤어 사용권
	case MAKE_ITEM_ID(12, 67):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_7, 	CASHITEM_GROUP_CUSTOM_CROSSHAIR);			// 커스텀 크로스헤어 사용권
	case MAKE_ITEM_ID(12, 68):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_CUSTOM_CROSSHAIR);			// 커스텀 크로스헤어 사용권
	case MAKE_ITEM_ID(12, 69):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_CUSTOM_CROSSHAIR);			// 커스텀 크로스헤어 사용권
	case MAKE_ITEM_ID(12, 70):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_AMMO_UP);					// 보유탄수 증가 90일
	case MAKE_ITEM_ID(12, 71):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_90,	CASHITEM_GROUP_COLOR_CLAN);					// 컬러 클랜명 90일
	case MAKE_ITEM_ID(12, 72):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_1, 	CASHITEM_GROUP_XP_PLUS_130);				// 경험치 130% 1일_Event	-> point로 변경	되었다고 함.
	case MAKE_ITEM_ID(12, 73):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_CHANGE_NICK);				// 닉네임 변경_Event
	case MAKE_ITEM_ID(12, 74):		return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_1, 	CASHITEM_GROUP_XP_PLUS_130);				// 경험치 130% 1일_Event
	case MAKE_ITEM_ID_EX(12, 75): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_1, 	CASHITEM_GROUP_GET_DROPPED_WEAPON);			// 적군 무기 줍기 1일
	case MAKE_ITEM_ID_EX(12, 76): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_7, 	CASHITEM_GROUP_GET_DROPPED_WEAPON);			// 적군 무기 줍기 7일
	case MAKE_ITEM_ID_EX(12, 77): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_GET_DROPPED_WEAPON);			// 적군 무기 줍기 30일
	case MAKE_ITEM_ID_EX(12, 78): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_XP_PLUS_X2_12PM);			// 12PM~3PM 경험치x2 30일
	case MAKE_ITEM_ID_EX(12, 79): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_XP_PLUS_X2_3PM);				// 3PM~6PM 경험치x2 30일
	case MAKE_ITEM_ID_EX(12, 80): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_XP_PLUS_X2_6PM);				// 6PM~9PM 경험치x2	30일
	case MAKE_ITEM_ID_EX(12, 81): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_XP_PLUS_X2_9PM);				// 9PM~12PM 경험치x2 30일
	case MAKE_ITEM_ID_EX(12, 82): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_PT_PLUS_X2_12PM);			// 12PM~3PM 포인트x2 30일
	case MAKE_ITEM_ID_EX(12, 83): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_PT_PLUS_X2_3PM);				// 3PM~6PM 포인트x2 30일
	case MAKE_ITEM_ID_EX(12, 84): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_PT_PLUS_X2_6PM);				// 6PM~9PM 포인트x2	30일
	case MAKE_ITEM_ID_EX(12, 85): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_30,	CASHITEM_GROUP_PT_PLUS_X2_9PM);				// 9PM~12PM 포인트x2 30일
	case MAKE_ITEM_ID_EX(12, 86): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_MEGA_BOMB);					// 캡슐 이용권 (랜덤 아이템)
	case MAKE_ITEM_ID_EX(12, 87): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_10,	CASHITEM_GROUP_XP_PLUS_X2_12PM);			// 12PM~3PM 경험치x2 10일
	case MAKE_ITEM_ID_EX(12, 88): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_10,	CASHITEM_GROUP_XP_PLUS_X2_3PM);				// 3PM~6PM 경험치x2 10일
	case MAKE_ITEM_ID_EX(12, 89): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_10,	CASHITEM_GROUP_XP_PLUS_X2_6PM);				// 6PM~9PM 경험치x2	10일
	case MAKE_ITEM_ID_EX(12, 90): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_10,	CASHITEM_GROUP_XP_PLUS_X2_9PM);				// 9PM~12PM 경험치x2 10일
	case MAKE_ITEM_ID_EX(12, 91): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_10,	CASHITEM_GROUP_PT_PLUS_X2_12PM);			// 12PM~3PM 포인트x2 10일
	case MAKE_ITEM_ID_EX(12, 92): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_10,	CASHITEM_GROUP_PT_PLUS_X2_3PM);				// 3PM~6PM 포인트x2 10일
	case MAKE_ITEM_ID_EX(12, 93): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_10,	CASHITEM_GROUP_PT_PLUS_X2_6PM);				// 6PM~9PM 포인트x2	10일
	case MAKE_ITEM_ID_EX(12, 94): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_10,	CASHITEM_GROUP_PT_PLUS_X2_9PM);				// 9PM~12PM 포인트x2 10일
	case MAKE_ITEM_ID_EX(12, 95): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_3, 	CASHITEM_GROUP_XP_PLUS_X2_12PM);			// 12PM~3PM 경험치x2 3일
	case MAKE_ITEM_ID_EX(12, 96): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_3, 	CASHITEM_GROUP_XP_PLUS_X2_3PM);				// 3PM~6PM 경험치x2 3일
	case MAKE_ITEM_ID_EX(12, 97): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_3, 	CASHITEM_GROUP_XP_PLUS_X2_6PM);				// 6PM~9PM 경험치x2	3일
	case MAKE_ITEM_ID_EX(12, 98): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_3, 	CASHITEM_GROUP_XP_PLUS_X2_9PM);				// 9PM~12PM 경험치x2 3일
	case MAKE_ITEM_ID_EX(12, 99): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_3, 	CASHITEM_GROUP_PT_PLUS_X2_12PM);			// 12PM~3PM 포인트x2 3일
	case MAKE_ITEM_ID_EX(12,100): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_3, 	CASHITEM_GROUP_PT_PLUS_X2_3PM);				// 3PM~6PM 포인트x2 3일
	case MAKE_ITEM_ID_EX(12,101): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_3, 	CASHITEM_GROUP_PT_PLUS_X2_6PM);				// 6PM~9PM 포인트x2	3일
	case MAKE_ITEM_ID_EX(12,102): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD,	CASHITEM_DAY_3, 	CASHITEM_GROUP_PT_PLUS_X2_9PM);				// 9PM~12PM 포인트x2 3일
		
	case MAKE_ITEM_ID_EX(12,103): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_QUICK_CHANGE_WEAPON);		// 
	case MAKE_ITEM_ID_EX(12,104): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_QUICK_CHANGE_WEAPON);		// 
	case MAKE_ITEM_ID_EX(12,105): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_QUICK_CHANGE_WEAPON);		// 
																									
	case MAKE_ITEM_ID_EX(12,106): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_QUICK_CHANGE_MAGAZINE);		// 
	case MAKE_ITEM_ID_EX(12,107): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_QUICK_CHANGE_MAGAZINE);		// 
	case MAKE_ITEM_ID_EX(12,108): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_QUICK_CHANGE_MAGAZINE);		// 
																									
	case MAKE_ITEM_ID_EX(12,109): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_MEGA_HP10);					// 
	case MAKE_ITEM_ID_EX(12,110): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_MEGA_HP10);					// 
	case MAKE_ITEM_ID_EX(12,111): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_MEGA_HP10);					// 
																									
	case MAKE_ITEM_ID_EX(12,112): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_INCREASE_INVINCIBLE_TIME);	// 
	case MAKE_ITEM_ID_EX(12,113): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_INCREASE_INVINCIBLE_TIME);	// 
	case MAKE_ITEM_ID_EX(12,114): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_INCREASE_INVINCIBLE_TIME);	// 
																									
	case MAKE_ITEM_ID_EX(12,115): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_BULLET_PROOF_VEST);			// 
	case MAKE_ITEM_ID_EX(12,116): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_BULLET_PROOF_VEST);			// 
	case MAKE_ITEM_ID_EX(12,117): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_BULLET_PROOF_VEST);			// 
																									
	case MAKE_ITEM_ID_EX(12,118): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_FULLMETALJACKETAMMO);		// 
	case MAKE_ITEM_ID_EX(12,119): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_FULLMETALJACKETAMMO);		// 
	case MAKE_ITEM_ID_EX(12,120): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_FULLMETALJACKETAMMO);		// 
																									
	case MAKE_ITEM_ID_EX(12,121): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_HOLLOW_POINT_AMMO);			// 
	case MAKE_ITEM_ID_EX(12,122): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_HOLLOW_POINT_AMMO);			// 
	case MAKE_ITEM_ID_EX(12,123): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_HOLLOW_POINT_AMMO);			// 
																									
	case MAKE_ITEM_ID_EX(12,124): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_ANTI_FLASHBANG_MASK);		// 
	case MAKE_ITEM_ID_EX(12,125): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_ANTI_FLASHBANG_MASK);		// 
	case MAKE_ITEM_ID_EX(12,126): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_ANTI_FLASHBANG_MASK);		// 
																									
	case MAKE_ITEM_ID_EX(12,127): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_C4_SPEED_KIT);				// 
	case MAKE_ITEM_ID_EX(12,128): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_C4_SPEED_KIT);				// 
	case MAKE_ITEM_ID_EX(12,129): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_C4_SPEED_KIT);				// 
																									
	case MAKE_ITEM_ID_EX(12,130): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_INCREASE_GRENADE_SLOT);		// 
	case MAKE_ITEM_ID_EX(12,131): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_INCREASE_GRENADE_SLOT);		// 
	case MAKE_ITEM_ID_EX(12,132): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_INCREASE_GRENADE_SLOT);		// 
																									
	case MAKE_ITEM_ID_EX(12,133): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_JACKETED_HELLOW_POINT_AMMO);	// 
	case MAKE_ITEM_ID_EX(12,134): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_JACKETED_HELLOW_POINT_AMMO);	// 
	case MAKE_ITEM_ID_EX(12,135): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_JACKETED_HELLOW_POINT_AMMO);	// 
																									
	case MAKE_ITEM_ID_EX(12,136): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_WEAPON_CRATE);				//	레어총기박스 (랜덤 아이템)
																									
	case MAKE_ITEM_ID_EX(12,137): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_3, 	CASHITEM_GROUP_XP_PLUS_130);				// 경험치 130% 3일
	case MAKE_ITEM_ID_EX(12,138): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_10,	CASHITEM_GROUP_XP_PLUS_130);				// 경험치 130% 10일
																									
	case MAKE_ITEM_ID_EX(12,139): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_3, 	CASHITEM_GROUP_PT_PLUS_130);				//	포인트 증가 130% 3일권
	case MAKE_ITEM_ID_EX(12,140): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_10,	CASHITEM_GROUP_PT_PLUS_130);				//	포인트 증가 130% 10일권
																									
	case MAKE_ITEM_ID_EX(12,141): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_XP_PLUS_200);				//	포인트 증가 200% 1일권
	case MAKE_ITEM_ID_EX(12,142): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_3, 	CASHITEM_GROUP_XP_PLUS_200);				//	포인트 증가 200% 3일권
																									
	case MAKE_ITEM_ID_EX(12,143): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_PT_PLUS_200);				//	포인트 증가 200% 1일권
	case MAKE_ITEM_ID_EX(12,144): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_3, 	CASHITEM_GROUP_PT_PLUS_200);				//	포인트 증가 200% 3일권
																									
	case MAKE_ITEM_ID_EX(12,145): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_GIGA_BOMB);					//	기가붐 (랜덤 아이템)
																									
	case MAKE_ITEM_ID_EX(12,146): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_MEGA_HP5);					//	MEGAHP
	case MAKE_ITEM_ID_EX(12,147): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_MEGA_HP5);					//	MEGAHP
	case MAKE_ITEM_ID_EX(12,148): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_MEGA_HP5);					//	MEGAHP
																									
	case MAKE_ITEM_ID_EX(12,149): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_DEFCON_1);					//	데프콘_1
	case MAKE_ITEM_ID_EX(12,150): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_DEFCON_2);					//	데프콘_2
	case MAKE_ITEM_ID_EX(12,151): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_DEFCON_3);					//	데프콘_3
																									
	case MAKE_ITEM_ID_EX(12,152): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_3, 	CASHITEM_GROUP_BULLET_PROOF_VEST);			//	데프콘_3
																									
	case MAKE_ITEM_ID_EX(12,153): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_3, 	CASHITEM_GROUP_MEGA_HP5);					//	MEGAHP 5% 3일권
	case MAKE_ITEM_ID_EX(12,154): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_3, 	CASHITEM_GROUP_MEGA_HP10);					//	MEGAHP 10% 3일권
																									
	case MAKE_ITEM_ID_EX(12,155): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_1, 	CASHITEM_GROUP_BULLET_PROOF_VEST_PLUS);		// 
	case MAKE_ITEM_ID_EX(12,156): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_3, 	CASHITEM_GROUP_BULLET_PROOF_VEST_PLUS);		// 
	case MAKE_ITEM_ID_EX(12,157): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_7, 	CASHITEM_GROUP_BULLET_PROOF_VEST_PLUS);		// 
	case MAKE_ITEM_ID_EX(12,158): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_PERIOD, 	CASHITEM_DAY_30,	CASHITEM_GROUP_BULLET_PROOF_VEST_PLUS);		// 
																									
	case MAKE_ITEM_ID_EX(12,159): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_WEAPON_CRATE_2);				// 
																									
	case MAKE_ITEM_ID_EX(12,160): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_3, 	CASHITEM_GROUP_QUICK_CHANGE_MAGAZINE);		// 
	case MAKE_ITEM_ID_EX(12,161): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_3, 	CASHITEM_GROUP_QUICK_CHANGE_WEAPON);		// 
																									
	case MAKE_ITEM_ID_EX(12,162): 	return MAKE_ITEM_ID(ITEM_TYPE_WRAP_COUNT,	CASHITEM_DAY_NO,	CASHITEM_GROUP_MINIBOMB);					// 

	case MAKE_ITEM_ID(15, 1):		// 쿠폰 포인트 3000		- Server에서만 처리되는 아이템						-
	case MAKE_ITEM_ID(15, 2):		// 쿠폰 포인트 5000		- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID(15, 3):		// 쿠폰 포인트 10000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID(15, 4):		// 쿠폰 포인트 100000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(15, 5):	// 쿠폰 포인트 1000		- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(15, 6):	// 쿠폰 포인트 2000		- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(15, 7):	// 쿠폰 포인트 4000		- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(15, 8):	// 쿠폰 포인트 100		- Server에서만 처리되는 아이템

	case MAKE_ITEM_ID(16, 7):		// 상품 포인트 20,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 8):	// 상품 포인트 30,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 12):	// 상품 포인트 12,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 13):	// 상품 포인트 4,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 14):	// 상품 포인트 1,500	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 15):	// 상품 포인트 5,500	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 16):	// 상품 포인트 2,500	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 17):	// 상품 포인트 3,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 18):	// 상품 포인트 3,500	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 19):	// 상품 포인트 4,500	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 20):	// 상품 포인트 6,500	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 21):	// 상품 포인트 7,500	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 22):	// 상품 포인트 8,500	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 23):	// 상품 포인트 9,500	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 24):	// 상품 포인트 11,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 25):	// 상품 포인트 13,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 26):	// 상품 포인트 14,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 27):	// 상품 포인트 15,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 28):	// 상품 포인트 16,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 29):	// 상품 포인트 17,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 30):	// 상품 포인트 18,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 31):	// 상품 포인트 19,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 32):	// 상품 포인트 25,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 33):	// 상품 포인트 30,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 34):	// 상품 포인트 35,000	- Server에서만 처리되는 아이템
	case MAKE_ITEM_ID_EX(16, 35):	// 상품 포인트 40,000	- Server에서만 처리되는 아이템
        return 0; 
	default:
		/* Do nothing */
		break;
	}

	return -1;
}

#endif

#endif	// __ITEMLIST_H__