#配置服务器地址
ServerAddr=114.80.135.71:8194

#SDK绑定的本地端口
LocalPort=10085

ConnectTimeOut=3

#标识GS的别名
HostName=0

#网络层消息超时时间(s)
StackMsgTimeOut=5

#必答消息最大缓存数量
MaxAckMsgCacheNumber=2048

#单个必答消息最大长度
MaxAckMsgCacheSize=1024

#业务层消息超时时间
BusinessMsgTimeOut=1

#消息队列最大长度
MaxMsgQueueSize=10024

#是否自动发送解冻消息
AutoUnLock=1





