//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by i3GuiEditor.rc
//
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   128
#define IDD_PANE_PREVIEW                130
#define IDD_PANE_TREEVIEW               131
#define IDD_PANE_UVEDIT                 132
#define IDD_PANE_LAYOUT                 133
#define IDD_PANE_PROPERTY               134
#define IDD_PANE_CONTROLSHAPE           135
#define IDD_PANE_EVENTNACTION           136
#define IDD_PANE_TEXTURELIST            137
#define IDD_PANE_GUITREEVIEW            140
#define IDC_DRAG                        140
#define IDR_POPUP_GUI                   142
#define IDD_SELECT_CONTROL              143
#define IDD_TEMPLATE_ADD                145
#define IDR_POPUP_RES                   146
#define IDR_POPUP_CTRLSHAPE             147
#define IDD_PROPERTY_COMMON             148
#define IDD_SELECT_TEXTURE              149
#define IDD_SELECT_TEMPLATE             150
#define IDR_POPUP_ACTION                154
#define IDD_EDITACTION_MOVE             155
#define IDD_EDITACTION_SCALE            156
#define IDD_EDITACTION_ROTATE           157
#define IDD_EDITACTION_SOUND            159
#define IDD_DIALOG1                     161
#define IDD_DIALOG_GETSTRING            162
#define IDC_PREVIEW_PLACEHOLDER         1000
#define IDC_RESLIST_TEXTURE             1011
#define IDC_COMBO_SELECT_CONTROL        1014
#define IDC_RESLIST_TEMPLATE            1014
#define IDC_EDIT1                       1016
#define IDC_PROP_COMMON_POSX            1017
#define IDC_ED_MOVE_TARGETPOSX          1017
#define IDC_EDITACTION_SOUNDVOLUME      1017
#define IDC_SPREAD_WIDTH                1017
#define IDC_PROP_COMMON_NAME            1018
#define IDC_ED_MOVE_TARGETPOSY          1018
#define IDC_EDITACTION_SOUNDSTARTTIME   1018
#define IDC_EDIT_SPREAD_HEIGHT          1018
#define IDC_LIST_SELTEX                 1019
#define IDC_EDITACTION_LOOPCOUNT        1019
#define IDC_LIST_SELTEMPLATE            1021
#define IDC_LIST_ENA_STATE              1023
#define IDC_LIST_ENA_ACTION             1024
#define IDC_CB_MOVE_SELFACTOR           1024
#define IDC_PROP_COMMON_POSY            1025
#define IDC_ED_MOVE_DURATION            1025
#define IDC_PROP_COMMON_WIDTH           1026
#define IDC_ED_SCALE_Y                  1026
#define IDC_PROP_COMMON_HEIGHT          1027
#define IDC_ED_SCALE_DURATION           1027
#define IDC_CB_SCALE_SELFACTOR          1028
#define IDC_ED_SCALE_X                  1029
#define IDC_CB_ROTATE_SELSPINDIR        1030
#define IDC_CHECK_LOOPSCALE             1031
#define IDC_CB_ROTATE_SELFACTOR         1032
#define IDC_ED_ROTATE_DURATION          1033
#define IDC_CHECK_LOOPROTATE            1034
#define IDC_ED_SOUND_FILESELECT         1040
#define IDC_CKB_LOOPPLAY                1041
#define IDC_EDITACTION_SOUND_SELFILE    1043
#define IDC_CB_SOUNDTYPE                1044
#define IDC_CB_SOUNDTYPE2               1045
#define IDC_CB_3DMODE                   1045
#define IDC_EDIT_SPREAD_COLCOUNT        1046
#define IDC_EDIT_NODENAME               1047
#define IDC_CHECK1                      1048
#define IDC_CHECK_SEARCH_EXACTLYSAME    1048
#define ID_POPUP_EXPAND                 32802
#define ID_POPUP_COLLAPSE               32803
#define ID_POPUP_SHOW                   32804
#define ID_POPUP_SELECT_SELECTALL       32805
#define ID_POPUP_SELECT_UNSELECTALL     32806
#define ID_POPUP_SELECT_SELECTALLDESCENDANTS 32807
#define ID_POPUP_SELECT_UNSELECTALLDESCENDANTS 32808
#define ID_POPUP_INSERT_INSERTCONTROL   32810
#define ID_POPUP_INSERT_INSERTWINDOW    32811
#define ID_POPUP_DELETE                 32812
#define ID_POPUP_SELECT_REVERSESELECTION 32813
#define ID_FILE_LOAD_PROJECT            32831
#define ID_FILE_SAVE_PROJECT            32832
#define ID_IMPORT_TEXTURE               32836
#define ID_IMPORT_ANIMATION             32837
#define ID_IMPORT_SCENEGRAPH            32841
#define ID_IMPORT_TEMPLATE              32842
#define ID_ADD_NEWTEMPLATE              32848
#define ID_SHAPE_ADD                    32851
#define ID_SHAPE_DELETE                 32852
#define ID_ADJUST_SIZEBY_UV             32862
#define ID_CTRLSHAPE_SETTEXTURE         32867
#define ID_POPUP_SETTEMPLATE            32870
#define ID_DELETE_RES                   32872
#define ID_LOADBG_AS_WORLD              32876
#define ID_LOADBG_AS_SKY                32877
#define ID_EXPORT_FILE                  32879
#define ID_MENU_SETWORKINGFOLDER        32881
#define ID_POPUP_REMOVEACTION           32885
#define ID_POPUP_EDITACTION             32886
#define ID_ACTION_ADDMOVE               32899
#define ID_ACTION_ADDROTATE             32900
#define ID_ACTION_ADDSCALE              32901
#define ID_ACTION_ADDSOUND              32902
#define ID_FILE_TEMPLATE_EXPORT         32905
#define ID_FILE_TEMPLATE_IMPORT         32906
#define ID_Menu                         32907
#define ID__EXPORTNODE                  32908
#define ID__IMPORTNODE                  32909
#define ID_32912                        32912
#define ID_MENU_SETLINECOLOR_WHITE      32915
#define ID_MENU_SETLINECOLOR_BLACK      32916
#define ID__FIXEDCOUNTSHAPETYPE         32917
#define ID_SET_FIXEDCOUNTSHAPETYPE      32922
#define ID_UNSET_FIXEDCOUNTSHAPETYPE    32923
#define ID__SETCURRENTROOT              32924
#define ID__ALIGN                       32925
#define ID_ALIGN_LEFT                   32930
#define ID_ALIGN_TOP                    32931
#define ID_ALIGN_RIGHT                  32934
#define ID_ALIGN_BOTTOM                 32936
#define ID_ALIGN_CENTER_X               32937
#define ID_ALIGN_CENTER_Y               32938
#define ID_COPY_UV_TOALLOTHERS          32940
#define ID_ERASESHAPE_EMPTY_FOROFFSET   32942
#define ID_ALIGN_LEFTTOP                32945
#define ID_ALIGN_RIGHTBOTTOM            32946
#define ID_CTRLSHAPE_SELECTALL          32948
#define ID_COPY_SIZE_TOOTHERS           32950
#define ID_CTRLSHAPE_SPREAD             32952
#define ID_SPREADSHAPES_DEFAULT         32959
#define ID_SPREADSHAPES_ALL             32960
#define ID_SPREADSHAPES_DEFAULT_BYVALUE 32962
#define ID_SPREADSHAPES_ALL_BYVALUE     32963
#define ID_SPREADSHAPES_SELECTED        32965
#define ID_SPREADSHAPES_SELECTED_BYVALUE 32966
#define ID_FIND_NODE                    32968
#define ID_CHECK_MNEMONICS              32970
#define ID_POPUP_FIND                   32973

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32974
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
