#pragma once


// PanelSpec dialog
enum PROPERTY_ITEM_ID
{
	//	property title
	PROPERTY_STATIC_FRAMEWORK_NAME = 0,
	PROPERTY_STATIC_FRAMEWORK_STARTSTAGE,
	PROPERTY_STATIC_FRAMEWORK_CMNRES,

	PROPERTY_STATIC_STAGE_NAME,
	PROPERTY_STATIC_STAGE_CLASSNAME,
	PROPERTY_STATIC_STAGE_FADEINCOLOR,
	PROPERTY_STATIC_STAGE_FADEINTIME,
	PROPERTY_STATIC_STAGE_FADEOUTCOLOR,
	PROPERTY_STATIC_STAGE_FADEOUTTIME,
	PROPERTY_STATIC_STAGE_NEXTSTAGE,
	PROPERTY_STATIC_STAGE_JUMPTYPE,
	PROPERTY_STATIC_STAGE_RSC,

	PROPERTY_STATIC_LAYER_NAME,
	PROPERTY_STATIC_LAYER_STYLE_2D,
	PROPERTY_STATIC_LAYER_STYLE_TRANS,

	PROPERTY_STATIC_INSTANCE_CLASSNAME,
	PROPERTY_STATIC_INSTANCE_COUNT,
	PROPERTY_STATIC_INSTANCE_UPDATEINTERVAL,
	PROPERTY_STATIC_INSTANCE_FIXEDCOUNT,
		
	//	property value
	PROPERTY_EDIT_FRAMEWORK_NAME,
	PROPERTY_EDIT_FRAMEWORK_STARTSTAGE,
	PROPERTY_EDIT_FRAMEWORK_CMNRES,

	PROPERTY_EDIT_STAGE_NAME,
	PROPERTY_EDIT_STAGE_CLASSNAME,
	PROPERTY_EDIT_STAGE_FADEINCOLOR,
	PROPERTY_EDIT_STAGE_FADEINTIME,
	PROPERTY_EDIT_STAGE_FADEOUTCOLOR,
	PROPERTY_EDIT_STAGE_FADEOUTTIME,
	PROPERTY_EDIT_STAGE_NEXTSTAGE,
	PROPERTY_EDIT_STAGE_JUMPTYPE,
	PROPERTY_EDIT_STAGE_RSC,

	PROPERTY_EDIT_LAYER_NAME,
	PROPERTY_EDIT_LAYER_STYLE_2D,
	PROPERTY_EDIT_LAYER_STYLE_TRANS,

	PROPERTY_EDIT_INSTANCE_CLASSNAME,
	PROPERTY_EDIT_INSTANCE_COUNT,
	PROPERTY_EDIT_INSTANCE_UPDATEINTERVAL,
	PROPERTY_EDIT_INSTANCE_FIXEDCOUNT,

	PROPERTY_ITEM_MAX
};

enum PROPERTY_VALUE_ID
{
	PROPERTY_VALUE_FRAMEWORK_NAME = 1000,
	PROPERTY_VALUE_FRAMEWORK_STARTSTAGE,
	PROPERTY_VALUE_FRAMEWORK_CMNRES,

	PROPERTY_VALUE_STAGE_NAME,
	PROPERTY_VALUE_STAGE_CLASSNAME,
	PROPERTY_VALUE_STAGE_FADEINCOLOR,
	PROPERTY_VALUE_STAGE_FADEINTIME,
	PROPERTY_VALUE_STAGE_FADEOUTCOLOR,
	PROPERTY_VALUE_STAGE_FADEOUTTIME,
	PROPERTY_VALUE_STAGE_NEXTSTAGE,
	PROPERTY_VALUE_STAGE_JUMPTYPE,
	PROPERTY_VALUE_STAGE_RSC,

	PROPERTY_VALUE_LAYER_NAME,
	PROPERTY_VALUE_LAYER_STYLE_2D,
	PROPERTY_VALUE_LAYER_STYLE_TRANS,

	PROPERTY_VALUE_INSTANCE_CLASSNAME,
	PROPERTY_VALUE_INSTANCE_COUNT,
	PROPERTY_VALUE_INSTANCE_UPDATEINTERVAL,
	PROPERTY_VALUE_INSTANCE_FIXEDCOUNT,

	PROPERTY_VALUE_MAX
};

class PanelSpec : public i3TDKDialogBase
{
	DECLARE_DYNAMIC(PanelSpec)

public:
	PanelSpec(CWnd* pParent = NULL);   // standard constructor
	virtual ~PanelSpec();

// Dialog Data
	enum { IDD = IDD_PANEL_SPEC };

public:
	enum PROPERTY_PAGE_ID
	{
		PROPERTY_PAGE_EMPTY = 0,
		PROPERTY_PAGE_GAME ,
		PROPERTY_PAGE_STAGE,
		PROPERTY_PAGE_LAYER,

		PROPERTY_PAGE_MAX
	};

	i3TDKListCtrl			m_ListCtrl;
	//PROPERTY_PAGE_ID		m_CurPage;

protected:
	i3TDKPropertySubItem * m_pPropertyItem[ PROPERTY_ITEM_MAX]; 

public:
	void		SelectPage( i3ElementBase * pData);
	void		ResetGame( void);

protected:
	
	void		_createProperty( void);
	void		_releaseProperty( void);

	//	RSC Dialog¿ë Callback ÇÔ¼ö
	static void callRSCDialogOnHit( CallOnHitRef * pRef);

protected:
	virtual void DoDataExchange(CDataExchange* pDX) override;    // DDX/DDV support
	virtual LRESULT WindowProc(UINT message, WPARAM wParam, LPARAM lParam) override;

	DECLARE_MESSAGE_MAP()
public:

	afx_msg void OnDestroy();
	afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);	
	afx_msg void OnSize(UINT nType, int cx, int cy);
	
};
