//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by i3Viewer2.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_i3Viewer2TYPE               130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define ID_PANEL_SG                     310
#define IDD_PANEL_SPEC                  310
#define ID_PANEL_SPEC                   311
#define IDB_ICONS_24                    312
#define IDB_ICONS_32                    315
#define IDD_BATCH_RENATTR_OPTI          316
#define IDD_BLEND_OPTION_APPLY          317
#define IDD_COLOR_OPTION_APPLY          318
#define ID_BTN_OPT4                     320
#define IDC_BRAO_BT_WRITE_RST           1002
#define IDC_BRAO_PB_PROGRESS            1003
#define IDD_BRAO_BT_OPTIMIZE            1004
#define IDC_BRAO_LB_LOG                 1005
#define IDC_BRAO_EB_SUBPATH             1006
#define IDC_BRAO_EB_WORKPATH            1008
#define IDC_BRAO_BT_BROWSE_WORKPATH     1009
#define IDC_BRAO_CK_SAVE_I3S_OPTI_SUCCESS 1010
#define IDC_COMBO_BLENDTYPE             1011
#define IDC_EDIT_REFVALUE               1014
#define IDC_CHK_EMISSION                1015
#define IDC_EDIT_SHININESS              1016
#define IDC_STATIC_COLOR                1017
#define IDC_STATIC_DIFFUSE              1018
#define IDC_STATIC_SPECULAR             1019
#define IDC_STATIC_EMISSION             1020
#define IDC_CHK_SPECULAR                1021
#define IDC_CHK_DIFFUSE                 1022
#define IDC_CHK_COLOR                   1023
#define IDC_CHK_SHINE                   1024
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_32771                        32771
#define ID_VIEW_NORMAL_VIEW             32772
#define ID_32773                        32773
#define ID_VIEW_MESH                    32774
#define ID_VIEW_NORMAL                  32775
#define ID_32776                        32776
#define ID_VIEW_COLLIDER                32777
#define ID_32778                        32778
#define ID_VIEW_WIRE                    32779
#define ID_32780                        32780
#define ID_VIEW_SELONLY                 32781
#define ID_32782                        32782
#define ID_VIEW_SHADOW                  32783
#define ID_32784                        32784
#define ID_VIEW_GRID                    32785
#define ID_ANIMATION_TIMESCALE          32786
#define ID_TOOLS_GEOMETRY               32787
#define ID_TOOLS_TEXTURES               32788
#define ID_TOOLS_PROJECTCONFIG          32789
#define ID_TOOLS_OPTIONS                32790
#define ID_OPTIONS_AMBIENTCOLOR         32791
#define ID_OPTIONS_CLEARCOLOR           32792
#define ID_OPTIONS_SHADOWSIZE           32793
#define ID_OPTIONS_LIGHTCOLOR           32794
#define ID_OPTIONS_LIGHTINTENSITY       32795
#define ID_OPTIONS_REFLECTMAP           32796
#define ID_OPTIONS_SHADOWTYPE           32797
#define ID_TOOLS_PANE                   32798
#define ID_PANE_SG                      32799
#define ID_PANE_SPEC                    32800
#define ID_TOOLS_PHYSIXTOOL             32801
#define ID_TOOLS_CHANGETEX              32802
#define ID_TOOLS_BATCH_RENATTR_OPTI     32803
#define ID_CAMERA_FOV                   32804
#define ID_EDIT_LIGHTINTENSITY          32805
#define ID_EDIT_LIGHTPOSRHO             32807
#define ID_EDIT_LIGHTPOSTHETA           32808
#define ID_BTN_OPT1                     32809
#define ID_BTN_OPT2                     32810
#define ID_BTN_OPT3                     32811
#define ID_SLIDER_LIGHTPOSRHO           32812
#define ID_SLIDER_LIGHTPOSTHETA         32813
#define ID_CHECK_LIGHTPOS               32814
#define ID_SLIDER_BLOOMINTENSITY        32815
#define ID_SLIDER_BLOOMTHRESHOLD        32816
#define ID_EDIT_BLOOMINTENSITY          32817
#define ID_EDIT_BLOOMTHRESHOLD          32818
#define ID_CHECK_BLOOM                  32819
#define ID_EDIT_BLURITERATION           32820
#define ID_EDIT_GAUSSIANTHETA           32821
#define ID_SLIDER_GAUSSIANTHETA         32822
#define ID_TOOLS_TOTALBLEND             32823
#define ID_TOOLS_TOTALCOLOR             32824
#define ID_BTN_TWOSIDE                  32825
#define ID_BTN_DEPTHWRITE               32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           321
#endif
#endif
