#pragma once

#define pp_intercept_impl		pp_intercept_

# define pp_intercept_0
# define pp_intercept_1
# define pp_intercept_2
# define pp_intercept_3
# define pp_intercept_4
# define pp_intercept_5
# define pp_intercept_6
# define pp_intercept_7
# define pp_intercept_8
# define pp_intercept_9
# define pp_intercept_10
# define pp_intercept_11
# define pp_intercept_12
# define pp_intercept_13
# define pp_intercept_14
# define pp_intercept_15
# define pp_intercept_16
# define pp_intercept_17
# define pp_intercept_18
# define pp_intercept_19
# define pp_intercept_20
# define pp_intercept_21
# define pp_intercept_22
# define pp_intercept_23
# define pp_intercept_24
# define pp_intercept_25
# define pp_intercept_26
# define pp_intercept_27
# define pp_intercept_28
# define pp_intercept_29
# define pp_intercept_30
# define pp_intercept_31
# define pp_intercept_32
# define pp_intercept_33
# define pp_intercept_34
# define pp_intercept_35
# define pp_intercept_36
# define pp_intercept_37
# define pp_intercept_38
# define pp_intercept_39
# define pp_intercept_40
# define pp_intercept_41
# define pp_intercept_42
# define pp_intercept_43
# define pp_intercept_44
# define pp_intercept_45
# define pp_intercept_46
# define pp_intercept_47
# define pp_intercept_48
# define pp_intercept_49
# define pp_intercept_50
# define pp_intercept_51
# define pp_intercept_52
# define pp_intercept_53
# define pp_intercept_54
# define pp_intercept_55
# define pp_intercept_56
# define pp_intercept_57
# define pp_intercept_58
# define pp_intercept_59
# define pp_intercept_60
# define pp_intercept_61
# define pp_intercept_62
# define pp_intercept_63
# define pp_intercept_64
# define pp_intercept_65
# define pp_intercept_66
# define pp_intercept_67
# define pp_intercept_68
# define pp_intercept_69
# define pp_intercept_70
# define pp_intercept_71
# define pp_intercept_72
# define pp_intercept_73
# define pp_intercept_74
# define pp_intercept_75
# define pp_intercept_76
# define pp_intercept_77
# define pp_intercept_78
# define pp_intercept_79
# define pp_intercept_80
# define pp_intercept_81
# define pp_intercept_82
# define pp_intercept_83
# define pp_intercept_84
# define pp_intercept_85
# define pp_intercept_86
# define pp_intercept_87
# define pp_intercept_88
# define pp_intercept_89
# define pp_intercept_90
# define pp_intercept_91
# define pp_intercept_92
# define pp_intercept_93
# define pp_intercept_94
# define pp_intercept_95
# define pp_intercept_96
# define pp_intercept_97
# define pp_intercept_98
# define pp_intercept_99
# define pp_intercept_100
# define pp_intercept_101
# define pp_intercept_102
# define pp_intercept_103
# define pp_intercept_104
# define pp_intercept_105
# define pp_intercept_106
# define pp_intercept_107
# define pp_intercept_108
# define pp_intercept_109
# define pp_intercept_110
# define pp_intercept_111
# define pp_intercept_112
# define pp_intercept_113
# define pp_intercept_114
# define pp_intercept_115
# define pp_intercept_116
# define pp_intercept_117
# define pp_intercept_118
# define pp_intercept_119
# define pp_intercept_120
# define pp_intercept_121
# define pp_intercept_122
# define pp_intercept_123
# define pp_intercept_124
# define pp_intercept_125
# define pp_intercept_126
# define pp_intercept_127
# define pp_intercept_128
# define pp_intercept_129
# define pp_intercept_130
# define pp_intercept_131
# define pp_intercept_132
# define pp_intercept_133
# define pp_intercept_134
# define pp_intercept_135
# define pp_intercept_136
# define pp_intercept_137
# define pp_intercept_138
# define pp_intercept_139
# define pp_intercept_140
# define pp_intercept_141
# define pp_intercept_142
# define pp_intercept_143
# define pp_intercept_144
# define pp_intercept_145
# define pp_intercept_146
# define pp_intercept_147
# define pp_intercept_148
# define pp_intercept_149
# define pp_intercept_150
# define pp_intercept_151
# define pp_intercept_152
# define pp_intercept_153
# define pp_intercept_154
# define pp_intercept_155
# define pp_intercept_156
# define pp_intercept_157
# define pp_intercept_158
# define pp_intercept_159
# define pp_intercept_160
# define pp_intercept_161
# define pp_intercept_162
# define pp_intercept_163
# define pp_intercept_164
# define pp_intercept_165
# define pp_intercept_166
# define pp_intercept_167
# define pp_intercept_168
# define pp_intercept_169
# define pp_intercept_170
# define pp_intercept_171
# define pp_intercept_172
# define pp_intercept_173
# define pp_intercept_174
# define pp_intercept_175
# define pp_intercept_176
# define pp_intercept_177
# define pp_intercept_178
# define pp_intercept_179
# define pp_intercept_180
# define pp_intercept_181
# define pp_intercept_182
# define pp_intercept_183
# define pp_intercept_184
# define pp_intercept_185
# define pp_intercept_186
# define pp_intercept_187
# define pp_intercept_188
# define pp_intercept_189
# define pp_intercept_190
# define pp_intercept_191
# define pp_intercept_192
# define pp_intercept_193
# define pp_intercept_194
# define pp_intercept_195
# define pp_intercept_196
# define pp_intercept_197
# define pp_intercept_198
# define pp_intercept_199
# define pp_intercept_200
# define pp_intercept_201
# define pp_intercept_202
# define pp_intercept_203
# define pp_intercept_204
# define pp_intercept_205
# define pp_intercept_206
# define pp_intercept_207
# define pp_intercept_208
# define pp_intercept_209
# define pp_intercept_210
# define pp_intercept_211
# define pp_intercept_212
# define pp_intercept_213
# define pp_intercept_214
# define pp_intercept_215
# define pp_intercept_216
# define pp_intercept_217
# define pp_intercept_218
# define pp_intercept_219
# define pp_intercept_220
# define pp_intercept_221
# define pp_intercept_222
# define pp_intercept_223
# define pp_intercept_224
# define pp_intercept_225
# define pp_intercept_226
# define pp_intercept_227
# define pp_intercept_228
# define pp_intercept_229
# define pp_intercept_230
# define pp_intercept_231
# define pp_intercept_232
# define pp_intercept_233
# define pp_intercept_234
# define pp_intercept_235
# define pp_intercept_236
# define pp_intercept_237
# define pp_intercept_238
# define pp_intercept_239
# define pp_intercept_240
# define pp_intercept_241
# define pp_intercept_242
# define pp_intercept_243
# define pp_intercept_244
# define pp_intercept_245
# define pp_intercept_246
# define pp_intercept_247
# define pp_intercept_248
# define pp_intercept_249
# define pp_intercept_250
# define pp_intercept_251
# define pp_intercept_252
# define pp_intercept_253
# define pp_intercept_254
# define pp_intercept_255
# define pp_intercept_256