#pragma once

#define pp_seq_for_each_product_impl(macro, sets) pp_seq_for_each_product_e(pp_for, macro, sets)
#define pp_seq_for_each_product_r_impl(r, macro, sets) pp_seq_for_each_product_e(pp_for_ ## r, macro, sets)

#define pp_seq_for_each_product_e(impl, macro, sets) impl((pp_seq_head(sets)(nil), pp_seq_tail(sets)(nil), (nil), macro), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_0)
#define pp_seq_for_each_product_p(r, data) pp_dec(pp_seq_size(pp_tuple_elem(4, 0, data)))
#define pp_seq_for_each_product_o(r, data) pp_seq_for_each_product_o_i data
#define pp_seq_for_each_product_o_i(cset, rset, res, macro) (pp_seq_tail(cset), rset, res, macro)
#define pp_seq_for_each_product_c(data, i) pp_if(pp_dec(pp_seq_size(pp_tuple_elem(4, 1, data))), pp_seq_for_each_product_N_ ## i, pp_seq_for_each_product_i)
#define pp_seq_for_each_product_i(r, data) pp_seq_for_each_product_i_i(r, pp_tuple_elem(4, 0, data), pp_tuple_elem(4, 1, data), pp_tuple_elem(4, 2, data), pp_tuple_elem(4, 3, data))
#define pp_seq_for_each_product_i_i(r, cset, rset, res, macro) macro(r, pp_seq_tail(res (pp_seq_head(cset))))
#define pp_seq_for_each_product_h(data) pp_seq_for_each_product_h_i data
#define pp_seq_for_each_product_h_i(cset, rset, res, macro) (pp_seq_head(rset)(nil), pp_seq_tail(rset), res (pp_seq_head(cset)), macro)

#define pp_seq_for_each_product_m_0(r, data) pp_seq_for_each_product_c(data, 0)(r, data)
#define pp_seq_for_each_product_m_1(r, data) pp_seq_for_each_product_c(data, 1)(r, data)
#define pp_seq_for_each_product_m_2(r, data) pp_seq_for_each_product_c(data, 2)(r, data)
#define pp_seq_for_each_product_m_3(r, data) pp_seq_for_each_product_c(data, 3)(r, data)
#define pp_seq_for_each_product_m_4(r, data) pp_seq_for_each_product_c(data, 4)(r, data)
#define pp_seq_for_each_product_m_5(r, data) pp_seq_for_each_product_c(data, 5)(r, data)
#define pp_seq_for_each_product_m_6(r, data) pp_seq_for_each_product_c(data, 6)(r, data)
#define pp_seq_for_each_product_m_7(r, data) pp_seq_for_each_product_c(data, 7)(r, data)
#define pp_seq_for_each_product_m_8(r, data) pp_seq_for_each_product_c(data, 8)(r, data)
#define pp_seq_for_each_product_m_9(r, data) pp_seq_for_each_product_c(data, 9)(r, data)
#define pp_seq_for_each_product_m_10(r, data) pp_seq_for_each_product_c(data, 10)(r, data)
#define pp_seq_for_each_product_m_11(r, data) pp_seq_for_each_product_c(data, 11)(r, data)
#define pp_seq_for_each_product_m_12(r, data) pp_seq_for_each_product_c(data, 12)(r, data)
#define pp_seq_for_each_product_m_13(r, data) pp_seq_for_each_product_c(data, 13)(r, data)
#define pp_seq_for_each_product_m_14(r, data) pp_seq_for_each_product_c(data, 14)(r, data)
#define pp_seq_for_each_product_m_15(r, data) pp_seq_for_each_product_c(data, 15)(r, data)
#define pp_seq_for_each_product_m_16(r, data) pp_seq_for_each_product_c(data, 16)(r, data)
#define pp_seq_for_each_product_m_17(r, data) pp_seq_for_each_product_c(data, 17)(r, data)
#define pp_seq_for_each_product_m_18(r, data) pp_seq_for_each_product_c(data, 18)(r, data)
#define pp_seq_for_each_product_m_19(r, data) pp_seq_for_each_product_c(data, 19)(r, data)
#define pp_seq_for_each_product_m_20(r, data) pp_seq_for_each_product_c(data, 20)(r, data)
#define pp_seq_for_each_product_m_21(r, data) pp_seq_for_each_product_c(data, 21)(r, data)
#define pp_seq_for_each_product_m_22(r, data) pp_seq_for_each_product_c(data, 22)(r, data)
#define pp_seq_for_each_product_m_23(r, data) pp_seq_for_each_product_c(data, 23)(r, data)
#define pp_seq_for_each_product_m_24(r, data) pp_seq_for_each_product_c(data, 24)(r, data)
#define pp_seq_for_each_product_m_25(r, data) pp_seq_for_each_product_c(data, 25)(r, data)

#define pp_seq_for_each_product_n_0(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_1)
#define pp_seq_for_each_product_n_1(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_2)
#define pp_seq_for_each_product_n_2(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_3)
#define pp_seq_for_each_product_n_3(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_4)
#define pp_seq_for_each_product_n_4(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_5)
#define pp_seq_for_each_product_n_5(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_6)
#define pp_seq_for_each_product_n_6(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_7)
#define pp_seq_for_each_product_n_7(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_8)
#define pp_seq_for_each_product_n_8(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_9)
#define pp_seq_for_each_product_n_9(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_10)
#define pp_seq_for_each_product_n_10(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_11)
#define pp_seq_for_each_product_n_11(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_12)
#define pp_seq_for_each_product_n_12(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_13)
#define pp_seq_for_each_product_n_13(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_14)
#define pp_seq_for_each_product_n_14(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_15)
#define pp_seq_for_each_product_n_15(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_16)
#define pp_seq_for_each_product_n_16(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_17)
#define pp_seq_for_each_product_n_17(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_18)
#define pp_seq_for_each_product_n_18(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_19)
#define pp_seq_for_each_product_n_19(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_20)
#define pp_seq_for_each_product_n_20(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_21)
#define pp_seq_for_each_product_n_21(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_22)
#define pp_seq_for_each_product_n_22(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_23)
#define pp_seq_for_each_product_n_23(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_24)
#define pp_seq_for_each_product_n_24(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_25)
#define pp_seq_for_each_product_n_25(r, data) pp_for_ ## r(pp_seq_for_each_product_h(data), pp_seq_for_each_product_p, pp_seq_for_each_product_o, pp_seq_for_each_product_m_26)
