#if !defined( __I3_MATH_GLOBAL_VARIABLE_H)
#define __I3_MATH_GLOBAL_VARIABLE_H

#include "i3MathType.h"

#if defined( I3_FIXED_POINT)
	I3_EXTERN_MATH FIXED32_VEC3D		I3_XAXIS;
	I3_EXTERN_MATH FIXED32_VEC3D		I3_YAXIS;
	I3_EXTERN_MATH FIXED32_VEC3D		I3_ZAXIS;
	I3_EXTERN_MATH FIXED32_VEC3D		I3_ZEROVECTOR;

	I3_EXTERN_MATH	FIXED32_MATRIX		I3_IDENTITYMATRIX;
#else
	I3_EXTERN_MATH VEC3D		I3_XAXIS;
	I3_EXTERN_MATH VEC3D		I3_YAXIS;
	I3_EXTERN_MATH VEC3D		I3_ZAXIS;
	I3_EXTERN_MATH VEC3D		I3_ZEROVECTOR;

	I3_EXTERN_MATH MATRIX		I3_IDENTITYMATRIX;
#endif

I3_EXTERN_MATH REAL32 g_SinTable[512];
I3_EXTERN_MATH REAL32 g_ASinTable[512];
I3_EXTERN_MATH FIXED32 g_FXDSinTable[512];
I3_EXTERN_MATH FIXED32 g_FXDASinTable[512];


I3_EXTERN_MATH PERSIST_VEC3D _random_vector_table[];


#endif
