all : Base Input Math Gfx Sound Scene

Base:
	cd i3$@; make

Input: 
	cd i3$@; make

Math:
	cd i3$@; make

Gfx: 
	cd i3$@; make

Sound:
	cd i3$@; make

Scene: 
	cd i3$@; make

clean:
	@-rm -r -f */*.o */*.d */*~ */*.bak
	
rebuild :
	make clean
	make
