#if !defined( __I3_MATH_ANIMATION_H)
#define __I3_MATH_ANIMATION_H

enum I3_ANIM_PLAY_MODE
{
	I3_ANIM_PLAY_MODE_STOP		= 0,
	I3_ANIM_PLAY_MODE_REPEAT,
	I3_ANIM_PLAY_MODE_CLAMP,
	I3_ANIM_PLAY_MODE_BOUNCE
};

enum I3_ANIM_BLEND_MODE
{
	I3_ANIM_BLEND_MODE_REPLACE		= 0,
	I3_ANIM_BLEND_MODE_BLEND,
};

#endif
