#include "i3SceneDef.h"
#include "i3AllAttrs.h"

void i3AttrRegisterMetas( void)
{
	/*
	i3RenderAttr::RegisterMeta();
	i3AbstractBoolAttr::RegisterMeta();
	i3AlphaFuncAttr::RegisterMeta();
	i3AlphaTestEnableAttr::RegisterMeta();
	i3BlendEnableAttr::RegisterMeta();
	i3BlendModeAttr::RegisterMeta();
	i3ClippingEnableAttr::RegisterMeta();
	i3ColorAttr::RegisterMeta();
	i3FaceCullModeAttr::RegisterMeta();
	i3FogColorAttr::RegisterMeta();
	i3FogDensityAttr::RegisterMeta();
	i3FogEnableAttr::RegisterMeta();
	i3FogModeAttr::RegisterMeta();
	i3FogNearFarAttr::RegisterMeta();
	i3GeometryAttr::RegisterMeta();
	i3GeometryAttr2::RegisterMeta();
	i3SkinGeometryAttr::RegisterMeta();
	i3LightingEnableAttr::RegisterMeta();
	i3MaterialAttr::RegisterMeta();
	i3ModelViewMatrixAttr::RegisterMeta();
	i3ProjectMatrixAttr::RegisterMeta();
	i3RenderAttrListAttr::RegisterMeta();
	i3RenderModeAttr::RegisterMeta();
	i3ShadeModeAttr::RegisterMeta();
	i3StencilFuncAttr::RegisterMeta();
	i3StencilOperationAttr::RegisterMeta();
	i3StencilTestEnableAttr::RegisterMeta();
	i3TextureBindAttr::RegisterMeta();
	i3TextureEnableAttr::RegisterMeta();
	i3TextureFilterAttr::RegisterMeta();
	i3TextureWrapAttr::RegisterMeta();
	i3TextureCoordSourceAttr::RegisterMeta();
	i3TextureMatrixAttr::RegisterMeta();
	i3TextureFunctionAttr::RegisterMeta();
	i3TextureCoordScaleAttr::RegisterMeta();
	i3TextureCoordOffsetAttr::RegisterMeta();
	i3UserAttr::RegisterMeta();
	i3ViewMatrixAttr::RegisterMeta();
	i3ZFuncAttr::RegisterMeta();
	i3ZTestEnableAttr::RegisterMeta();
	i3ZWriteEnableAttr::RegisterMeta();
	i3LightAttr::RegisterMeta();
	i3BoneMatrixListAttr::RegisterMeta();
	i3PointSpriteAttr::RegisterMeta();
	i3SpriteAttr::RegisterMeta();
	i3Sprite2DAttr::RegisterMeta();
	i3QuadAttr::RegisterMeta();
	i3BillboardAttr::RegisterMeta();
	i3TextInfo::RegisterMeta();
	i3TextAttr::RegisterMeta();
	i3GPUCommandListAttr::RegisterMeta();
	i3RenderTargetAttr::RegisterMeta();
	i3ShadowMapEnableAttr::RegisterMeta();
	i3NormalMapEnableAttr::RegisterMeta();
	i3SpecularMapEnableAttr::RegisterMeta();
	i3NormalMapBindAttr::RegisterMeta();
	i3SpecularMapBindAttr::RegisterMeta();
	i3LuxMapEnableAttr::RegisterMeta();
	i3LuxMapBindAttr::RegisterMeta();
	i3NormalMapWrapAttr::RegisterMeta();
	i3SpecularMapWrapAttr::RegisterMeta();
	i3LuxMapWrapAttr::RegisterMeta();
	i3ZBiasAttr::RegisterMeta();
	i3ReflectMapEnableAttr::RegisterMeta();
	i3ReflectMapBindAttr::RegisterMeta();
	i3ReflectMapWrapAttr::RegisterMeta();
	i3ReflectMaskMapEnableAttr::RegisterMeta();
	i3ReflectMaskMapBindAttr::RegisterMeta();
	i3ReflectMaskMapWrapAttr::RegisterMeta();
	i3ShaderAttr::RegisterMeta();
	i3ViewportAttr::RegisterMeta();
	i3FresnelAttr::RegisterMeta();
	i3OcclusionQueryAttr::RegisterMeta();
	i3AmbientAttr::RegisterMeta();
	*/
}
