; once a semicolon(;) is appeared, all of left string are treated as comments.

;---------------------------------------------------------------------------------------------------------
;Relay Server Setting
[Default]
LogFilePath			= "d:\\PbLog\\Relay"		; LogFilePath
UdpIp				= "192.168.2.2"			; Relay Server UDP IP(Public IP)
UdpIpActive			= "192.168.2.2"			; Copnnect Relay Server UDP IP(Public IP)

;---------------------------------------------------------------------------------------------------------
; 
[LogD]								; NC LOGD Server
LogDActive			= 0				; 0 : Not Use, 1: Use
LogDServerIp			= "192.168.1.1"			; LogD IP
LogDServerPort			= 20204				; LogD Port	Korea:10204, Thailand:20204
;---------------------------------------------------------------------------------------------------------

;---------------------------------------------------------------------------------------------------------
[Control]
ControlServerIp			= "218.145.27.236"		; Control Server IP
ControlServerPort			= 39120				; Control Server Port
;----------------------------------------------------------------------------------------------------------