#ifndef __ITEMMECRODEF_H
#define	__ITEMMECRODEF_H

#include "ItemType.h"

//////////////////////////////////////////////////////////////////////////
// 캐릭터별 디폴트 파츠 설정
//////////////////////////////////////////////////////////////////////////
enum SETTING_PARTS_TYPE
{
	INSERT_LOGIN	= 0,
	INSERT_BUY,
	DELETE_CHARA,
};

enum CHARACTER_TYPE
{
	CHARA_NONE		= 0,
	CHARA_RED_BULLS	,
	CHARA_ACID_POLE	,
	CHARA_TARANTULA	,
	CHARA_KEEN_EYES	,	// 여기까지 DummyCharacter로 사용됩니다. 아래의 캐릭터는 더미캐릭터중 하나로 먼저 로딩됨.
	CHARA_VIPER_RED	,
	CHARA_DEFOX		,
	CHARA_LEOPARD	,
	CHARA_HIDE		,

	CHARA_COUNT
};

#define		CHARA_PARTS_COUNT		1+ITEM_TYPE_DINO-ITEM_TYPE_CHARA	// 총 10종

enum DEFAULT_CHARA_PARTS
{
	DCP_CHARA		= 0,	// 캐릭터 몸체
	DCP_HEADGEAR,			// HeadGear
	DCP_FACEGEAR,			// FaceGear
	DCP_UPPER,				// 상의
	DCP_LOWER,				// 하의
	DCP_GLOVE,				// 장갑
	DCP_BELT,				// 벨트
	DCP_HOLSTER,			// 권총집

	DCP_ITEM,				// 아이템(베레모)
	DCP_DINO,				// 공룡

	DCP_COUNT,
};

enum UNLOCK_ROUND_COUNT
{
	UNLOCK_11_ROUND,	// 11라운드 시작제한 해제권
	UNLOCK_21_ROUND,	// 21라운드 시작제한 해제권
	UNLOCK_31_ROUND,	// 31라운드 시작제한 해제권
	UNLOCK_41_ROUND,	// 41라운드 시작제한 해제권
	UNLOCK_51_ROUND,	// 51라운드 시작제한 해제권

	ROUND_UNLOCK_END,	// 라운드권이 추가되면 위로 순서대로 추가해야 합니다.

	// 이 아래 있는 애들은 건드리지 마세요!! 위로 올리면 배열 꼬입니다.
	UNLOCK_01_ROUND = 127,
	UNLOCK_00_ROUND = -1
};

const T_ItemID	g_UnlockRoundItemID[ROUND_UNLOCK_END] =
{
	2400141,	// 11라운드 시작제한 해제권
	2400142,	// 21라운드 시작제한 해제권
	2400143,	// 31라운드 시작제한 해제권
	2400144,	// 41라운드 시작제한 해제권
	2400145		// 51라운드 시작제한 해제권
};

//////////////////////////////////////////////////////////////////////////
// Default Item
//////////////////////////////////////////////////////////////////////////

//#define DEFAULT_WEAPON_ASSAULT	MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_ASSAULT,			4)	//  103004 : K-2
//#define DEFAULT_WEAPON_SNIPER		MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER,			3)	//  105003 : SSG-69	
//#define DEFAULT_WEAPON_SMG		MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SMG,				6)	//  104006 : K-1
//#define DEFAULT_WEAPON_SHOTGUN	MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SHOTGUN,			1)	//  106001 : 870MCS
//#define DEFAULT_WEAPON_MG			MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_MG,				9)	//  110009 : MK.46.Non.Ext
//#define DEFAULT_WEAPON_THROWING1	MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_THROWING1,	WEAPON_CLASS_THROWING_GRENADE,	1)	//  407001 : K400
//#define DEFAULT_WEAPON_THROWING2	MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_THROWING2,	WEAPON_CLASS_THROWING_CONTAIN,	1)	//  508001 : SMOKE
//

#define DEFAULT_HEADGEAR			700005
#define DEFAULT_DINO				1500511

#define DEFAULT_WEAPON_ASSAULT_K2_IN_MODE		MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_ASSAULT, 47)		// 103047 : K2 IN MODE
#define DEFAULT_WEAPON_SNIPER_SSG69_IN_MODE		MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SNIPER,  25)		// 105025 : SSG69 IN MODE
#define DEFAULT_WEAPON_SHOTGUN_870MCS_IN_MODE	MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_SHOTGUN, 7)		// 106007 : 870MCS IN MODE
#define DEFAULT_WEAPON_BAREFIST_IN_MODE			MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_MELEE,		WEAPON_CLASS_KNUCKLE, 1)		// 323001 : KNIFE_BAREFIST_IN_MODE

#define DEFAULT_WEAPON_TUTORIAL_M4		MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_ASSAULT, 45)				// 103045 : M4 SR-16 F.C
#define DEFAULT_WEAPON_TUTORIAL_AK		MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_PRIMARY,		WEAPON_CLASS_ASSAULT, 58)				// 103058 : AK-47 F.C
#define DEFAULT_WEAPON_RPG7				MAKE_ITEM_FLAG(ITEM_EVENT_TYPE_NONE, ITEM_TYPE_TEMP,		WEAPON_CLASS_ROCKET_LAUNCHER, 1)		// 5116001 : RPG
#define DEFAULT_WEAPON_TUTORIAL			DEFAULT_WEAPON_TUTORIAL_AK



enum CHARA_DEFAULT_ITEMID {
	CDI_RED_BULLS	= 601001,
	CDI_ACID_POLE	= 602002,
	CDI_TARANTULA	= 601003,
	CDI_KEENEYES	= 602004,
	CDI_GRAY		= 601069,
	CDI_WOLF		= 602070
};

//////////////////////////////////////////////////////////////////////////
#endif